### ISSUE TITLE
ReCaptcha v1 fails to load (1.12.1.3)

### ISSUE THREAD

**Issue by saero** [ccd0/4chan-x#1008]
I've been unable to have my post form load any sort of ReCaptcha v1 at all today.

Messed with my DNS, etc. I don't know if its a local issue with Google or that something was broken concerning v1 ReCaptcha.

**Comment by ccd0** [comment]
Does it work on this page?
https://www.google.com/recaptcha/demo/

**Comment by saero** [comment]
Disregard this post. I forgot last night I temporarily blocked all of Google scripts. Of course, this is why it wasn't loading. 

Gah, I just realized it now. Gonna set as closed. Thanks ccd0.
