### ISSUE TITLE
Thread Excerpt in Tab Title

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1011]
Not sure if this is a bug or intentional, but the option to "remove thread excerpt" from the tab title has disappeared.

If this was intentional, could this feature please be re-added to future versions of the script?  It's extremely irritating that 4chan thread comments now clutter my browser history and the browser tab-list in general when there are many 4chan tabs open at once.

**Comment by i-cant-git** [comment]
Tbh, I like excerpts, it makes really easy to search in browser history.

**Comment by ccd0** [comment]
I've restored the option.
