### ISSUE TITLE
How to highlight with different styles on filter?

### ISSUE THREAD

**Issue by AnastasiaDunbar** [ccd0/4chan-x#1019]
Highlighting the post with a custom CSS style to recognize which filter is used.

**Comment by ccd0** [comment]
You can add `;highlight:classname;top:no` to the end of the entry to add a CSS class to posts instead of hiding them.

Based on

> to recognize which filter is used.

it sounds like you want something like #126.

**Comment by AnastasiaDunbar** [comment]
It works.
