### ISSUE TITLE
Filtering IDs per-thread

### ISSUE THREAD

**Issue by BravoBravissimo** [ccd0/4chan-x#1029]
Filtering by IDs on boards that have per-thread poster IDs, like /pol/, can have the effect of hitting different posters in different threads, and having "dead" lines accumulate in your filter. Therefore, I suggest adding an option to filter IDs (or any criterion, for that matter) per-thread. 

Perhaps this could be implemented with a new post-fix setting, like "thread:". 
For example: 
/XXXXXX/thread:YYYYYYY

**Comment by ccd0** [comment]
I think the way of doing it in #1092 makes more sense, so merging there.
