### ISSUE TITLE
Show the page number in the thread watcher list

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1030]
Submitter: Anonon
Email: no@no.no
I think it'd be convenient to have an option to show the page the thread is currently on right in the thread watcher.
This way it would be possible to see if the thread is about to die without manually opening it, and bump if necessary.

**Comment by dzamie** [comment]
Could this be done by adding another ajax in ThreadWatcher.fetchStatus to look at /threads.json (and then doing essentially what ThreadStats does), or would that cause a race?

**Comment by ccd0** [comment]
from TW: Warn if a thread is about to get pruned #1268 

@ididntknowicoulddothatXD:
> Not sure if duplicate, if so, I'm sorry.
> 
> Thread watcher should maybe get a little symbol (!) next to each thread that's on page 9 or 10.

@Yoposoc:
> This is not a bad idea.
