### ISSUE TITLE
CSS question

### ISSUE THREAD

**Issue by Fasmea** [ccd0/4chan-x#1032]
Sorry if this is the wrong category now but I'd like to know how a certain CSS tweak works.

https://i.imgur.com/Xk5ihRy.png

I want to replace the tineye link with a fitting favicon, of the same size, 16x16. As you can see, it works with Google and even the tumblr uploader I've got from somewhere else. The original code is
a[href*="https://www.google.com/searchbyimage?"] {
    content: url(https://i.imgur.com/RVdQ4Cg.png);
    height: 14px;
    margin: -2px;
    }

a[href*="https://www.tumblr.com/share/photo?"] {
    content: url(https://secure.assets.tumblr.com/images/favicons/favicon.ico?_v=30431af5d1371b48312a8594e6924ede);
    height: 14px;
    position: relative;
    right: -4px;
    margin: -2px;
    }

The CSS I've set for Tineye is
a[href*="https://tineye.com/search?"] {
    content: url(https://i.imgur.com/HOUQL2r.png)!important;
    height: 14px;
    position: relative;
    right: -4px;
    margin: -2px;
    }
but it doesn't work.

Help?

**Comment by ccd0** [comment]
Assuming you're using the example in the default Sauce settings, the href attribute is `//tineye.com/search?url=%IMG`, not `https://tineye.com/search?url=%IMG`. So to make it work you will need to remove the "https:" from the CSS.

**Comment by Fasmea** [comment]
Thank you, it worked.
