### ISSUE TITLE
add deepmindy.com to sauce list

### ISSUE THREAD

**Issue by pokeball99** [ccd0/4chan-x#1033]
this is basicly whatanime.ga for porn stars, not too sure how to implement this as it seems to have no url format afaik

**Comment by pokeball99** [comment]
any thoughts on this @ccd0 ?

**Comment by ccd0** [comment]
I looked at it, and didn't even see useful information for source hunting, it just brings up more similar faces. Also,

> not too sure how to implement this as it seems to have no url format afaik

you are right that we don't have a way to add this unless #572 is implemented.

**Comment by pokeball99** [comment]
@paradox460 completely forgot about this, was something like this implemented(site seems to have died since) or just closing out a pointless issue?

**Comment by paradox460** [comment]
Closing out a pointless issue since the site is dead. Sorry it wasn't actually solved when it was useful!
