### ISSUE TITLE
feature request: multireddits

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1035]
Submitter: minecraftkid2003
Email: sage
you know how on reddit you can combine subreddits by putting multiple subreddit names in the url separated by plus signs

like `https://reddit.com/r/aaa+bbb` shows posts from `/r/aaa` and `/r/bbb`

wouldnt it be cool if you could do that with boards on 4chan.com

**Comment by dzamie** [comment]
This looks like it'd require a rewriting a very large portion of the code, since it involves changing pretty much anything that references g.BOARD - in the final compiled script, there's 127 matches of `/\Wg.board/i`.
