### ISSUE TITLE
[Request] Get screeshot/image from clipboard

### ISSUE THREAD

**Issue by Poilaucul** [ccd0/4chan-x#1040]
Is it possible to fetch a picture from the clipboard to attach to a post?

**Comment by ccd0** [comment]
Yes, just paste it. Or in Firefox prior to version 50, right click the paste icon ![screenshot from 2016-08-19 00-17-35](https://cloud.githubusercontent.com/assets/5894749/17802003/60a66968-65a2-11e6-9fac-ef46067a5e12.png) and paste it there.

**Comment by Poilaucul** [comment]
Doesn't work for picture copied from Firefox tho.
I'm using Firefox 44.0.2

**Comment by ccd0** [comment]
Are you copying the image or the URL?

Also sometimes image copying in Firefox will fail because the image is too large.

**Comment by Poilaucul** [comment]
It's all good now, it was just me not clicking the icon.
