### ISSUE TITLE
"Error Not Modified (403)" on hover

### ISSUE THREAD

**Issue by Fasmea** [ccd0/4chan-x#1046]
https://boards.4chan.org/g/thread/56221172#p56221447

Link to /qa/.

**Comment by ccd0** [comment]
Works fine for me. What browser are you using?
May be a recurrence of #945.

**Comment by Fasmea** [comment]
Was Chrome, the console shows nothing.
I additionally use uBlock and uMatrix very customized already, not sure if it's part of the reason.
I tested it here again https://boards.4chan.org/g/thread/56221172#p56227593 and /qa/*666 is still handing out this error while the other link doesn't.

**Comment by ccd0** [comment]
> I additionally use uBlock and uMatrix very customized already, not sure if it's part of the reason.

Can you try testing with them off?

**Comment by ccd0** [comment]
Also, what version of Chrome? Are you using the Chrome extension or the userscript?

**Comment by Fasmea** [comment]
I have disabled and re-enabled both of them and now the quotelink in /g/ works.
Using Chrome 52.0.2743.116 and the extension.

Seems to be fine. Closing for now.
