### ISSUE TITLE
NoScript reCaptcha stopped working

### ISSUE THREAD

**Issue by HASJ** [ccd0/4chan-x#1047]
I did something like 30 recaptcha, with no success.
Turned off the Noscript reCaptcha option and it worked.
Is Google phasing out noscript mode? Normal recaptcha has become unusable with a keyboard...

If it is from Google's side, this is just a report but if you can do something about, you're now aware.

**Comment by ccd0** [comment]
#1048:
> Submitter: 4chins
> Email: 123@gmail.com
> recaptcha doesn't work anymore with 4chanX 1.12.2.1 + Firefox 44
> audio captcha options says activate JavaScrip

**Comment by ccd0** [comment]
I was also seeing this problem earlier, including on Google's demo site
https://www.google.com/recaptcha/api2/demo
but it seems to be fixed now. Anyone still having a problem?

**Comment by HASJ** [comment]
No, it fixed itself for me too.
