### ISSUE TITLE
New IPs are not always marked

### ISSUE THREAD

**Issue by mahkoh** [ccd0/4chan-x#1049]
I.e. the tooltip shows 1 post by this ID but the IP count does not appear next to the ID. For example

```
---------------------
Anonymous (ID: XXXX)  (6) 9 minutes ago No.123
Shitpost
---------------------
---------------------
Anonymous (ID: YYYY)  8 minutes ago No.124
Shitpost
---------------------
---------------------
Anonymous (ID: ZZZZ)  (8) 5 minutes ago No.125
Shitpost
---------------------
```

**Comment by ccd0** [comment]
New/old IPs are marked based on the IP count changes. If there are multiple posts during a thread update, it will not always be possible to tell which were new IPs, at least from the count.

**Comment by mahkoh** [comment]
That's too bad.
