### ISSUE TITLE
Sauce in gallery mode

### ISSUE THREAD

**Issue by an-electric-sheep** [ccd0/4chan-x#1052]
I often use gallery mode to browse a thread for save-worthy images, but i'm also a pedant about quality, so i want to reverse search to get higher quality versions if they're available.

It would be great if the sauce links also were available in gallery mode.

**Comment by ccd0** [comment]
The menu might be a good place for it. In that case #391 is related.

**Comment by ccd0** [comment]
thth added this in #2845 and it should be available in the next beta version.
