### ISSUE TITLE
Feature to manually set posts as being yours/Post hi-lighting feature

### ISSUE THREAD

**Issue by MisakaImoutoWaifu** [ccd0/4chan-x#1054]
It'd be useful if there was a way to manually fix 4chan/4chan X/Your browser losing track of which posts are yours from the drop down menu.  What might be even more useful is bringing back the hi-lighting system that used to be much older versions of 4chan X.

**Comment by ccd0** [comment]
>What might be even more useful is bringing back the hi-lighting system that used to be much older versions of 4chan X.

Not sure what you mean by this. Can you explain what this was?

**Comment by MisakaImoutoWaifu** [comment]
Sometimes you get posting errors where client side it seems as if your post failed, but it actually gets submitted. This leads to the post you made not being tracked as one of your posts. For situations like this it'd be nice to have a way of manually setting posts to be watched as if you made them. This would also be useful for other people's posts that you want to watch, for whatever reason. 
As for the second part, when Mayhem/Aerosynth maintained 4chan X there was a feature where you entered regex expressions which would hi-light matching posts, much like a post would currently be hi-lighted if someone was replying to you.

**Comment by ccd0** [comment]
You can put
`/regexp/;highlight`
in your filter list. That still works. Is that what you're talking about, or something more fancy? I know Mayhem had been working on a new filtering interface around the time he stopped working on 4chan X, although you would have only seen stuff from that if you were using the nightly version.

**Comment by MisakaImoutoWaifu** [comment]
Oh, I completely glossed over that. I'm not sure how. 
I still think adding an item to manually add/remove which posts are yours would please a lot of people though, especially when the site is acting up and people get posting issues.

**Comment by ccd0** [comment]
>I still think adding an item to manually add/remove which posts are yours would please a lot of people though, especially when the site is acting up and people get posting issues.

Yeah, that's been requested several times, and I want to do it as well. #195
It will happen when I or someone else gets around to implementing it.
