### ISSUE TITLE
Thread Watcher not working

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1055]
Submitter: Raymond
Email: evas665@yahoo.com
I'm having the same issue here:
https://github.com/ccd0/4chan-x/issues/1050

I don't have a Firefox account sync'd up so I can't use the solution.
Also tried using default settings for 4chanX, not working.

Greasemonkey and 4chanx are all updated. Other scripts/extensions installed:
ublock origin
ex hentai easy 2
anti-adblock killer | reek

error code from console:
http://imgur.com/a/ekBHH

**Comment by ccd0** [comment]
>I don't have a Firefox account sync'd up so I can't use the solution.

You don't need a Firefox account.
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Red-M** [comment]
I'm also encountering the same bug but for anything to do with catalog or with board indexes.
Page refuses to load properly due to the new ad JS that is trying to load.

**Comment by ccd0** [comment]
4chan has been shitting itself every night recently. It has nothing to do with that ad Javascript.
