### ISSUE TITLE
Some cross-thread links are incorrectly marked dead

### ISSUE THREAD

**Issue by mahkoh** [ccd0/4chan-x#1057]
For example:

![2016-09-07-161750_332x193_scrot](https://cloud.githubusercontent.com/assets/1882250/18315376/13794f5a-7517-11e6-9f28-bb30e626aa3a.png)

**Comment by ccd0** [comment]
In
https://boards.4chan.org/int/thread/64561276#p64564584
?

I'm not seeing this. Is it like this when the thread is first opened, or do you have to try to load the post (or other posts)?

**Comment by mahkoh** [comment]
It's fixed after reloading the post. Mostly it happens like this:

- Someone opens a new general and posts a link in the old one
- I open the new thread while keeping the old one open
- Someone replies in the new thread to a in the old thread
- The backlink is shown as dead

**Comment by mahkoh** [comment]
Here is another example from a thread right now. 
![2016-09-09-172331_1366x768_scrot](https://cloud.githubusercontent.com/assets/1882250/18392544/6f681926-76b2-11e6-85ff-efcab728d635.png)

**Comment by mahkoh** [comment]
And in this case reloading does not fix the problem. https://boards.4chan.org/int/thread/64653140#p64653348

**Comment by mahkoh** [comment]
Opening the new thread in a new window did fix the problem:

![dead2](https://cloud.githubusercontent.com/assets/1882250/18392806/7bd1d8ae-76b3-11e6-8aad-9aaac2d6e58b.gif)

And after reloading the thread multiple times it's also fixed in the original now.

**Comment by ccd0** [comment]
Is there any sort of proxy between you and 4chan?

**Comment by mahkoh** [comment]
Not that I know of.

**Comment by ccd0** [comment]
Any web filtering software you know of (possibly part of an antivirus package)?

**Comment by mahkoh** [comment]
I semi-recently installed HTTPS everywhere. But nothing else.

**Comment by ccd0** [comment]
It would be good to see what's happening in the network section of your console (F12) as this happens.

**Comment by mahkoh** [comment]
I tried it in [this](https://boards.4chan.org/int/thread/64665572#p64665650) thread. What happens is that it queries https://a.4cdn.org/int/thread/64643156.json which returns 304. Then it tries desustorage.

**Comment by ccd0** [comment]
Can you select https://a.4cdn.org/int/thread/64643156.json, go to the Response tab in the right-hand section, click on the last item to expand it, and check what the post number is?

**Comment by mahkoh** [comment]
It says "This request has no response data available". But I think it says that for all 304 responses. The last non-304 response in the original thread contains the post:

```
    {
      "country_name": "Latvia",
      "country": "LV",
      "resto": 64643156,
      "time": 1473450998,
      "com": "<a href=\"/int/thread/64665572#p64665572\" class=\"quotelink\">&gt;&gt;64665572</a><br><br><a href=\"/int/thread/64665572#p64665572\" class=\"quotelink\">&gt;&gt;64665572</a><br><a href=\"/int/thread/64665572#p64665572\" class=\"quotelink\">&gt;&gt;64665572</a><br>new",
      "name": "Anonymous",
      "now": "09/09/16(Fri)15:56:38",
      "no": 64665598
    }
```

**Comment by ccd0** [comment]
> It says "This request has no response data available". But I think it says that for all 304 responses

No, if it's loading it from cache, it should have the data.

Do you have any other extensions besides HTTPS Everywhere? Any unusual cache-related settings? What version of Firefox are you using?

Can you check the contents of the Headers tab for the https://a.4cdn.org/int/thread/64643156.json entry that appears when you try to load a cross-thread quote?

**Comment by mahkoh** [comment]
I'm using Chromium not Firefox.

**Comment by ccd0** [comment]
What version? Any other extensions besides 4chan X and HTTPS Everywhere?

**Comment by ccd0** [comment]
Good chance this is a Chromium bug. You might want to look for a version that's closer to what stable Chrome is based on.

**Comment by mahkoh** [comment]
52.0.2743.116

- Advanced Font Settings
- AutoScroll
- Better History
- Checker Plus for Gmail™
- Google Input Tools
- imgur Extension by Metronomik
- Reddit Enhancement Suite
- rikaikun
- Search by Image (by Google)
- Stylish
- Tampermonkey
- uBlock Origin

Plus various extension I've written myself.

**Comment by ccd0** [comment]
It would be good to know if you can reproduce it without all those extensions enabled.

**Comment by ccd0** [comment]
This is likely a recurrence of #945 and #1046.

**Comment by ccd0** [comment]
Haven't reproduced it on my end yet, but looks like it might be this bug:
https://bugs.chromium.org/p/chromium/issues/detail?id=643659
They still haven't fixed this unfortunately.

**Comment by ccd0** [comment]
Do you have `Quote Inlining` on or off?

**Comment by mahkoh** [comment]
[x] Quote Inlining: Inline quoted post on click.

**Comment by ccd0** [comment]
Managed to reproduce on both Google Chrome 55.0.2853.0 (Official Build) dev-m (64-bit) and the stable version 53.0.2785.101 (Official Build) m (64-bit):

1. Open old thread.
2. Refresh at least twice, with last refresh not adding new posts (304).
3. Switch to new thread.
4. Try to view quote from old thread.

At first I thought it mattered whether the new thread was opened in the same tab, which is why I asked if you had Quote Inlining on, but it looks like it happens either way.

It seems to be due to the yet-unfixed Chromium bug
https://bugs.chromium.org/p/chromium/issues/detail?id=643659

A user-end workaround when this happens is to clear your cache, then reload the page. I'd have to think about whether there's a good way to work around it in 4chan X.

**Comment by ccd0** [comment]
I've put a workaround in the latest beta version (v1.12.3.0). Can you confirm whether it works for you?

**Comment by mahkoh** [comment]
I have not seen it since.

**Comment by ccd0** [comment]
Thanks.
