### ISSUE TITLE
Make noscript captcha take up less space in Quick Reply

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1066]
Very annoying on devices with a small screen resolution.
Will have to think about the best way to do it. Suggestions welcome.

**Comment by saxamaphone69** [comment]
![qr](https://cloud.githubusercontent.com/assets/877480/18415643/fcc26e9e-783c-11e6-95fc-372e5bb17d9a.jpg)
Is this the noscript one? How small of a device are we talking that can't display the 300x400 `iframe`?

If you have control on the `iframe` styling, maybe remove the footer, the extra textarea (unless it is used for something?), reduce the font size of the 'select all images...' text, and/or reduce the thumbnail size of the images?

Not sure if it could work out, but maybe you could get fancy with `100vh` or `100vw` and scale the captcha accordingly.

Alternatively, if that isn't the noscript captcha, nevermind.

**Comment by ccd0** [comment]
> Is this the noscript one? How small of a device are we talking that can't display the 300x400 iframe?

The problem isn't so much the size of the iframe as the size of the whole Quick Reply dialog. Add to that the browser chrome and a header/footer from the OS, and it can easily become awkward even at the old 1366x768. There are scroll bars provided, so it's usable, but it's annoying to have the comment jump to the top as you're typing, and for not all the fields to be visible at once. A possible solution would be some sort of popup separate from the QR that only appears when you focus on the captcha section, although that might also be annoying. Or maybe move the captcha section to the side.

> the extra textarea (unless it is used for something?)

Normally it shouldn't be visible. It only appears if inter-frame communication is not working for some reason, in which case you'll have to copy a code from the iframe to the textarea.

> reduce the thumbnail size of the images?

I don't think we want to do this, as that will make them harder to identify.

**Comment by ccd0** [comment]
And yes, that is the noscript captcha.

> A possible solution would be some sort of popup separate from the QR that only appears when you focus on the captcha section, although that might also be annoying.

Or just hide the captcha section when it's not focused. A big part of the problem is that it's in your face and encourages you to fill the captcha out and get it out of the way when filling in the captcha should ideally be the last step (as it can expire).

**Comment by ccd0** [comment]
Example of a QR that's just barely too tall, so that the bottom controls are hidden unless you scroll:
![qr](https://cloud.githubusercontent.com/assets/5894749/18415767/d4cd41be-77b2-11e6-90c4-97d67cb01348.png)

**Comment by ccd0** [comment]
Something like that. It would probably be better to have it shown on just focusing / hovering to minimize the number of mouse / keyboard actions needed, but I'd have to test it out to make a final call.

**Comment by saxamaphone69** [comment]
![qr1](https://cloud.githubusercontent.com/assets/877480/18415849/337d4484-7844-11e6-8a83-f3df23dd98ba.gif)
Just mucking around with ideas, this is playing with `max-height` on hover.
I'm sure you'll work something out @ccd0!
