### ISSUE TITLE
Filters and highlights

### ISSUE THREAD

**Issue by TheOvertNinja** [ccd0/4chan-x#1087]
![filters and highlights](https://cloud.githubusercontent.com/assets/22266766/18612017/ad67420c-7d3c-11e6-991d-58f027a7e3a6.png)

Before using this version of 4chanX I had the options of selecting which words and phrases should be filtered or highlighted through this interface. Now this option is no longer available.

I noticed another way to add filters with 4chanX through the settings but I'm having issues adding words to be highlighted and sent to the top of the catalog.

For example, I tried adding "top:/CYOA/i;boards:tg;op:only" to the subject line in filters with no success.

**Comment by ccd0** [comment]
You want
`/CYOA/i;boards:tg;op:only;highlight`

The native version of the catalog is still available at https://boards.4chan.org/tg/catalog, and if you prefer it, you can make the [Catalog] links point there by unchecking `Use 4chan X Catalog` in the settings.

**Comment by TheOvertNinja** [comment]
Ah, I see. Thanks a lot.

What's the difference between the 4chanX catalog and the normal catalog?

**Comment by ccd0** [comment]
The 4chan X catalog is generated by 4chan X on the index page (e.g. https://boards.4chan.org/tg/) whereas the native catalog is generated by 4chan's Javascript on https://boards.4chan.org/tg/catalog. Most 4chan X features don't work on the native catalog; it's a separate thing.

**Comment by TheOvertNinja** [comment]
Alright, thanks again.
