### ISSUE TITLE
Customizable Post Info

### ISSUE THREAD

**Issue by paradox460** [ccd0/4chan-x#1089]
Right now, we have the ability to customize the way time formatting, file info formatting, and sauce formatting, but not the actual post header.

It would be nice to have the ability to customize the post header, using a similar tokenized format.

This idea mostly came to me when I was trying to make a tweak to my userstyle to show the flag names, in plain text, alongside the flag. Would be helpful for flags like this one:

![1474183585009](https://cloud.githubusercontent.com/assets/168193/18614637/2bd9fcb0-7d47-11e6-9ee7-e10f76bae078.png)

Ultimately, I couldn't get the effect I wanted without having to use some custom JS.

**Comment by saxamaphone69** [comment]
`.flag::after { content: attr(title); }` might give you what you're after (in Chrome at least).

**Comment by paradox460** [comment]
Thats what I tried with my userstyle, unfortunately, due to a combination of 4chan's use of sprites and the limitations of psuedo-elements, this displays the text, but will overlap any neighboring content.

**Comment by ccd0** [comment]
How about this?

```
.flag::after {
  content: "\A0" attr(title);
  white-space: nowrap;
  margin-left: 16px;
  background: #f0e0d6;
}
.reply:target .flag::after, .reply.highlight .flag::after {
  background: #F0C0B0;
}
.flag {
  width: auto;
  line-height: 11px;
  top: 0;
}
```

**Comment by paradox460** [comment]
I should have thought of something like that. That does the trick nicely, and solves the background problem
