### ISSUE TITLE
4chanX is gone

### ISSUE THREAD

**Issue by Votapardo** [ccd0/4chan-x#1094]
Hi
Today I updated to 1.12.3.2 and then I noticed, when I went to the Catalog, that 4chanX has disappeared. It's not there, as if it had never been installed. I'm using Firefox 40.0.3. What happened here? Thank you.

**Comment by ccd0** [comment]
If it's not showing up on any pages despite being enabled in your Greasemonkey settings, and it's been that way since an update, there might have been an error while downloading the update. Try reinstalling it. As long as you don't uninstall before reinstalling, your settings should be kept.

**Comment by Votapardo** [comment]
It worked. Thank you!
