### ISSUE TITLE
Post button not submitting post

### ISSUE THREAD

**Issue by DeckardEdward** [ccd0/4chan-x#1095]
Somehow, whatever it is in my 4chan X that submits post content seems to have broken. When I attempt to make a text, image, or text+image post, 4chan X cashes in my completed captcha, but my post submission seems to get forgotten. With post on captcha completion checked, the submission process doesn't start when captcha is completed, manually clicking the post button after captcha completion cashes in the captcha without starting the submission process, and clicking submit again tells me that I do not have a valid captcha. I have tried unchecking post on captcha completion, turning off Oneechan, and turning off NameSync, and none of the above have helped. Turning off 4chan X and attempting to post with the native extension works without issue.
The problem first appeared when I woke my computer up after I put my computer to sleep for a few hours; I haven't personally made any changes to my 4chan X script settings, any other script settings, or my browser settings for at least a couple months, and this issue arose only a few hours prior to the time of this post.

I'm not very script-savvy, so I don't know what other details I should report on, but those are all the things I could think to check before dropping a line here.

In case it helps identify the problem at all, I'm including links to my current 4chan X settings and my current Oneechan settings.
4chan X: https://dl.dropboxusercontent.com/u/25349796/Old/4chan%20X%20v1.12.3.2-1474524665669.json
Oneechan: https://dl.dropboxusercontent.com/u/25349796/Old/OneeChan%20v5.5.43%20Settings.json

**Comment by ccd0** [comment]
Can you check the Javascript console (F12) and the web console (Control+Shift+J) for any errors that appear at the moment you post?

Are you still using Firefox? What version?
Do you still have the problem if you make a new Firefox profile?

**Comment by DeckardEdward** [comment]
Well fuck. I am still using Firefox, and I *just* accidentally updated it while I was checking the version. Up until a few seconds ago, I was using whatever the public release was prior to Firefox 49.0. My random 4chan X setting swaps seem to have stopped since creating the new profile (*thank you very, very much for that, by the way*)

I'm checking the console now. This post will be updated shortly...
