### ISSUE TITLE
Changing the page icons

### ISSUE THREAD

**Issue by OmegaEx** [ccd0/4chan-x#1098]
Hello, i don't have any specific problem wi th the program i would just like to change the icon of the the page and making them my own custom ones (rather then t he pre packaged one the program came with) what file should i edit?

**Comment by ccd0** [comment]
They're in
https://github.com/ccd0/4chan-x/blob/master/src/Monitoring/Favicon.coffee
https://github.com/ccd0/4chan-x/tree/master/src/Monitoring/Favicon

**Comment by ccd0** [comment]
Having a UI setting to add custom favicons is a good idea. (issue at #1045).
