### ISSUE TITLE
Boardnav: External text and emojis

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#1100]
Using the latest version of Chrome, emojis appear colored in my custom boardnav.
For example: [ɐ / b / co / vp] [🔎/ 📝] [qa / t]
This is irritating because they look really out of place now.

I saw this post on /qa/ today and the emojis came up colorless: https://boards.4chan.org/qa/thread/646652#p687345
Quoting the same post on Chrome will show fancy emojis in the QR.

Is it possible to force text-like emojis on the boardnav like 4chan natively does now?

**Comment by ccd0** [comment]
I think whether they're colored depends on the font. So you'd just need to use custom CSS to change the font in the header to one you're happy with.

**Comment by ididntknowicoulddothatXD** [comment]
I wasn't aware of that. It does seem to work now. Thanks.
