### ISSUE TITLE
Quoting highlighted text sometimes quotes additional text

### ISSUE THREAD

**Issue by mahkoh** [ccd0/4chan-x#1108]
This is not a 4chan-x bug as far as I can tell but maybe something 4chan-x can fix. Consider the following post

```
Anonymous No.1234
A A A A A A A A A A A

B B B B B B B B B B B

C C C C C C C C C C C
```

Triple clicking on the `A` paragraph will highlight this paragraph and clicking on the post number will quote the paragraph.

However, the same does not quite work for the `C` paragraph. Triple clicking on it will highlight it but when you click on the post number the quoted text might look like this:

```
>>1234
>C C C C C C C C C C C>>
```

Note the additional `>>`. These meme arrows are not visible in on the page at all but are probably somewhere in the html. Sometimes even more text is added at the end when the post in question is the last post in the thread.

Browser: Chromium

**Comment by ccd0** [comment]
It's probably quoting the arrows in front of the next post (you might have hidden these).
We should probably trim the text quoted to text within the post quoted.
