### ISSUE TITLE
Make 4chan pass less obnoxious

### ISSUE THREAD

**Issue by fibre1** [ccd0/4chan-x#1122]
This whole feature goes against the principles of an imageboard and you're the only party capable of filtering it globally.

Turn it into an indicator next to the ID if you have to, or hide the date of purchase information unless moueovered. 

The shit shouldn't be visible at all

Save us from the cancer, ccd0

![4chan Pass user since December 2012.](https://cloud.githubusercontent.com/assets/16143161/19019875/fc677df8-88e1-11e6-81d5-dd29ff814479.png)

**Comment by ccd0** [comment]
Looks like it was already implemented on 4chan's end.

**Comment by fibre1** [comment]
wew
