### ISSUE TITLE
Filter option for '4chan pass' logo flair users

### ISSUE THREAD

**Issue by DrLore** [ccd0/4chan-x#1123]
There's already issues about the larger 'signature' version, but there's some kind of 4chan logo flag version that looks like this, and as you can see it's indicative of low-quality posting:

[![pure scum](https://cloud.githubusercontent.com/assets/3742026/19022788/e9ae844a-88d7-11e6-9f73-1121d68ad4f0.png)](http://boards.4chan.org/tv/thread/74920402#p74920592)

I'd like a way of filtering them. The HTML is different, but maybe you could treat it as a 'Flag' and call it '4chanPass' or something.

**Comment by ccd0** [comment]
I think you can have both flags and this, but we could treat it as a capcode.

**Comment by ccd0** [comment]
Or maybe give it its own entry. I don't know if it's possible for a post to have both a capcode and this pass thing, but the HTML is different, so I suspect you can.

**Comment by bui** [comment]
It should be its own thing; not a capcode - if you look at the API, there's a new `since4pass` key for posts that use it.

**Comment by bakugo** [comment]
Not entirely related but I've been meaning to ask: why does 4chan X even have an input field for each kind of filter?

Why not have a single field for entering filters and add an option to each filter to specify which parts of a post to apply it to? It would make adding new filter types trivial and also make it easier for users to filter something in multiple parts of a post.

```
/^(?!$)/;type:pass # filter anyone with a pass icon
/^(?!$)/;type:tripcode,pass # filter anyone with a tripcode OR pass icon
```

**Comment by ccd0** [comment]
It's on beta now; I'll add it to stable soon if everything is working right and they haven't changed things up again.

**Comment by ccd0** [comment]
@bakugo
Downside is that if you have a lot of filters, you'd have to repeat the type option on each one. But the situation is similar for other options. I think it would be a good idea to combine them all into one field and have an options line above a block of filters so you don't have to repeat them. We could slso have a graphical mode for setting the options (I think we should keep the text mode available for easy import/export).

This should be in a separate issue, though.

**Comment by ccd0** [comment]
Single issue opened at #1124.

**Comment by ccd0** [comment]
Now on stable.
