### ISSUE TITLE
is.4chan.org - Apparent new image server

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#1141]
Found it here, for example: https://boards.4chan.org/v/thread/354215415#p354215678
https://is.4chan.org/v/1476011106948.jpg

For now it returns ERR_CONNECTION_REFUSED errors on Chrome, guess it's a 4chan problem.

**Comment by ccd0** [comment]
I don't see is.4chan.org anywhere in that page.

**Comment by ccd0** [comment]
I'm seeing it in some active threads, though. Doesn't seem to be used all the time.

**Comment by ccd0** [comment]
Looks like full images are broken on the HTTPS version of is.4chan.org.

**Comment by ccd0** [comment]
Actually, all images, it's just not trying to load thumbs from there yet. HTTPS on is.4chan.org seems to be completely broken.

A quick fix would be to rewrite all the links back to i.4cdn.org, but they ought to have this fixed on 4chan's end soon anyway.

**Comment by ccd0** [comment]
Went ahead and pushed an update since it's been broken for 5 hours already.

**Comment by ccd0** [comment]
is.4chan.org appears to be substantially slower, so we should avoid it as long as possible.

**Comment by ccd0** [comment]
Seems to be gone now, but will continue monitoring the situation. He might add it back when HTTPS is working.

**Comment by ididntknowicoulddothatXD** [comment]
Thanks for your effort.

**Comment by ccd0** [comment]
> A quick fix would be to rewrite all the links back to i.4cdn.org

This needs to be made optional but default-on.
