### ISSUE TITLE
Menu entry for Sauce

### ISSUE THREAD

**Issue by arrnonymous** [ccd0/4chan-x#1142]
Mockup:
![image](https://cloud.githubusercontent.com/assets/22729309/19221764/d6ae7b1e-8e1f-11e6-9137-ad0faa32cae0.png)

**Comment by ididntknowicoulddothatXD** [comment]
Would support it but only if it stay optional.

**Comment by ccd0** [comment]
Duplicate of #391. No idea when it might happen, but a pull request implementing it would certainly be welcome.
