### ISSUE TITLE
bug ''1 day ago'' and ''24 hours ago''

### ISSUE THREAD

**Issue by Janaue** [ccd0/4chan-x#1148]
since less than a week, I *always* get these ''1 day ago'' and ''24 hours ago'' instead of the proper amount of time between the time of the post and the time I read the post.
the absolute time is fine though [when I let the mouse hover over the ''1 day ago'']

I use palemoon 26.5 with the latest version of 4chan x and with greasemonkey 3.9
https://github.com/janekptacijarabaci/greasemonkey/releases

**Comment by ccd0** [comment]
Have you checked that your computer's time and time zone settings are correct?

**Comment by Janaue** [comment]
yes they are fine. I run server 2012r2. I remember that at the anniversary, it was fine, but the version afterwards showed the bug.

**Comment by ccd0** [comment]
What do you get when you type `Date.now()` in the console (F12)?

**Comment by Janaue** [comment]
[23:20:05.274] 1476393605276

okay so I ran chromium and it already did this with version 1.13.0.6.

I upgraded to v1.13.0.10 on chromium, reseted the settings and I still get ''1 day ago'', even though the absolute time of the post are OK.

**Comment by ccd0** [comment]
> [23:20:05.274] 1476393605276

That's tomorrow. Your computer's date is set wrong.

**Comment by Janaue** [comment]
okay I changed the date and it is fine.

**Comment by ccd0** [comment]
Good to hear.
