### ISSUE TITLE
Prefetch images

### ISSUE THREAD

**Issue by Isc4u** [ccd0/4chan-x#1149]
I cannot seem to be able to turn on image prefetching for all boards and to be always on. Every time I enter a new thread I have to turn the damn thing on when I just want very thread to automatically prefetch all images. Is it not a feature? If not, would it be possible to add it as one?

**Comment by ihavenoface** [comment]
Basically prefetching is bad and you should not use it.

**Comment by Isc4u** [comment]
And why is that if I may ask?

**Comment by ihavenoface** [comment]
Because loading any kind of content increases server load meaning less reources for the rest of the user base. Doing that while not being conscious about the content you're requesting is, as @ccd0 mentioned in the issue he referenced, straight out rude.
