### ISSUE TITLE
Thread watcher unread count sometimes not updated

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1154]
There seems to be an issue on the beta version where scrolling to the bottom of the page sometimes doesn't update the unread count in the thread watcher to zero. Still trying to work out when this happens so I can reproduce it on demand.

**Comment by zephcom** [comment]
I can reproduce this problem while using Firefox 49. Using Firefox 49 also stops me from scrolling pages with the mouse wheel, related? Downgrading to Firefox 48 fixes both issues.

**Comment by ccd0** [comment]
Interesting. Can you reproduce it at will? I don't know what conditions make it happen. And do you have cookies enabled on 4chan?

> Using Firefox 49 also stops me from scrolling pages with the mouse wheel, related?

This I've never seen, so it's possible you have a different problem.

**Comment by ccd0** [comment]
@zephcom
Were you seeing any messages about NS_ERROR_FILE_CORRUPTED, possibly in your console (F12)? Might be a case of #1144. Still wouldn't explain the scrolling issue, though.

**Comment by swablueme** [comment]
@ccd0 I am experiencing this as well. Chrome 54.0.2840.59. Thread watcher count will constantly fail to update and I must manually click the refresh button to make the numbers change. 

Also, it seems like lines such as 'script.js:3938 XHR finished loading: GET "http://a.4cdn.org/vp/catalog.json?s=Index".' is not displayed in console at all unless I manually refresh.

**Comment by ccd0** [comment]
Possibly related:
- watch thread, read thread to bottom
- close thread and navigate to index
- thread gets new post
- watcher autoupdates
- unread count larger than it should be
Seen in v1.13.0.16 (beta) but not v1.12.3.11 (stable).

**Comment by swablueme** [comment]
@ccd0 
Please disregard my comment. I realised that it was an UNRELATED ISSUE as the unread count was updated to 0 and furthermore I wasn't on the beta. The full details have been submitted in issue #1164

**Comment by ccd0** [comment]
@zephcom
Have you tried upgrading to Firefox 49 and creating a new profile?
https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by ccd0** [comment]
> Possibly related:
> 
> - watch thread, read thread to bottom
> - close thread and navigate to index
> - thread gets new post
> - watcher autoupdates
> - unread count larger than it should be
> 
> Seen in v1.13.0.16 (beta) but not v1.12.3.11 (stable). Chromium 53.0.2785.143. Will investigate when I have time.

On closer examination, this one appears to be merely due to 4chan X limiting the rate at which the last read post is saved. If there is sufficient time (2 seconds) between scrolling to the bottom and closing the thread, the watcher gets the right numbers when it autoupdates.

On the other hand, we need to limit the rate at which the thread watcher unread count data is saved, which can be excessive.

**Comment by zephcom** [comment]
@ccd0 Sorry for not being able to respond faster. Creating a new profile on Firefox 49 fixes the issue. I was not able to reproduce this issue on my other machine, should have figured a new profile was the way to go.

**Comment by ccd0** [comment]
New theory for why the original bug happens: It could be due to a race condition that occurs when the scrolling (and thus updating of the unread count) takes place between the thread watcher starting to refresh and it finishing. If that's the case, it's not a new bug in the beta version, but already present in v1.12.3.6, which means I don't need to wait to fix it before pushing v1.13.
