### ISSUE TITLE
Quick reply personas possible bug

### ISSUE THREAD

**Issue by broski93** [ccd0/4chan-x#1165]
So I'm using this feature to automatically have a tripcode when posting only on a certain board. It works, but when I switch to another board where I should be Anonymous it keeps it in the name field and I have to manually clear it. This happens only if I submit a post with the automatically set tripcode, not if I simply open the quick reply window and then close it.
This is the command I use: 
name:"Anonymous # tripkeyword";boards:vip;always

**Comment by ccd0** [comment]
Will fix. Until then, a workaround is to put
name:"";always
at the top of your personas.

**Comment by ccd0** [comment]
In stable now.
