### ISSUE TITLE
advertising option

### ISSUE THREAD

**Issue by fullmetal1** [ccd0/4chan-x#1166]
I noticed that 4chan x seems to automatically block ads. While this is a good feature, I think it should be optional, since some people might want to view ads

**Comment by ccd0** [comment]
4chan X blocks ad scripts, not ads in general. If you want to run scripts from an advertiser, add it to the Javascript Whitelist setting in the Advanced settings.

**Comment by fullmetal1** [comment]
Maybe the javascript whitelist should be optional then

**Comment by ccd0** [comment]
You can set it to allow everything.
