### ISSUE TITLE
The new download with original filename button that cannot be removed

### ISSUE THREAD

**Issue by Nekoragi** [ccd0/4chan-x#1178]
After I updated today this button popped up:
https://i.gyazo.com/e2d59b5795ea8708fd6cc2d139412dcb.png
It stands out like a sore thumb and I went through the whole settings and there is no option to remove it. It does the same thing as if you opened the context menu and clicked download file. Further, when you actually use it, it opens the window that doesn't let you pick where you want to download the file, it just uses the default browser download location. I fucking hate it please delete this.

**Comment by ccd0** [comment]
It's in Advanced > File Info Formatting.

**Comment by Nekoragi** [comment]
I'm sorry and thank you
