### ISSUE TITLE
Catalog hover expand keeps turning itself on

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1200]
Submitter: Chris Draper
Catalog hover expand keeps turning itself on

**Comment by ccd0** [comment]
It turns on/off on click. Turn off "Catalog Hover Toggle" if you don't want that.

**Comment by MrDanCorbs** [comment]
Having the same issue. I disable it in the prefs, but it keeps turning back on.

**Comment by ccd0** [comment]
@MrDanCorbs 
As I said, it turns on/off on click. You need to turn off "Catalog Hover Toggle" if you don't want that.
