### ISSUE TITLE
Gallery mode save image hotkey

### ISSUE THREAD

**Issue by alidan** [ccd0/4chan-x#1203]
I'm sorry if this is already a thing and I'm just not seeing it, I just found an extension that saves images to separate folders, and I can symbolically link the image folder to my normal image save folder which is where I import images to the hyrdus client from. Before I was dragging and dropping, not bad, it worked, but now that I have a new method using a save feature makes sense.

**Comment by ccd0** [comment]
Additional requests for this: #2264 #2456 #2493

**Comment by alidan** [comment]
forgot I asked for this, for the record, I would still find this very useful as I have had to go through a few galleries and manually save. 

Thanks in advance if this ever happens.

**Comment by Qsefawd** [comment]
Pardon the hijack. Which extension are you using, @alidan ?

**Comment by alidan** [comment]
Downloads Router 0.8.1
It needs to save files within chrome's native folder of choice, but with this and symbolically linking folders, I can have various things save off into their own areas. 
at least for images and torrents it is a great tool so they dont clog a download folder till you deal with it, and mixing images with hydrus for me just made everything so much easier. 

I could probably part out video, ebook, and zip/rar into their own folders too

**Comment by Qsefawd** [comment]
Sounds good to give it a try. Let me know if there's anything else to lookout for other than the extension and hydrus. 

Hope we'll have a hotkey soon!

Thank you so much for your reply! 

> Downloads Router 0.8.1
> It needs to save files within chrome's native folder of choice, but with this and symbolically linking folders, I can have various things save off into their own areas.
> at least for images and torrents it is a great tool so they dont clog a download folder till you deal with it, and mixing images with hydrus for me just made everything so much easier.
> 
> I could probably part out video, ebook, and zip/rar into their own folders too

**Comment by alidan** [comment]
buster for dealing with captcha, 
click and save, when I still used it it was a drag and save mode, but hydrus kind of killed the need for it entirely, though my use of hydrus is kind of stupid in the sense I shotgun downloaded craploads of threads, if you just want a few images in a thread that is probably still better. 
possibly gif scrubber, not sure if there is better, but it made looking at gifs easier when I wanted a specific portion of a long one, hydrus has replace all function in this reguard. 

that's about it as it would pertain to 4chan

**Comment by saxamaphone69** [comment]
I believe this was done with https://github.com/ccd0/4chan-x/commit/690d532d52a5f0f382d63f683c3efbab97fe2e21.
