### ISSUE TITLE
See images only if directly clicked on them

### ISSUE THREAD

**Issue by Con7e** [ccd0/4chan-x#1216]
I would love to be able to view images on 4chan only if I click on them. This would allow me to browse 4chan at work, which otherwise wouldn't be possible since even SFW boards have dickheads posting NSFW images.

**Comment by ccd0** [comment]
You can check "Werk Tyme" in the header menu or press "Shift+w".

**Comment by Con7e** [comment]
Exactly what I needed. Thanks a lot!
