### ISSUE TITLE
Error: Upload failed

### ISSUE THREAD

**Issue by porkslope** [ccd0/4chan-x#1217]
I am constantly getting this error whenever I try to post anything on any board (other than /trash/ oddly enough). I'm using 1.13.1.12

This started happening after an automatic update on Sunday November 27. I'm at a loss at what the problem could be but it's extremely irritating. I can only post if I disable the script completely.

![error](https://cloud.githubusercontent.com/assets/24279290/20768886/a7149c5a-b70d-11e6-971c-c0df0aedca21.png)

**Comment by porkslope** [comment]
Just an update, the latest beta build does not have this issue

**Comment by ccd0** [comment]
There aren't any changes to the quick reply in the current beta version. Maybe it's something to do with your old settings. Did you have anything set in the persona settings, like a password? If you still have your old settings, could you export and post them? (You can edit out any sensitive information.)

**Comment by ccd0** [comment]
This happens when you post with "moot" or "#faggot" in the name field, and probably other things. Perhaps your name or trip got banned.

**Comment by SRGOM** [comment]
I'm having the same. I cleared cookies infinite times but no luck. Using the "text captcha", not the image one. 

Same IP, using Opera with no extensions/scripts works fine...

**Comment by ccd0** [comment]
@SRGOM
Can you open a new issue with more details?
