### ISSUE TITLE
More of a request then a issue/error, add something next to a thread you've posted in, and added to the watcher,  when someone has replied to your post. Rather than opening every thread in the watcher.

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#1220]
I tend to to add a whole heap of threads which I've posted in to the watcher, I know that the eye is a darker blue when someone replies to your post in one of the watched threads, but I don't know which one so I have to open them all to see. It would be great if their was a little exclamation point or something next to the certain thread for which your particular post was replied to.

**Comment by ccd0** [comment]
The thread changes color too. Are you using Oneechan or some other custom CSS? You might have to fix it on that end.

**Comment by jimmyrustles** [comment]
![capture](https://cloud.githubusercontent.com/assets/5096684/20864929/f304a9d2-ba57-11e6-9277-b4bf7f55f74b.PNG)

Is the thread you've been replied to like change to bold or something? I've never noticed, I'm just using your fork. The 'Custom CSS needs to be checked in Advanced if you want to add your own shit, right?

**Comment by ccd0** [comment]
Both the eye and the thread are supposed to turn red.
What browser are you using? Any other extensions?
Can you try exporting your settings after you've been replied to? (You can reply to your own post from another browser to trigger this.)

**Comment by jimmyrustles** [comment]
Ah, I see now, you're right, they do. I never noticed the threads changing red, when I've added a thread to watcher from a blue board, the eye just becomes darker, I never noticed the thread changing colour too.
![untitled](https://cloud.githubusercontent.com/assets/5096684/20865079/f6ff6884-ba5b-11e6-9a5c-a83ab83201b6.png)

**Comment by ccd0** [comment]
Is everything working for you then?

**Comment by jimmyrustles** [comment]
Yep,  thanks anyway!

On Dec 4, 2016 8:59 PM, "ccd0" <notifications@github.com> wrote:

Is everything working for you then?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ccd0/4chan-x/issues/1220#issuecomment-264694573>, or mute
the thread
