### ISSUE TITLE
[Bug] Auto posting sometimes gets stuck

### ISSUE THREAD

**Issue by ahtebe** [ccd0/4chan-x#1223]
Version 1.13.1.12 (but also happened in the previous version and possibly before that)

When queuing multiple posts (like when dumping a bunch of images), sometimes the timer (auto) will stop and it will stop posting.
It stops after a (seemingly) random amount of posts, at a random cooldown time.
This often occurs when multiple captchas have been successfully solved. 

It works again if the reply box is closed and reopened or if the first file on the queue when the timer stopped is removed from the queue when clicking the x in between the edit in tegaki and dump list icons. 
Both reset the timer on the submit button and it will show "Submit" instead of the number the timer got stuck in.

**Comment by ccd0** [comment]
Did you by chance disable cookies without reloading the page?

**Comment by ccd0** [comment]
Also, are there any messages in the error console when this happens?

**Comment by ahtebe** [comment]
>Did you by chance disable cookies without reloading the page?
No.
>Also, are there any messages in the error console when this happens?
Will check the console when it happens again and post results.

**Comment by ahtebe** [comment]
After dumping around 100 images using the auto poster (using version1.13.2.2), I haven't been able to reproduce the bug. Maybe after updating the issue got fixed.
I don't plan on dumping anything on the foreseeable future which means I'm not going to be using the auto poster, so I'm not going to be reporting or testing for this bug anymore.
