### ISSUE TITLE
post from URL not working

### ISSUE THREAD

**Issue by pacyoate** [ccd0/4chan-x#1225]
I'm having troubles getting images and webms to attach when using the "post from URL" button. I was using an earlier version of 4chanx, and the problem persisted when I updated to the new one.

**Comment by ccd0** [comment]
What browser and userscript engine?

**Comment by ccd0** [comment]
Also, can you give an example of a URL that didn't work?

**Comment by pacyoate** [comment]
I'm use Pale Moon 27.0.2 and Greasemonkey.

I haven't gotten any URL to work, so I can't point to a specific one.

**Comment by ccd0** [comment]
What version of Greasemonkey?
Please post an example of a URL that didn't work.

**Comment by pacyoate** [comment]
Whoops, false alarm. I updated to the newest version of Greasemonkey and now everything works fine. Sorry.

**Comment by pacyoate** [comment]
Whoops, false alarm. I updated to the newest version of Greasemonkey and now everything works fine. Sorry.

**Comment by pacyoate** [comment]
Whoops, false alarm. I updated to the newest version of Greasemonkey and now everything works fine. Sorry.
