### ISSUE TITLE
Desktop notifications not working on Chrome

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1229]
I always browse 4chan in incognito mode on google chrome (latest installed. Happens on both a Windows and Linux install). 4chan x is installed from the website.

When I go on, I am prompted as to whether or not notifications are to be enabled or disabled. I click enable, but the prompt does not go away. It takes a few clicks of enable before the prompt disappears. But the notifications do not work.

If I use Firefox with Greasemonkey, they do work OK. I've tried to see if there is a setting somewhere that is being restored via Google Syncing settings across, but removing it entirely and reinstalling causes the same issue.

Errors seen in the logs:

core.min.1011.js:1 Refused to load the script 'https://s.zkcdn.net/ados.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org 'self' 'unsafe-inline' 'unsafe-eval'".

initAds @ core.min.1011.js:1
core.min.1011.js:1 Refused to load the script 'https://utraffic.engine.adglare.net/?422617483' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org 'self' 'unsafe-inline' 'unsafe-eval'".

initAdsAG @ core.min.1011.js:1
core.min.1011.js:1 Refused to load the script 'https://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org 'self' 'unsafe-inline' 'unsafe-eval'".

**Comment by ccd0** [comment]
Tested with Chrome 55.0.2883.87 (64-bit, Windows); confirmed desktop notifications are not working in incognito mode. Seems to be an issue on Chrome's end since even `new Notification('hello world')` does not work.

**Comment by saxamaphone69** [comment]
Fast forward to 2023 and it won't work.
![image](https://user-images.githubusercontent.com/877480/236147022-a5ee414a-1bd1-4f8b-a76e-ef418dd2de4d.png)
