### ISSUE TITLE
Cover Preview Problem w. Youtube links

### ISSUE THREAD

**Issue by BondiBear** [ccd0/4chan-x#1231]
Cover Preview can no longer be disabled for yt links - I get the preview popup regardless.

See screenshot:
![image1](https://cloud.githubusercontent.com/assets/2057221/21294008/b191d8f8-c533-11e6-9331-138f3fe6439e.png)

**Comment by ihavenoface** [comment]
Post the settings you're using.

**Comment by ccd0** [comment]
Works fine for me. Please export and post your settings if you're still having trouble.

**Comment by BondiBear** [comment]
Don't know why or how, but it seems to work today. Closing.
