### ISSUE TITLE
"fit height" never really worked for me

### ISSUE THREAD

**Issue by unalignedcoder** [ccd0/4chan-x#1243]
"fit width" works, but "fit height" never really worked for me.

When I click on "expand all images" they are contained by width, but their height goes way past the viewport, regardless whether "fit height" is ticked.

I wonder if I should not really expect this to work, since I've never seen this feature in action. Or is it only me?

I use firefox and no conflicting scripts

**Comment by ccd0** [comment]
It has worked and still works fine for me, although I found a minor bug (#1244) while testing.

Can you export your settings?
What version of Firefox, Greasemonkey, and 4chan X are you using?
Are you using OneeChan? If so, please test whether it happens without OneeChan.
A screenshot and URL where you see the problem happening would be helpful.
And it might be helpful to try in a [fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles) to check that there really are no conflicting scripts or extensions.

**Comment by unalignedcoder** [comment]
thanks for the answer.
all versions are most recent & stable. I don't use OneeChan.

Here's a screen that shows an image on /hr/ not fitting in the height of the window:
![2017-01-06 13_51_38-debauchery](https://cloud.githubusercontent.com/assets/16850566/21711162/7bc830c6-d417-11e6-9ca8-72ca18b30d84.jpg)

this other screen shows what happens if "fit width" is not checked:
![2017-01-06 13_55_09-debauchery](https://cloud.githubusercontent.com/assets/16850566/21711216/d20b8294-d417-11e6-8f60-2c365d6deb8a.jpg)

but scratch all of the above, I've just tried on a virgin profile and it does work! so I guess it is a problem with my settings, though I have no idea what exactly.

**Comment by ccd0** [comment]
Do you use any custom CSS / user styles?

It might help to right click > "Inspect Element" on the image, look for the CSS rule that's messing it up, and figure out where that's from. If you have trouble finding it, you could compare the list of rules to the list you get in a fresh profile.

Also, under View > Page Style, make sure it's set to "switch".

**Comment by ccd0** [comment]
Did you ever figure this out?

**Comment by unalignedcoder** [comment]
No sorry, before I realized it was "too soon" I had already reset my settings and was thus in the impossibility of retracing the reason why that had happened. But I am confident it will happen again down the line, and I will be ready then.
What a fine script, by the way. Tremendous job.
