### ISSUE TITLE
Link Title icons don't show in Chrome if first thing in post

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1247]
Example: https://boards.4chan.org/s4s/thread/5036636 in 55.0.2883.87 (Official Build) m (64-bit)
![iconbug](https://cloud.githubusercontent.com/assets/5894749/21740587/af3d16f0-d472-11e6-8b91-f4418fafe963.png)

Does work in Firefox, though.

**Comment by bakugo** [comment]
Don't really understand why this happens, but it's pretty simple to work around.

```
.postMessage::before {
	content: "";
}
```

**Comment by saxamaphone69** [comment]
![image](https://user-images.githubusercontent.com/877480/79289116-ceda4400-7f0b-11ea-8163-a0e2e806d3bd.png)

Not sure when, how, or if something changed, but in Chrome 81 this appears to work as intended now (on my machine at least).
