### ISSUE TITLE
Title of post does not appear in catalog

### ISSUE THREAD

**Issue by Curnivore** [ccd0/4chan-x#1249]
https://boards.4chan.org/int/thread/69653217

How it is when entering the thread:

https://i.imgur.com/16rAxR2.png

How it is on the catalog:

https://i.imgur.com/UDrxHai.png

**Comment by ccd0** [comment]
That's because they put it in the name field.

**Comment by Curnivore** [comment]
damn 4chan X, you fooled me, thought it was "name of thread".

ok, deleted.
