### ISSUE TITLE
Every page now flashes. Completely unusable.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1251]
Steps to reproduce:
1) Have 4chan X
2) Open any page that uses the extension (i.e. literally anything other than the frontpage, this occurs on every board)

Here's the bug in action (https://my.mixtape.moe/kphdpf.mp4)

Extensions:
Disabled everything but 4chan X and problem still persists

Versions:
-Browser: Chrome 55.0.2883.87m
-4chan X: 3.20.14

No errors in console and this is a fresh version of the extension so there are no settings to upload. I'm not sure what else to add here. There are no errors that show up and this is very new, only started happening a few days ago. Nothing I've tried has fixed this issue (aside from not using 4chan X, obviously).

**Comment by saxamaphone69** [comment]
It appears that this user is using Mayhem's old, unsupported, and unmaintained 4chan X.

**Comment by ccd0** [comment]
> It appears that this user is using Mayhem's old, unsupported, and unmaintained 4chan X.

Yep.
