### ISSUE TITLE
Any way to make the image hover/expansion work with Desuarchive (or the backups in general)

### ISSUE THREAD

**Issue by zezikaaikwe** [ccd0/4chan-x#1254]
The archive redirection is great, as is the image expansion, but is there any way to enable that feature? I find myself missing it a lot when a thread is dead.

**Comment by ccd0** [comment]
Do you mean making 4chan X work on sites like Desuarchive, or are you having problems with image hover after a thread 404s? Image hover does load from the archives, although you may have to hover a while before you see anything because of the archives' slower image servers.

**Comment by zezikaaikwe** [comment]
Does it? I am talking about image hover directly on desu, and I've let it hover for a while and nothing seems to happen.

**Comment by ccd0** [comment]
That's the first one then. 4chan X doesn't run on the archive sites.

https://github.com/Fiddlekins/SpookyX
does though.

**Comment by zezikaaikwe** [comment]
Gotcha, thank you.
