### ISSUE TITLE
Media hover not working on archive when 4chan x is activated 

### ISSUE THREAD

**Issue by Matt80k** [ccd0/4chan-x#1256]
When i hit the box 'disable native extension' it work great, but not with 4chan x activated.

**Comment by ccd0** [comment]
Could you be more clear about what's not working? What did you do, what did you expect, and what happened?

**Comment by Matt80k** [comment]
![untitled](https://cloud.githubusercontent.com/assets/25152579/22393046/c01c4560-e4e7-11e6-8e63-63209f98f26e.png)

Mouse hover doesn't display the thumbnail. Only works with 4chan x disabled.

**Comment by ccd0** [comment]
I added quote preview in the links in the archive. Is this what you wanted?
