### ISSUE TITLE
Add archive reporting back.

### ISSUE THREAD

**Issue by 4tanner** [ccd0/4chan-x#1260]
Hey, I have the same type of fgts.jp style reporting system for my website and I was wondering if you could bring that back to 4chan-X. The commit to revert seems to be 91aa12f . The endpoint is https://sys.4tan.org/report/ .

Also if any other archives would like reports forwarded to their archive through this system, just give me a shout: tanner@4tan.org

**Comment by ccd0** [comment]
I'll bring it back in the next beta version, with the endpoint set via an extra "report" field in the archive JSON data.

You should make a pull request to
https://github.com/MayhemYDG/archives.json
if you want people to use your archive.

On the matter of forwarding reports, 4plebs has some relevant APIs:
https://4plebs.tech/foolfuuka/#4plebs-specific-intel-share
https://4plebs.tech/foolfuuka/#4plebs-specific-offsite-report

**Comment by 4tanner** [comment]
So boards that are reportable need to be listed individually in the archives.json file as well or am I completely misreading this?

**Comment by pleebe** [comment]
Since ccd0 mentioned my site, I feel I should clarify those endpoints.
I made this plugin for FoolFuuka to provide HTML report form: https://github.com/pleebe/foolfuuka-plugin-popup-report . It looks like this http://archive.4plebs.org/plebs/report/1/ .
I added that offsite report API to the plugin because another admin was supposed to make a report function that POSTs reports to all archivers (that have the plugin installed) at once. I guess 4chan X could be made to POST them directly as well, but to prevent abuse it's protected by access keys. I could modify it so that if no access key is specified the source IP can't be modified. Other report limits (bans, previous reports, etc.) are obviously enforced since it uses main FoolFuuka functions.

Intel Share endpoint is also a plugin https://github.com/pleebe/foolfuuka-plugin-intel-share . It can be used to give out globally banned MD5 hashes like this http://archive.4plebs.org/_/api/chan/intel/?page=1 . And it can be used to fetch banned MD5 hashes from other archivers that have the plugin (4plebs and desuarchive). It's admin panel has more instructions.

**Comment by 4tanner** [comment]
Perhaps we could setup forwarding from sys.4tan.org to your site with an API key. And then just add https://sys.4tan.org/report/ to the report field on archives.json for your site. It would give the users a singular interface for reporting (and also my archive will receive the reports as well).

**Comment by pleebe** [comment]
Send you a key via email.

**Comment by ccd0** [comment]
> I made this plugin for FoolFuuka to provide HTML report form: https://github.com/pleebe/foolfuuka-plugin-popup-report . It looks like this http://archive.4plebs.org/plebs/report/1/ .

Thanks, I wasn't aware of that one. If you add `"report": "https://archive.4plebs.org/%board/report/%post/"` to archives.json, you should be able to get reports from 4chan X starting from the latest beta version. On the other hand, if you want to have the reports come through 4tanner's site, you can just leave it as is (you don't need to add the sys.4tan.org endpoint for your site's entry unless you're archiving boards 4tan isn't).

**Comment by pleebe** [comment]
I will leave it as is since 4tan seems to have all boards.

**Comment by ccd0** [comment]
> I guess 4chan X could be made to POST them directly as well, but to prevent abuse it's protected by access keys. I could modify it so that if no access key is specified the source IP can't be modified.

This would be easier on users because they wouldn't have to fill out two forms. Would you be okay with reports where the reason field is just "Illegal content"?

The interface I'm envisioning is an additional "Report to archives" checkbox on the usual 4chan report form, and a "Reason" text field that shows up if the box is checked. The box would be unchecked by default, but if you select "Illegal content" as the report type on the original interface, it would check the box and fill in "Illegal content" as the reason. You'd be able to edit this, but most users probably won't bother.

**Comment by 4tanner** [comment]
The way it works now is just to redirect if the report reason is illegal content anyway, so I don't see why we couldn't implement this using sys.4tan.org (and in-fact I think it would be cleaner than the current redirect method).

**Comment by ccd0** [comment]
We could do it with sys.4tan.org too.

What I'd like to avoid is having to support multiple reporting APIs for different sites. It would be okay to specify the URL in archives.json, but we probably don't want to have to list the field names and the encoding type.

Even if we decide to have 4chan X only report to one archive and have that archive share reports with all others, we want to be able to rapidly change who receives the reports in the event that archives go down. And given how often archives go down temporarily, a solution where 4chan X POSTs the reports to all archives would be the most robust.

So whichever format we decide on, whether it's `board`, `post_no`, `reason_text` in the usual `application/x-www-form-urlencoded` encoding, or `board`, `num`, `reason` in JSON, or some other variant, we'd want all archive sites to be ready to accept data in that format.

**Comment by ccd0** [comment]
@pleebe
I see you just updated the plugin. Is it okay for me to report >>>/plebs/1 for testing purposes?

**Comment by pleebe** [comment]
I'm fine with whatever method is most convenient for users. I've now modified the plugin thusly https://github.com/pleebe/foolfuuka-plugin-popup-report/commit/1b78373cd972e65d906e7c51c40cc60dc4b10b79
Now anyone can post to it. Acecss key is used when IP needs to be specified. It's live on 4plebs.org for testing.
Currently it takes board, num and reason fields as application/x-www-form-urlencoded. It returns response content type application/json with either {"success":"message"} or {"error":"message"} object with success status code 200 or error codes 403, 404, 422 and 500.
@ccd0 Yes go ahead.

**Comment by ccd0** [comment]
@pleebe
On second thought, I would need to be testing with posts that are actually on 4chan. Is that okay if I put "test ignore" as the reason?

**Comment by pleebe** [comment]
@ccd0 
Pretty sure we can distinguish test reports so go ahead with whatever. Just as long as the reason isn't blank. Once you have tested it I can tell desuarchive admin to update the plugin since they have it as well.

**Comment by pleebe** [comment]
@ccd0 Also tell me if I understood correctly that the POSTs will be coming from sys.4chan.org, since I updated CORS.

**Comment by 4tanner** [comment]
Reporting to all archives would work, if 4chan-X did this natively that would be awesome, as that was the whole point of sys.4tan.org. I'll install pleebe's updated plugin on 4tan. Also to save headache, maybe just have the report variable in archives.json be a true/false type of deal, since every archive will ideally just have this plugin installed?

**Comment by ccd0** [comment]
> Also tell me if I understood correctly that the POSTs will be coming from sys.4chan.org, since I updated CORS.

They will be in the initial version of this. But it's possible we might want to do reporting directly from boards.4chan.org in the future.

> Reporting to all archives would work, if 4chan-X did this natively that would be awesome, as that was the whole point of sys.4tan.org. I'll install pleebe's updated plugin on 4tan. Also to save headache, maybe just have the report variable in archives.json be a true/false type of deal, since every archive will ideally just have this plugin installed (and have the same api endpoint)?

Sounds good. But we should use a different name for the boolean so that people with the version already released (albeit only on the beta channel) don't end up redirected to something like https://sys.4chan.org/board/true after reporting CP. Maybe "reports".

**Comment by 4tanner** [comment]
Is anyone using a build with archive reporting built in? It seems to me like unless they built the script themselves between yesterday and today (which is of course possible) then they would have the current archive report system, but it does not look like there was a beta build made during this time.

**Comment by ccd0** [comment]
@pleebe
Did the offsite reporting endpoint ever take JSON in the request body, or is the example in the documentation just wrong?
https://4plebs.tech/foolfuuka/#4plebs-specific-offsite-report

**Comment by 4tanner** [comment]
I wondered that too, but I ultimately got it working using 

`curl -X POST "https://boards.4tan.org/_/api/chan/offsite_report/" --data "board=tan&num=1&reason=report+reason"`

**Comment by pleebe** [comment]
@ccd0 @4tanner No it did not. That's just bad example that was generated automatically. I will update it with correct parameters later.

**Comment by ccd0** [comment]
> it does not look like there was a beta build made during this time.

You're right. Seems I forgot to push it. A good thing, in this case.
I think `"reports": true` reads a bit better than `"report": true`, though.

**Comment by 4tanner** [comment]
Also feel free to test reporting with my archive, if necessary. Later tonight I'll update archives.json with the relevant changes if no one else has by then.

**Comment by ccd0** [comment]
It seems `multipart/form-data` works as well. Can I expect that to continue working? It might be a bit more convenient because it's what's used when you AJAX send a FormData object.

**Comment by ccd0** [comment]
@4tanner
Your endpoint is returning 404 whenever an `Origin: https://sys.4chan.org` header is sent with the request. I assume this is what
https://github.com/pleebe/foolfuuka-plugin-popup-report/commit/542ee74ecc569842652b9eef1329548b31fc2ab4
fixed, in which case, you'll need to update the plugin on your site to include that fix.

**Comment by 4tanner** [comment]
Are you using the new endpoint? It’s https://boards.4tan.org/_/api/chan/offsite_report/ instead of the old sys.4tan.org one. I am also already running that commit

**Comment by ccd0** [comment]
> pleebe/foolfuuka-plugin-popup-report@542ee74

Specifically, before the change it was sending `Access-Control-Allow-Origin: sys.4chan.org` when it should have been sending `Access-Control-Allow-Origin: https://sys.4chan.org`. It appears your server translates responses that don't include the right `Access-Control-Allow-Origin` header to a 404.

**Comment by ccd0** [comment]
@pleebe
It might be a good idea to reject requests that don't have a correct Origin header set; otherwise someone can make a page that uses CSRF to make its visitors spam reports.

**Comment by ccd0** [comment]
> It might be a good idea to reject requests that don't have a correct Origin header set; otherwise someone can make a page that uses CSRF to make its visitors spam reports.

Make sure this is documented in the example, though.

**Comment by 4tanner** [comment]
Give it another try. I updated to the newest commit.

**Comment by ccd0** [comment]
@4tanner
It's working now. Haven't changed anything on my end, and yes, I was using the new endpoint.

**Comment by ccd0** [comment]
Alright, this is now in the beta version for real this time. Version 1.13.5.0.
Updated archives.json also.

@pleebe @desustorage
Once the plugin is updated on DesuArchive, we should update its archives.json entry, and it should work there as well.

**Comment by ccd0** [comment]
In stable now.
