### ISSUE TITLE
I think something might be wrong with 4chan X.

### ISSUE THREAD

**Issue by NaturalHarmonia** [ccd0/4chan-x#1263]
Sometimes when I'm on 4chan it appears as if I don't have 4chan X installed or turned on on Google Chrome even though I do. The catalog goes back to looking like what it would be without 4chan X.

**Comment by ihavenoface** [comment]
4chan X won't run on URLs that end in `/catalog`, ie. `https://boards.4chan.org/z/catalog`.

**Comment by ccd0** [comment]
> Sometimes when I'm on 4chan it appears as if I don't have 4chan X installed or turned on on Google Chrome even though I do. The catalog goes back to looking like what it would be without 4chan X.

Which URL are you on? If you visit for example https://boards.4chan.org/g/catalog, that is the native catalog. You need to be on the index page, https://boards.4chan.org/g/, to use the 4chan X catalog.

> 4chan X won't run on URLs that end in `/catalog`, ie. `https://boards.4chan.org/z/catalog`.

That's not quite right; 4chan X will run, but it doesn't do much. In particular, it does not replace the native catalog with the 4chan X version, although it adds a link to the 4chan X version if you are configured to use it.

**Comment by NaturalHarmonia** [comment]
> Which URL are you on? If you visit for example https://boards.4chan.org/g/catalog, that is the native catalog. You need to be on the index page, https://boards.4chan.org/g/, to use the 4chan X catalog.

https://boards.4chan.org/a/catalog

I went to the index page and it's still the same. I'll try to check my settings the next time I get to.

**Comment by ccd0** [comment]
Are you using 4chan X as a Chrome extension or as a userscript through Tampermonkey or Violentmonkey?

Are there any errors in the console (F12)?

Have you checked that you're not running low on disk space or memory?

**Comment by NaturalHarmonia** [comment]
I have 58.9 GBs free. And I have 4chan X as a Chrome extension. How do I know if I'm running low on memory?

**Comment by ccd0** [comment]
Never mind that and first check if there are any errors in the console.

**Comment by NaturalHarmonia** [comment]
I found this.

Failed to load resource: net::ERR_BLOCKED_BY_CLIENT 

https://s.zkcdn.net/ados.js
https://www.google-analytics.com/analytics.js

include.preload.js:468 Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.

**Comment by ccd0** [comment]
> Failed to load resource: net::ERR_BLOCKED_BY_CLIENT 
> 
> https://s.zkcdn.net/ados.js
> https://www.google-analytics.com/analytics.js

This is normal.

> include.preload.js:468 Calling Element.createShadowRoot() for an element which already hosts a shadow root is deprecated. See https://www.chromestatus.com/features/4668884095336448 for more details.

This doesn't look like it comes from 4chan X. Which leads to another question: Have you tried temporarily disabling all other extensions and seeing if 4chan X works?

**Comment by ccd0** [comment]
And what version of Chrome are you using?

**Comment by NaturalHarmonia** [comment]
The problem is on and off. Right now it's working but I'll turn off all other extensions.

I have Version 55.0.2883.87 m (64-bit) of Chrome right now.

**Comment by NaturalHarmonia** [comment]
The error didn't occur this time and it looks like Chrome is update to date now. I'm on Version 56.0.2924.76 (64-bit).

**Comment by ccd0** [comment]
Good to hear. Let me know if it starts happening again.
