### ISSUE TITLE
Sauce elements are created even if not required

### ISSUE THREAD

**Issue by saxamaphone69** [ccd0/4chan-x#1272]
4chan X creates an empty `<a target="_blank" class="sauce"></a>` for sauce links, even if they are not required.

Given that 5 new sauce options were added (not to mention the defaults), that's 5 empty elements created for every file, for no reason (where only some of them would match those parameters, which would them populate the sauce element).

Probably not that big of a deal in the grand scheme of things.

**Comment by ccd0** [comment]
This was originally done to support MD5 in sauce links on /f/, where the data isn't available on the page and has to be loaded from the API. That way it can create the link and populates it later. It would probably be a worthwhile optimization to restrict this behavior to that particular case.
