### ISSUE TITLE
Suggestion: Reassign position of the post marker

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#1277]
> #195 

Might it be possible to put it down one or two positions in the menu? Or give us an option to not use it at all, if we want to?
I change my filter every day and it's just irritating for me.

I would prefer if the menu looked like this (for me): Report -> Delete -> Filter -> [] You -> Archive

Maybe make it possible to reassign menu positions in general? Just a suggestion.

**Comment by ccd0** [comment]
You can get this with custom CSS
```#menu {
    display: flex;
    flex-direction: column;
}
.toggle-you {
    order: 60 !important;
}```
although the keyboard order will still be in the original order.
And
```.toggle-you {
    display: none;
}```
hides it.
But I may change the default position.
What do you think of putting the `You` checkbox after `Archive`? That way all the items with submenus are still grouped together.

**Comment by ccd0** [comment]
Latest beta version (v1.13.8.0) has `You` after `Archive`.

**Comment by ididntknowicoulddothatXD** [comment]
Thanks, also didn't know you could do that sort of thing with CSS.
