### ISSUE TITLE
external archive media handling suggestion

### ISSUE THREAD

**Issue by pleebe** [ccd0/4chan-x#1287]
When expanding external archive posts that have media, you should check if the file was banned before showing it. It's banned when `banned` field in the `media` object is `1`, `0` if not.
I'm suggesting this because the file might still be cached somewhere down the line for a short while after being banned. I also suggest that you show the file deleted icon for banned images. Also I'm considering a change to the API so that it doesn't reveal any information for the file except that it has been banned.
Example JSON of a banned file:
`{
	"doc_id": "47339192",
	"num": "79078689",
	"subnum": "0",
	"thread_num": "79078351",
	"op": "0",
	"timestamp": 1486175263,
	"timestamp_expired": 1486175434,
	"capcode": "N",
	"email": null,
	"name": "Anonymous",
	"trip": null,
	"title": null,
	"comment": "This one",
	"poster_hash": null,
	"poster_country": null,
	"sticky": "0",
	"locked": "0",
	"deleted": "1",
	"nreplies": null,
	"nimages": null,
	"fourchan_date": "2\/3\/17(Fri)21:27",
	"comment_sanitized": "This one",
	"comment_processed": "This one",
	"formatted": false,
	"title_processed": null,
	"name_processed": "Anonymous",
	"email_processed": null,
	"trip_processed": null,
	"poster_hash_processed": null,
	"poster_country_name": false,
	"poster_country_name_processed": "",
	"media": {
		"media_id": "10767518",
		"spoiler": "1",
		"preview_orig": "1486175263144s.jpg",
		"media": "1486175263144.webm",
		"preview_op": null,
		"preview_reply": "1486175263144s.jpg",
		"preview_w": "125",
		"preview_h": "70",
		"media_filename": "(NK_008)-1.webm",
		"media_w": "640",
		"media_h": "360",
		"media_size": "2865729",
		"media_hash": "kGKp4EdDof0ba\/7tNHo0PA==",
		"media_orig": "1486175263144.webm",
		"exif": null,
		"total": "1",
		"banned": "1",
		"media_status": "banned",
		"safe_media_hash": "kGKp4EdDof0ba_7tNHo0PA",
		"remote_media_link": null,
		"media_link": "https:\/\/img.4plebs.org\/boards\/tv\/image\/1486\/17\/1486175263144.webm",
		"thumb_link": "https:\/\/img.4plebs.org\/boards\/tv\/thumb\/1486\/17\/1486175263144s.jpg",
		"media_filename_processed": "(NK_008)-1.webm"
	},
	"board": {
		"name": "Television \u0026 Film",
		"shortname": "tv"
	}
}`

Thanks.

**Comment by ccd0** [comment]
Should be pretty easy to make these show as "File Deleted".

> Also I'm considering a change to the API so that it doesn't reveal any information for the file except that it has been banned.

It shouldn't break anything in 4chan X, since all forks I'm aware of check that `media_filename` is populated before treating it as a post with a file. If you want to be sure nobody loads CP from a cache due to an archive-fetched post, that's what you'd have to do, since there will always be people with old versions / forks.

**Comment by ccd0** [comment]
Done.

**Comment by pleebe** [comment]
Thanks.

>>Also I'm considering a change to the API so that it doesn't reveal any information for the file except that it has been banned.

>It shouldn't break anything in 4chan X, since all forks I'm aware of check that media_filename is populated before treating it as a post with a file

Good to know. I always figured mayhem made it differently right from the beginning, but that makes sense.

**Comment by ccd0** [comment]
It used to check for `media_filename` before the API was changed to put all those items under `media`:

https://github.com/MayhemYDG/4chan-x/pull/749 (0c2907db8569495fbf21eb51bc103605cd393b5d)
`data.media_filename` -> `data.media.media_filename`
https://github.com/MayhemYDG/4chan-x/pull/750 (c4d049f280361a9ae0e52411c342e59f71c91dae)
`data.media.media_filename` -> `data.media?.media_filename` (bugfix for previous)

That change went into both Mayhem's v2.35.1 and the v3 branch, which was still in alpha at the time.
