### ISSUE TITLE
Mark threads as unread/Reset read posts

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#1299]
Someone linked to a post on an interesting thread, which I'd like to fully read later.

**Comment by ccd0** [comment]
I'd find this useful, too. A good implementation could be tricky, though. If you reset the unread posts and then start scrolling again, what does it do? You probably don't want it to set the unread position again, but what if you start reading again and want to save your place, possibly forgetting that you had reset the unread position?

**Comment by ccd0** [comment]
This has been added.
