### ISSUE TITLE
Option to remove old 'New Thread' buttons?

### ISSUE THREAD

**Issue by adzie95** [ccd0/4chan-x#1301]
http://s9.postimg.org/qukbgply7/4324.png
These buttons are useless when 4chanx already provides Quick Reply. Is there an option to remove them? if not, please add an option.

**Comment by saxamaphone69** [comment]
Adding `.qr-link-container, #togglePostFormLink { display: none !important; }` to the Custom CSS option (in Advanced) should be what you're after.

**Comment by adzie95** [comment]
that worked, thanks
