### ISSUE TITLE
Connection error retries got me banned. 

### ISSUE THREAD

**Issue by alidan** [ccd0/4chan-x#1302]
Ok, so I tried to post, got a connection error, saw the newest post on a usually fast board was a half hours ago, so I let it keep retrying till it posts. 

come back 10 minutes or so later, banned for "Sending an excessive number of server requests"

Also, the message posted, them posted again 6 minutes later, then again 5 minutes after that. 

Just a heads up that you may want to make an option for automatic retries to be on or off and how often it retries. Also a post check on it to stop it from retrying again once one of them gets through

**Comment by ccd0** [comment]
Probably the easiest thing to do would be to put a time limit on how long it retries.

**Comment by ccd0** [comment]
Or number limit. Can we just set it to 10 or is there a great demand for a way to adjust it?

**Comment by ccd0** [comment]
Alternately we could just gradually increase the cooldown.

**Comment by alidan** [comment]
Sorry it's been a while. If I remember what happened right, I tried to reply to something, it wouldn't post, then when it finally got through it posted, then posted it again, then again. 

The fixes I can think of would be trying 3-5 times in semi rapid succession, like a 5 second timer to retry opposed to what I remember it being like 1-2 seconds. If it fails continually it stops that with a 1 minute timer till it retries. I have had a few times in the past where it would time out on me or fail to connect a few times but then get through, but not consecutive fails for a minute ish.

Also, on it posting more than once, there may be an issue with the 4chan tab not being the focus in chrome with it retries, I can't think of a way to test this out... maybe disconnecting the internet, posting, leaving the tab to another one then reconnecting. I can't think of why it would post 3 times over a 10 minute period of time, possibly an issue with 4chan when it was not accepting connection, possibly an issue with this extension and tab focus.

**Comment by n4ru** [comment]
This just happened to me and I got a 24h ban.

**Comment by ccd0** [comment]
4chan X now stops retrying after 5 attempts.
