### ISSUE TITLE
4chan x not working in Firefox any longer

### ISSUE THREAD

**Issue by CorWilson** [ccd0/4chan-x#1311]
I currently had to turn on the native extension for the time being cause 4chan x stopped working two days ago. None of its features are working. I turned the script on and off to see if that would fix it, but still nothing. I don't know if you guys are aware of the issue or not.

**Comment by ccd0** [comment]
It's working fine for me. Try redownloading (click the install link on https://www.4chan-x.net/ again), as well as the stuff described at https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs especially testing in a [fresh profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles).

**Comment by ccd0** [comment]
Also make sure Greasemonkey itself is enabled.

**Comment by CorWilson** [comment]
That first reinstall link worked. Guess the script was disabled by Firefox for some reason. Thank you.
