### ISSUE TITLE
Own comments not highlighting, no way to check when they reply to me (4chan X v1.13.8.4)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1313]
Submitter: Useraro
Before installing this I could simply Ctrl+F "(you)" and instantly find my comments. Now I don't know how to re-enable that AND when others reply to me they don't get highlighted (as it says in the settings of your extension).

**Comment by ccd0** [comment]
Unable to reproduce; please try the [usual steps](https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs) to get more information.

**Comment by saxamaphone69** [comment]
![enable ong](https://cloud.githubusercontent.com/assets/877480/23653928/8327e7d6-0382-11e7-8d1a-e43c0abedb47.PNG)

Also ensure the setting is enabled.

When you say "before installing this", it implies either you were using another script or perhaps the default 4chan extension. Ensure those are disabled before using 4chan X.
