### ISSUE TITLE
Clicking on an Image/Video opens it in a new tab in Chrome in addition to expanding it

### ISSUE THREAD

**Issue by mrDindu** [ccd0/4chan-x#1325]
Clicking on an Image/Video opens it in a new tab in Chrome in addition to expanding it

**Comment by ccd0** [comment]
Works fine for me. Please [give more details](https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs).

**Comment by drewmerc** [comment]
been suffering from this since it was first posted (i was the one who liked OPs post)
anyways as per this thread https://github.com/ccd0/4chan-x/issues/1358 
it was Pop up blocker for Chrome™ - Poper Blocker 4.0.3.1 addon causing the issue, white listing 4chan fixed the issue
