### ISSUE TITLE
Unable to play webms inline on Firefox for Android

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#1329]
I installed _Firefox_ on my android device, then I installed a userscript manager ([usi](https://addons.mozilla.org/en-us/firefox/addon/userunified-script-injector/)) as a plugin for _Firefox for Android_ and finally I installed _4chan-x_ as a new script. Everything seems to work fine but it looks like I can't play webms inline in the threads. The thumbnail for the video is greyed when I tap on it, a new media played by _Firefox_ is detected in the notification window but nothing happens, the thumbnail stays greyed and no sounds at all. Disabling the onmouse-over popup feature does not help either. Opening the webm in a new page plays the video without problems, so it's probably a _4chan-x_ incompatibility. Is _4chan-x_ even officially supported on android?

**Comment by ccd0** [comment]
Confirming this.

> Is 4chan-x even officially supported on android?

I try to fix issues in all modern browsers where practical, although sometimes it's less of a priority.
