### ISSUE TITLE
4chan X issues with replies and notifications

### ISSUE THREAD

**Issue by Icarus77** [ccd0/4chan-x#1335]
I have recently noticed a few issues with 4chan X. The first thing I've noticed is that there is no longer a timer on my "Submit" button. Instead there is an orange notification on the top that repeatedly pops up saying how many seconds until I can post again. This is very annoying because it also shows the notification as a browser popup if I go to a different tab while waiting.

The second thing I have noticed is that there seems to be issues with the plugin registering replies to me. Sometimes I would get the regular (You) reply and the "!" icon on my tab, but recently it has become extremely common for replies to my posts to not have any of these things appear, not even the (You). I have also noticed that threads I create are sometimes not put onto my watchlist like they used to be, and replies to the OP of my thread would not show any indication that they're in response to me either.

I am using Cyberfox.

**Comment by ccd0** [comment]
> Instead there is an orange notification on the top that repeatedly pops up saying how many seconds until I can post again.

Do you have a screenshot of this? Are you using any other extensions?

**Comment by Icarus77** [comment]
I uninstalled 4chan X completely (apparently had a beta build installed) and installed the latest stable version. Works fine now.

**Comment by ccd0** [comment]
There isn't a new beta build out at the moment, so that shouldn't make any difference, but glad to hear you fixed it, however it happened.
