### ISSUE TITLE
Thread new posts not working

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1339]
The option at the bottom of the page to thread new posts is gone and posts aren't threading automatically. Resetting settings didn't work.

**Comment by ccd0** [comment]
You need to turn it on in the header menu, not just in the settings panel.

**Comment by rctdude2** [comment]
That fixed it, thanks.
It seems like it messed up when I clicked a toggle button to show replies in a 1000+ reply thread, not sure if that's something that needs to be fixed.
Here's the one, for reference: https://boards.4chan.org/tg/thread/52705335

**Comment by ccd0** [comment]
If you're in a thread where it only shows the last N replies, that turns quote threading off in that thread (since the features aren't compatible at this point), but it shouldn't affect other threads, and you can turn it back on from the menu.
