### ISSUE TITLE
4chanX hiding threads and replies for no reason

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1340]
Submitter: Bob Jones
When i went to 4chan today to the catalog of any board, 90% of the threads are hidden, showing only one row of threads. when i click on a thread, all the replies are hidden and i have to click each one individually to view anything. this has never happened before

**Comment by ccd0** [comment]
Check your filters first, and if you don't find a filter causing the problem, export and upload your settings so I can check them.

**Comment by Tenome** [comment]
Since this randomly happened to me, here are my settings for it. Dunno if the issue will be replicated though.
https://z.zz.ht/BLojD.json

**Comment by ccd0** [comment]
In your Name filters it looks like you are filtering all Anonymous posters.
