### ISSUE TITLE
quick reply: captcha iframes don't get removed, wasting memory

### ISSUE THREAD

**Issue by epicgirl1998** [ccd0/4chan-x#1341]
4chan-x version `1.13.8.5`, tested in chrome and a fresh install of firefox with and without other extensions

#### reproduction steps:

1. open the quick reply
2. press "captchas: 0" to load a captcha
3. wait until the captcha loads and focuses itself (checkbox becomes blue)
4. press "captchas: 0" again to hide it (or just complete it)
5. maybe repeat steps 2-4 a couple times for good measure

or: just post in a thread multiple times using the clicky captchas and the quick reply

#### expected result:

after a captcha is completed or hidden, it should be removed from the document so there should be little to no memory impact from repeating the steps (browsers have this thing called garbage collection)

#### what actually happens:

the element added by a captcha (that contains an iframe!) is **>>NOT<<** removed when the captcha is completed or hidden, so every time you hide or complete a captcha it needlessly increases the tab's memory usage

---

[i took this screenshot of the elements (i should've expanded one to show the iframe in it but f*ck it)](https://files.catbox.moe/znvkkv.png)

the memory problem is probably worse if you use (m)any browser extensions that run in iframes

it was in chrome with several extensions installed but the tab for a thread i had made several posts in along the day had its memory usage drop from 550MB to 141MB after i manually removed the elements

> 7. Test if the bug occurs using the **native extension** with 4chan X disabled. If it does, it's likely a problem with 4chan or your browser rather than with 4chan X.

the native extension gets this right and removes the elements when the quick reply is closed

**Comment by ccd0** [comment]
Can you check if the latest beta version (v1.13.9.1) fixes it?

**Comment by epicgirl1998** [comment]
yes!

it's all fixed now
