### ISSUE TITLE
4chan X's post timer is occasionally frozen on Firefox + Unread Post Bug

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1342]
Submitter: James
USERSCRIPT MANAGER --> Greasemonkey (3.10)
BROWSER                       --> Mozilla Firefox (53.0, 32-bit)
SCRIPTS                          --> 4chan X (1.13.9.0)

The bug tends to happen when I attempt to post after having recently made another post. The post timer that replaces the SUBMIT button is supposed to countdown, but it stays frozen on a number. For example, the countdown commonly freezes at 59 seconds, and clicking it puts it onto Auto 59 seconds, but changes nothing still. The only clear I have is to refresh the entire page after making a post to avoid a frozen timer on the next post. 
Sometimes, I switch a tab while the timer counts down, return, and it's frozen again despite the fact that it was working fine moments before. The most consistent thing about the bug for me is that it always happens when I reply to a post or make a post, forcing me to refresh the page. The bug does not occur on the native extension, and occurs regardless of custom options on 4chan X. Checking the console also brings up no reports.

The second problem is that occasionally, when a thread updates with new posts, the unread count will still show on the tab despite the posts being read already. I haven't found any specific trigger to this, but I've noticed that it happens way more often on Firefox than it does on Chrome. Almost every couple of posts causes the bug, whereas in Chrome it was incredibly rare.

If it helps, I just recently switched from Google Chrome, where I was using 4chan X for months with no post timer bug.

**Comment by ccd0** [comment]
Moved the main issue to #1323.

Regarding
> The second problem is that occasionally, when a thread updates with new posts, the unread count will still show on the tab despite the posts being read already. I haven't found any specific trigger to this, but I've noticed that it happens way more often on Firefox than it does on Chrome. Almost every couple of posts causes the bug, whereas in Chrome it was incredibly rare.

this might happen if you have both http: and https: versions of the tab open, or cookies disabled.

**Comment by ccd0** [comment]
Second issue goes to #594.

**Comment by ccd0** [comment]
I just pushed a workaround; let me know if it's working.

**Comment by h633537** [comment]
The timer has frozen on 1 second quite a few times since updating to 1.13.9.2. This is on Firefox 53 64bit.
