### ISSUE TITLE
Quick reply timer freezes Firefox 53.0 (32-bit), Windows 10 64-bit (creators update)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1344]
Submitter: 2b's ass
With new version of Firefox 53.0 (32-bit), Windows 10 64-bit (creators update) "quick reply" timer is frequently freezing and is not counting down making posting impossible.

**Comment by jabjab** [comment]
I've found that cutting the post content and then pasting it back can fix the timer hanging/allow posting, but that doesn't always work.

**Comment by Irru-** [comment]
Also seems that usernames/tripcodes are removed after posting

**Comment by anonnyj** [comment]
Only reliable way I found is to refresh the page. Not fun!

Also happening on Windows 7 64-bit (Firefox 53.0 (32-bit)).

**Comment by jabjab** [comment]
This is just a hunch, but I suspect this may be a Greasemonkey issue
related to changes to Firefox internals due to the multiprocess push.

**Comment by throwaway666** [comment]
this has been an issue for a few days, no new updates. creator busy or abandoned project?

**Comment by ccd0** [comment]
Had trouble reproducing it at first, but seeing it now. Not sure if there's anything I can do from my end other than try to narrow down the bug to something I can report to the Greasemonkey repo. If you need to, you can downgrade Firefox or see if Tampermonkey works.

**Comment by ccd0** [comment]
Duplicate of #1344.
