### ISSUE TITLE
"Use Recaptcha v1 in Reports" not working when reporting thread on catalog

### ISSUE THREAD

**Issue by h633537** [ccd0/4chan-x#1346]
Since v1.13.9.0 I'm getting the image captcha instead of text captcha on the report page with "Use Recaptcha v1 in Reports" enabled. This only happens when reporting a thread from the catalog view.

I'm using Firefox 53 with greasemonkey.

**Comment by h633537** [comment]
I just noticed this only happens when reporting threads from the catalog. Not when in a thread and reporting a post.

**Comment by throwaway666** [comment]
happening to me in the 'view all pages' mode too when replying to a thread

**Comment by ccd0** [comment]
Can you post the URL of the page you were on and the URL of the reporting window?

**Comment by h633537** [comment]
Reporting from catalog: https://boards.4chan.org/g/catalog
Report URL: https://sys.4chan.org/g/imgboard.php?mode=report&no=60119490 (image captcha)

Reporting from inside thread: https://boards.4chan.org/g/thread/60119490
Report URL: https://sys.4chan.org/g/imgboard.php?mode=report&no=60119490&altc=1 (text captcha)

**Comment by EroticSpork** [comment]
Similar bug here, and can't submit posts/reports even with a successfully completed captcha

**Comment by ccd0** [comment]
@EroticSpork
What version are you on?

**Comment by EroticSpork** [comment]
1.13.8.7

The issue only appears on the catalogue, from any thread I am still able to reply using the legacy captcha

**Comment by ccd0** [comment]
@EroticSpork
You can't create threads with the legacy captcha; that's a change on 4chan's end.
Can you open a new issue with a detailed description of the problem you're having? Since you're on stable, it's not related to this issue.
