### ISSUE TITLE
clicking 2nd post link removes all newlines

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1351]
When I click a 2nd post ID after writing a reply to the first, and pressing enter, the newlines disappear and the 2nd post link is inserted directly below the last text 

This has only started happening in the last few days, after the last update. I have not added or changed any extensions. I'm on chrome

**Comment by epicgirl1998** [comment]
it's a chrome bug:

https://bugs.chromium.org/p/chromium/issues/detail?id=714425

**Comment by epicgirl1998** [comment]
blog update: chrome 59 which contains the fix [is now in stable](https://chromereleases.googleblog.com/2017/06/stable-channel-update-for-desktop.html) so the issue can be closed

i installed the update and the bug is gone
