### ISSUE TITLE
LaTeX not working on /sci/

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1356]
Submitter: a
The [math] [/math] tags suddenly stopped working with last update and look like this http://i.imgur.com/VDYwxH5.png

**Comment by krackers** [comment]
I can confirm that this doesn't work. Disabling 4chanx allows it to work again. Seems to have started within the last month or so?

**Comment by ccd0** [comment]
Confirming, it's due to a hosting change in the MathJax script. Will push out a fix shortly.

**Comment by krackers** [comment]
Ah right that definitely makes sense. I remember reading about that: MathJax was shutting down their own cdn

**Comment by ipatrol** [comment]
Has this version still not gone live yet?

**Comment by ccd0** [comment]
This issue was resolved some time ago. If you are having issues with LaTeX on /sci/ now, you should open a new issue. But check if it works with 4chan X disabled. You may be having issues with the new ad filters recently added.
