### ISSUE TITLE
Can no longer expand pictures within the thread

### ISSUE THREAD

**Issue by ArchangelPT** [ccd0/4chan-x#1358]
Or better yet i can but it also opens a new tab with the picture and it's quite annoying

Tried reinstalling, i was using the base version from the chrome store. After that i uninstalled completely and tried 1.13.9.2 but the issue persists.

I use the latest chrome and here's a list of all my extensions

> 4chan X 1.13.9.2
> Cross-browser userscript for maximum lurking on 4chan.
> Detalhes
>   
> Adobe Acrobat 15.1.0.6
> Converter página da Web atual em um arquivo Adobe PDF (apenas para Windows)
> Detalhes  Opções
>   
> AlienTube for YouTube™ 2.6
> Reddit Comments for YouTube
> Detalhes  Opções
> 
> Apresentações Google 0.9
> Criar e editar apresentações
> Detalhes
> 
> Checker Plus for Gmail™ 20.1.1
> Visualizar novos e-mails, receber notificações via desktop ou ler ou excluir e-mails sem necessidade de abri-los entre
> Detalhes  Opções
>   
> Documentos do Google offline 1.4
> Conclua tarefas offline com a família de produtos do Documentos do Google.
> Detalhes
> 
> Enhanced Steam 9.3
> Enhances the Steam Experience
> Detalhes  Opções
>   
> Flash Video Downloader 28.1.1
> Popular Video Downloader. Downloads most popular media formats like flash, videos, audios etc..
> Detalhes  Opções
>   
> Full Page Screen Capture 2.2
> Capture a screenshot of your current page in entirety and reliably—without requesting any extra permissions!
> Detalhes
>   
> Google Docs 0.9
> Criar e editar documentos
> Detalhes
>   
> Google Folhas de Cálculo 1.1
> Criar e editar folhas de cálculo
> Detalhes
> 
> Moderator toolbox for reddit 3.6.3
> A set of tools to be used by moderators on reddit in order to make their jobs easier.
> Detalhes  Opções
>   
> Pop up blocker for Chrome™ - Poper Blocker 4.0.3.1
> #1 Extensão para bloquear popups, popunders e sobreposições irritantes de maneira fácil e eficaz. Navegue sem interferência em todos os sites.
> Detalhes  Opções
>   
> Reddit Enhancement Suite 5.6.1
> A suite of modules that enhance your Reddit browsing experience
> Detalhes  Opções
>   
> Reddit Trading Flair Linker Enhanced 1.14.403.1
> Adds additional functionality to flair on trade subreddits (SteamGameSwap, tf2trade, and Dota2Trade)
> Detalhes
>   
> RSS Feed Reader 5.6.6
> Get a simple overview of your RSS and Atom feeds in the toolbar
> Detalhes
>   
> Search by Image (by Google) 1.5.2
> This extension allows you to initiate a Google search using any image on the web. By the Google Images team.
> Detalhes  Opções
> 
> Ativada
>   
> Speed Dial 2 2.1.3
> Speed dial 2 is ultimate replacement of new tab page with quick access to your most visited pages, bookmarks and browsing history.
> Detalhes  Opções
>   
> Steam Inventory Helper 1.10.9.1
> Ofecere muitas utilidades para o inventário e mercado da Steam (notificações de ofertas, venda rápida, compra, ofertas de trocas, checagem de preços)
> Detalhes  Opções
>   
> TunnelBear VPN 1.2.12
> Rawwwr! Put a Bear in your browser and experience a more open and private Internet in seconds!
> Detalhes
>   
> uBlock Origin 1.12.1
> Finalmente, um bloqueador eficiente. Leve na CPU e memória.
> Detalhes  Opções
>   
> uBlock Origin Extra 2.23
> A companion extension to uBlock Origin: to gain ability to foil early hostile anti-user mechanisms working around content blockers.
> Detalhes
> 
>

**Comment by ccd0** [comment]
Does it still happen if you turn all of those extensions off? If not, please locate the extension causing the conflict by progressively turning them back on.

**Comment by ArchangelPT** [comment]
I feel stupid for not having thought to do that sooner. For the record the problem was the popup blocker, i just added 4chan to the whitelist and it solved the problem.

Thank you for the help.
