### ISSUE TITLE
Embed links don't give the option to unembed

### ISSUE THREAD

**Issue by saxamaphone69** [ccd0/4chan-x#1362]
Windows 10, Chrome 58, 4chan X 1.13.8.6

Only noticed this today/yesterday.

1. Find a YouTube/Twitter embed
2. Click (embed)
3. (embed) doesn't switch to (unembed)

Not sure if related, but 4chan recently added [ads served via Service Workers](https://boards.4chan.org/qa/thread/1315145), so that could be causing issues?

**Comment by ccd0** [comment]
Works for me. Any specific URLs where it's failing?
Also, do you have either of `Auto-embed` or `Floating Embeds` turned on?

**Comment by saxamaphone69** [comment]
So far, any YouTube link or Tweet.

I just toggled the settings around, it fails with `Floating embeds` on, but works with it turned off.

Nothing in the console, although, when I'm on the 'Sources' tab in the Dev Tools, with `Floating embeds` off I see the YouTube URL appear upon embed, and disappear upon unembed. But with `Floating embeds` on, it appears, and then clicking any other (embed) link adds it to the list.

**Comment by ccd0** [comment]
That's how it's always worked with `Floating embeds`. You can close it with the "x" in the window.

**Comment by saxamaphone69** [comment]
Oh... I could've sworn I was able to hit (unembed) to also close the floating window. Never mind then!
