### ISSUE TITLE
/qa/ and /trash/ lack [current-title] support

### ISSUE THREAD

**Issue by Yaanu** [ccd0/4chan-x#1366]
In Custom Board Navigation settings, you can set up quick-links to the two hidden boards, /qa/ (Question & Answer) and /trash/ (Off-Topic). However, 4chan X does not have support to display their titles when requested in the settings; they only appear as their short-names of "qa" and "trash".

**Comment by Yaanu** [comment]
(i have no idea if i can add labels, but if i could i'd say it's an annoyance.)

**Comment by saxamaphone69** [comment]
#384 and #642 explain what is going on (4chan X loads the board list from the original board list element, as opposed from externally à la `//a.4cdn.org/boards.json`).

**Comment by Yaanu** [comment]
Oh, whoops, my bad. Thanks for the backlinks!
