### ISSUE TITLE
Suggestion - Prune Dead Threads Button on the Thread Watcher

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1371]
I'm sure many use the thread watcher and many of us want to see replies even after a thread dies, so I think it'd be more convenient to have a button (maybe next to the Check Threads button) to prune dead threads since it's used so often instead of having to click the arrow>prune dead threads. 

I figure I would suggest this since 4chan X is all about convenience.

**Comment by saxamaphone69** [comment]
I believe this has been implemented.
