### ISSUE TITLE
Porblem after uninstall

### ISSUE THREAD

**Issue by darcain** [ccd0/4chan-x#1377]
I uninstalled 4chanX after barely using it and I can't post anymore when clicking on a number, I can't view posts of quoted numbers unless I click on it

I don't know if I missed something, I used CCleaner afterwards and the problem is still there

**Comment by ccd0** [comment]
https://github.com/ccd0/4chan-x/blob/master/README.md#please-note
Uninstalling: 4chan X disables the native extension, so if you uninstall 4chan X, you'll need to re-enable it. To do this, click the [Settings] link in the top right corner, uncheck "Disable the native extension" in the panel that appears, and click the "Save Settings" button.

**Comment by darcain** [comment]
I unchecked it and then uninstalled but I still cannot post now

**Comment by ccd0** [comment]
Make sure you click the save button, also you need to do it separately for http and https.

**Comment by darcain** [comment]
I feel stupid, I can't find the save button

**Comment by ccd0** [comment]
Your ad blocker may be blocking it.

**Comment by darcain** [comment]
you're right, it was my adblock all along ! thanks alot for your help, it would have been more frustrating without

have a nice day
