### ISSUE TITLE
Captcha v2 broken

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#1378]
When all legacy captcha settings are disabled, I am unable to submit any replies. When legacy settings are on, replies work fine. I've tested most possible combinations of captcha settings, and am completely unable to get v2 to work. Other sites that use v2 are fine, as is 4chan with the extension disabled.

**Comment by EroticSpork** [comment]
Version is 1.13.8.7

**Comment by ccd0** [comment]
Can you export and post your settings? Also, do you have any extensions or settings that are or might be changing the referrer?

**Comment by EroticSpork** [comment]
Referrer is on, tried disabling all non-gm extensions. Can't upload .json, how would you like me to submit it?

**Comment by ccd0** [comment]
You should be able to just rename it to .txt.

**Comment by EroticSpork** [comment]
[4chan X v1.13.8.7-1495431822335.txt](https://github.com/ccd0/4chan-x/files/1017849/4chan.X.v1.13.8.7-1495431822335.txt)

**Comment by ccd0** [comment]
Also, what's your browser and browser version?

**Comment by ccd0** [comment]
You have v1 turned on everywhere in those settings. If you want to use v2, you need to turn the appropriate "Use Recaptcha v1..." checkboxes off.

**Comment by EroticSpork** [comment]
FF Nightly 55.0a1 (2017-05-20)

**Comment by EroticSpork** [comment]
Yes, the issue only appears when v2 is turned on. I tried all combinations of those settings and none allowed v2 to work.

**Comment by ccd0** [comment]
Can you post the settings where you have the problem then? And tell me what page you are posting from, whether you are posting a new thread or a reply, and what if any error messages you get.

**Comment by ccd0** [comment]
Also, do you know if this happens in stable/beta/developer Firefox? Nightly generally has a lot of bugs.

**Comment by EroticSpork** [comment]
The v2 errors appear any time I try to post, start a new thread, report, basically any action requiring a captcha 

The exact error is "No valid captcha.". This is after completing the captcha and hitting submit. 

Will attempt to replicate in stable firefox
[4chan X v1.13.8.7-1495433367983.txt](https://github.com/ccd0/4chan-x/files/1017876/4chan.X.v1.13.8.7-1495433367983.txt)
.

**Comment by EroticSpork** [comment]
Issue is replicable in 53.0.3 (latest stable release, 64 bit) and reconfirmed with all extensions disabled.

**Comment by ccd0** [comment]
Does it happen in a fresh profile?

**Comment by EroticSpork** [comment]
Not replicable in a new profile. Not sure what could be causing it then.
