### ISSUE TITLE
Random Captcha error.

### ISSUE THREAD

**Issue by NaturalHarmonia** [ccd0/4chan-x#1388]
![screenshot 36](https://cloud.githubusercontent.com/assets/16900516/26520839/25a89b70-42a0-11e7-9121-ec2aa26fe79f.png)

I tried uninstalling and then installing again but it didn't work.

**Comment by Nusharik** [comment]
I believe this may be a 4chan error and not dependent on 4chanx but I cannot say.

**Comment by ferongr** [comment]
I can confirm the error too.

**Comment by ferongr** [comment]
It fixed itself now, (probably server related).

**Comment by NaturalHarmonia** [comment]
Thank you, both of you.
