### ISSUE TITLE
qa-replace in header doesn't show board title

### ISSUE THREAD

**Issue by lc-guy** [ccd0/4chan-x#1390]
![](http://gateway.glop.me/ipfs/QmWo22LyQi6DkKeTzb3s69hXN75Uvr5WF1z1t3VACB69cr/TApzZz.png)

v1.13.9.3
oneechan also used

**Comment by saxamaphone69** [comment]
https://github.com/ccd0/4chan-x/issues/1366#issuecomment-301650449

**Comment by lc-guy** [comment]
Whoops
>I've reported this inconsistency to them.
Anyway, it seems that hasn't been updated since then, so maybe a hotfix of some sorts could be put in place?

**Comment by ccd0** [comment]
Closing as duplicate of #384.
