### ISSUE TITLE
Submit counter randomly stops at 1 disallowing posting.

### ISSUE THREAD

**Issue by nezumisama** [ccd0/4chan-x#1394]
I have an issue in that the counter on the QR window (the one on the submit button) sometimes stops at one and doesn't change to submit, making me unable to submit a reply. Refreshing the tab temporarily solves the problem.

**Comment by saxamaphone69** [comment]
Sounds like the same issue as #1323, which is a result of a Greasemonkey and Firefox 53 compatibility issue.

**Comment by nezumisama** [comment]
That might be it.
For reference, my GM is 3.11, FF 53.0.3.
