### ISSUE TITLE
Banners don't work: feature or bug?

### ISSUE THREAD

**Issue by Talcon** [ccd0/4chan-x#1395]
With the banner contest over, I think it'd be cool to see them on the boards I visit, but I don't see option to turn them on in 4chan X settings. Was there just no way to make them work with 4chan X?

**Comment by saxamaphone69** [comment]
This may be a result of your adblocking extension (disable it and see if they now appear), as the contest banners are within the `.middlead` element. You'd have to create an exception.

**Comment by Talcon** [comment]
ah, I figured it out. It was Oneechan user script. Thank you for your time - and advice.
