### ISSUE TITLE
New flags on /pol/ don't work

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#1403]
/pol/ has reverted to the option to choose what flag to post with, which seems to have broken the script. Not all of the flags are visible, and there is no option box to pick which one to post as.

**Comment by ccd0** [comment]
Working on it. More than just a revert, there's now a mix of troll and country flags we have to deal with.

**Comment by ccd0** [comment]
Updated beta version, will update stable shortly if everything seems to be working.

**Comment by ccd0** [comment]
Updated the stable version as well. There should be more updates forthcoming to get archive stuff working, but posting with and viewing /pol/'s custom flags should work now.
