### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by NaturalHarmonia** [ccd0/4chan-x#1404]
Sometimes when I stay off 4Chan for a while and go to a catalog for any board the catalog will look as if I don't have 4Chan X installed. I usually just have to wait a few minutes and refresh the page and it'll be back to the way it's supposed to be. The Catalog Hover Expand doesn't work either when it's like this. Just curious if this is normal. Here's a
![screenshot 40](https://user-images.githubusercontent.com/16900516/27088666-ed176a9e-501d-11e7-94d8-8ffd4a368dc7.png)
 picture.

**Comment by ididntknowicoulddothatXD** [comment]
You're on https://boards.4chan.org/v/catalog, this is the native link. If you want to use 4chan X' catalog, you will have to use https://boards.4chan.org/v/#catalog.
