### ISSUE TITLE
Anyway to have post reply number links return to being smaller text, different color and underlined?

### ISSUE THREAD

**Issue by YoshiYogurt** [ccd0/4chan-x#1406]
Might be from so much time without 4chan X but it looks much nicer when the reply links are underlined and a separate font size and color form the actual post number. Can't seem to find the setting to revert this change

In the images, compare with and without 4chan X.

![screen shot 2017-06-13 at 11 46 34 pm](https://user-images.githubusercontent.com/29419835/27114634-011d5f4c-5093-11e7-83f8-fb4c29c8a91a.png)
![screen shot 2017-06-13 at 11 47 55 pm](https://user-images.githubusercontent.com/29419835/27114652-0ef80e5a-5093-11e7-895b-a1e15e9d3e98.png)

**Comment by saxamaphone69** [comment]
In the Custom CSS you could always add something like:

```css
.backlink {
  font-size: 90%;
  text-decoration: underline;
}
```

or such to recreate the effect.

**Comment by YoshiYogurt** [comment]
I will try that, thank you! Only seems to be a problem on blue boards(which I use the most), the beige/tan boards have the backlinks as a nice bright blue.
