### ISSUE TITLE
A general is invisible to the 4chan X catalog

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1407]
Currently on /vg/ if you search mhg, Monster Hunter General does not show up at all. Despite having a subject and tag guaranteeing it should. This only began recently after the announcement of a new game, so I'm thinking something in the thread's copy pasta actually causes a problem in 4chan X's catalog. It would be nice if you could determine what exactly.

**Comment by saxamaphone69** [comment]
Works on my machine.

![literally works fine](https://user-images.githubusercontent.com/877480/27214089-e60dae74-52ad-11e7-969a-80ba0f43a1f5.jpg)

What browser are you using? What version of 4chan X are you using? Do you have any other extensions running - does it happen with them off? Are there any errors in the console?

**Comment by ccd0** [comment]
In addition to what he said, check that the thread isn't being hidden by one of your filters.

**Comment by Anyonymous** [comment]
Thanks for realizing it could be a filter. That's what I get for having this:

/ofwgkta/i;op:only
/earl/i;op:only

earl was picked up as part of "early". I could delete this filter of course, but am curious if there's a proper way to parse it.

**Comment by ccd0** [comment]
`\b` matches a word break, so if you want to match only the whole word "earl" (case insensitive), change `/earl/i` to `/\bearl\b/i`.

**Comment by Anyonymous** [comment]
Thanks, and feel free to close this issue!
