### ISSUE TITLE
Matching non-stub name filter overrides stub:no on tripcode filters

### ISSUE THREAD

**Issue by DrLore** [ccd0/4chan-x#1414]
If you activate the default name filter to collapse namefag posts:

/^(?!Anonymous$)/

Then try and filter a post by a non-Anonymous user with a tripcode with no stub (e.g. by doing Filter > Tripcode and adding ;stub:no to the end then refreshing the page), their post stub will not be removed. Commenting out the name filter and refreshing the page will then remove the stub of their posts correctly.

**Comment by ccd0** [comment]
Thanks for reporting. This should be fixed now. Let me know if it isn't.
