### ISSUE TITLE
"Image/video appears corrupt"

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1417]
4chan X version 1.13.8.8
FF version 48.0.2

Any image or video submitted, even ones I've posted before, now generate a "Image appears corrupt" error message.  Just started this morning a few hours ago, and was posting happily maybe a day ago.  Might be on their end...?

**Comment by krackers** [comment]
Something similar happens when I try to upload an image by copying it in. Whereas before it would upload and show a nice thumbnail, not it shows something like:

![image](https://user-images.githubusercontent.com/20675996/27463505-e7e42452-577c-11e7-9ea0-f48331eac45f.png)

And submitting the post fails.

**Comment by ccd0** [comment]
Any errors in the console (also check the browser console -- Shift+Control+J if Firefox)? What browser and version? Does it happen in a fresh profile?

**Comment by krackers** [comment]
@ccd0 No, Chrome 59.

I'm getting the following:

`boards.4chan.org/:1 Refused to load the image 'blob:https://boards.4chan.org/7d1ce5a3-ef2a-43ff-8a7f-54245b2f4376' because it violates the following Content Security Policy directive: "default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by anonwhatever** [comment]
>EDIT 2: It turns out adblock was the reason for this. My issue is therefore invalid.
>
>The easylist filter includes the following: *$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'. I can unblock this manually for 4chan.

>I can unblock this manually for 4chan.

how? 

i don't know how to do that. 

![how 72 x124 1323132968001](https://user-images.githubusercontent.com/29671613/27506638-c71b9108-58ab-11e7-816f-28403131d4ff.png)


i'm also having this issue. 

>firefox portable esr 38.7.1
>4chan x 1.1.13.8.8
>adblock plus 2.8.2
>easylist 20170624

>post any image
>"x.png: Image appears corrupt
[delete post] [delete all]"

there's no preview of the image in the image queue. 

i can still post the images. 

yeah, but it's still a pain. 

the main issues with this; if they're not obvious. 

>can't see previewed images in image queue
>you get flooded with - 
>"x.png: Image appears corrupt"
>"[delete post] [delete all]"
>every time you queue an image

i can't disable filters individually for individual sites on adblock. or it's not immediately obvious to me. 

i can click on the adblock icon and select "disable on boards.4chan.org" when i'm on the thread page. 

i can use ublock, noscript, ghostery, peerblock portable, etc. instead. 

but i'd like to have adblock remain on for this page and every page. 

i'd like to know know how to do this. just in case if it's needed in the future. or if anyone doesn't want to - or can't - run more than adblock, etc.. 


also i was having issues uploading an image to post on here. 

>drag and drop an image
>"something went really, really wrong"
>manually browse and upload image
>"something went really, really wrong"
>turn off adblock
>manually browse and upload image
>works
>drag and drop an image
>"something went really, really wrong"
>turn adblock back on
>go to a new page
>can upload images here normally

i don't know what the hell is going on with that. but. just in case that's related. putting it out there. 


too long; didn't read: 

>EDIT 2: It turns out adblock was the reason for this. My issue is therefore invalid.
>
>The easylist filter includes the following: *$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'. I can unblock this manually for 4chan.

>I can unblock this manually for 4chan.

how? 


thanks to ccd0 for keeping this issue open. 

please help me.

**Comment by xFears** [comment]
I have the same issue. Chrome 59 with uBlock Origin

>Refused to load the image 'blob:http://boards.4chan.org/1bbb1dcb-7a52-48e7-b4f8-596f48f4cca7' because it violates the following Content Security Policy directive: "default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

core.1012.js:26 Uncaught TypeError: o.hasAttribute is not a function
    at HTMLDocument.onMouseOver (core.1012.js:26)
onMouseOver @ core.1012.js:26

**Comment by ABearWithAGun** [comment]
To fix this, add this to your custom filters
`@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'`

**Comment by ccd0** [comment]
> To fix this, add this to your custom filters
> `@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'`

This works but it would be a good idea to report this to https://forums.lanik.us/viewforum.php?f=64.

**Comment by JackJohnJoe** [comment]
> To fix this, add this to your custom filters
@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'

I am using ABP. I did exactly that, restarted the browser (Firefox), it's not working.

**Comment by d3athrow** [comment]
I am receiving the same issue as of a few days ago and it still persists with every addon except greasemonkey disabled.
FF v55.0b3
```
Content Security Policy: The page’s settings blocked the loading of a resource at blob:http://boards.4chan.org/dc8c26b2-6be2-4da7-ae23-cee12c91111d (“default-src http://boards.4chan.org * data: 'unsafe-inline' 'unsafe-eval'”).
```

**Comment by ccd0** [comment]
@d3athrow
That's very odd, since that specific setting in your error message is known to come from EasyList. I would double check that you are seeing it with your ad blocker off. Maybe you forgot to reload the page?

**Comment by ccd0** [comment]
@JackJohnJoe
For ABP use
`@@|blob:$domain=4chan.org`

**Comment by ccd0** [comment]
`@@|blob:$image,domain=4chan.org`
if you want to be more specific. Not sure precisely what it's blocking, probably something related to the obfuscated ad script now included in the page itself.

**Comment by d3athrow** [comment]
@ccd0 
![ublock disabled](http://ss13.moe/uploads/firefox_2017-06-28_17-11-29.png)

**Comment by ccd0** [comment]
If you have uBo on at all, you need to add the filter in https://github.com/ccd0/4chan-x/issues/1417#issuecomment-310836943. Whitelisting 4chan won't work.

**Comment by ccd0** [comment]
I think the previous reply is wrong as whitelisting without adding the filter appears to work for me. Filter still the best approach, though.

**Comment by d3athrow** [comment]
Filter fixed it for me, thanks.

**Comment by phaux** [comment]
Anybody reported it to ublock/adblock plus devs yet?

**Comment by krackers** [comment]
@phaux It's not a ublock issue. It's a filter issue.

**Comment by phaux** [comment]
@krackers ...and they bundle these filters by default

**Comment by Lapan** [comment]
ABP Filter works for images but not for WEBM's

**Comment by ccd0** [comment]
@Lapan
Try
`@@|blob:$image,media,domain=4chan.org`

**Comment by AssCrab** [comment]
I have this problem too. Every time i dump an image to upload, the notification comes up that
"Corrupt image or error reading metadata."; but when i ignore the notification and just continue on to
 post it, it posts successfully.

**Comment by aathrowaway** [comment]
Copy/pasting the comment in #1447 into ublock origin didn't work for me. It wouldn't accept it.

**Comment by deadman3000** [comment]
The problem is back and none of the above fixes it.

**Comment by ccd0** [comment]
@deadman3000
Are you sure you have the recommended filter set? uBlock Origin recently switched to the WebExtensions system causing all users' settings to be reset.

**Comment by ccd0** [comment]
#1441
Submitter: Some Anonymous Guy
Whenever I try to post an image regardless of file extension the message "X.jpg/png/gif: Corrupt image or error reading metadata. [More info]
[delete post] [delete all]" pops up. At first I thought it was just a problem on my end (and panicked because I thought my 4chan folder was corrupt) but later on I saw other users have the same complaint. 
I've tried adding "@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'" to ublock origin at the suggestion of another user that managed to solve his problem by doing so but it still didn't work. 
I've also tried updating to the newest 4chanX release but it still displayed the same message. 
Also, my post timer gets sometimes stuck at either 5 or 12 seconds, closing the reply form and reopening it seems to solve the issue but it's been happening more frequently lately. 
Any suggestions on what could be wrong?

Kein:
Same here, Vivaldi 1.1x, latest 4chanX, all Webms show this error

**Comment by tidux** [comment]
The uBlock, Origin filter no longer works on nightly.  This makes 4chanX completely unusable since I'm not turning off uBO entirely with the coin mining scripts around.

**Comment by tidux** [comment]
I've had issues with Tampermonkey on Firefox (although oddly, not on Edge).  Try Violentmonkey 

On August 26, 2018 3:20:52 PM PDT, lakitu13 <notifications@github.com> wrote:
>Just updated from FF52 ESR to FF61 and got that, and @tidux 's filters
>didn't fix it.
>uBO, tampermonkey beta.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/ccd0/4chan-x/issues/1417#issuecomment-416076950

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lakitu13** [comment]
I've tried Violentmonkey before on FF52 but it made the browser really slow. Anyway, I tried Violentmonkey and I still get the corrupted message.
