### ISSUE TITLE
"Image/video appears corrupt" Yep, it was AdBlock Plus

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1420]
Thanks other guy.  Disabling ABP solved the problem.  Thanks and sorry for the multiple posts.

**Comment by Nusharik** [comment]
Is there anyway for me to manually fix it on my end so I can still keep ABP on?

**Comment by geldimedov** [comment]
i get the same error but it doesnt stop me from posting the image.

**Comment by ccd0** [comment]
@Nusharik
see https://github.com/ccd0/4chan-x/issues/1417#issuecomment-310836943
