### ISSUE TITLE
4chanX displays "metadata error or corruption" error message when posting images

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1441]
Submitter: Some Anonymous Guy
Whenever I try to post an image regardless of file extension the message "X.jpg/png/gif: Corrupt image or error reading metadata. [More info]
[delete post] [delete all]" pops up. At first I thought it was just a problem on my end (and panicked because I thought my 4chan folder was corrupt) but later on I saw other users have the same complaint. 
I've tried adding "@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'" to ublock origin at the suggestion of another user that managed to solve his problem by doing so but it still didn't work. 
I've also tried updating to the newest 4chanX release but it still displayed the same message. 
Also, my post timer gets sometimes stuck at either 5 or 12 seconds, closing the reply form and reopening it seems to solve the issue but it's been happening more frequently lately. 
Any suggestions on what could be wrong?

**Comment by Kein** [comment]
Same here, Vivaldi 1.1x, latest 4chanX, all Webms show this error

**Comment by ccd0** [comment]
Merging to #1417, but needs more detail. Adding that filter should fix it, but maybe you did something wrong.

For
>Also, my post timer gets sometimes stuck at either 5 or 12 seconds, closing the reply form and reopening it seems to solve the issue but it's been happening more frequently lately.

see
https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions#im-using-4chan-x-with-firefox-53-and-greasemonkey-why-am-i-seeing-bugs-such-as-the-cooldown-timer-freezing-or-my-settings-not-saving
