### ISSUE TITLE
Can't post webm, ".webm: Corrupt video or error reading metadata."

### ISSUE THREAD

**Issue by zackultimate** [ccd0/4chan-x#1442]
I already solved the imagine problem by adding 

>@@|blob:$image,domain=4chan.org

To addblock.

What's the solution for webm?

**Comment by ccd0** [comment]
Try
`@@|blob:$image,media,domain=4chan.org`

**Comment by Poilaucul** [comment]
I have the same issue, I have uBlock Origin

**Comment by ccd0** [comment]
For uBlock Origin use
`@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'`
see
https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions#error-reading-metadata

**Comment by ccd0** [comment]
merging into #1417
