### ISSUE TITLE
Resolution in gallery mode

### ISSUE THREAD

**Issue by DeckardEdward** [ccd0/4chan-x#1455]
So I'm picking through /wg/ looking for new wallpapers at the moment, and I'm scrolling through in gallery mode so I can actually see things, but I'm having to bail out of gallery mode whenever I find something I like so I can see the image's resolution on the post info. Any chance that gallery mode could have an element added to show a given image's resolution for the sake of streamlining wallpaper collection, among other tasks?

**Comment by saxamaphone69** [comment]
#198
