### ISSUE TITLE
Tab post numbers dont reduce as you scroll down a thread

### ISSUE THREAD

**Issue by BondiBear** [ccd0/4chan-x#1460]
This started with Firefox 55. 4chanx 1.13.10.5
Open a new thread, number of total post in tab for example 5 (see pic).
As you scroll down, the number in the tab remains at 5.
It doesn't decrease to 4,3,2...0 as you scroll down the thread.

![4cx](https://user-images.githubusercontent.com/2057221/29127315-06341bfa-7d21-11e7-9077-a100de00d1be.PNG)

**Comment by ccd0** [comment]
Does it happen in Firefox ESR?

**Comment by BondiBear** [comment]
Don't know about ESR, but Tabmixplus has just updated, maybe that was causing the issue.
I'll see how it goes - I'm cautiously optimistic.

**Comment by BondiBear** [comment]
I've noticed that it might be that when a post in the thread is deleted, the post counter freezes.

**Comment by BondiBear** [comment]
Just switched from Greasemonkey to Webextension Tampermonkey.

Maybe the issue was with FF55 and GM.

Looks good so far.

**Comment by BondiBear** [comment]
yeah, seems GM was the cause.
