### ISSUE TITLE
Pass question

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1465]
Submitter: Dustin Peterson
Email: Flipback012@gmail.com
Hi i dont mean to be a bothe but i'm just wondering where i put in  my info for the 4chan pass that i just bought, into 4chan x. if its not possible or im looking in the wrong place just send an email with the instructions. thank you

**Comment by saxamaphone69** [comment]
In the Settings, there is an option: `Pass Link: Add a 4chan Pass login link to the bottom of the page.`, which you'll then find near the style selector at the bottom of the page.

Alternatively, https://sys.4chan.org/auth is what you're after.
