### ISSUE TITLE
[Question] What's the class of the div rendered when hovering the cursor on a post ID to preview it?

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#1467]
Sorry if I have to use github for this question but I'm working on some CSS edits and I need to know the class of the div rendered when you hover the cursor on a post ID to preview it.

![immagine](https://user-images.githubusercontent.com/11262717/29288699-fc83f4d2-8139-11e7-913c-46b0170958b4.png)
![immagine](https://user-images.githubusercontent.com/11262717/29288865-be05f5a6-813a-11e7-99ca-6ef75a247219.png)

As you can see the font-size is different. This is the script part causing the preview to show:

```
function(e) {
  var boardID, i, len, origin, post, postID, posts, qp, ref, threadID;
  if (($.hasClass(this, 'inlined') && !$.hasClass(doc, 'catalog-mode')) || !d.contains(this)) {
    return;
  }
  ref = Get.postDataFromLink(this), boardID = ref.boardID, threadID = ref.threadID, postID = ref.postID;
  qp = $.el('div', {
    id: 'qp',
    className: 'dialog'
  });
  $.add(Header.hover, qp);
  new Fetcher(boardID, threadID, postID, qp, Get.postFromNode(this));
  UI.hover({
    root: this,
    el: qp,
    latestEvent: e,
    endEvents: 'mouseout click',
    cb: QuotePreview.mouseout
  });
  if (Conf['Quote Highlighting'] && (origin = g.posts[boardID + "." + postID])) {
    posts = [origin].concat(origin.clones);
    posts.pop();
    for (i = 0, len = posts.length; i < len; i++) {
      post = posts[i];
      $.addClass(post.nodes.post, 'qphl');
    }
  }
}
```

And this is my custom CSS part the changes the font-size for posts:

```
div.thread div.postContainer:not(.catalog-container) {
  font-size: 12pt;
}
```

**Comment by saxamaphone69** [comment]
`#qp`, and if you need to be more specific then add some descendant selectors.

Inspect the `#hoverUI` element towards the top of the DOM tree (I think it appears before `.board`) and you'll see the quote preview populate it. You can hover over a post and use the arrow keys to navigate to and expand the element/DOM tree when you have the inspector open.

**Comment by hhiru** [comment]
tha's it. I used the `#hoverUI` tag since there's only one element with that tag. worked just fine.
