### ISSUE TITLE
[Feature Request] Add option to push backlinks to the bottom of the post

### ISSUE THREAD

**Issue by ErraticFox** [ccd0/4chan-x#1469]
Hello, I am purposing a feature to push the backlinks to the bottom of that post. I seen someone mockup in a thread. I've made the JavaScript to do it, but I don't know CoffeeScript currently or which file I'd even include it in. I've attached the Mockup and my code for an example.

```js
var replies = document.getElementsByClassName('thread')[0].getElementsByClassName('replyContainer');

for (i = 0; i < replies.length; i++) {
  
	var id = document.getElementById(replies[i].getAttribute('id')).getElementsByClassName('reply')[0].getAttribute('id');
	
	document.getElementById(id).appendChild(document.getElementById(id).getElementsByClassName('container')[0]);
	
}
```

![image](https://user-images.githubusercontent.com/6486865/29296503-bd85846e-8128-11e7-86de-266eec40a3e0.png)

**Comment by saxamaphone69** [comment]
#101 

I guess I should be flattered?

**Comment by ErraticFox** [comment]
Oh, so this has been a ongoing feature for a while... Has there been any progress on it?

**Comment by ccd0** [comment]
The backlinks code is in
src/Quotelinks/QuoteBacklink.coffee

No, nobody's working on it AFAIK; it's just been a feature request for a while. It's a good idea, though, and I'd accept a pull request (provided everything works correctly, of course).

**Comment by ccd0** [comment]
#101
