### ISSUE TITLE
(You)teens

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#1475]
Requesting an optional setting to turn broken quotelinks into the proper format. It's hard to keep track of conversations thanks to retards being obsessed with imaginary online points.

![chrome_18-08-2017_15-02-58](https://user-images.githubusercontent.com/1091166/29460146-202824e0-8427-11e7-8f4e-10dc12203d87.png)

**Comment by CuntDestroyer** [comment]
I'd like this too, it's a bit of a meme at the moment...

here's a (you).
