### ISSUE TITLE
Quote Previewing error

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#1478]
Crossthread links will not display posts originating in hidden threads on the index if hovered. Quote Inlining will also fail.

![23-08-2017_22-30-32](https://user-images.githubusercontent.com/1091166/29637011-0207c012-8853-11e7-9e4c-e6e44541f6ce.gif)

>Uncaught TypeError: Cannot read property 'ID' of undefined
>    at new Post (script.js:6072)
>    at new Fetcher (script.js:5636)
>    at HTMLAnchorElement.mouseover (script.js:23679)
>Post @ script.js:6072
>Fetcher @ script.js:5636
>mouseover @ script.js:23679

_"It is not visible, so it probably doesn't exist."_

**Comment by ididntknowicoulddothatXD** [comment]
It works if you reach the end of the index when the hidden threads are anchored, yet still visible.

**Comment by ccd0** [comment]
Thanks for reporting. This should be fixed now.

**Comment by ididntknowicoulddothatXD** [comment]
Thanks for fixing.
