### ISSUE TITLE
"no valid captcha" after trying to post 

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1481]
Submitter: Archy
Email: maxleyaxel@yahoo.com
Current version: 1.13.10.7
Had this problem for 2-3 days
Problem: As soon as I try to post I get that error ("no valid captcha") despite having completed the captcha.

What I tried: 1) Resetting the options. Did not work
2) Using Yandex or deactivating 4chanX. Works.

**Comment by zqjpymbk** [comment]
Issue only with legacy captcha, normal one works fine. Looks like Hiroshima Nagasaki has shut down v1 support.

**Comment by ccd0** [comment]
You have to use the v2 (image) Recaptcha to post new threads. The v1 (text) Recaptcha still works for replies.

**Comment by CharAznableLoNZ** [comment]
Using the V2 this error still occurs.  The script refuses to upload the completed captchas and then errors with no valid captcha.  This has been ongoing for a few months now.

**Comment by ccd0** [comment]
Obsolete issue, open a new one if you are having a similar problem.
