### ISSUE TITLE
WEBM does not load completely in Firefox with 4chanX enabled

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1488]
Attempt to load a webm on 4chan in its own Firefox tab from a non-4chan source (e.g. a manually-pasted URL), observe that less than 30% of the file is downloaded before the process stops.
Disable 4chanX, manually request the file again via ctrl-f5 and notice the file buffers completely. None of 4chanX's settings in the Images and Videos section appear to have any impact on this.

**Comment by whoknows22** [comment]
This sounds a lot like the issue I had a few months ago that had to do with the latest Greasemonkey version. Older versions work.
