### ISSUE TITLE
Save settings missing

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1495]
Before this previous update I had my settings saved but now my settings are reset and it keeps opening the settings menu everytime I refresh or open a new page and there is no way to save my settings. I've tried turning off my adblocker and my cookie blocker but nothing works. I checked the console but there's nothing about 4chanX in there

**Comment by hmt721** [comment]
Happening to me too since mine got updated. Settings keep popping up everytime I refresh or open a new window and they're always reset.
4chanx 1.13.10.7 
Greasemonkey 3.11
Firefox 55.0.3

**Comment by ccd0** [comment]
Use Firefox ESR or Violentmonkey/Tampermonkey. Greasemonkey + current Firefox is ultra-buggy right now, and won't be fixed until the WebExtensions rewrite is complete.
