### ISSUE TITLE
Scrolldown Button

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1498]
Submitter: Ahmet kazan
Its not an issue but can you please add a scroll down button to the right corner?

**Comment by saxamaphone69** [comment]
![image](https://user-images.githubusercontent.com/877480/235342609-cead2329-ce7c-4575-9583-aac2de4d78c1.png)

Enabling this adds an up and down button (can be positioned with CSS) to scroll to the top or bottom of a thread/index.
