### ISSUE TITLE
Filter word types

### ISSUE THREAD

**Issue by alidan** [ccd0/4chan-x#1506]
Ok this will be a bit hard to explain. 
I'm getting really sick of reading variations of "BRAAAAAAAAP"
Now I would filter this, but there is honestly no way I can think of to filter all variations other than adding each individually
Could there/is there a way to filter it so br any amount of A's and p in that order can get filtered?

**Comment by ccd0** [comment]
/BRA+P+/i

**Comment by MisakaImoutoWaifu** [comment]
/(b)\1*(r)\2*(a)\3*(p)\4*/i

I've yet to have that give me a false positive. It also captures non-standard forms like BRAPPFFFFPFPPPPFFFFF
