### ISSUE TITLE
i.4cdn.org images opened in new tab display as blank

### ISSUE THREAD

**Issue by saero** [ccd0/4chan-x#1508]
Firefox 55.0.3 64bit
Up to date 4chan-x
Greasemonkey (up to date)
Edit: Even disabled the "loop webms loaded in new tab" etc in that same category.

I believe it's only due to 4chan-x. When I disable Greasemonkey, i.4cdn.org then displays my images fine in their own tab. Funnily enough, once the image is loaded when the script is DISABLED/GS OFF, it stays loaded in the tab when the script is reenabled\GS turned on.
I have no idea what gives. It's obviously not a confliction with my uBlock Origin, I've disabled it as well. Definitely only gets 'fixed' when I disable 4chan-x script or Greasemonkey itself.

I'd refresh and start with a fresh install of 4chan-x, but I have about 5-7 dead threads in my Watch and I don't have the time to go through each before I reinstall 4chan-x.

a) Should I install another ____monkey?
b) Do I edit the script domain permissions?
c) Possible theory: Is it relating to 4chan-x's redirection to using the i.4cdn.org domain for high\better quality images (over is/mobile _____m.jpg/png versions).
No I am not running Mobile obviously.
Note: I recently updated from 53.0.3 (I think?) 32bit to 55.0.3 64bit just to try and solve this issue. No dice.

**Comment by Epic25** [comment]
Does this happen when trying to view images from any other domains? I had a similar issue which affected not only 4chan images, but image links from Discord as well. I solved my issue by removing Reek's Anti-Adblock Killer user script from Greasemonkey.

**Comment by saero** [comment]
No it does not. Like I said, the only correlation is disabling 4chan-x or Greasemonkey itself. My scripts I use are basically this, a Linkify (I dont use x's settings) and another script that edits Google page results.

**Comment by Phooh** [comment]
I've been having this same issue for some days probably weeks now. Opening images in a new tab is just a blank page with the link as the title tab and I have to turn off 4chanX just to see them. I'm not using Linkify but I am using a simular add-on called Text Link if that's part of the problem. Also on Firefox 54.0.1 with updated Greasemonkey and 4chanX

**Comment by ccd0** [comment]
I think it's a Greasemonkey bug, probably the same as #1484 and #1487. I can report it upstream if people insist, but with GM4 coming out soon and data migration bugs still unfixed, I'm not sure if it's enough of a priority.

**Comment by ccd0** [comment]
Seems to have already been reported:
https://github.com/greasemonkey/greasemonkey/issues/2524

**Comment by saero** [comment]
ccd0, would you suggest Tampermonkey over Greasemonkey?

**Comment by madmuffinz** [comment]
I wouldn't. It's a webextenstion so local/custom scripts will not work
