### ISSUE TITLE
Slow scrolling

### ISSUE THREAD

**Issue by ObsidianGuard** [ccd0/4chan-x#1510]
When I'm in a thread and try to scroll up or down it will slow Firefox down, almost like it's lagging. Doesn't happen when I turn 4chanX off.

**Comment by mglagla** [comment]
Same here, ever since 1.13.11.5 4chan-x became so slow in Firefox (55.0.2, Linux Mint 64bit) that i had to disable it.

**Comment by ccd0** [comment]
Merging into #1515 which has more details. This is https://github.com/greasemonkey/greasemonkey/issues/2602.

**Comment by ccd0** [comment]
Fixed in https://addons.mozilla.org/firefox/downloads/file/735451/greasemonkey-3.17beta1-fx.xpi
