### ISSUE TITLE
4chanx settings and installation all broken

### ISSUE THREAD

**Issue by Nusharik** [ccd0/4chan-x#1511]
So I woke up today and noticed there seemed to be a captcha issue. I would fill out the captcha and try to post but the captcha wouldn't count and stayed at 0 unless I re-did it or just closed and re-opened the QR box. I figure maybe I needed to update or something? So I go to update it and for some reason i had to click "install" 3-4 times, like the button for installing wouln't work. It installs and I restart and I somehow don't have 4chanx, it's not in my scripts, it's not on 4chan, it's not there. So I go to 4chanx's page and install again, it works this time, except none of my settings are there, and any attempt to import them doesn't work as they don't save if I open a new tab or go to a new thread. So at this point I disable and remove it. Reinstall the whole thing, and now it's not even saying it's installed:

 https://i.imgur.com/v3rciHF.png

https://i.imgur.com/6o0AiGY.png

I'm not sure what this is related to, but I'm thinking it is Firefox related. Also

-Firefox is up to date, 56.0
-Greasemonkey is up to date, 3.16
-4chanx isn't even applicable since apparently it isn't installed now.

I wen and installed it just now to get anything from the browser console and this is what popped up in it when installing.

https://i.imgur.com/hCv82Vt.png

I also went 4chan and this popped up as well in the console

https://i.imgur.com/STwW2YX.png

The only other script I have is youtube link title and I disabled it and still 4chanx would not work. I assume it HAS to be something related to what I see in the console

**Comment by ccd0** [comment]
Greasemonkey has been a bit buggy lately with the transition to WebExtensions taking priority over other Firefox changes that may break things. You can try the alpha version of Greasemonkey with the beta version of 4chan X and see if it works well enough, or use Violentmonkey or Tampermonkey. If you want to try to diagnose the issue you're having in GM3 (which there may or may not be time for anyone to fix), see if you can reproduce this in a fresh Firefox profile. Alternately, it's possible this is something wrong with your profile and a fresh one will simply fix it.

**Comment by Nusharik** [comment]
Thank you very much ccd0, I removed Tampermonkey and reinstalled 4chanx and it works perfect now, the one thing that showed me it worked is what it wasn't doing before, when I imported my settings it wouldn't say "Import successful, reload page?" It does now and it did, and it works perfect. Thank you for your help.
