### ISSUE TITLE
Very slow response for scrolling and mouse hovering

### ISSUE THREAD

**Issue by nfp0** [ccd0/4chan-x#1515]
Since version 1.13.11.5 (which coincided with my update to Firefox 56), page responsiveness became extremely slow intermittently. One moment mouse actions are working fine, but the next 5 seconds or so, there is no response from input. The mouse moves but hovering over things or clicking them takes a long time to respond. This only happens with 4chanX enabled.

This is on Greasemonkey 3.16. On Greasemonkey 4.0 alpha I couldn't make 4chanX work at all.

**Comment by nnotstorm** [comment]
Same problem here

**Comment by Hairo** [comment]
Same problem for me, using the 1.13.12.1 beta had the same result.

**Comment by Hairo** [comment]
Seems to be working with violentmonkey, could be a greasemonkey issue?

**Comment by ccd0** [comment]
It's most likely this issue:
https://github.com/greasemonkey/greasemonkey/issues/2602

**Comment by nnotstorm** [comment]
yep greasemonkey was the issue

**Comment by BlueNinja0** [comment]
Yup, it was the Greasemonkey 3.16 update.
I've downgraded to 3.15 and everything works smoothly.

**Comment by ccd0** [comment]
Fixed in GM beta:
https://github.com/greasemonkey/greasemonkey/issues/2602#issuecomment-333593758

> Please try, and let me know if it helps:
> 
> https://addons.mozilla.org/firefox/downloads/file/735451/greasemonkey-3.17beta1-fx.xpi
