### ISSUE TITLE
Quick Reply Super long

### ISSUE THREAD

**Issue by randoomdude** [ccd0/4chan-x#1516]
Quick reply is super wide and won't go back to normal trying to resize it, not sure why.

![image](https://user-images.githubusercontent.com/6027132/31053019-3f32212c-a648-11e7-84ef-9da1ad8a2b36.png)

**Comment by ccd0** [comment]
What browser and version are you using?

**Comment by randoomdude** [comment]
latest version of Chrome, running it on violent monkey, I can't think of anything that I changed recently that would cause it.

**Comment by ccd0** [comment]
Thanks, should be fixed now.

**Comment by randoomdude** [comment]
Now I can adjust the text box inside the quick reply box but the quick reply box itself is still adjustable.
![image](https://user-images.githubusercontent.com/6027132/31267209-25ea7132-aa2c-11e7-811f-bcc7972b0dee.png)

**Comment by saxamaphone69** [comment]
This is due to iex, which uses a combination of `display: table` and `width: 100%`, causing the Quick Reply to take up the entire width of the window.

**Comment by randoomdude** [comment]
ah, I see, is there a way to run iex still or do I have to completely disable it? I really like iex so I hope that's not the case.

**Comment by ccd0** [comment]
As a temporary fix you can add
```.iex_quick_reply_label_table {
  width: calc(300px - .25em) !important;
}```
to custom CSS. You should report this issue to the iex tracker so it can be fixed better there.
