### ISSUE TITLE
"Polyfill" initialization crashed. with Violentmonkey 2.8.10 and Random Agent Spoofer's(0.9.5.6) Disable Canvas Support setting, no issue with Greasemonkey 

### ISSUE THREAD

**Issue by nnadd** [ccd0/4chan-x#1524]
Pops up on every 4chan board page or thread, as mentioned in the tittle it only appears when RAS's 'Disable Canvas Support' option is enabled, happens with Tampermonkey and Violentmonkey, doesn't happen with Greasemonkey.  
I'm unsure to which addon repo this issue should be posted on.

Ignore the useragent, it's spoofed. 
I'm using 52.4.0 ESR

Script: 4chan X ccd0 v1.13.12.3 userscript
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.36
URL: https://boards.4chan.org/g/thread/62774447

TypeError: setting a property that has only a getter
Polyfill</Polyfill.toBlob@https://boards.4chan.org/g/thread/62774447:10873:7
Polyfill</Polyfill.init@https://boards.4chan.org/g/thread/62774447:10866:7
Main</Main.initFeatures@https://boards.4chan.org/g/thread/62774447:24793:11
Main</Main.init/</<@https://boards.4chan.org/g/thread/62774447:24686:18
$</$.asap@https://boards.4chan.org/g/thread/62774447:4607:14
Main</Main.init/<@https://boards.4chan.org/g/thread/62774447:24670:16
$</$.getSync@https://boards.4chan.org/g/thread/62774447:5232:14
Main</Main.init@https://boards.4chan.org/g/thread/62774447:24664:15
@https://boards.4chan.org/g/thread/62774447:25126:1
@https://boards.4chan.org/g/thread/62774447:143:2
@https://boards.4chan.org/g/thread/62774447:2:2
@https://boards.4chan.org/g/thread/62774447:1:676
value@https://boards.4chan.org/g/thread/62774447:1:175
g@https://boards.4chan.org/g/thread/62774447:3:11620
b/<@https://boards.4chan.org/g/thread/62774447:3:13109
value@https://boards.4chan.org/g/thread/62774447:3:4479
@https://boards.4chan.org/g/thread/62774447:1:47
@https://boards.4chan.org/g/thread/62774447:1:2
d@https://boards.4chan.org/g/thread/62774447:3:4053
module.exports</b.c/<@https://boards.4chan.org/g/thread/62774447:3:4344
b@https://boards.4chan.org/g/thread/62774447:3:13122
c@https://boards.4chan.org/g/thread/62774447:3:13191
module.exports</q.LoadScripts@https://boards.4chan.org/g/thread/62774447:3:13728
d@https://boards.4chan.org/g/thread/62774447:3:7601
module.exports</b.c/<@https://boards.4chan.org/g/thread/62774447:3:4322

**Comment by ccd0** [comment]
4chan X uses canvas for various things including generating the Quick Reply thumbnails. It's natural there will be errors if you disable it.
