### ISSUE TITLE
'Replace PNG: Replace png thumbnails with the actual image' is always enabled

### ISSUE THREAD

**Issue by BondiBear** [ccd0/4chan-x#153]
The option 'Replace PNG: Replace png thumbnails with the actual image' is always always enabled, despite the option in the menu being DISABLED.

This was fine before the latest update (Current version is 1.9.4.1).

**Comment by ccd0** [comment]
Is this still happening?

**Comment by BondiBear** [comment]
No, I think not. I will close this.
