### ISSUE TITLE
4chanX not available when browsing boards on 4chan.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1549]
Submitter: Rah
Email: rahmeesh@gmail.com
I'm not getting the 4chanX overlay or any of the features when browsing threads since the halloween theme was put out. I tried checking some boards today and It wont work. I tried changing off of the special page background and it still didn't change anything.

I am using Firefox Quantum 57.0b12 (64-bit), 4chan-x Beta, Grease Monkey 4.0alpha11, Better better booru, and exlinks as my only scripts. Everything is up to date as of this post.

**Comment by mloki** [comment]
Same issue but with ViolentMonkey 2.8.16

**Comment by Rahmeesh** [comment]
Did some more fiddling around and got the latest beta build of Greasemonkey 4.0Alpha12.
Now it works like before. Hope that helps.

**Comment by ccd0** [comment]
@Rahmeesh
Good to hear. Likely this was just some bug in the Greasemonkey alpha.

@mloki
see #1546

**Comment by mloki** [comment]
@ccd0 Fixed by switching from VM to GM 4.0Alpha13. Switched to VM by /g/ suggestion.
>inb4 he fell for the VM meme.
