### ISSUE TITLE
Previews have transparent background when using 4chanX

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#1552]
![image](https://user-images.githubusercontent.com/11262717/32273797-3dd8a33a-bf04-11e7-9b4b-f85002022be8.png)

Tried disabling all the userscripts and leaving only 4chan X active and tried running the browser in incognito mode to test the normal 4chan behavior. It's 4chan X somehow

**Comment by ccd0** [comment]
Make sure 4chan X is up to date.

**Comment by hhiru** [comment]
Can't tell if it's because they un-toggled the halloween theme or because it updated meanwhile but now it works again
