### ISSUE TITLE
Extension not loading at all in firefox

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1555]
Submitter: John
Email: mr.p2kk.ickkck@gmail.com
I had only begun using firefox again recently and when I first opened it the extension seemed to be working, but after updating the page returned to vanilla, not only that, but restarting firefox wipes out the script completely and without warning. My only other script is doodlehelper fullspectrum from https://gist.github.com/haicat/cdab3d709be3a6245190  and other add ons are adblocker and avira safety, disabling them doesn't change this behavior.
The console gives the following info:

A network error occurred.  loadFile.js:56:13
A network error occurred.  loadFile.js:56:13
A network error occurred.  loadFile.js:56:13
Loading failed for the <script> with source “https://utraffic.engine.adglare.net/?100532792”.  395493924:1
A network error occurred.  loadFile.js:56:13
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.  (unknown)
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: try {

(function injectPageScriptAPI(scr....  CONTRIBUTING.md:1
Loading failed for the <script> with source “https://www.google-analytics.com/analytics.js”.  4chan-x:1
Loading failed for the <script> with source “https://js-agent.newrelic.com/nr-1044.min.js”.  4chan-x:1
A network error occurred.  loadFile.js:56:13
Loading failed for the <script> with source “https://utraffic.engine.adglare.net/?710227704”.

**Comment by ccd0** [comment]
Are you using Violentmonkey? If so, see https://github.com/ccd0/4chan-x/issues/1546

**Comment by gnapr** [comment]
Nope, Greasemonkey 3.17

**Comment by ccd0** [comment]
Can you reproduce the problem in a fresh profile? https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles
