### ISSUE TITLE
Open thread in new tab does not work in default catalog with HTTPS

### ISSUE THREAD

**Issue by tallos** [ccd0/4chan-x#1560]
The open threads in new tab option currently does not work on the default 4chan catalog when using HTTPS, which is different from the HTTP default catalog behavior. Currently it only opens new tabs from the index, or from the 4chanX catalog.
Please fix so that it also works on the default 4chan catalog when using HTTPS.

**Comment by ccd0** [comment]
You can change this in the catalog's settings. It has nothing to do with 4chan X.

**Comment by tallos** [comment]
ah the setting must have reset on a browser update without me noticing.
