### ISSUE TITLE
Corrupt image or error reading metadata.

### ISSUE THREAD

**Issue by Question2** [ccd0/4chan-x#1572]
Getting this popup warning everytime i try to post an image via the 4chanx QR form. I can still post the image though. Started happening today...updated to the latest version, still happening on firefox 52.4 ESR 64 bit.

Edit : adding @@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval' to ublock origin didnt help.

**Comment by dlfsjdfjodifjsodifjsdo** [comment]
I'm happy with this feature tbh. metadata creeps me out.

**Comment by Question2** [comment]
Its happening for every image...strange thing is its no longer happening now.
