### ISSUE TITLE
4chan X broken in new Firefox Quantum

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1601]
Submitter: Matt
Email: mattrlee53@live.com

**Comment by Dopebear** [comment]
Seconded.

With the new Firefox Quantum update, I can no longer post while using 4chan x. However every other feature of 4chan x seems to be working just fine (as far I can see).

**Comment by ccd0** [comment]
@Dopebear
Are you using a pass? If so, that is #1597. Can you check if the latest version of 4chan X works for you?

To OP, if you're having a different problem than @Dopebear, you'll need to be more specific.

**Comment by Dopebear** [comment]
My apologies, ccd0. I was still on 'Current version: 1.13.14.6' even though I had thought I had manually updated it. I retried to update manually and it now works and I can post again.

Something is awry with Greasemonkey and/or the new FF. You need to go 'back' a page after selecting a script to install for Greasemonkey--only then will it let you install. Funnily, 4chan-x doesn't show up in about:addons.

Thanks for your quick response and time.

**Comment by ccd0** [comment]
Nothing to apologize for, I hadn't pushed the update yet when you first posted.

**Comment by Flame102** [comment]
It's still broken for me despite updating.

I get a message box saying "Used GM_xmlhttpRequest when not defined" and I can't post

**Comment by foogies** [comment]
Default navigation to catalog no longer works when using the sidebar. Hover to expand image in catalog is also broken.

Two biggest issues for me right now.

**Comment by ccd0** [comment]
@foogies
Are you OP or reporting your own issues?

Using https://www.4chan.org/frames is broken in Greasemonkey right now due to https://github.com/greasemonkey/greasemonkey/issues/2574. Hover to expand image in catalog as well as all other features will be nonfunctional in Greasemonkey if you use the frames view until this is fixed.

Hover to expand image in catalog seems to be working fine provided not using frames, using 4chan X catalog, and the option ("Image Hover in Catalog") is enabled.

**Comment by ccd0** [comment]
Got an email from OP; it was due to his version of 4chan X being out of date.

@foogies
Moving your issue to #1624.
