### ISSUE TITLE
"Used GM_xmlhttpRequest when not defined" 

### ISSUE THREAD

**Issue by Flame102** [ccd0/4chan-x#1606]
As it says on the tin.

I get a message saying "Used GM_xmlhttpRequest when not defined" 

And I can't post. Don't have pass.

**Comment by ccd0** [comment]
What browser and userscript engine are you using? What versions are you using of these and 4chan X? What did you do when the error happened?

**Comment by Flame102** [comment]
Using the updated Firefox that's breaking everyone elses 4chan X. I updated 4chan X to the latest version, which fixed the entire thing crashing, but still have this lingering leftover.

using Greasemonkey.

As for what i'm doing, just opening a page, any page, on any board, gets me that popup. I get it on the Catalog, I get it on normal pages. 

it seems to only prevent Quick Reply from working. if I disable quick reply in the settings, normal posting works

**Comment by ccd0** [comment]
What version of Greasemonkey?

**Comment by Flame102** [comment]
4.0

**Comment by ccd0** [comment]
Any other extensions? Can you reproduce the error in a fresh profile?

**Comment by Flame102** [comment]
Extensions...
I have 4Chan Media Player and 4Chan sound player. Disabling  Media Player gets rid of the error, so it seems that was the cause of the error, but my quickreply is still broken. Captcha works fine, but nothing happens when I hit submit.

I also have Reek's anti-adblock killer, Pixiv Translation plus, and Clear Imageboard.

I'm not sure what you mean by fresh profile.

**Comment by ccd0** [comment]
> I'm not sure what you mean by fresh profile.

https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by Flame102** [comment]
I tried it in a new profile. New profile has no issues

**Comment by ccd0** [comment]
> Captcha works fine, but nothing happens when I hit submit.

This might be #1625. Can you check if v1.13.14.8 fixes it in your main profile?

**Comment by Flame102** [comment]
yeah that did the trick.

**Comment by ccd0** [comment]
Greasemonkey 3.16 had a bug in the data migration to Greasemonkey 4. It was fixed in Greasemonkey 3.17, but anyone who updated straight from Greasemonkey 3.16 to Greasemonkey 4 got stuck with corrupt data.

This affects the settings of other userscripts too, so if you have other scripts with settings you don't want lost, you should follow what I wrote here:
https://github.com/ccd0/4chan-x/issues/1625#issuecomment-344793681
