### ISSUE TITLE
Custom CSS can't be used

### ISSUE THREAD

**Issue by Bjarkil** [ccd0/4chan-x#1611]
Hey,

first of all thanks for keeping this extension up to date for such a long time.
Secondly, there seems to be bug with the custom style-sheet in the "Advanced" settings.
I had a pretty nice script for my personal 4chan style, but it's gone now (perhaps because of the Firefox 57 update?). And the box where I would input that custom CSS is greyed out, so I can't write a new style even if I wanted to.

I hope you find a way to fix this soon 😄

**Comment by ccd0** [comment]
Can you export and post your settings?
If the custom CSS box is greyed out, you should just need to check the box above enabling it.

If you're having problems with setting corruption, try this:

- Install Firefox ESR from https://www.mozilla.org/en-US/firefox/organizations/all/ or Firefox 56 from https://ftp.mozilla.org/pub/firefox/releases/56.0.2/
- Install version 3.17 of Greasemonkey from https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/3.17
- Your Greasemonkey data should not be migrated properly. You can now update to the latest versions of Firefox and Greasemonkey. Just in case there is still a problem, it's a good idea to export your settings so you can reimport after the upgrade if needed.

**Comment by Bjarkil** [comment]
You're right, my Greasemonkey was acting up.
I reinstalled it and now everything is working fine.
Thanks
