### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1625]
Submit button on the quick reply doesn't work in firefox 57.

**Comment by ccd0** [comment]
Are you using Greasemonkey? What does it do? Are there any error messages?

**Comment by TGGeko** [comment]
Using Greasemonkey 4.0. No error messages. I click the button and nothing happens.

**Comment by ccd0** [comment]
Is your 4chan X up to date? Any other extensions? Does it happen in a fresh profile?

**Comment by TGGeko** [comment]
I'm using 13.14.7 Issue still persists with a fresh profile. In addition to greasemonkey, I have adblock plus, and "No Youtube Comments" and the MEGA extension.

**Comment by ccd0** [comment]
Any errors that appear in the browser console (Shift+Control+J) when you submit?

**Comment by TGGeko** [comment]
TypeError: this.captchas.findIndex is not a function  ExtensionContent.jsm:20510:11

Also the issue persists with  Recaptcha v1 either enabled or disabled.

**Comment by ccd0** [comment]
Can you export and post your settings?

As a possible fix, you can try this if you want to keep your settings/filters/etc. or just reset your settings:

- Install Firefox ESR from https://www.mozilla.org/en-US/firefox/organizations/all/ or Firefox 56 from https://ftp.mozilla.org/pub/firefox/releases/56.0.2/
- Install version 3.17 of Greasemonkey from https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/3.17
- Your Greasemonkey data should now be migrated properly. You can now update to the latest versions of Firefox and Greasemonkey. Just in case there is still a problem, it's a good idea to export your 4chan X settings so you can reimport after the upgrade if needed.

**Comment by TGGeko** [comment]
[4chan X v1.13.14.7-1510796949976.zip](https://github.com/ccd0/4chan-x/files/1477069/4chan.X.v1.13.14.7-1510796949976.zip)

I'll try as you suggest.

**Comment by ccd0** [comment]
In your case it might be enough to just re-import what you exported. The setting that is presumably corrupted (captcha cache) isn't in the exported settings.

**Comment by TGGeko** [comment]
Oddly enough, that worked. Thanks!
