### ISSUE TITLE
Quick Reply doesn't submit posts

### ISSUE THREAD

**Issue by Burnyx** [ccd0/4chan-x#1634]
Since FF updated to 57 clicking submit on the quick reply form after filling all fields does nothing. That's on the latest version of Greasemonkey.

**Comment by ccd0** [comment]
Is your 4chan X up to date?

**Comment by Xibster** [comment]
Yeah same issue

**Comment by ccd0** [comment]
"Force Noscript Captcha for v1" is broken in Greasemonkey for now. If that's not your issue, please give more info about your captcha settings. #1610
