### ISSUE TITLE
Upload Failed

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1686]
Every post gets an "Upload Failed" error, even if there's no file to upload.

**Comment by ccd0** [comment]
Have you checked whether it happens when using the post form at the top of the page?

**Comment by OnTheGrind** [comment]
I also get the same issue whether I use Quick Reply or the Original Form. The captcha no longer ask to be solved. As soon as you click it, it automatically shows as solved instead of presenting a puzzle.

Basically, I cannot give a response to the boards in any manner.

**Comment by ccd0** [comment]
Are you using Recaptcha v2 (the checkbox version)?

**Comment by OnTheGrind** [comment]
The captcha I use is whatever the default one it is. I haven't changed it.

**Comment by ccd0** [comment]
Is there any difference with 4chan X disabled?

**Comment by ccd0** [comment]
Also it might be worth checking if you can post with Recaptcha v1, although that's a temporary solution now if it works. It's very likely not related to the captcha, though. "Upload Failed" is 4chan's generic message when the post is blocked for some reason. Are you using a name or tripcode? That may be blocked. You could also try clearing your cookies (back up any native extension or catalog setting/filters first).

**Comment by OnTheGrind** [comment]
After really finagling with it, I am now able to post.

As I stated in previous post, the captcha was not presenting me with a puzzle. I suspected this was the issue. After turning off 4chanx in tamper monkey, restarting Firefox, turning 4chanx back on, the cpatcha now presents me with a puzzle when posting and I can post successfully.
