### ISSUE TITLE
ublock origin + re\captcha

### ISSUE THREAD

**Issue by 1xch** [ccd0/4chan-x#1690]
Is there a combination of rules and/or filters to allow interaction between 4chanx - ublock - and captcha. 

I just started poking around trying to get it work and thought I'd ask if there is an easier way someone has listed I can reference.

**Comment by ccd0** [comment]
Are you using Greasemonkey 4? That has problems in frames causing known issues #1559 and #1654.

**Comment by thrisp** [comment]
@ccd0 
yes I'm using Greasemonkey 4

**Comment by ccd0** [comment]
Are you having a problem other than what's in those two issues? Those problems will need to be fixed in Greasemonkey.
