### ISSUE TITLE
4chan-x not enabled in frames mode?

### ISSUE THREAD

**Issue by pmourlanne** [ccd0/4chan-x#1698]
I'm using FF 57.0, Greasemonkey 4.0 and 4chan-x 1.13.14.10. This issue has appeared since I installed FF Quantum. It appears on Ubuntu 14.04, Ubuntu 16.10 and Windows 10.

To reproduce:
- Go to `https://www.4chan.org/frames`
- On the left hand, click on `/g/ - Technology`, for example
- 4chan-x does not seem to be enabled on the page (I don't see the moving header with the boards and the settings, image hover does not work etc.)

If I go to `https://boards.4chan.org/g/` directly, without frames, 4chan-x is enabled, and works properly.

**Comment by ccd0** [comment]
See #1624.
