### ISSUE TITLE
Reply Box scrolls to top of page

### ISSUE THREAD

**Issue by Listie** [ccd0/4chan-x#1699]
Don't know why this is happening. Say I am at the bottom of a large thread. If I click on reply, the reply box comes up but the entire page scrolls back to the top of the page, and the new reply box sits at the top of the page. I can still reply but I have to manualyl scroll down to see what I was referring to.
How can i get the Reply box to open next to the post I am replying to ?

1.13.14.10

**Comment by saxamaphone69** [comment]
Browser?
Operating system?
Are you using a userscript manager, or the extension itself?
Do you have any other extensions, userscripts, or userstyles installed (in other words disable everything and re-attempt)?

**Comment by Listie** [comment]
Firefox 56.02 Windows 10
Greasemonkey
Disabled everything. Still happens

**Comment by Listie** [comment]
Installing the beta fixed it
