### ISSUE TITLE
Post menu follows you while scrolling

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#170]
![unbenannt](https://cloud.githubusercontent.com/assets/1091166/4709560/516b114e-58a0-11e4-841c-4f684ae035c6.png)
Chrome, latest.

.
Also, where is 4chan X downloading the images posted from urls?

**Comment by ccd0** [comment]
Since v1.10.0.0 menus close on scroll, so this should no longer be a problem.
