### ISSUE TITLE
Script not working on MS Edge.

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#1713]
.....

**Comment by Nexxkinn** [comment]
Can you check whenever the site run under https, and "always use https" mode checked on native extension?

I also got into that kind of problem before and somehow got fixed by forcing to https, somehow.

**Comment by leewdch** [comment]
The script is not launching on MS Edge. Currently I have Tampermonkey and uBlock Origin installed.
Tampermonkey 4.5.5648
uBlock Origin v1.15.4
Microsoft Edge 41.16299.15.0
