### ISSUE TITLE
Twitter embeds not loading

### ISSUE THREAD

**Issue by BondiBear** [ccd0/4chan-x#1716]
FF 57.0.2 64 / 4cx 1.13.14.10 / Tampermonkey 4.5.5633

Twitter embeds are no longer loading for me. see pic.

Possibly another thing broken by FF57 since it worked on previous FF versions, or indeed Tampermonkey (used GM before it shat itself).

Disabled all add-blocking and similar privacy addons, but the problem persists.

![twittcrap](https://user-images.githubusercontent.com/2057221/33795115-be40c446-dcda-11e7-92e7-7f5f9cf806b7.PNG)

**Comment by ccd0** [comment]
..

  -----Original Message-----
  From: <reply@reply.github.com>
  Sent: Sat, 09 Dec 2017 03:18:53 -0800
  To: 6502153649@txt.att.net
 Subject: [ccd0/4chan-x] Twitter embeds not loading (#1716)

>FF 57.0.2 64 / 4cx 1.13.14.10 / Tampermonkey 4.5.5633
>
>Twitter embeds are no longer loading for me. see pic.
>
>Possibly another thing broken by FF57 since it worked on previou

==================================================================
This mobile text message is brought to you by AT&T

**Comment by boogiepop** [comment]
Bump, I'm having the same problem even on a clean Firefox profile.
This is the console output when I try to embed a tweet: "Loading failed for the <script> with source “https://platform.twitter.com/widgets.js”."
