### ISSUE TITLE
workaround for 4chan css being rekt due to hiroshmoot fuckery

### ISSUE THREAD

**Issue by fuaxio** [ccd0/4chan-x#1734]

**Comment by Supertatortots** [comment]
Is this the issue where everything suddenly turns white? I've noticed that it happens when you scroll all the way to the bottom.

**Comment by Willy156** [comment]
Dammit, hope this gets fixed soon. 4chan x is not usable atm

**Comment by timwelter09** [comment]
What did that jap fuck do now?

**Comment by ccd0** [comment]
I've heard about it but I haven't seen it myself yet. What's your configuration?

**Comment by Willy156** [comment]
The problem is when you scroll to the very bottom of the page, everything will turn white and the css gets removed

**Comment by ccd0** [comment]
Yeah, as I said, I don't see it on my end, at least not yet. What's your browser and userscript manager and ad blocker and versions of all of that?

**Comment by Willy156** [comment]
Browser: Google Chrome Version 63.0.3239.84 (Official Build) (64-bit)
Adblocker: uBlock Origin 1.14.20

**Comment by timwelter09** [comment]
Browser: Chrome Version 63.0.3239.84 (Official build) (64-bits)
Adblock: uBlock Origin 1.14.20
Userscript manager: Tampermonkey 4.4
Also using StyleChan 1.0.14 + Extra flags for int 0.30

**Comment by ccd0** [comment]
I've got it reproduced on Chromium.
Does this fix it for you? It worked for me, but might not be reliable especially with Tampermonkey (haven't tested with that yet).
https://boards.4chan.org/g/thread/63894609#p63896479
> If you use 4chan X, go settings->advanced->javascript whitelist and put a # in front of 'unsafe-eval'. It seems like that fixes it for now.

**Comment by timwelter09** [comment]
It does but it also disables all other scripts I've got running. At least it's a temporary solution.

**Comment by Supertatortots** [comment]
Browser: Vivaldi 1.13.1008.36 (Stable channel) (64-bit)
Adblock: uBlock Origin 1.14.20

Interesting note, 4chan X is working fine on /qa/. This probably has to do with some new ads or whatever that's being run.

**Comment by Willy156** [comment]
Yeah, 4chan X is working on /toy/ but not on /a/ for me

**Comment by fuaxio** [comment]
1. Install uBlock Origin
	https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm
	https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
2. Install a userscript manager
	https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo
	https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/
3. Open uBlock's options, go to "My filters" tab and paste this:
	https://pastebin.com/raw/4Jm6G4gJ
4. Open Tampermonkey/Greasemonkey, add a script and paste this:
	https://pastebin.com/raw/28Lcd7KR

This makes the captcha not work. but otherwise works.

**Comment by ecrvnr** [comment]
Thanks @fuaxio that did the trick

**Comment by DumbIdiot** [comment]
@fuaxioFix works, but it breaks the catalog and the reply form at the top is not hidden anymore.

Chrome

**Comment by timwelter09** [comment]
@fuaxio Would use this but if it breaks the captcha it's kinda pointless for me. Thanks anyway.

**Comment by ecrvnr** [comment]
@DumbIdiot @timwelter09 Not getting any issue with captcha nor catalog here.

**Comment by ccd0** [comment]
Removing the HTML element where the ad is supposed to go seems to be enough to stop this behavior. I've put that out as a temporary fix. Ideally we'd like to prevent the script from running, but it may be difficult to do that without breaking other things.

**Comment by DumbIdiot** [comment]
@ecrvnr It's the 4chan catalog that breaks. The 4chan X Catalog works.

**Comment by DumbIdiot** [comment]
The pastebin userscript has been updated and fixed the native catalog, but anon says the original reply form at the top of pages being unhidden cannot be fixed as it's an issue with 4chan x.

**Comment by bakugo** [comment]
It's possible to work around this new anti-adblock method completely in a cross-browser way by blocking all inline scripts (via uBlock or directly with CSP `unsafe-inline`) and manually `eval`ing the ones the site still needs (like the ones that define `style_group` and `recaptchaKey`). An example implementation is [here](https://pastebin.com/LkEx7Ybe).

Unfortunately this does not play nice with 4chan X since it uses inline scripts in the `$.globalEval` function. It still mostly works, but some things are broken, such as the lack of the `js-enabled` class in the document root which causes the original post form to always display.

**Comment by Dragas** [comment]
@bakugo It's really not. The API is public and all you would need to do is write a couple of templates. 4chanx already links each post which it would quote. Pop it through your favorite front end framework and BAM. You've got your 4chan webapp.

**Comment by Khris777** [comment]
I have been using @fuaxio's fix for a while with Waterfox and it worked fine until yesterday, now the css looks as broken as before,

4chan-X still seems to be working, I can use Quick Reply and the Gallery, the latter is having some lag issues in longer threads thought.

**Comment by ccd0** [comment]
See also #1885
