### ISSUE TITLE
Issue viewing threads

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1735]
Submitter: NA
Started today. When I scroll to the end of a thread, the page freezes for a few seconds and then displays as a plain text page. No images or anything. 
I took a screenshot: https://imgur.com/OIzJx65

**Comment by Justy89** [comment]
Same issue here. Started happening about fifteen minutes ago. Reloading the page displays it normally while it's loading, but once it finishes loading, it reverts to the plain text on white background. Only disabling 4chanX fixes it.

**Comment by skeptacle** [comment]
i have the exact same issue. started today, temorarily disabled 4chanX as countermeasure.
