### ISSUE TITLE
Pages turning into (raw?) text

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1738]
When a thread is scrolled to the bottom, there's a brief pause, and then the whole page turns into only text.
Seems to occur with the larger boards - tried it on /a/ and /v/ and it came up, but other smaller/slower boards like /ic/ didn't have the issue.
Had AdBlockerPlus running - tried getting the issue to come up with ADBP disabled, and it still comes up.

Here are the error messages that appeared:

[Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
s @ 165894896:1

Refused to load the script 'https://utraffic.engine.adglare.net/?653284199' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

initAdsAG @ core.min.1013.js:1

Refused to load the script 'https://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

Refused to load the script 'blob:https://boards.4chan.org/494a6b8b-e139-4b26-8979-349db5663eb7' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

Refused to load the script 'https://jsc.mgid.com/4/c/4chan.org.182890.js?t=11711195' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

Refused to load the script 'data:text/javascript;base64,LyptYXJrZXRnaWQuY29tVjMqL2lmKCF0aGlzLk1hcmtldEdpZEpTT04peyBNYXJrZXRHaWRKU09OPWZ1bmN0aW9uKCl7ZnVuY3Rpb24gZihuKXtyZXR1cm4gbjwxMD8nMCcrbjpuO31EYXRlLnByb3RvdHlwZS50b0pTT049ZnVuY3Rpb24oKXtyZXR1cm4gdGhpcy5nZXRVVENGdWxsWWVhcigpKyctJytmKHRoaXMuZ2V0VVRDTW9udGgoKSsxKSsnLScrZih0aGlzLmdldFVUQ0RhdGUoKSkrJ1QnK2YodGhpcy5nZXRVVENIb3VycygpKSsnOicrZih0aGlzLmdldFVUQ01pbnV0ZXMoKSkrJzonK2YodGhpcy5nZXRVVENTZWNvbmRzKCkpKydaJzt9O3ZhciBtPXsnXGInOidcXGInLCdcdCc6J1xcdCcsJ1xuJzonXFxuJywnXGYnOidcXGYnLCdccic...gpIHsgcmV0dXJuICdyaWdodCcgfSBlbHNlIHsgcmV0dXJuICdjZW50ZXInOyB9IH07fTsgdGhpc1snTWFya2V0R2lkQ01vbml0b3JCbG9jazE4Mjg5MCddLmNhbGwodGhpc1snTWFya2V0R2lkSW5mQzE4Mjg5MCddLCB0aGlzWydNYXJrZXRHaWRJbmZDMTgyODkwJ10pOyB0aGlzWydNYXJrZXRHaWRJbmZDMTgyODkwJ11bJ2Z1bmNCbG9ja3MnXVsnTW9uaXRvciddID0gJ01hcmtldEdpZENNb25pdG9yQmxvY2sxODI4OTAnOyBNYXJrZXRHaWRJbmZDMTgyODkwLmluaXQoKTsgaWYgKHR5cGVvZiBNYXJrZXRHaWRJbmZDMTgyODkwLkhFLk1hcmtldEdpZEMxODI4OTBEaXNhYmxlU3RhcnQgPT0gJ3VuZGVmaW5lZCcpIHsgTWFya2V0R2lkSW5mQzE4Mjg5MC5zdGFydCgpOyB9IH0=' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

VM833:3 Refused to load the script 'data:text/javascript;base64,LyoqLw==' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

**Comment by bluefiberbread** [comment]
Yeah I'm getting the same issue on Chrome too

**Comment by toshiya44** [comment]
Removing `'unsafe-eval'` from the Javascript Whitelist seems to fix the issue. (will it break any functionality?)

**Comment by anonymau5** [comment]
I'm seeing this as well, I've noticed some differences between yesterdays page and today's broken page.  I'm thinking mootwo did something and broke everything.   The larger image called worked is the before, the smaller image called broken is todays.

![worked](https://user-images.githubusercontent.com/2172796/34132648-b5a89444-e405-11e7-86c4-cba302c5dba4.png)
![broken](https://user-images.githubusercontent.com/2172796/34132649-b5c1840e-e405-11e7-854a-2b22e9d992dd.png)

**Comment by anonymau5** [comment]
Just refreshed the page and see it's back to normal.  Perhaps he is fucking with stuff.
![fixed](https://user-images.githubusercontent.com/2172796/34132766-4f0d935a-e406-11e7-9264-72db28808067.png)
