### ISSUE TITLE
All white pages? Theme not staying

### ISSUE THREAD

**Issue by DrBossRabbit** [ccd0/4chan-x#1739]
So I just recently installed 4chan X due to all of today's fuckery, and I'm noticing that my theme of Yotsuba B doesn't stick and resets on every page. How do I stop this?

**Comment by VariableZero** [comment]
Are you using uBlock Origin by chance?

**Comment by nice-person** [comment]
Could it be NoScript?
I'm having a similar problem: when I only allow JavaScript from google.com, the website works "normally", but when I allow JavaScript from 4chan.org the page formatting goes away.

My guess is that new code was added to coerce the user into allowing JavaScript from piguiqproxy.com, amgload.net, and smgcheck.org.
