### ISSUE TITLE
Threats becoming raw text

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1740]
Submitter: Oscar Duarte
Email: ordg1993@gmail.com
hi, just having a issue when i scroll all the way down on a threat they show a "Loading" freezes for like 5 sec and the the hole threat become raw and 4chanX seems to not work anymore till y refresh page

**Comment by kratos284** [comment]
Use this filter to uBlock origin to fix the css.
boards.4chan.org##script:inject(abort-current-inline-script.js, String.fromCharCode)

**Comment by hhiru** [comment]
Can confirm. It happens to me too. it doesn't matter how long the thread is, when you reach the bottom the page stops reacting, you can't scroll up and a page without CSS is rendered

![image](https://user-images.githubusercontent.com/11262717/34162793-43b8fab0-e4d5-11e7-9d62-93d3035ad2e6.png)
