### ISSUE TITLE
Header bar and various elements randomly break

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1741]
Submitter: rookah
Email: gisselairel@gmail.com
Using firefox 52.4.0 and greasemonkey 3.17, after updating 4chan X to latest release/beta over from 1.13.11 some elements such as header bar, relative post time and others randomly break (or don't load correctly) and require a page refresh to be displayed correctly again. It seems default 4chan elements are displayed instead (default board list, no 4chan X shortcuts...)

**Comment by rookah** [comment]
Side by side comparison, bottom is expected result: https://a.pomf.cat/rrbdwn.png
