### ISSUE TITLE
Hotfix for Ads Not Working

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1744]
Submitter: Chris
Email: ghostypheus@gmail.com
Hello,

The latest update meant to address the ads breaking 4chan are not currently working on my Google Chromebook. Despite having the latest version, when I scroll to the bottom of the thread, the whole page freezes up and then changes to the broken plain text view. Do you know if there are any suggested workarounds, or will a future version address this issue on Chromebooks/Chrome OS? 

Thanks for the hard work, I have thoroughly enjoyed using your plugin.

**Comment by ccd0** [comment]
For best results you should install an ad blocker such as uBlock Origin.

**Comment by azacock** [comment]
I think I'm having this issue as well. Running uBlock Origin, uMatrix, and 4chan-X in Tampermonkey on Firefox 57.0.1. Loading indices or catalogs is fine, but when loading threads, it often switches to a broken plain text view. Refreshing the page sometimes fixes it, but sometimes I have to refresh the page many times.
