### ISSUE TITLE
Cant find themes?

### ISSUE THREAD

**Issue by friendlytherapist** [ccd0/4chan-x#1748]
Maybe im an idiot but I cant seem to find the themes option. Is there one?

**Comment by friendlytherapist** [comment]
yea im an idiot

**Comment by yeaiknowit1** [comment]
Nope probably not ur just thinking to much and probably overlooking a simple fix im sorry you fell that way

**Comment by yeaiknowit1** [comment]
Just know that someone else is an idiot
