### ISSUE TITLE
Some posts not visible

### ISSUE THREAD

**Issue by darkred3** [ccd0/4chan-x#1760]
I just noticed that with this addon enabled some posts are not visible, as though they were deleted.

Example:
https://boards.4chan.org/a/thread/167058586
Post number 167058835 is not visible

Firefox 57.0.4 64bit, Greasemonkey 4.1, 4chan-x 1.13.14.7

**Comment by ccd0** [comment]
Try checking your filters for anything that might be hiding it.

**Comment by darkred3** [comment]
I have not set any filters.

**Comment by ccd0** [comment]
Do you have Forward Hiding turned on?

**Comment by darkred3** [comment]
Couldn't find that setting in the menu but according to my exported settings it's turned on, yes.

 "Forward Hiding": true,

**Comment by ccd0** [comment]
It's under Quote Links > Quote Inlining.
Forward Hiding: Hide original posts of inlined backlinks.

**Comment by darkred3** [comment]
Hmmm.. but I had Quote Inlining disabled.

**Comment by darkred3** [comment]
It's happened again.
Specifically, this post was hidden: https://boards.4chan.org/a/thread/174737410#p174740837

Version used: 1.14.2.1

**Comment by darkred3** [comment]
'kay, found the issue. Filtering -> Filter seems to have been the problem. Which is weird since I hadn't set any filters but whatever...
