### ISSUE TITLE
Error: upload failed message when uploading images

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1765]
Submitter: zezil
Email: 9pzc4a+lzez7jn7w3tg@sharklasers.com
Using latest version of 4chanX and FF 40.0.3. Every time I upload an image I get the ERROR: UPLOAD FAILED message, no matter the kind of image or the board. Thanks.

**Comment by InsaneHyena** [comment]
Do you happen to be a russian?

**Comment by pochamago** [comment]
it's sitewide, not a 4chanx issue
