### ISSUE TITLE
Skipping Verification with CAPTCHA v2

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1767]
Submitter: Anon
With the v1 support gone, the native 4chan extension allows users to skip CAPTCHA verification for their next post, while 4chan X's CAPTCHA does not support this. Any way to port this over? Example: https://img.fireden.net/v/image/1516/72/1516723270706.png
Thanks.

**Comment by leedoyle** [comment]
@ccd0 got a different problem. With "captcha fixes" and "force noscript captcha" enabled I cannot leave replies - getting messages "you mistyped the captcha or captcha malfunctioned". Chromium 63, Tampermonkey, latest version from https://github.com/ccd0/4chan-x/raw/beta/builds/4chan-X.user.js

**Comment by deadman3000** [comment]
With force noscript captcha enabled I have no box to paste the verification code into. I have to click the captcha button twice to get the verification box to appear so I can paste it.

**Comment by ccd0** [comment]
The latest beta version (v1.13.15.4) should allow you to skip the captcha when the cookie in question is set. It will be moved to stable in about an hour or two if there are no new kinks to work out.

**Comment by leedoyle** [comment]
@ccd0 what about my issue? Is it solved in the new version?

**Comment by ccd0** [comment]
@leedoyle
I haven't reproduced yours yet. Also, can you open a new issue?

**Comment by leedoyle** [comment]
@ccd0 you got it.

**Comment by deadman3000** [comment]
@ccd0 .4 seems to be working fine at the moment. Thanks.
