### ISSUE TITLE
Seperate "Index sort" for every board

### ISSUE THREAD

**Issue by Tyilo** [ccd0/4chan-x#178]
I like to browse some board with threads sorted by bump order and others sorted by creation date.

Would it be possible to remember the selection made for the "Index sort" on a per-board basis?

**Comment by ccd0** [comment]
> adding a sort option to the custom navigation as was done in Mayhem's fork would accomplish more or less the same thing

This should be out in next beta, but on further reflection, it creates even more reason to do this. If I set one board link in the header to use a particular order, I don't want it to change the order on all boards.

**Comment by ccd0** [comment]
Added in v1.11.28.0.
