### ISSUE TITLE
Webm not closing when clicked, pausing instead.

### ISSUE THREAD

**Issue by Nusharik** [ccd0/4chan-x#1783]
Hi, recently as of the newest update I've noticed on my laptop webm's don't close, instead they open when clicking them and any further clicking on them only pauses them.  I'm not sure why this happens, it seems to be that any webm I click on does it but only on my laptop. I'm using tampermonkey on my laptops browser, which is firefox. I only have 4chanx and a youtube link title script, and 4 other extensions on my laptop browser. I tried disabling all of them and the problem still persists. My console has nothing significant at all when opening a webm and trying to close (which is essentially impossible since it just pauses it).

**Comment by tidux** [comment]
This behavior has existed on Firefox since 57.

**Comment by Nusharik** [comment]
I have current firefox and have no experienced this issue until recently, I also noticed there is a "contract" button near the webm. on Desktop and PC. My desktop version I can click them closed, but laptop I can't and use the button. Is there a way to get my laptop back to how it was before? Ie clicking them closed.

**Comment by Chibicon** [comment]
I have the same issue and the only way to fix it is to disable "Show Controls" in the 4chanx settings.

**Comment by azurekite** [comment]
Thanks mate, I guess "Show Controls" is getting disabled till further updates since I was starting to have this issue just today.

**Comment by Nusharik** [comment]
Yeah, firefox updated on my desktop and made it so I have to click contract now, much like on my laptop.  Disabling show controls does work too, so thank you Chibicon. Maybe ccd0 will fix it in a future update or something.

**Comment by losnappas** [comment]
I am not sure if it was always like this, but non-capturing 'click' listeners do nothing. Sometimes. I have no idea when/why. Was this always the case?
`$0.addEventListener('click', ()=>console.log("hi"),false)`
^nothing
`$0.addEventListener('click', ()=>console.log("hi"),true)`
^works
both work in youtube videos, though.
