### ISSUE TITLE
Quote highlighting broke since Chrome 64

### ISSUE THREAD

**Issue by Nekousagida** [ccd0/4chan-x#1787]
Look at this shit, the more I move the mouse around on a post link the worse it gets
![fuck off](https://user-images.githubusercontent.com/23322621/35512154-03812f54-04ff-11e8-87b1-b5180cde8c21.png)

**Comment by saxamaphone69** [comment]
What version of 4chan X, which userscript manager - or is it installed via the extension, and does it still occur when you disable the other extensions?

**Comment by Nekoragi** [comment]
Version 1.13.15.7 installed via extension
I disabled all the other extensions and it still occurs

**Comment by ccd0** [comment]
Have you tried disabling hardware acceleration?

**Comment by Nekoragi** [comment]
Still persists with no hardware acceleration and no extensions

**Comment by epicgirl1998** [comment]
chrome regression: https://crbug.com/807900
