### ISSUE TITLE
Sauce links search thumbnails as opposed to whole images

### ISSUE THREAD

**Issue by zetapulse** [ccd0/4chan-x#1788]
This has been an issue with me since starting to use 4chan X years ago, but at one point an anon mentioned a solution that worked. Unfortunately I lost all my settings & can't recall what the solution was. Tried replacing %IMG with %URL to no avail.
I know for a fact that I'm not the only one this happens to.

**Comment by saxamaphone69** [comment]
It's all there for you in the Sauce tab.

![suace](https://user-images.githubusercontent.com/877480/35550311-eac6d100-05dd-11e8-8d87-741b19fb17bd.JPG)

**Comment by zetapulse** [comment]
Unironically literally exactly identical line of code.
![literally exactly](https://user-images.githubusercontent.com/10345194/35564662-09c86ed4-060f-11e8-971b-176b79593175.png)

**Comment by ccd0** [comment]
Can you copy the URL that the link points to?

**Comment by saxamaphone69** [comment]
Oh wait it does the same for me lol (I rarely used reverse image search, my apologies)

Using `%IMG` links to `https://www.google.com/searchbyimage?image_url=https%3A%2F%2Fi.4cdn.org%2Fv%2F1517352286174.png&safe=off`

![error](https://user-images.githubusercontent.com/877480/35605900-05a11d7e-06a0-11e8-96b8-4c51621e5435.png)

**Comment by zetapulse** [comment]
Here's the link it generates for me:
https://www.google.com/searchbyimage?image_url=https%3A%2F%2Fi.4cdn.org%2Fv%2F1517370663898.jpg&safe=off
It's funny, the link is to the whole image, but when it reaches google it switches to the thumbnail at some point.
This has been an issue for a long time by the way, & I believe happens with the native extension as well. I'd confirm this but I can't seem to find the Greasemonkey scripts page, either because of the new FF or because I switched to Linux.

**Comment by saxamaphone69** [comment]
This may have fixed itself, at least on my setup.

![sauce-links](https://user-images.githubusercontent.com/877480/60431198-8a164280-9c42-11e9-9201-53be46785d5d.png)
