### ISSUE TITLE
cant reply after uninstalling the extension

### ISSUE THREAD

**Issue by daclaro** [ccd0/4chan-x#1808]
when I click a post number to reply nothing happens , this is ridiculous , I installed the extension but seems liek It didnt uninstall successfully , I'm using chrome

Looks like javascript is broken  on the entire site!great!

**Comment by daclaro** [comment]
Also I know about : 
Uninstalling: 4chan X disables the native extension, so if you uninstall 4chan X, you'll need to re-enable it. To do this, click the [Settings] link in the top right corner, uncheck "Disable the native extension" in the panel that appears, and click the "Save Settings" button.


there is no settings link , its greyed out

**Comment by ccd0** [comment]
Right here in the upper right corner.

![screenshot from 2018-02-10 20-44-09](https://user-images.githubusercontent.com/5894749/36069672-39fbfa20-0ea3-11e8-83c3-9bc4ef1d1390.png)
