### ISSUE TITLE
Noscript Captcha doesn't load in Firefox Nightly

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1817]
Submitter: Anonymous
Email: fakefuuxeen@outlook.com
Firefox Nightly v60.0a1 with uBlock Origin v1.15.4, ViolentMonkey v2.8.28 and 4Chan X v1.13.15.9
The non-Javascript captcha fails to load, instead an error message that says "Sorry, something went wrong. Please try reloading the page." appears. Enabling or disabling uBlock Origin, enabling or disabling private mode and cleaning cookies doesn't solve the problem.
Noscript captcha loads normally in Safari 11.0.3 with JS Blocker 5.3.0

**Comment by ccd0** [comment]
Please test the noscript captcha without 4chan X by disabling Javascript and using the top post form.
You should also test in a fresh profile to see if the difference might be due to some settings change you made, such as blocking referrers.

**Comment by anon-nona** [comment]
Tested it in a fresh firefox profile with Javascript disabled, Noscript text captcha works as expected. I will try changing my custom settings in about:config

**Comment by ccd0** [comment]
@onabi
Please test the noscript captcha without 4chan X by disabling Javascript and using the top post form.
You should also test in a fresh profile to see if the difference might be due to some settings change you made, such as blocking referrers.
