### ISSUE TITLE
Images all of a sudden stopped loading

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1820]
Submitter: butt
I haven't changed any settings on 4chan x since install.

Google Chrome Version 64.0.3282.140 (Official Build) (64-bit)
Tampermonkey 4.5
4chan x v1.14.0.7

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' * blob: data:". Either the 'unsafe-inline' keyword, a hash ('sha256-pqhfF8NR1vyXv078jTMmyvBV92BrlIRsUdbMbjD6ZeY='), or a nonce ('nonce-...') is required to enable inline execution.
script.js:24706 Uncaught TypeError: Cannot read property 'href' of null
    at Object.setClass (script.js:24706)
    at initStyle (script.js:24701)
    at MutationObserver.<anonymous> (script.js:4575)
catalog:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' * blob: data:". Either the 'unsafe-inline' keyword, a hash ('sha256-qkB1PU/a+wvvo3McJyM1bpMhFAUGg61n/3yjZt3/I+4='), or a nonce ('nonce-...') is required to enable inline execution.
catalog:1 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'unsafe-eval' * blob: data:". Either the 'unsafe-inline' keyword, a hash ('sha256-5oPliZ6sqtGGFau/OoLmkCh5+4Tt2opCczldOVWY53o='), or a nonce ('nonce-...') is required to enable inline execution.
core.min.1013.js:1 Refused to load the script 'https://utraffic.engine.adglare.net/?975717069' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".
core.min.1013.js:1 Refused to load the script 'https://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".
core.min.1013.js:1 Refused to load the script 'https://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

Only other script I'm using is the 4chan block fix

**Comment by mrtbonex** [comment]
I was the one who submitted this. I cleared my cache and now everything is fine.
