### ISSUE TITLE
New tab behavior

### ISSUE THREAD

**Issue by SkySkimmer** [ccd0/4chan-x#183]
When you post a reply to a thread / a new thread from the board page, 4chanX opens a new tab for that post. The new tab used to be next to your current tab (from which you posted) but is now put at the end of the tab list.
See also https://github.com/RequestPolicyContinued/requestpolicy/issues/488

**Comment by ccd0** [comment]
Not sure if you still have this issue, but make sure you have `browser.tabs.insertRelatedAfterCurrent` in your `about:config` set to true.

**Comment by ccd0** [comment]
So much of Greasemonkey has been rewritten since this time that this is most likely moot by now.  If you see similar issues in Greasemonkey 3.1 and `browser.tabs.insertRelatedAfterCurrent` is set the way you want it, open a new issue, preferably on the Greasemonkey tracker.
