### ISSUE TITLE
Cloudflare DDoS protection breaks XHR

### ISSUE THREAD

**Issue by nonijod** [ccd0/4chan-x#1834]
Recently Hiro upped the protection level in Cloudflare setting. As a result if CF thinks you're suspicious (for example by having updater with low timeout), it marks your IP and requires you to periodically see the "Checking your browser" page, which also drops a cf_clearance cookie that is then used with each request.
First annoyance is that, as people don't really have a reason to type in 4cdn.org, they won't see this page and won't know why isn't anything loading. All that has to be done in this situation is to open for example an image in new tab.
Second and the most significant annoyance is that anything requested via XHR, such as thread updater or JSON index stops working as it doesn't send the cookie with the request, to which CF responds with 503.
Non-XHR requests such as expand image work fine.

Firefox 52.6.0 ESR
Greasemonkey 3.17

**Comment by anonymau5** [comment]
![screenshot_20180215_132812](https://user-images.githubusercontent.com/2172796/36281894-2de75022-1254-11e8-8da2-c153b3b83850.png)
I'm guessing this is related.

**Comment by anonymau5** [comment]
Ok, I fixed it. First I disabled umatrix and 4chanx and refreshed. Then I renabled 4chanx and refreshed. Then I renabled umatrix and refreshed. It broke. I enabled cookies for 4cdn.org and that made it work again.

No idea if this is going to be a long term fix but we'll see.

**Comment by nonijod** [comment]
No cookies being blocked or nuked here.

**Comment by riesza** [comment]
The whole site has been turbo fucked for me all day today.
I think this is 
![vyclh 1](https://user-images.githubusercontent.com/1399263/36288641-0999fea0-12bc-11e8-8bc0-0fd77ab3d823.png)
from https://github.com/ccd0/4chan-x/issues/1746

**Comment by handpain** [comment]
4chanX Catalog is broken too

**Comment by ccd0** [comment]
merging into #1746
