### ISSUE TITLE
Updating threads connection error

### ISSUE THREAD

**Issue by hamwich15** [ccd0/4chan-x#1835]
I am unable to update threads to add newer psots. I get a connection error and am only able to see new posts by refreshing the page. This is only happening on Firefox

**Comment by riesza** [comment]
I have the same except it's also happening in 63.0.3239.108 Chromium.

**Comment by whoknows22** [comment]
Assuming this is the same issue I'm having, it's unrelated to 4chanX. No clue what's causing it.

**Comment by ccd0** [comment]
duplicate of #1746
