### ISSUE TITLE
Download Image From Gallery Mode Keybind [enhancement]

### ISSUE THREAD

**Issue by EDR-Hat** [ccd0/4chan-x#1839]
Add a keybind to download the currently viewed image from the gallery mode.
I originally thought this could be accomplished by having the mouse on the image, pressing the "menu" key (which right clicks the mouse in most contexts) and pressing v but something about gallery mode makes that not work. Anyway I know I can just right click then v but this addition would make it a little smoother.

**Comment by ccd0** [comment]
jakem72360 implemented this in #2850; it should be available in the next beta version.
