### ISSUE TITLE
OneeChan/StyleChan failing to load CSS

### ISSUE THREAD

**Issue by Icarus77** [ccd0/4chan-x#1844]
Is it possible for you to try and update OneeChan and/or StyleChan to fix the CSS failing to load? The page often-times just loads completely white and black with only basic 4chan X settings functioning.

Both of these scripts also no longer have the checkbox next to posts. Would appreciate a fix for this too if possible.

**Comment by KevinParnell** [comment]
I am now maintaining a working version of OneeChan and will continue to update it - https://github.com/KevinParnell/OneeChan
