### ISSUE TITLE
What does 4chan x actually need to properly run ?

### ISSUE THREAD

**Issue by qutetemp** [ccd0/4chan-x#1847]
What does 4chan x need on qutebrowser (or any browser for that matter ) ?
I'm using the latest git version with merged per domain settings and after already enabled local storage and javascript 4chan x still resets everytime I visit another 4chan page.

config.set('content.javascript.enabled', True, '*://*.4chan.org/*')
config.set('content.local_storage', True, '*://*.4chan.org/*')

I also tried enabling these settings globally.

**Comment by The-Compiler** [comment]
As per https://github.com/qutebrowser/qutebrowser/issues/3644 this is due to qutebrowser currently using local storage for GreaseMonkey, and @qutetemp having private browsing turned on.
