### ISSUE TITLE
Images opening in new page even though I have that turned off

### ISSUE THREAD

**Issue by drambit** [ccd0/4chan-x#1866]
I have my 4chan X set to expand images if I click on them, not open them in their own page. When I expand an image it initially does just expand within the thread, but then immediately redirects to the image link for that image, its very annoying.

**Comment by ccd0** [comment]
[More info](https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs) would be helpful to reproduce this.

**Comment by ccd0** [comment]
Oh, I see you posted some more in #1872. Closing this issue in favor of that one then.
