### ISSUE TITLE
Connection Error While Posting

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1868]
Submitter: Mono
Email: wierdmonkeycat@gmail.com
Hi, I can't seem to post anything. I've tested it with Adblock disabled, but the issue seems to persist. Here's the errors that I found in the console when it occurs.

171378396:1 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
s @ 171378396:1
core.min.1014.js:1 Refused to load the script 'https://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

(anonymous) @ core.min.1014.js:1
VM62:3084 Refused to load the script 'blob:https://boards.4chan.org/cd44591d-1b01-443d-99b9-98865d3aab46' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

t @ VM62:3084
VM62:194 Refused to load the script 'https://loadercdn.com/match.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

(anonymous function) @ VM62:194
sys.4chan.org/a/post Failed to load resource: the server responded with a status of 502 (Bad Gateway)

**Comment by Willy156** [comment]
Is it just me or is 4chan completely dead? Last post was 3 hours on /a/ for me

**Comment by bakugo** [comment]
Yes, 4chan is dead.

If something doesn't work with 4chan X, you should check if it works without it before submitting an issue.
