### ISSUE TITLE
4chan X forgetting (you)s and last spot in threads 

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1875]
Submitter: Corridor89
Email: trhallway63@yahoo.com
I have already tried with cleared settings and, with cleared cookies even a fresh install of the extension, but occasionally 4chan x will unmark my posts and forget where I was in a thread, even for watched threads (I will refresh and the watcher will say there's hundreds of news posts). The extension isn't forgetting which threads I was watching or any of my other settings, though. And It seems to be inconsistent, when I lose place in one thread, it'll be the same as where it was in another thread.
I am using Chrome as my browser (66.0.3359.117) with the 1.13.15.10 version of 4chan X.

**Comment by Corridor89** [comment]
Here's the json I was `using`
``
[4chan X v1.13.15.10-1524250075448.txt](https://github.com/ccd0/4chan-x/files/1933660/4chan.X.v1.13.15.10-1524250075448.txt)

**Comment by Corridor89** [comment]
I guess the issue was tied to my chrome account. Even after nuking all of my file folders, 4chan X would still occasionally forget the (you) and thread data. I ended up just having to make a whole new chrome account. Not really happy about that, but so far it looks like it's fixed.

**Comment by Corridor89** [comment]
Never mind that didn't work either.

**Comment by DocHobo** [comment]
I've also been having the same problem, however I don't use syncing; I don't even have a proper account set up. 4chanx 1.13.15.10, tampermonkey 4.5, chrome  66.0.3359.117

**Comment by Corridor89** [comment]
Well I ended up turning off syncing and the issue still occurred. maybe it's a chrome in general issue?
Right now I am seeing if it'll happen when using 4chan's native extension.

**Comment by ccd0** [comment]
@Corridor89
Do you have 4chan X installed as a Tampermonkey script or an extension?

**Comment by Corridor89** [comment]
@ccd0 
I initially had the chrome extension installed, but have since switched to the tampermonkey extension.
Both have had the same issue with thread history and (you)s getting cleared. But the extension version happened far more frequently on average. Several times a day, vs tampermonkey script's once every couple days.

**Comment by Corridor89** [comment]
@ccd0 
I should also point out that I've had the same issue on multiple computers (second computer also running latest chrome + 4chan x extension version), but wasn't linked by something like a shared browser account

**Comment by gotmilk0112** [comment]
Also having this issue. Happens every 2-3 days.

**Comment by LainiWeiz** [comment]
Having a similar problem. At one point it forgot the last spot in threads I'd viewed but only for one board. Also had it forget threads I'd hidden at the same time as it lost (you)s and last positions. 
Initially thought it was because I'd loaded up the catalog in Incognito mode once but it's happened without doing that or visiting 4chan in any other browser or on any other computer.

**Comment by theanimedelusion** [comment]
hi ccd - I am getting this issue as well 

I made a thread, with it being auto added to my thread watcher - when I went back to catalog it was no longer there

I posted in a thread, and checked if it was added to the thread watcher - it was - when I went back to catalog it disappeared, and did not come back after going back into the thread.  

4chan X is not saving posts or threaads I made as mine 

I am using violentmonkey, with latest version of 4chan X - this only started after 4chan X updated.

**Comment by gotmilk0112** [comment]
I'll try using the beta version and see if that fixes it.

**Comment by theanimedelusion** [comment]
no longer getting this issue

**Comment by gotmilk0112** [comment]
Also hasn't happened to me yet, but it usually happened every 3 or 4 days, so I'll wait and see.

**Comment by theanimedelusion** [comment]
edit - nevermind, everything is still fucked 

another thing ccd - this happened even before the last few updates as well - when I try to clear the thread watcher, then go back to catalog, it doesn't actually clear. I think it's related to this issue

**Comment by Corridor89** [comment]
Nope. Can confirm that the beta script (1.14.0.15) (tampermonkey with chrome browser) still has the issue.

**Comment by ccd0** [comment]
Okay, I had another idea what this might be. Can you see if it still happens in v1.14.1.1 (current beta)?

**Comment by Corridor89** [comment]
Nope. Just happened again with 1.14.1.1 beta script

**Comment by swablueme** [comment]
I forgot to mention that the onset of the issue occurred a few weeks ago. Prior to this, I had never experienced (You)s and thread watcher progress being wiped.

**Comment by JackJohnJoe** [comment]
I'm having the problem on Firefox 60.0.1 with version 1.14.2.0. Sometimes it'll work for a while during the day, then stop. I can hide threads and instantly refresh and they'll be there.

**Comment by gotmilk0112** [comment]
Still happening every 2-3 days in version 1.14.2.0

desktop Chrome, version 67.0.3396.87

All manually-hidden threads show up again, all (You)s forgotten, and every watched thread is entirely marked as unread.

**Comment by swablueme** [comment]
For now it doesn't seem to be occurring 
4chan X | 1.14.2.1 extension
Chrome Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by theanimedelusion** [comment]
Data loss is still occurring for me - Posts which I have already read are still throwing up notifications when I return to the thread, still showing up as red in the thread watcher 

using 4chan X  1.14.2.1 [latest beta version] as of July 4th

**Comment by swablueme** [comment]
I think it's fixed for me

**Comment by gotmilk0112** [comment]
Yeah, I haven't lost data in like 2 weeks now. I think it's fixed.

**Comment by Corridor89** [comment]
I think it just happened to me again for the first time in a month. running chrome extension version  1.14.2.1 with chrome at Version 67.0.3396.99.
It cleared my thread history in some /co/ threads

**Comment by madprops** [comment]
This happened to me some days ago. I tried resetting settings, I tried localStorage.clear(), I tried reinstalling the script, I tried reinstalling violentmonkey .. any ideas?

**Comment by ccd0** [comment]
@madprops
You might be having the same issue as #2884. If it doesn't seem to be the same issue, open a new issue.

This old issue was probably caused by the problem whose resolution is discussed in #1910.
