### ISSUE TITLE
Redirect to HTTPS doesn't work in Edge

### ISSUE THREAD

**Issue by SuperIronBob** [ccd0/4chan-x#1876]
Redirect to HTTPS exits the script from initializing, and is set by default. Turning off the setting causes the script to load correctly. Manually navigating to the https protocol also works.

Specifically this location.replace isn't working:

if !$.perProtocolSettings and /\.4chan\.org$/.test(location.hostname) and (items['Redirect to HTTPS'] ? Conf['Redirect to HTTPS']) and location.protocol isnt 'https:'
    location.replace('https:' + location.host + location.pathname + location.search + location.hash)
    return

this constructs a url https:www.4chan.org

Changing 'https:' to 'https://' manually appears to fix this.

4chan-x ver: 1.14.0.12 
Tampermonkey: 4.6.5757

**Comment by mariojuniorjp** [comment]
@SuperIronBob How you get 4chan-x working on EDGE? Doesn't work for me.

**Comment by ccd0** [comment]
This should be fixed now.

**Comment by mariojuniorjp** [comment]
@ccd0 Now the script is working again on Edge! Thank you very much!
