### ISSUE TITLE
4chan CSS broken for some reason

### ISSUE THREAD

**Issue by mraper3** [ccd0/4chan-x#1880]
4chan's CSS seems broken for some reason, even when looking at 4chan-x's settings.  Images and console error messages, umatrix grid for an example page (the /a/ catalog page), and pic of Tampermonkey/script versions attached.  

![tampermonkey scripts](https://user-images.githubusercontent.com/5323781/39255602-881a9942-4872-11e8-98dd-10cd77a740c5.png)
![umatrix grid](https://user-images.githubusercontent.com/5323781/39255344-ec63413e-4871-11e8-9ab5-a748b96151c7.png)
![broken css even in 4chanx settings](https://user-images.githubusercontent.com/5323781/39253645-ed76d148-486d-11e8-8dcb-2f60e60a69e9.jpg)
![broken css](https://user-images.githubusercontent.com/5323781/39253646-ed8eb678-486d-11e8-8318-4025059617da.jpg)
![console error messages](https://user-images.githubusercontent.com/5323781/39253647-eda28568-486d-11e8-877e-3dcf3e5e7f1a.jpg)

**Comment by bakugo** [comment]
If you block those domains at the bottom of umatrix, 4chan will break its own CSS as an anti-adblocking measure.

Use ublock instead, it has filters that kill the script and stop this from happening.

**Comment by mraper3** [comment]
Weird, I have uBlock active already.  Attached is how uBlock looks on the /a/ catalog page.
![ublock on _a_ catalog](https://user-images.githubusercontent.com/5323781/39258047-997a1694-4878-11e8-8abf-9de13f091800.png)

**Comment by mraper3** [comment]
Huh; I set both columns for the three scripts settings to red, then refreshed.  The CSS is still broken, though.

**Comment by mraper3** [comment]
@bakugo, do you know which specific filter does this?

**Comment by bakugo** [comment]
The specific filter that should kill the script is this:
`4chan.org##script:inject(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)`
It should be in the "uBlock filters" built-in list, make sure it's up to date.
If it still doesn't work, see if it works with umatrix off. I've heard that running both ublock and umatrix at the same time can cause issues.

**Comment by mraper3** [comment]
OK, I see that filter in the built-in list, as you said.  That said, all my filters seem out-of-date (they have they little ! icon next to them), but when i update they fail with "a network error prevented the resource from being updated".  So it looks like I can't update the filter lists for some reason.

**Comment by mraper3** [comment]
4chan seems to be working fine now.  Only change I made after coming back from outside was to change all the 4cdn.org entries under the "frame" column in uMatrix to green; 4cdn.org was mentioned in #1746, which made me think it was somehow related.  So if it's alright with ccd0 et al, I'd like to keep this issue open while I use 4chan for a day or two and see if it's really back to normal for me, then close afterwards if it looks OK.

**Comment by mraper3** [comment]
4chan seems fine now, no further problems with the CSS.  Closing this issue.
