### ISSUE TITLE
Website is all broken and only text

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1886]
Submitter: Taj
Email: alcharani17@gmail.com
What the title says.

**Comment by SneedChuck** [comment]
Same here.
![picture 2018-05-04 13_14_11](https://user-images.githubusercontent.com/38987918/39641763-637f4b5a-4f9d-11e8-8a04-69c083263d45.png)

**Comment by vervik** [comment]
Same problem, 4chin probably again changed their advertisement system and it broke X.

**Comment by memeinventor** [comment]
getting cucked as well ova here fellas

**Comment by ccd0** [comment]
This is an anti-adblock script. Use uBlock Origin to block it.

**Comment by ccd0** [comment]
I updated the old workaround, but you should still use uBlock Origin.
