### ISSUE TITLE
No background, just text

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1889]
Submitter: bob
Email: bob@bob.bob
Since yesterday (around 2 am EST I think) there's no background when I use 4chan x, only a white page and the text. When I disable it the website runs just fine, I get the background and all. I uninstalled/reinstalled 4chan x (not sure if there's another way to update it, didn't see one. anyway, my version is 1.13.15.10), I don't use any scripts or anything like that. I'm on Chrome. Error message is [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.

**Comment by Confrade** [comment]
Same problem, version bug maybe?

**Comment by ccd0** [comment]
This is an anti-adblock script. Use uBlock Origin to block it.

**Comment by ccd0** [comment]
I updated the old workaround, but you should still use uBlock Origin.
