### ISSUE TITLE
catalog broken

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1891]
Whenever I try to use the catalog, the site layout breaks and the website reverts to a basic, imageless page, however if I am to use the index, everything works fine. The version I am currently using is 1.13.15.10, and the only errors in the console are the "content security policy" mentioned to be ignored in these scenarios.

**Comment by MistahM** [comment]
I've been having the same exact problem, I have no idea what's going on. Was it something with the site? Or is it Chrome?
Could really use some help, but it's good to know I'm not the only one.

**Comment by ccd0** [comment]
This is an anti-adblock script. Use uBlock Origin to block it.

**Comment by ccd0** [comment]
I updated the old workaround, but you should still use uBlock Origin.
