### ISSUE TITLE
Backgroud issue.

### ISSUE THREAD

**Issue by Confrade** [ccd0/4chan-x#1892]
![capturar](https://user-images.githubusercontent.com/38992969/39656780-d811ee60-4fd8-11e8-87c6-0360c27c631f.PNG)

Everytime i access with 4chanX this happens. How do i fix it?

**Comment by ccd0** [comment]
This is an anti-adblock script. Use uBlock Origin to block it.

**Comment by ccd0** [comment]
I updated the old workaround, but you should still use uBlock Origin.
