### ISSUE TITLE
CSS or something broken?

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1893]
Submitter: Nobody
Email: ilikeweirdstuffs@gmail.com
In individual threads once one scrolls down and reaches the bottom the style of the page disappears and it becomes plain text with images interspersed instead. 
In the board/catalog view, this happens as soon as the page finishes loading.
This happens since earlier today. There was an update to the extension today wasn't there.... fiiiix

**Comment by N0B0DY-1MP0R7AN7** [comment]
Well shit. I didn't realize everyone else was seeing this since the new ads went on.

**Comment by ccd0** [comment]
This is an anti-adblock script. Use uBlock Origin to block it.

**Comment by ccd0** [comment]
I updated the old workaround, but you should still use uBlock Origin.
