### ISSUE TITLE
4chan looses all formatting

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1894]
Submitter: edspear
Email: deviantedspear@gmail.com
Just a little thing i've noticed today hitting the bottom of a thread makes the entire thread lose formatting, and I cannot reply or anything.

Is this a exension issue or a 4chan itself issue

http://puu.sh/Agd1B/64c2af95a2.png

**Comment by Zyklon-Garrison** [comment]
Nah it's an extension issue. I disabled the extension and 4Chan works fine.

Here's an image of mine:
[http://prntscr.com/jdyjdw](url)

**Comment by ccd0** [comment]
I updated the old workaround, but you should still use uBlock Origin.

**Comment by Herny64** [comment]
Why is this not an 4chanX issue when it's only happening with 4chanX installed ?
I did the following:
-removed all addons and userscripts
-went to a thread on /g/
-scrolled to the bottom
-everything looks normal
-installed 4chanX 1.14.0.14
-went to same thread
-scrolled to the bottom
-breaks stylesheet
