### ISSUE TITLE
/int/ crashing

### ISSUE THREAD

**Issue by Confrade** [ccd0/4chan-x#1898]
Same problem as yesterday's, now on /int/ and on a few other boards too.
![aaa](https://user-images.githubusercontent.com/38992969/39665119-4fd8b14a-5065-11e8-8ec3-23959bef51c7.PNG)

**Comment by ccd0** [comment]
This is not an extension issue but an anti-adblock script added by Hiroyuki. You need to install a better adblocker. uBlock Origin works well.
