### ISSUE TITLE
All boards on 4chan loading strange with 4chan x

### ISSUE THREAD

**Issue by Kluel** [ccd0/4chan-x#1899]
All boards on 4chan load in a basic text format without any cataloging or images at all.   The board looks like normal for a second or so then switches to a strange plaintext format.   Disabling fixes the issue however.  

Any fixes or ideas?

**Comment by Kluel** [comment]
I have adblock instralled.  I dont think it changes anything.

**Comment by ccd0** [comment]
This is not an extension issue but an anti-adblock script added by Hiroyuki. You need to install a better adblocker. uBlock Origin works well.
