### ISSUE TITLE
worksafe board formatting breaking when using 4chanX

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1900]
Submitter: Chris
Email: thesyndromeis@hotmail.com
Hi, I've been using 4chanX for some time with no issues, but yesterday the formatting broke on worksafe boards, I don't visit /b/ but I tested it since I know that it has run from a different source for a number of years, and sure enough it appears fine; also I tested by disabling 4chanX and refreshing worksafe boards and with 4chanX disabled they appear fine; I've included a copy of the errors I found in the chrome console in case they help
Refused to load the script '<URL>' because it violates the following Content Security Policy directive: "script-src <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> 'self' 'unsafe-inline' 'unsafe-eval'".

:48 Mixed Content: The page at 'https://www.4chan.org/frames' was loaded over HTTPS, but requested an insecure image 'http://img.2ch.sc/img/4_0217.png'. This content should also be served over HTTPS.
(unknown) WebSocket connection to 'wss://a.ekansovi.com/wsp' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
WrappedWebSocket
(index):1 [Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
s @ (index):1
VM214:3832 Refused to load the script 'blob:https://boards.4chan.org/87d81e9c-e3d2-41bd-bdaa-99525b469083' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

**Comment by TT-392** [comment]
I am getting the same issue with qutebrowser and oneechan (also without oneechan) the wierd thing is that I had the same issue with an older version of 4chan x (it was why I upgraded 4chan x)

**Comment by ccd0** [comment]
This is not an extension issue but an anti-adblock script added by Hiroyuki. You need to install a better adblocker. uBlock Origin works well.

**Comment by TT-392** [comment]
The issue does seem to appear only with the 4chan x plugin, so 4chan x has at least some form of influence. I am using qutebrowser and I expect a lot of people on 4chan to be using browsers like qutebrowser so "a different adblocker" is simply not an option.
