### ISSUE TITLE
4chanX is breaking the formatting every time you scroll to the bottom

### ISSUE THREAD

**Issue by MewMew7** [ccd0/4chan-x#1902]
Whenever you reach the bottom of any thread, for some reason it crashes the formatting completely. The same thing also happens in 4chanX catalog (however, it's always instant because catalog takes some time to load the thumbnails and thus you see the bottom of the page, which causes the glitch).  Seems to happen on every page, doesn't happen with pages that don't use 4chanX (such as archives and standard catalogs).

![ss 2018-05-05 at 11 46 34](https://user-images.githubusercontent.com/34717730/39667451-51016076-50bf-11e8-9052-7f8cca3a2c4c.png)
)

**Comment by sdziscool** [comment]
Also happens to me, I already had the same problem a few days back when I was still running 1.13.9, but back then just updating to 1.13.15 fixed it. Now the problem has returned.

**Comment by ccd0** [comment]
This is not an extension issue but an anti-adblock script added by Hiroyuki. You need to install a better adblocker. uBlock Origin works well.
