### ISSUE TITLE
uBlock Origin won't work

### ISSUE THREAD

**Issue by gorudohidu** [ccd0/4chan-x#1904]
Hello
We are suffering from a certain problem called "4chanX whiteback" and ccd0-san tells us that introducing uBlock Origin is a good way to fix.
However even though I downloaded it from chrome web store the situation won't change.
What means is left for me?

**Comment by ubone** [comment]
could you explain whiteback? do you mean white background of the page or a white flash? if so clear the theme cookie and use `@import "https://s.4cdn.org/css/tomorrow.673.css";` instead
