### ISSUE TITLE
Chrome 68 captcha issues

### ISSUE THREAD

**Issue by chrome68issues** [ccd0/4chan-x#1906]
In Chrome 68 (68.0.3418.2 and earlier version too) you encounter issues when posting on 4chan.

You can post once in a thread and then captcha stops working. Sometimes just for that thread sometimes for others too.

Tested with the exact some configuration without 4chan-x and the issue disappears.

Inspecting the captcha iframe and expanding document -> html -> body and just clicking on 

`<div class="rc-anchor rc-anchor-normal rc-anchor-light">`

Forces it to load apparently because then you can right click on reload and the captcha loads normally. Until you refresh the page or post. 

I made a video to demonstrate.

https://my.mixtape.moe/upwsun.mp4

This issue does not appear with 4chanx disabled on the exact same configuration on  chrome 65 nor on chrome 68

This happens with both stable and beta 4chanx

**Comment by anonymau5** [comment]
I'm seeing this on Chrome 67 as well.
Version 67.0.3396.30 (Official Build) beta (64-bit)

**Comment by anonymau5** [comment]
A gentle bump, this is a rather annoying issue.  Makes you really value the one post you get in a thread.

**Comment by ccd0** [comment]
Have you tried different captcha settings?

**Comment by anonymau5** [comment]
Yes, I have tried both the no JS captcha and the JS enabled captcha.  I can fill out one captcha with success then every captcha after that in that thread does not load.  The behavior seen is the same as in the video posted above.

**Comment by ccd0** [comment]
>The behavior seen is the same as in the video posted above.

What I see in the video is the checkbox not showing up. What happens for the no JS captcha?

Just to check, are you taking into account the fact that you can post for 3 minutes without a captcha after a successful reply?

What happens if you turn off "Captcha Fixes"? What are all the captcha settings you're using?

**Comment by anonymau5** [comment]
I had Captcha Fixes on and No JS on.  I disabled Captcha Fixes.  That seems to have fixed it for both Captchas.  
I've never had the no captcha posting, I always have to solve one.

**Comment by anonymau5** [comment]
Correction, the no JS one does not load.  The regular one loads fine with captcha fixes disabled.

**Comment by ccd0** [comment]
Are you using the extension or the userscript?
Do you have cookies disabled or are using any other extensions?

**Comment by anonymau5** [comment]
I did my testing within incognito with ublock origin and 4chanx enabled.

**Comment by chrome68issues** [comment]
Seems to be fixed with the 1.14.1.0, no idea why, at least I'm not having this issue anymore

> What I see in the video is the checkbox not showing up. What happens for the no JS captcha?

Nothing happens the no JS captcha doesn't load at all. 

>Just to check, are you taking into account the fact that you can post for 3 minutes without a captcha after a successful reply?

Yes, you could post for 3 minutes after without captcha, but after 3 minutes have passed you couldn't post anymore, since it wouldn't give you any captcha to solve no matter the settings.

I was using the userscript, still am, and since updating it to 1.14.1 I had no issues with captcha at all, not with or without captcha fixes or no JS. 

Tried plenty of different versions before though, both userscript and extension, the same still happens on 1.13.15 and 1.14.0  , not on the new one though.

**Comment by ccd0** [comment]
Might be related to Hiro's anti-adblock script then. I think we have that successfully blocked now, but if you have trouble again, try installing/enabling uBlock Origin.

**Comment by anonymau5** [comment]
Thanks for the fantastic work.  I wish Hiroshimoot would just leave shit alone.  I use Ublock Origin by default.

**Comment by captchadead** [comment]
Shamelessly bumping.

I get the same problem too using chromium 68.0.3424. However the problem is a bit unique, the JS recaptcha only doesn't produce the UI (so if you know the location of tick button, you can just tick it and you'll go) inside the thread. Outside the thread, like in the catalogue, it produces its UI.
