### ISSUE TITLE
let us use quick-reply and 4chan-x normally; even if the thread is archived. 

### ISSUE THREAD

**Issue by alptest** [ccd0/4chan-x#1912]
![4chan-x quick-reply is broken in archived threads](https://user-images.githubusercontent.com/32177419/39952604-aede1bde-5589-11e8-8a4d-27b2c4d93de5.png)

let us use quick-reply and 4chan-x normally; even if the thread is archived. 

i've brought this up in the past many times; but it never happened. so i'll explain it again here. 

＞bookmark a thread for later
＞go back to the thread
＞it's archived
＞you have replies that you want to reply to by making a new thread
＞click the post-number to bring up quick-reply
＞quick-reply doesn't come up
＞for no reason!! 

i don't see any reason why quick-reply -shouldn't- come up. especially when it already comes up even if the thread is archived and you were still in the thread when it wasn't archived. i don't really see any practical purpose to this other than either "i added this extra code to be fancy for no reason", "i don't see a reason why i need this so i dictate that no one needs it for no reason", and "i took out this useful feature for no reason"; to be honest.  

and. i recall this working in the past. so i don't see any reason why it shouldn't work now. there's no real down-side. either way you can't post in the thread. but with this option you can work on text in your quick-reply or psuedo-notepad or psuedo-pastebin here. useful. makes sense. 

i usually make threads on /b/ or /g/. but i decided to make it here this time. 

ccd0 said something like "don't make me use a tripcode" on /g/. so. don't make me make a thread on 4. 

i hope that everyone doesn't go "why would you ever need that if it's archived. we don't need that." for no reason. again. 

by the way i was told in the past that i could post here anonymously. but i don't see any clear way to. attempting to look it up just leads to random things unrelated to what i'm looking for but contains the keywords i used to look it up. 

also i can't delete posts here. which is annoying. it's like i don't even have ownership of my own posts. if it can't be changed then github is- ... not good. so it'd be swell to post elsewhere or continue to post on /g/ or something etc.; relatively. i'd probably just like to make this issue and delete it. so if you want to fix the issue and then delete this then this is fine. if you could anonymize me then that'd be cool too. 

this isn't intended to be hostile, offensive, insulting, etc.. in anyway. i hope that you don't take it wrong. 

i'm just frustrated that i'll have to type out ">>" and copy-paste every post manually in a notepad if i want to reply to them. i'd also have to press enter and add ">" and highly and copy-paste the text to the right-side of it if i want to quote them or "green-text" quote them. 

please fix this as fast as possible. 

too long; didn't read: let us use quick-reply and 4chan-x normally; even if the thread is archived. as fast as possible. 

thank you in advanced; if fixed. 

thank you.

**Comment by ubone** [comment]
@ccd0 request reopen issue

## reason
far too often write a reply only to find out the thread is dead
## request
make this feature optional

**Comment by ccd0** [comment]
@ubone

That could happen before this change by leaving open a thread which eventually died. In either case, the Quick Reply submit button should indicate the thread is dead. If you have ideas for a better UI, please post them in a new issue.

You could also consider going to the archive and copypasting your reply as a ghost reply.

**Comment by ubone** [comment]
I don't really care about replying like op so that's ok
I'll think about the UI
