### ISSUE TITLE
"Image Expansion" crashed on node Post No.37920853 (k).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1918]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.13.14.12 userscript
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0
URL: https://boards.4chan.org/k/thread/37920853

TypeError: el is undefined
userScript/</$</$.on@user-script:4chan-X/4chan%20X:5125:7
node@user-script:4chan-X/4chan%20X:13584:7
userScript/</Callbacks</Callbacks</Callbacks.prototype.execute@user-script:4chan-X/4chan%20X:5829:13
fn@user-script:4chan-X/4chan%20X:25405:9
softTask@user-script:4chan-X/4chan%20X:25409:16
callbackNodesDB@user-script:4chan-X/4chan%20X:25420:14
initThread@user-script:4chan-X/4chan%20X:25374:16
initReady@user-script:4chan-X/4chan%20X:25318:16
execTask@user-script:4chan-X/4chan%20X:5237:14

`<div class="postContainer opContainer" id="pc37920853" data-full-i-d="k.37920853"><div id="p37920853" class="post op"><div class="postInfoM mobile" id="pim37920853"> <span class="nameBlock"><span class="name">Anonymous</span><br><span class="subject"></span> </span><span class="dateTime postNum" data-utc="1526447621">05/16/18(Wed)01:13:41 <a href="#p37920853" title="Link to this post">No.</a><a href="javascript:quote('37920853');" title="Reply to this post">37920853</a></span></div><div class="file" id="f37920853"><div class="fileText" id="fT37920853"><span class="file-info">1443049669792.jpg  <a href="https://i.4cdn.org/k/1526447621658.jpg" download="1443049669792.jpg" class="fa fa-download download-button"></a> (236 KB, 851x1517)</span><span class="fileText-original">File: <a href="//i.4cdn.org/k/1526447621658.jpg" target="_blank">1443049669792.jpg</a> (236 KB, 851x1517)</span></div><a class="fileThumb" href="//i.4cdn.org/k/1526447621658.jpg" target="_blank" data-m=""><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">236 KB JPG</div></a></div><div class="postInfo desktop" id="pi37920853"><input name="37920853" value="delete" type="checkbox"> <span class="subject"></span> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1526447621">05/16/18(Wed)01:13:41</span> <span class="postNum desktop"><a href="#p37920853" title="Link to this post">No.</a><a href="javascript:quote('37920853');" title="Reply to this post">37920853</a></span><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a><span class="container"></span></div><blockquote class="postMessage" id="m37920853">/k/, it's almost time for summer antics, and I ask your help in building the ultimate potato cannon. I will definitely make wax/gravel slugs like that one anon. But I ask for your assistance. Design ideas. Ammunition concepts. How to rifle it. Interchangeable barrels. Etc. Go crazy. Let's create a nightmare and a blueprint for it.</blockquote></div></div>`

**Comment by ccd0** [comment]
duplicates: #1919 #1920 #1921 #1922 #1923 #1924 #1925 #1926 #1927

If you're having this issue, please let me know what other extensions / userscripts you have installed.

**Comment by Trodrigs1120** [comment]
I'm encountering this issue myself. 
I am using 4chanx inside of grease monkey and no other user scripts. Other than that its just adblock plus.

**Comment by ccd0** [comment]
#1928 #1929 #1930

**Comment by ccd0** [comment]
#1931 #1932 #1934 #1937 #1938 #1939 #1940 #1941 #1942 #1943 #1945 #1946 #1947 #1948 #1950 #1951 #1952

**Comment by ccd0** [comment]
also #1944

**Comment by ccd0** [comment]
one report now that's not from a pre-fix version number: #1955

**Comment by ccd0** [comment]
Merging into #1885
