### ISSUE TITLE
"Image Expansion" crashed on node Post No.172099913 (pol).

### ISSUE THREAD

**Issue by 13lackWidow** [ccd0/4chan-x#1939]
Script: 4chan X ccd0 v1.13.14.10 userscript
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0
URL: https://boards.4chan.org/pol/thread/172099913

TypeError: el is undefined
userScript/</$</$.on@user-script:4chan-X/4chan%20X:5275:7
node@user-script:4chan-X/4chan%20X:13728:7
userScript/</Callbacks</Callbacks</Callbacks.prototype.execute@user-script:4chan-X/4chan%20X:5979:13
fn@user-script:4chan-X/4chan%20X:25549:9
softTask@user-script:4chan-X/4chan%20X:25553:16
callbackNodesDB@user-script:4chan-X/4chan%20X:25564:14
initThread@user-script:4chan-X/4chan%20X:25518:16
initReady@user-script:4chan-X/4chan%20X:25462:16
execTask@user-script:4chan-X/4chan%20X:5387:14

`<div class="postContainer opContainer" id="pc172099913" data-full-i-d="pol.172099913"><div id="p172099913" class="post op"><div class="postInfoM mobile" id="pim172099913"> <span class="nameBlock"><span class="name">Anonymous</span> <span class="posteruid id_tNZFab3Y">(ID: <span class="hand" title="Highlight posts by this ID">tNZFab3Y</span>)</span> <span title="United States" class="flag flag-us"></span><br><span class="subject">pol humor</span> </span><span class="dateTime postNum" data-utc="1526679886">05/18/18(Fri)17:44:46 <a href="#p172099913" title="Link to this post">No.</a><a href="javascript:quote('172099913');" title="Reply to this post">172099913</a></span></div><div class="file" id="f172099913"><div class="fileText" id="fT172099913"><span class="file-info"><a href="https://i.4cdn.org/pol/1526679886304.png" target="_blank">efZVd8J.png</a> <a href="https://i.4cdn.org/pol/1526679886304.png" download="efZVd8J.png" class="fa fa-download download-button"></a> (56 KB, 1080x398)</span><span class="fileText-original">File: <a href="//i.4cdn.org/pol/1526679886304.png" target="_blank">efZVd8J.png</a> (56 KB, 1080x398)</span> <a target="_blank" class="sauce" href="//imgur.com/efZVd8J">imgur</a> <a target="_blank" class="sauce" href="https://www.google.com/searchbyimage?image_url=https%3A%2F%2Fi.4cdn.org%2Fpol%2F1526679886304.png&amp;safe=off">google</a> <a target="_blank" class="sauce" href="https://www.yandex.com/images/search?rpt=imageview&amp;img_url=https%3A%2F%2Fi.4cdn.org%2Fpol%2F1526679886304.png">yandex</a> <a target="_blank" class="sauce" href="https://tineye.com/search?url=https%3A%2F%2Fi.4cdn.org%2Fpol%2F1526679886304.png">tineye</a> <a target="_blank" class="sauce" href="//iqdb.org/?url=https%3A%2F%2Fi.4cdn.org%2Fpol%2F1526679886304.png">iqdb</a> <a target="_blank" class="sauce" href="https://whatanime.ga/?auto&amp;url=https%3A%2F%2Fi.4cdn.org%2Fpol%2F1526679886304.png">wait</a> <a target="_blank" class="sauce" href="https://saucenao.com/search.php?url=https%3A%2F%2Fi.4cdn.org%2Fpol%2F1526679886304.png">saucenao</a> <a target="_blank" class="sauce" href="http://exif.regex.info/exif.cgi?imgurl=https%3A%2F%2Fi.4cdn.org%2Fpol%2F1526679886304.png">regex</a></div><a class="fileThumb" href="//i.4cdn.org/pol/1526679886304.png" target="_blank"><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">56 KB PNG</div></a></div><div class="postInfo desktop" id="pi172099913"><input name="172099913" value="delete" type="checkbox"> <span class="subject">pol humor</span> <span class="nameBlock"><span class="name">Anonymous</span> <span class="posteruid id_tNZFab3Y">(ID: <span class="hand painted" title="Highlight posts by this ID" style="color: rgb(0, 0, 0); background-color: rgb(205, 202, 134);">tNZFab3Y</span>)</span> <span title="United States" class="flag flag-us"></span></span> <span class="dateTime" data-utc="1526679886">05/18/18(Fri)16:44:46</span> <span class="postNum desktop"><a href="#p172099913" title="Link to this post">No.</a><a href="javascript:quote('172099913');" title="Reply to this post">172099913</a></span><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a><span class="container"></span></div><blockquote class="postMessage" id="m172099913"></blockquote></div></div>`

**Comment by ccd0** [comment]
Install uBlock Origin
