### ISSUE TITLE
Mark posts as yours

### ISSUE THREAD

**Issue by unknown--** [ccd0/4chan-x#195]
Basically you would go into the menu and it would have a button to 'tag' a post which would then let you know when other people reply to it. Much like how you receive notifications when people reply to your own posts. It could also be marked like your own posts are with that border on the left side i.e. `.quotesYou`

**Comment by unknown--** [comment]
One example would be when there is a connection error but your post still goes through. It doesn't get marked as your own and thus you don't get notified of any replies.

**Comment by ccd0** [comment]
Requested in #651
>A function (maybe in the post's arrow menu?) to mark that post as "sent by the user" would be nice if, for example, I posted from another device and want to have notifications/new replies shown on the computer running 4chan X.

and

https://rbt.asia/g/thread/S53725582#p53731068

Related but slightly different: #844
>Something I've been interested in for quite a while is marking posts so their replies get a similar marker when quoted. It could say (Lit) as in highlight, or (Mark), or a copy of (You). Perhaps a custom name you can fill in yourself? What it says doesn't really matter, but replies to it will stand out similar to the OP's and yours.

**Comment by ccd0** [comment]
sanitysama in https://github.com/ccd0/4chan-x/issues/1039:
> I use 4chan on mobile more than I use it on my desktop. Obviously I don't get desktop notifications for replies made on my phone so I wanted to ask if you could add a feature to take ownership of a post made from another device. It'd also be cool to be able to mark interesting posts made by other people and watch the replies they receive. Thanks.

**Comment by ccd0** [comment]
MisakaImoutoWaifu in #1054:
> It'd be useful if there was a way to manually fix 4chan/4chan X/Your browser losing track of which posts are yours from the drop down menu.

**Comment by ccd0** [comment]
This is in the stable version now.
