### ISSUE TITLE
4chanX crashing on Opera

### ISSUE THREAD

**Issue by Confrade** [ccd0/4chan-x#1953]
![capturar](https://user-images.githubusercontent.com/38992969/40441281-fd94887e-5e96-11e8-85c0-ed375048d975.PNG)

Started in a few threads and now the whole website is going to textmode.

**Comment by Corridor89** [comment]
yeah, it's crashing chrome too. 4chan's css keeps breaking

**Comment by ccd0** [comment]
install uBlock Origin
