### ISSUE TITLE
Broken CSS

### ISSUE THREAD

**Issue by sinfex** [ccd0/4chan-x#1954]
It broke a few hours ago when I was on /g/, I tried messing around with an ancient and unsupported extension (4chan plus) before deciding to use StyleChan, it worked temporarily but now the CSS is broken along all SFW boards, NSFW boards are fine at the moment.
![broken css](https://user-images.githubusercontent.com/39570790/40450586-01d22258-5e91-11e8-98f6-e8c45ffef978.JPG)

**Comment by sinfex** [comment]
Already have ublock origin installed.

**Comment by ccd0** [comment]
enable it, update its filters, update 4chan X

**Comment by Smithy3** [comment]
It might just be a coincidence, but this also happened to me a couple of hours ago with fully updated uBlock Origin. All seems fine now though, but I don't think its an isolated thing. There was also another issue on this opened at the same time by someone else but it seems to be removed now.

**Comment by sinfex** [comment]
I updated 4chan X and updated the filters, CSS is still broken.

**Comment by ccd0** [comment]
What version of 4chan X are you running?

**Comment by sinfex** [comment]
I'm running ungoogled chromium with tampermonkey, I disabled 4chan X and renabled it several times, switch the style from tomorrow to yotsuba and now its working just fine, I'm not too sure why that worked.

**Comment by sinfex** [comment]
Spoke to soon, the CSS broke when I try to load a thread.

**Comment by ccd0** [comment]
Do you have "uBlock Filters" turned on in uBlock Origin?

**Comment by sinfex** [comment]
Yes.

**Comment by ccd0** [comment]
Also might be helpful to restart your browser if you haven't done that since updating everything.

**Comment by sinfex** [comment]
I restarted, disabled and enabled both 4chan X and ublock, CSS is still broken on blue boards.

**Comment by Rerunto** [comment]
I've also been getting this too. I'm using Firefox with uBlock Origin, and Tampermonkey but switched to Violentmonkey to see if that does anything, and version 1.14.1.1 of 4chan X. Everything's up to date.

**Comment by ccd0** [comment]
Can you post uBlock Origin's log when you reload one of the pages?

**Comment by sinfex** [comment]
I switched to palemoon and everything is working just fine, even on version 1.14.0.15, although I'm getting an "error fetching archive data" error, it's better than not working at all.

**Comment by ccd0** [comment]
>error fetching archive data

for that see #1853

Other comments about the anti-adblock script getting through should go to #1885

**Comment by ccd0** [comment]
I've noticed the people this issue so far post-1.14.0.15 are using Tampermonkey. It might be helpful to go to Tampermonkey's settings, change `General > Config mode` to `Advanced`, then scroll down to `Experimental > Inject Mode` and change it to `Instant`. Alternately you can try another userscript engine or the Chrome extension version.
