### ISSUE TITLE
"Image Expansion" crashed on node Post No.10644406 (ck).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1955]
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.14.1.1 userscript
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
URL: https://boards.4chan.org/ck/thread/10640689

TypeError: el is undefined
$</$.on@https://boards.4chan.org/ck/thread/10640689:4794:7
node@https://boards.4chan.org/ck/thread/10640689:13662:7
Callbacks</Callbacks</Callbacks.prototype.execute@https://boards.4chan.org/ck/thread/10640689:5506:13
fn@https://boards.4chan.org/ck/thread/10640689:24917:9
softTask@https://boards.4chan.org/ck/thread/10640689:24921:16

`<div class="postContainer replyContainer" id="pc10644406" data-full-i-d="ck.10644406"><div id="sa10644406"><a class="hide-reply-button" href="javascript:;"><span class="fa fa-minus-square-o"></span></a></div><div id="p10644406" class="post reply"><div class="postInfoM mobile" id="pim10644406"> <span class="nameBlock"><span class="name">Anonymous</span><br></span><span class="dateTime postNum" data-utc="1527066427">05/23/18(Wed)05:07:07 <a href="#p10644406" title="Link to this post">No.</a><a href="javascript:quote('10644406');" title="Reply to this post">10644406</a></span></div><div class="postInfo desktop" id="pi10644406"><input name="10644406" value="delete" type="checkbox"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1527066427">12:07:07 May 23</span> <span class="postNum desktop"><a href="#p10644406" title="Link to this post">No.</a><a href="javascript:quote('10644406');" title="Reply to this post">10644406</a></span><a class="menu-button" href="javascript:;"><i class="fa fa-angle-down"></i></a><span class="container"></span></div><div class="file" id="f10644406"><div class="fileText" id="fT10644406"><span class="file-info">148 KB <a href="javascript:;" class="fa fa-times quick-filter-md5"></a> 1229x995 <a href="https://i.4cdn.org/ck/1527066427879.jpg" download="1526435963609.jpg" class="fa fa-download download-button"></a> <a href="https://i.4cdn.org/ck/1527066427879.jpg" target="_blank">1526435963609.jpg</a></span><span class="fileText-original">File: <a href="//i.4cdn.org/ck/1527066427879.jpg" target="_blank">1526435963609.jpg</a> (148 KB, 1229x995)</span></div><a class="fileThumb" href="//i.4cdn.org/ck/1527066427879.jpg" target="_blank"><div data-tip="" data-tip-cb="mShowFull" class="mFileInfo mobile">148 KB JPG</div></a></div><blockquote class="postMessage" id="m10644406"><a href="#p10644057" class="quotelink">&gt;&gt;10644057</a><a class="hashlink" href="https://boards.4chan.org/ck/thread/10640689#p10644057">#</a></blockquote></div></div>`

**Comment by ccd0** [comment]
Try installing / enabling uBlock Origin.

**Comment by ubone** [comment]
uBO (with only uBOs filters) helped
