### ISSUE TITLE
[Feature Request] Highlight things in a post that are getting filtered

### ISSUE THREAD

**Issue by gotmilk0112** [ccd0/4chan-x#1956]
I've built up a whole lot of filters over the years, really just image MD5 and Comment filters, but often times I come across a thread that is getting filtered and I have no fucking clue why it's getting filtered.

I checked every single word in the post and nothing comes up on the comment filter. I checked the image MD5 and it's not being filtered. I checked the filesize, filename, everything...as far as I can tell, nothing about this thread should be getting caught in my filters, and yet it's still being filtered.

Can there be a feature to highlight filtered things instead of filtering? Just as a kind of debug mode to see what is getting filtered.

**Comment by saxamaphone69** [comment]
#126 & #867
