### ISSUE TITLE
4chanX crashing on Opera

### ISSUE THREAD

**Issue by Confrade** [ccd0/4chan-x#1957]
Everytime i enter a new board or thread it goes on text mode again and again. I opened another "Issue" yesterday but it got closed? Tampermonkey problems maybe?

**Comment by ccd0** [comment]
Do you have uBlock Origin installed and enabled?

**Comment by Confrade** [comment]
Nope, nothing.

**Comment by ccd0** [comment]
You should start by installing uBlock Origin to block this script.
Also this should continue in #1885; no need to keep opening duplicate issues.

**Comment by Confrade** [comment]
Ok, thanks. Sorry for the trouble.
