### ISSUE TITLE
missing X for " Quick filter MD5: %f " and remove from watchlist buttons

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1958]
since 1.14.1.1 or 1.14.1.0 the X to filter images and the X to remove threads from the watchlist disappeared
firefox 60 violent monkey

**Comment by ccd0** [comment]
Couldn't reproduce. Using any other extensions? Try turning them off temporarily to see if there's a conflict.

**Comment by ubone** [comment]
[mozilla's binary](http://ftp.mozilla.org/pub/firefox/releases/60.0.1/linux-x86_64/)
Decentraleyes	2.0.4
Javascript Control	1.1
Toggle Website Colors	2.0.1
Violentmonkey	2.9.4
disabled them, reset 4chX, refreshed ff /nuked the ff profile/, installed 4chX again, removed /etc/hosts
the x is not visible :(

**Comment by ubone** [comment]
did the same as the previous post /installed violent monkey and 4chx/ but in a new profile, X is visible, my bad

**Comment by ubone** [comment]
did the same as the previous post /installed violent monkey and 4chx/ but in a new profile
X is visible, my bad

**Comment by ubone** [comment]
@ccd0 found the issue

about:preferences#general
Fonts & Colors
Advanced
Allow pages to choose their own fonts, instead of your selections above

if unchecked x vanish (didn't up until recent versions) but leaving it checked makes pages unreadable for me - for example [ddg](http://ddg.gg/lite/?q=test), and enables easier user tracking by probing available os fonts

i think you could include that the x icon from font awesome in 4chanx?
or what commit changed it

**Comment by ubone** [comment]
this is weird because the download button does not disappear @ccd0

**Comment by ubone** [comment]
https://fontawesome.com/v4.7.0/icon/times
this is not visible but all the other `times` icons  are visible
could it be fontconfig ?
could you replace `fa-times` with `fa-times-circle` ?

```
grep '>times<' /etc/fonts/conf.d/*
/etc/fonts/conf.d/30-metric-aliases.conf:98:      <family>Times</family>
/etc/fonts/conf.d/30-metric-aliases.conf:105:     <family>Times</family>
/etc/fonts/conf.d/30-metric-aliases.conf:112:     <family>Times</family>
/etc/fonts/conf.d/30-metric-aliases.conf:457:     <family>Times</family>
/etc/fonts/conf.d/30-metric-aliases.conf:488:     <family>Times</family>
/etc/fonts/conf.d/30-metric-aliases.conf:517:     <family>Times</family>
/etc/fonts/conf.d/45-latin.conf:82:             <family>Times</family>
/etc/fonts/conf.d/60-latin.conf:20:                     <family>Times</family>
/etc/fonts/conf.d/69-nimbus-roman.conf:24:      <family>Times</family>
/etc/fonts/conf.d/69-nimbus-roman.conf:30:    <family>Times</family>
/etc/fonts/conf.d/69-urw-fallback.conf:145:      <family>Times</family>
/etc/fonts/conf.d/69-urw-fallback.conf:219:    <family>Times</family>
```

**Comment by ccd0** [comment]
You can change it yourself by overriding the CSS.

**Comment by ubone** [comment]
`.quick-filter-md5:before { content: "\f057"; }`

solved
