### ISSUE TITLE
AdGlare?

### ISSUE THREAD

**Issue by krypxern** [ccd0/4chan-x#1967]
uBlock Origin has started blocking 4chan X because 4chan X is trying to access AdGlare.net

Was there malware implanted in this recently?

**Comment by Boldwin** [comment]
Same issue here, 4chan X suddenly no longer works at all unless I disable uBlock.

**Comment by ccd0** [comment]
You can see for yourself that there is nothing related to AdGlare.net in 4chan X. I believe that has been an ad server used on 4chan for some time now, though.
