### ISSUE TITLE
Error evaluating Tomorrow [Modded]'s theme.customCCS

### ISSUE THREAD

**Issue by oluapris** [ccd0/4chan-x#1971]
Chrome's been giving me this error every time I open a thread today. Everything seems fine but I still dunno what it means.

![chrome_2018-06-01_23-12-04](https://user-images.githubusercontent.com/11916733/40870023-15bde90e-65f4-11e8-9ded-34eb7b14b63b.png)

**Comment by gitmage** [comment]
I'm also having a similar issue. Trying to use the Tomorrow theme is throwing an error saying something about "eval()".

**Comment by speedymaan** [comment]
I'm getting this error too, but I think it's a OneeChan/StyleChan issue.

[https://github.com/nebukazar/OneeChan/issues/109](https://github.com/nebukazar/OneeChan/issues/109)

**Comment by ccd0** [comment]
related: #1968

**Comment by lc-guy** [comment]
Nebukazar just deleted his account (probably in response to the Microsoft thing?), so oneechan's repo is gone...

**Comment by Sloppy9649** [comment]
Fixed this by removing the customCSS: lines from StyleChan.user.js.

**Comment by oluapris** [comment]
Thought doing that would work but I'm still getting the popup even after deleting all the themes that give me an error.

**Comment by Sloppy9649** [comment]
Actually deleting them or deleting them in the menu? cause that just hides them.
Here's mine if you want:
[https://gist.github.com/Sloppy9649/514ef3a2692554de842145fb117de006](url)

**Comment by ubone** [comment]
`@import "https://s.4cdn.org/css/tomorrow.673.css";`
in Custom CSS instead of the bottom left selector

**Comment by Smithy3** [comment]
Add this to your uBlock Origin filters:
`@@||boards.4chan.org^$csp`
