### ISSUE TITLE
[Feature Request] Red outline around the watch threads when there is a reply

### ISSUE THREAD

**Issue by Janaue** [ccd0/4chan-x#1972]
Currently in the catalog of each board, there is a bright blue outline around the threads which are watched. When a reply to a post is posted, the watcher turns red, but it would be nice also to make, in the catalog, the bright blue outline turn bright red around the thread which gets a reply.

**Comment by ccd0** [comment]
If you want to change the colors, you can do that with custom CSS.

**Comment by ubone** [comment]
@Janaue 
>bright blue outline

it's always been red, it may depend on the theme css in use

**Comment by saxamaphone69** [comment]
```css
.replies-unread { border: 1px solid red; }
```
Or some variation of that should meet your needs.
