### ISSUE TITLE
"Cross-Origin Request Blocked" when posting via the Quick Reply

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1976]
A couple of days ago I've randomly started getting a "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sys.4chan.org/vg/post. (Reason: CORS header 'Access-Control-Allow-Origin' missing)" when using QR. Posting via the original form works fine.
This first happened on Firefox 59.0.3 w/ Greasemonkey, and now the issue persists on Firefox 60.0.1. As far as I'm aware, I didn't do anything out of ordinary to trigger the error, since I haven't installed any new scripts or add-ons in the past week. Switching to Violentmonkey or Tampermonkey doesn't help — TM doesn't even recognize 4chan-x as a script, and the same issue happens on VM.

Screenshot of F12 console log:
https://i.imgur.com/hd715NS.jpg

**Comment by ccd0** [comment]
Try turning off "Show Upload Progress".

**Comment by Zufallszahl** [comment]
That solved the issue, thanks. Why was this particular option causing it, though?
