### ISSUE TITLE
OneeChan & StyleChan No Longer Exists

### ISSUE THREAD

**Issue by Icarus77** [ccd0/4chan-x#1987]
OneeChan's Github page has been 404'd, as has StyleChan's. I don't know why, but I can no longer alter the settings of either of them. They both just reset upon refreshing or going to another page.

Is there any way that this could be resolved? OneeChan and StyleChan are still around on other fork websites, but I think the GitHub page being deleted messed up how it saves settings.

If this can't be resolved by you, cod0, you should probably just remove the link from your 4chan X page.

**Comment by Smithy3** [comment]
No problems on my end with OneeChan and saving settings.
What version of it are you using?

>GitHub page being deleted messed up how it saves settings

That wouldn't have anything to do with it, the only time the GitHub page is referenced is for links to the wiki, changelog and so on.
