### ISSUE TITLE
Volume controls fucked.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#1988]
Submitter: music user
Recent update fucked the volume controls up. Only able to mute or play in 50% volume on webms. Disabling extension allows full volume

**Comment by taocrofl** [comment]
Volume controls are fucked for me as well. Except for me they are permanently muted. If I disable 4chanx volume controls work properly, so it does seem to be 4chanx at fault. Tried the flag in ParrotParrot's post and didn't work.
