### ISSUE TITLE
no sound in wembs

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2001]
Submitter: Bfreak
Hi. This could be a wide variety of chrome addons doing this, but webms played when using 4chanX are muted, and the mute button cannot be toggled.

Works fine in incognito.

**Comment by GetTuh** [comment]
I had the same problem, and it was caused by new chrome player (with no volume control, nice job google)
Fix: 
Enter "chrome://flags/#enable-modern-media-controls" in your browser and disable New Media Controls.
