### ISSUE TITLE
Allow Sound Disabling itself

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2002]
Submitter: Joel Rodriguez
Email: taquitobrown@gmail.com
every time i open a webm allow sound will disable itself

**Comment by claydegruchy** [comment]
if anyone has this issue, hit the drop down in the top right and click allow sound.
![image](https://user-images.githubusercontent.com/13542565/42722517-8c904a5c-874d-11e8-92b2-9284745e5c50.png)

**Comment by jemand-the-holograms** [comment]
Can we delete this issue as the first comment has my email and name in it?

**Comment by saxamaphone69** [comment]
Best I can do is edit, which I've done, though it still shows previous versions of comments. Only @ccd0 can delete an issue as the owner.

**Comment by jemand-the-holograms** [comment]
> Best I can do is edit, which I've done, though it still shows previous versions of comments. Only @ccd0 can delete an issue as the owner.

good enough thank you
