### ISSUE TITLE
Refresh issue

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2005]
Submitter: uma delicia
Having major issue with 4chan X today, every time I refresh or change pages its reset to its previous state. When I try to prune dead threads in the thread watcher, I refresh and they all come back. When I post, I'll refresh and it no longer recognizes (My) posts, meaning there's no (You) attached to the replies and it gets removed from the thread watcher. I'm using the latest version with violentmonkey. Only other addons are uBlock Origin and Rikaichamp. Never had this issue before today

**Comment by tttae444** [comment]
I had the same problem and switching to tampermonkey fixed it (so far). I assume it's an issue with violentmonkey.
