### ISSUE TITLE
Oneechan ceased to exist. Any alternatives?

### ISSUE THREAD

**Issue by dmxt** [ccd0/4chan-x#2007]
Oneechan's style script 404: https://nebukazar.github.io/OneeChan/builds/OneeChan.user.js
His GitHub is gone.

I love my themes and mascots, is there any stylescript I can install either with Violetmonkey/**monkey or as a Chrome extension?

Let me know, please. Thanks.

**Comment by Smithy3** [comment]
Their GitHub is gone but its not like the userscript has suddenly stopped working, you can still find it online on greasyfork.org or from GitHub forks of it which haven't been deleted.

Coincidentally I made a repo a few hours ago that hosts the userscript file, maybe that is of some use to you.

As far as I'm aware there aren't really any proper replacements.

**Comment by dmxt** [comment]
@Smithy3 Thanks.

**Comment by KevinParnell** [comment]
I am now maintaining a working version of OneeChan and will continue to update it - https://github.com/KevinParnell/OneeChan
