### ISSUE TITLE
Expanding boards menu creates a mess

### ISSUE THREAD

**Issue by SIX10** [ccd0/4chan-x#2019]
When opening the board catalog it shows every boards full name (not the board code) and it has this out of style "close" button that is kind of annoying. Attached are screenshots of not expanded and expanded.
![screenshot_1](https://user-images.githubusercontent.com/34385243/43362958-763d6570-92bd-11e8-9ccd-f542f660cdde.png)
![screenshot_2](https://user-images.githubusercontent.com/34385243/43362959-764cf0ee-92bd-11e8-9d00-8e392667014e.png)

**Comment by saxamaphone69** [comment]
You have Catgrills' additional userscript used for their [userstyle](https://github.com/Catgrills/Pygmalion-Z) running; turn that off.
