### ISSUE TITLE
The page didn't load completely. Some features may not work unless you reload.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2021]
on /g/, /k/, /tv/ and a bunch of other boards I get this error and catalog doesn't load. some boards work fine though.

**Comment by gotmilk0112** [comment]
Getting this error on /trash/ as well.

**Comment by gotmilk0112** [comment]
Oh, and it seems to have forgotten all yous/manually hidden posts, again.

**Comment by gotmilk0112** [comment]
It seems 4chan's servers are down now. That's probably causing all these issues.
