### ISSUE TITLE
4chan won't work

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2023]
Submitter: Anon
Email: Mr.waluigi1@gmail.com
VM106:8 Uncaught Error
    at String.fromCharCode (<anonymous>:8:21)
    at l ((index):1)
    at (index):1
    at (index):1
String.fromCharCode @ VM106:8
l @ (index):1
(anonymous) @ (index):1
(anonymous) @ (index):1
core.min.1014.js:1 Refused to load the script 'https://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

**Comment by NaturalHarmonia** [comment]
I might be having a similar issue. I'm getting "The page didn't load completely. Some features may not work unless you reload." when I go to boards like /vg/ and /vp/ and when I try to post I get a connection error.

**Comment by gotmilk0112** [comment]
It seems 4chan's servers are down now. That's probably causing all these issues.

**Comment by VinLark** [comment]
Almost every board is down it seems. /v/ works though.
