### ISSUE TITLE
important

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2024]
Submitter: anon
this is actually not an issue - I didn't know where to send this suggestion.
in default 4chan you can post in a thread from the index without a new window opening oe youe current tab visiting the thread url after post.
could this also be implemented into 4chan X so posters reading from the index can post in a thread without opening specific thread?

pls reply soon

**Comment by saxamaphone69** [comment]
![image](https://user-images.githubusercontent.com/877480/236135805-c53c355f-ab43-4fab-ae57-d899d3585e11.png)
Such a feature exists.
