### ISSUE TITLE
[Feature Request] 4chan navigation dropdown on browser-bar button click

### ISSUE THREAD

**Issue by fozzibab** [ccd0/4chan-x#2030]
Hope this is the right place to drop FRs, but I couldn't find another method of it. A while back there was a separate 4chan extension that provided an easy menu to rapidly navigate the site. You clicked on the browser bar button and a drop-down would pop up, and you just clicked on whatever board you wanted to go to, which would open in a new tab. Navigating 4chan is a bit of a pain in the ass, and that menu saved a lot of time. I wouldn't bother asking for the feature if an alternative existed, but as far as I can find, none does.

I was hoping it might be relatively possible/easy/feasible/etc to add it to 4chan X. Of course, I'm pretty much completely ignorant about programming and have no idea of the extent of what I'm actually asking. If it's reasonable, it would be awesome. 

Thanks!

**Comment by saxamaphone69** [comment]
Add this to your Custom Board Navigation:
`external-text:"SHOW ME THE BOARDS","javascript:(function(){const a = document.querySelector('#boardSelectMobile');const b = document.querySelector('#header-bar');b.prepend(a);})();"`
