### ISSUE TITLE
Feature request: Thumbnails with transparency work with every theme

### ISSUE THREAD

**Issue by lplp6lkhp** [ccd0/4chan-x#2035]
![image](https://user-images.githubusercontent.com/42627495/44498810-cce4b280-a64e-11e8-9fed-f18344ae351c.png)
I like using Tomorrow, but images with transparency apply a background of the default board theme. It would be more pleasing to the eye if it worked with the selected theme, if possible.

**Comment by HushBugger** [comment]
You can do that with the "Replace PNG" setting, which replaces thumbnails of PNG images by the real image, including real transparency. That does make threads a bit slower to load and heavier on memory.
