### ISSUE TITLE
Use Faster Image Host Option - Still needed?

### ISSUE THREAD

**Issue by BondiBear** [ccd0/4chan-x#2046]
_Use Faster Image Host: Change is*.4chan.org links to point to the faster i.4cdn.org host._

Is this still needed? 4chan by default seems to use i.4cdn.org. 
Option seems to actually slow image loading a bit, but I have no hard data to back that up.

**Comment by BondiBear** [comment]
4chanx still uses the slower i.4cdn.org. Why?? 

**is2.4chan*.org** loads images A LOT faster.

Even with this option disabled, all new posts containing images are reverted back to i.4cdn from is2.4chan, slowing everything down!

Can you fix this pls?

**Comment by ccd0** [comment]
i.4cdn.org is still faster from my end.
Hiroyuki has changed the default image server a lot and I don't want to have to release a code update for every change, especially when most people are going to be loading from i.4cdn.org anyway.
I could add an option to set the image server to whatever works best for you, though.

**Comment by bakugo** [comment]
The key difference here is cloudflare.
i.4cdn.org uses cloudflare caching, while is2.4cdn.org is hosted at OVH with no proxy.
On my end, i.4cdn.org is faster if the image is cached at cloudflare, but quite a bit slower if it isn't.
No idea how the OVH server works though. Maybe it has all images, or maybe it caches them from the main server for some time like cloudflare does. If it is a cache, it's not defeated by adding a query to the URL like cloudflare is, so it's hard to tell.

I do agree that the option should be renamed, maybe something like "Force Original Image Host"?

>all new posts containing images are reverted back to i.4cdn

The native extension has this issue as well right now. The API doesn't say what image host should be used so there's no way for an extension to tell without hardcoding it or trying to guess based on other posts already in the thread.

**Comment by DosAmp** [comment]
> Even with this option disabled, all new posts containing images are reverted back to i.4cdn from is2.4chan, slowing everything down!

This mirrors the behavior of the native extension, which has kept using i.4cdn.org as image host for inline loaded posts since https://github.com/Floens/ChanTracking/commit/487852016e6880a05355dd442dfcf5f64ec38a02 (deprecation of is.4chan.org). The server-side HTML template may deviate from that at any point.

**Comment by BondiBear** [comment]
> I could add an option to set the image server to whatever works best for you, though.

If this is possible, it would be appreciated since I see quite a speed difference. 
Perhaps use of _is2.4chan*_ (or future Mook image server addresses) could be forced.

**Comment by ccd0** [comment]
Newest beta has this option under `Advanced` > `Override 4chan Image Host`.

**Comment by BondiBear** [comment]
Thanks! I'll test it for a few days.

**Comment by BondiBear** [comment]
Works great! I entered _is2.4chan.org_ into the field and everything loads a lot faster.
(One thing though: catalog thumbnails still load from i.4cdn, but that is not an issue.)
Good work!
