### ISSUE TITLE
WEBM sound disabled (also no volume control?)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2048]
Using 4chanX 1.14.2.1 on Opera 55.0
Even though the option to open webm files unmuted is selected in the 4chanX settings, opening up a webm file it will be muted anyways (the audio icon has a slash through it indicating that its muted, and it plays no sound either). However no amount of clicking on the audio icon will unmute it. Also right clicking on the webm opens up the (html5?) options and the mute/unmute option for the sounds there is also useless whether its turned on or off.

Double checking that it isnt any issues on my end I opened up the same thread in a private window, which doesnt load 4chanX, and sure enough the audio plays in those webm files, and the audio/mute button can be accessed.

I was on 4chan several days ago viewing webm files with audio and didnt have any problems. Only had this problem start today.
Also where the hell did the volume control go on the audio icon, I distinctly remember the player controls for webm had a volume control, now the audio icon just mutes or unmutes the audio.

**Comment by Sergster1** [comment]
The newest versions of Chromium's media player removed the audio control function. You can set a flag in chromium to use the legacy player with audio control.
