### ISSUE TITLE
Captcha Malfunction

### ISSUE THREAD

**Issue by Confrade** [ccd0/4chan-x#2052]
Just started to happen, everytime i tried to post it gives to me the "captcha malfunction". I already enabled and disable the javascript captcha and nothing fixed, uninstalled and installed and also nothing. Pls help.
![image](https://user-images.githubusercontent.com/38992969/45504404-288ef100-b760-11e8-940d-15a79e763dad.png)

**Comment by Nusharik** [comment]
I'm having the same issue.

**Comment by Confrade** [comment]
What gives this?

**Comment by Nusharik** [comment]
> 
> 
> What gives this?

Just attempting to post gives it to me, with or without an image as well.

**Comment by Confrade** [comment]
> > What gives this?
> 
> Just attempting to post gives it to me, with or without an image as well.

Yep, tried to clean my cookies as well and nothing. I just saw a update also but still no changes.

**Comment by dosudosu** [comment]
Having the same problem.

**Comment by ParrotParrot** [comment]
Same issue with no visible errors in console (outside of previous unrelated error with recaptcha webworkers), using chrome store version on 68.0.3440.106 (x64)
