### ISSUE TITLE
Fails to load main board page, won't autorefresh threads. Gives two different error messages

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2057]
Submitter: Anon
When loading a board, no threads will load, and instead an error message saying "Failed to load board configuration. Connection Error", "Error fetching archive data from
https://mayhemydg.github.io/archives.json/archives.json Connection Error", and "Index Refresh Failed. Connection Error".

When opening up a thread, the error messages "Failed to load board configuration. Connection Error" and "Error fetching archive data from
https://mayhemydg.github.io/archives.json/archives.json Connection Error" appear, and the thread will not automatically update, but instead require you to refresh the page, which will make the error messages reappear.

**Comment by boxerdemon** [comment]
I have the same issue. Disabling all forms of adblock eliminates the issue and restores 4chan-x functionality. When I turn on any form of adblock, scripts or otherwise, all threads/catalogs are gone. 

There's probably a new ad causing this issue and breaking 4chan, maybe?

**Comment by TheDong** [comment]
This is an issue with an easylist update.

I suspect it's this commit: https://github.com/easylist/easylist/commit/70572c899f6a42a9625fd37186354efb0111d654

Specifically, the line:

```
|https://$third-party,xmlhttprequest,domain=4chan.org|....
```


I think that's blocking the request made by 4chan X from the 4chan.org domain to the 4cdn domain.

If I go into "uBlock Origin -> Settings -> My Filters" and add `@@a.4cdn.org/*`, that gets things working again for me.

I don't think this is a 4chan X issue, but rather an easylist issue.

**Comment by grumble9684** [comment]
> This is an issue with an easylist update.
> 
> I suspect it's this commit: [easylist/easylist@70572c8](https://github.com/easylist/easylist/commit/70572c899f6a42a9625fd37186354efb0111d654)
> 
> Specifically, the line:
> 
> ```
> |https://$third-party,xmlhttprequest,domain=4chan.org|....
> ```
> I think that's blocking the request made by 4chan X from the 4chan.org domain to the 4cdn domain.
> 
> If I go into "uBlock Origin -> Settings -> My Filters" and add `@@a.4cdn.org/*`, that gets things working again for me.
> 
> I don't think this is a 4chan X issue, but rather an easylist issue.

That worked for me too, thank you!

**Comment by Zyklon-Garrison** [comment]
Inserting that line into my filters doesn't work for me, still comes up with a "Connection Error"

**Comment by inconspiciousfbivan** [comment]
Same here. If I already have pages open, I can still post but I have to manually refresh the page to see my post or other's new posts. Hitting refresh then stopping the page from loading after I see the front page/catalog images I can then choose pages to open and post in.

**Comment by boxerdemon** [comment]
Nothing in this thread has worked for me, but I haven't tried TheDong's fork.

**Comment by mariojuniorjp** [comment]
> This is an issue with an easylist update.
> 
> I suspect it's this commit: [easylist/easylist@70572c8](https://github.com/easylist/easylist/commit/70572c899f6a42a9625fd37186354efb0111d654)
> 
> Specifically, the line:
> 
> ```
> |https://$third-party,xmlhttprequest,domain=4chan.org|....
> ```
> I think that's blocking the request made by 4chan X from the 4chan.org domain to the 4cdn domain.
> 
> If I go into "uBlock Origin -> Settings -> My Filters" and add `@@a.4cdn.org/*`, that gets things working again for me.
> 
> I don't think this is a 4chan X issue, but rather an easylist issue.

Works for me. Thanks!

**Comment by Griffy117** [comment]
> This is an issue with an easylist update.
> 
> I suspect it's this commit: [easylist/easylist@70572c8](https://github.com/easylist/easylist/commit/70572c899f6a42a9625fd37186354efb0111d654)
> 
> Specifically, the line:
> 
> ```
> |https://$third-party,xmlhttprequest,domain=4chan.org|....
> ```
> I think that's blocking the request made by 4chan X from the 4chan.org domain to the 4cdn domain.
> 
> If I go into "uBlock Origin -> Settings -> My Filters" and add `@@a.4cdn.org/*`, that gets things working again for me. (Edit: more specifically, `@@||a.4cdn.org^$xmlhttprequest,domain=4chan.org` works)
> 
> I don't think this is a 4chan X issue, but rather an easylist issue.

Adding that exception worked, seems to fix the problem while allowing easylist to still block the annoying ads.  Great! made a github account literally just to thank you.

**Comment by alidan** [comment]
I have 2 lists in custom I have no idea where they came from

EasyList without element hiding rules​​​​​​​​​
Fanboy+Easylist-Merged Ultimate List

these two give issue with downloading images with file names remaining the same, just a shot in the dark asking here, but anyone know if I can do without these two, and assuming custom means I imported them myself, what the hell I even have them for? god knows If I added anything to the ad blocking it was something I was told to do on 4chan or a problem on 4chan that one of them solved.
