### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2058]
Submitter: Andrew
I get a notification for this and can't see any threads.
Error fetching archive data from
https://mayhemydg.github.io/archives.json/archives.json
Connection Error

**Comment by ccd0** [comment]
https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions#connection-errors-index

**Comment by nahga** [comment]
Yeah that's not it. It's sourcing that json from the op's error and that page doesn't exist.
Nor does https://mayhemydg.github.io
Should be sourcing it here:  https://github.com/MayhemYDG/archives.json       and it's not.

**Comment by Ofunniku** [comment]
I can confirm this over here, too.

even a clean chrome profile with newly minted installs of tampermonkey and 4chanX is giving me the error

**Comment by Photosounder** [comment]
I can confirm, I turned off AdBlock Plus and now it works fine again.
