### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2061]
Submitter: Jake
Email: timelessjunkbin@gmail.com
doesn't display anything in individual boards tried uninstalling and it worked reinstalled from chrome store and it broke the site again. 
get the errors  "Failed to load board configuration. Connection Error", "Error fetching archive data from
https://mayhemydg.github.io/archives.json/archives.json
Connection Error", "Index refresh failed and threads won't update"

**Comment by Chibicon** [comment]
Had the same problem. Turns out it was uBlock. Needed to purge and update lists.

**Comment by Virus-Hunter** [comment]
Tried Chibicon's solution and it worked out. Now I just get a _"Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error"_ message, but haven't noticed any problems browsing the site

**Comment by Nzash** [comment]
> 
> 
> Tried Chibicon's solution and it worked out. Now I just get a _"Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error"_ message, but haven't noticed any problems browsing the site

Yep, same here. Site seems to work fine now that I added that one line into the "my filters" section in uBlock, but I d o get that error message.
