### ISSUE TITLE
script not loading some times

### ISSUE THREAD

**Issue by alidan** [ccd0/4chan-x#2062]
Been having a problem recently where the script won't load or takes a refresh or two to load. 
I moved over to the script with the whole forgetting (you)'s and hidden issues, 

I'm using tampermonkey right now, 

There anything that would load this faster? is the extension better for this issue? and as of now are all the you/hidden issues dealt with regardless of how I use this?

**Comment by ccd0** [comment]
Check if the issue happens with your ad blocker off; you might have to add some exception filters.

>There anything that would load this faster? is the extension better for this issue?

It could be. Less complicated loading process.

>and as of now are all the you/hidden issues dealt with regardless of how I use this?

Probably. I wouldn't really know until it starts getting reported again.
