### ISSUE TITLE
Can't save images/webms using the download button

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2066]
Submitter: pommetto
Email: andersaur24@gmail.com
If I click on the little save button next to the filename of an image or file, it gives me a message at the top that says "could not download" plus the link to the file. I've tried uninstalling and reinstalling 4chan X, but it still gives me the same error message..

**Comment by jamesxmcintosh** [comment]
It only affects the extension 1.14.3.0. 
The userscript 1.14.3.0 works.

**Comment by alidan** [comment]
> It only affects the extension 1.14.3.0.
> The userscript 1.14.3.0 works.

Its inconsistent, with the extension, possibly also consistent with the script too, I went back to the extension for reasons of the script not loading correctly so I can't really test to find out.

**Comment by ccd0** [comment]
from #2068:
Submitter: gnog
Email: basedgnog@gmail.com
Pressing the image download button gives me a brown popup box with a message saying "Could not download [image adress]". The problem has persisted for a few days, downloading images normally works just fine.

**Comment by ccd0** [comment]
Should be fixed as of v1.14.3.1.
