### ISSUE TITLE
Error fetching archive data

### ISSUE THREAD

**Issue by bluefiberbread** [ccd0/4chan-x#2069]
"Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error" 

Whenever I open a thread, this pops up.

**Comment by Vulgaris-Viridis** [comment]
Here as well..

**Comment by ccd0** [comment]
@Vulgaris-Viridis
Your issue is likely due to #2520 which is fixed now.

**Comment by Vulgaris-Viridis** [comment]
> Your issue is likely due to #2520 which is fixed now.
Hi, @ccd0 I can confirm it's fixed, much appreciated!
