### ISSUE TITLE
Support for embedding SWFs on /f/

### ISSUE THREAD

**Issue by PolarManne** [ccd0/4chan-x#207]
It's something the native extension supports, and I don't like having to keep 4chan X disabled on /f/'s front page, especially since the native extension gets automatically disabled by 4chan X so I have to turn it back on whenever I refresh the page.

**Comment by ccd0** [comment]
OK, Appchan doesn't actually have this, it just uses the native extension.  But disabling the native extension is optional now, so you can get this feature by turning the native extension on and disabling all the stuff that 4chan X does.  You probably also want to put

    .postMenuBtn {
      display: none;
    }

in custom CSS to hide the native extension's post menu.

**Comment by ccd0** [comment]
I went ahead and merged the code from Appchan X that just activates the native extension's Flash embedding.  It's now in the beta version (v1.10.5.0).
