### ISSUE TITLE
4chan X quick reply window will not open after Update button is used and shows new posts in thread

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2074]
Submitter: Guy
4chan X's quick reply window will open normally, but when the Update button below the last post in a thread is used and the thread is updated with new posts, that quick reply window will no longer open until the page is refreshed.  The native extension's quick reply window will still open if that is enabled.

Firefox 62.0.2, Violentmonkey 2.9.7, 4chan X 1.14.3.1

No error messages appear in the console when this occurs.
No error messages appear in the loggers of uBlock Origin or uMatrix (when that is still enabled).
This occurs when all other scripts/add-ons are disabled (except uBlock Origin)
This occurs when Adblock+ replaces uBlock Origin
This occurs when using a new (default) Firefox profile with only Violentmonkey, (default) 4chan X, and (default) uBlock Origin.

**Comment by ubone** [comment]
can't reproduce
FF VM 1.14.3.1

**Comment by ccd0** [comment]
I seem to recall talking to OP on /qa/ and he was using the native extension updater.
