### ISSUE TITLE
Reply to thread from Index [request]

### ISSUE THREAD

**Issue by chanmioo** [ccd0/4chan-x#2075]
Please allow 4chan-x an additional option to reply to a thread from the index without having to open the thread (in either the same page or another tab).
Vanilla 4chan allows this by default. I think it would be a nice addition considering you would be able to post in any/your pinned and watched thread(s) without visiting the thread's URL. 
[](url)

**Comment by ubone** [comment]
just click the post number

**Comment by chanmioo** [comment]
I have been trying that, but I realize now why it would open a new tab whenever I tried posting in a thread. I had the option in Posting & Captchas turned on (which opens replies/new threads in new tabs).
