### ISSUE TITLE
4chanx changes my font

### ISSUE THREAD

**Issue by zobavalazu** [ccd0/4chan-x#2077]
![213](https://user-images.githubusercontent.com/25892517/46086477-75cf8180-c1a8-11e8-87ab-84e428fb26e2.png)
I have font like that one on the right, but 4chanX changes it to the one on the left!
How I hack this code to make font persistent like on the right?

**Comment by ubone** [comment]
looks like windows, might help if you tell which os, browser, etc.

**Comment by saxamaphone69** [comment]
```css
body {
  font-family: 'nameoffont' !important;
}
```

Or something to that extent in your Custom CSS.
