### ISSUE TITLE
"Index failed - connection error"

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2088]
Submitter: anon
Email: steve@apple.com
with json index enabled and any suboptions

**Comment by Endovior** [comment]
I get the same error (and see no posts) with 4chan X enabled. With 4chan X disabled, I am able to access 4chan normally. So the problem is probably with 4chan X.

**Comment by bakugo** [comment]
@Endovior Go to any board and try to make a post.

**Comment by Snigeln** [comment]
Perfect excuse to go out and get some fresh air for once
