### ISSUE TITLE
Tweets not embedding properly

### ISSUE THREAD

**Issue by taocrofl** [ccd0/4chan-x#2103]
Running version 1.14.3.1 in Firefox 62.0.3 (64-bit).

I notice that tweets don't embed properly. The issue is present when all other plugins are disabled.

This is what I see when attempting to embed the tweet.

![image](https://user-images.githubusercontent.com/26388917/47239090-4f20f700-d3b2-11e8-8726-46d4096863f2.png)

Youtube embedding works fine. 

I don't normally use Firefox so it's unclear to me how new this issue is.

**Comment by Scrxtchy** [comment]
Do you have tracking protection turned on or off?

**Comment by taocrofl** [comment]
> Do you have tracking protection turned on or off?

that was it, thanks
