### ISSUE TITLE
whatanime.ga moved

### ISSUE THREAD

**Issue by leewdch** [ccd0/4chan-x#2107]
The new domain is: https://trace.moe/
This is[ the facebook post](https://www.facebook.com/whatanime.ga/posts/1720251444770284?__xts__%5B0%5D=68.ARDKIz7qY0WyR3yg_8ByosqH-y2GHeE7yOkyv_mAZkF8YT3jeEFhIkMQDhgZAT0QvQ5GHaV0twG9Mu8fKBgwckT5OAAIhwdctj-6CSGyrPQhyAiUtMzPrfugkz28-9O9TSMAWmktc8iB5TPnA_t48uwn2VzY0Ue6syru78Fj7etAwKixlBpoF1F9gqRtYhdd9th3vyTjYupX7rp5-aHRLpU&__tn__=-R) announcing it.

https://github.com/ccd0/4chan-x/blob/7c030f93246b063e4a55bb45aef5820a5fe65aa1/builds/4chan-X.user.js#L12060

**Comment by ccd0** [comment]
It's fixed. #2106
