### ISSUE TITLE
Script doesn't work anymore with ViolentMonkey?

### ISSUE THREAD

**Issue by zackultimate** [ccd0/4chan-x#2108]
Anyone experiencing this? Suddenly it doesn't work with it.  It still works with Tampermonkey, however.

**Comment by Shadesttone** [comment]
Having this exact same problem. ViolentMonkey is simply infinite loading script list and won't display. 4chan X not working, started several hours ago. Cannot re-add script, cannot load list. [https://my.mixtape.moe/jnrzfs.png](url)

**Comment by Diskmaster** [comment]
ref: https://github.com/violentmonkey/violentmonkey/issues/466
