### ISSUE TITLE
Add support for negative lookbehinds in filters regex

### ISSUE THREAD

**Issue by Mrfiregem** [ccd0/4chan-x#2110]
It'd be helpful if filters supported neg. lookbehinds, eg. `/\w+(?<!foo)bar/` matching any `/\w+bar/` result except `foobar` when filtering comments, titles, etc.

**Comment by ccd0** [comment]
4chan X uses your browser's regexp engine, so lookbehinds will be available as soon as your browser supports them.

**Comment by Mrfiregem** [comment]
Gotcha. Did some digging, and [this](https://bugzilla.mozilla.org/show_bug.cgi?id=1225665) is where the issue's being tracked for Firefox. People using Edge can find progress [here](https://github.com/Microsoft/ChakraCore/issues/3448).
