### ISSUE TITLE
Move the image download location

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2114]
Submitter: flowers
Email: sage@example.come
there are download buttons next to image filenames, but image filenames are not the same length and if you mouseover the filename it expands, which moves the download button.

Why the fuck is the button not to the LEFT of the filename and thus in a consistent spot and it never moves

some people would be autistic about it changing so make it an option or something

**Comment by saxamaphone69** [comment]
If you go into the Settings > Advanced, scroll down to `File Info Formatting`, you can customise the entire file information area. To achieve what you want, simply type `%d` to be on the left.
