### ISSUE TITLE
Upon loading any page: "Failed to load board configuration. Connection Error". Upon loading index, catalog, &c: "Index refresh failed. Connection Error".

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2115]
Submitter: lisa
Been dealing with these issues for a month now. Happens using Firefox 63.0.1, using Greasemonkey 4.7, using either 4chan X 1.14.3.2 or 4chan X beta 1.14.4.1.
I have tried disabling all other extensions, I've tried resetting the 4chan X settings  - the issues persist.
It might be interesting to note that I have other issues with 4chan even while forced to disable this add-on: Threads will not update automatically and often css/images will not load until I have opened an image by clicking it and Cloudflare determined I am not a robot.

Please send help.

**Comment by Lokiamis** [comment]
I have been having these exact same issues for months and have been unable to fix any of them myself.
