### ISSUE TITLE
4chan splitting into 2 domains

### ISSUE THREAD

**Issue by bakugo** [ccd0/4chan-x#2123]
![image](https://user-images.githubusercontent.com/6014513/48663772-d5e9f200-ea8c-11e8-81d1-9b4d625a1a2f.png)

https://github.com/Floens/ChanTracking/commit/0d1082d54541f460f15ec4947a3fff6f4c907fe9

**Comment by Twilicious** [comment]
I'm still using the stylechan script as well and everything seems to be working fine for now. I imagine this change will stop that being the case though. With nebukazar gone is there a easy way to add the new domain to stylechan/oneechan?

Thanks

**Comment by LtPinback** [comment]
I just checked and boards.4chan.org is hard linked across the script so my guess is that some works is indeed needed. 
ccd0 seems to be a capable maintainer so I do not think it will take long.
In the mean time you can probably copy the script change its name, make the changes I suggest + changing the hard links to the new domain and see if that works as a temp solution.

**Comment by Confrade** [comment]
It's fixed now for Chrome version.
