### ISSUE TITLE
Extension stoped working at all from nothing

### ISSUE THREAD

**Issue by BielCoelho** [ccd0/4chan-x#2127]
I was using it for a few months  but from nothing its just not working anymore, seeing old related problem I couldn't find anything at console, also tried disabling every extension, also didn't worked
Its like the extension is disabled but it's not, it loads the default 4chan without anything from extension
Tried tampermonkey + script but didn't worked too

Extension ver: `1.14.3.2`
official Chrome ver: `70.0.3538.102 (Versão oficial) 64 bits (cohort: Stable)`
Windows 10 64bit ver: `1803(17134.407)`

**Comment by BieowCuei** [comment]
also sometimes works the same way it stoped, I cant find a pattern or a reason. just from nothing

**Comment by bakugo** [comment]
Are you on 4channel.org when it stops working?

**Comment by BieowCuei** [comment]
nope, 4chan.org, randomly

**Comment by Confrade** [comment]
It's been working on 4chan and 4channel normally until a few hours ago it stopped working completely on 4channel. I'm using the Chrome version btw and fuck Hiromoot.

**Comment by StephanFS** [comment]
It just stopped working for me too all of a sudden.
