### ISSUE TITLE
4channel boards only list SFW boards on index

### ISSUE THREAD

**Issue by deadman3000** [ccd0/4chan-x#2137]
As topic states. Only the SFW boards are listed on 4channel.org. On 4chan.org all the boards are listed on the index.

**Comment by Twilicious** [comment]
This is how it's intended to be. The whole reason for the switch to 4channel is to quarantine all the NSFW boards to 4chan.org so hiro can attempt to get more advertisers on the SFW ones.

**Comment by deadman3000** [comment]
How can I add them back? I don't know how to add them in custom.

**Comment by deadman3000** [comment]
Nevermind I fixed it by pasting all the board letters into the custom board box and enabled custom board.

**Comment by Twilicious** [comment]
You dont? Just add /pol/ or /b/ or whatever nsfw board you want to go to to the end of https://4channel.org/ and it will redirect you to the nsfw 4chan board. If you go to the advanced tab in 4chanX settings you can customize what boards show up in the header under Custom Board Navigation.

**Comment by saxamaphone69** [comment]
Looks like they fixed this on 4chan's end.
