### ISSUE TITLE
watch threads not the same on 4channel and 4chan + main page

### ISSUE THREAD

**Issue by alidan** [ccd0/4chan-x#2138]
Is it possible to merge the two?

on a side note, is it possible to inject some text and boards to the main page to kind of restore the way 4chans main page was?

**Comment by ccd0** [comment]
>on a side note, is it possible to inject some text and boards to the main page to kind of restore the way 4chans main page was?

Can't you just visit the main page at 4chan.org if you want that?

**Comment by saxamaphone69** [comment]
Potentially related, but when on `4chan.org`, the links in the thread watcher all link to `4chan.org` regardless, which then redirects the SFW boards.

When on `4channel.org`, the links in the thread watcher all link to `4channel.org` regardless, which then redirects the NSFW boards.

Or should I open a new issue?

**Comment by ccd0** [comment]
>Or should I open a new issue?

Yes. Should be an easy fix though.

**Comment by alidan** [comment]
ok, not sure if all the images will import, tried to make the window as small as needed to show what needed to be there. 

![chrome_2018-11-23_19-16-39](https://user-images.githubusercontent.com/2681758/48963264-8efc7080-ef54-11e8-92d2-a0e6b681d155.png)

this is now 4chan.org for me. 

![chrome_2018-11-23_19-17-13](https://user-images.githubusercontent.com/2681758/48963265-97ed4200-ef54-11e8-8479-5e02ca6ce195.png)

this is 4 channel with the thread watcher having nothing

![chrome_2018-11-23_19-17-45](https://user-images.githubusercontent.com/2681758/48963267-a20f4080-ef54-11e8-9cf7-d5150961eb5f.png)

this is 4chan.
