### ISSUE TITLE
4chan Pass doesn't work in 4channel but works in 4chan

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2140]
Submitter: John
After installing the new version of 4chan X (1.14.4.5) it would seem that the 4chan Pass I have doesn't work in 4channel. When trying to post, the QR box acts as if I have authenticated my 4chan Pass, and as such I see no captcha anywhere to solve. But when I click the Submit button it tells me that I have to solve the captcha. Using the original form allows me to circumvent this problem but it is very inconvenient.

I have checked both https://sys.4channel.org/auth and https://sys.4chan.org/auth and both tell me that I have authenticated my pass, reloading doesn't do anything. Moreover, the pass still works in 4chan proper, but not in 4channel. I have downloaded the version of 4chan X from https://www.4chan-x.net/ downloaded it as a .js file and dragged it into the browser for installation

I have also fulfilled the conditions of the Shift+Control+J, but since it also occurs in 4chan where the problem doesn't happen I found that it is irrelevant. I'll just include the error message for clarity:
core.min.1026.js:1 Refused to load the script 'https://www.google-analytics.com/analytics.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com 'self' 'unsafe-inline' 'unsafe-eval'".

I thought this was a problem with the other version of 4chan X that I had that I could not uninstall (literally just manually removed it from the browser's extension folder) but persisted on the list and I couldn't remove it (clicking on the trash icon) until I clicked on details of the extension and clicked the remove button. Seeing this I immediately tried posting but it still won't work. 

So I conclude that the problem is with the extension.

**Comment by instagramtest** [comment]
The issue is related to the QR window. If you disable the QR window (and leave everything as is) then you can use the 4chan form to post using a 4chan Pass and 4chan X on 4channel. So it seems that the QR window is checking the wrong source for the pass AUTH, which is why it doesn't let you post.

**Comment by observeroftime02** [comment]
It worked for me on 4channel after allowing cookies from 4chan.org in uMatrix. I can post with pass and qr box just fine after this.

**Comment by BondiBear** [comment]
Can confirm: posting with **authenticated 4channel.org pass using QR** currently does not work on 4channel.

![4ch](https://user-images.githubusercontent.com/2057221/48967413-4a1e1b80-efe0-11e8-9d8d-bad007aef76b.PNG)

**Comment by bakugo** [comment]
Works for me on chrome/tampermonkey. Probably has something to do with cookies not being sent in cross-domain requests (since 4chan X always uses sys.4chan.org even for 4channel.org)

**Comment by instagramtest** [comment]
Seems to be a Firefox exclusive issue then. Allowing cookies through Firefox + uMatrix doesn't change a thing. I even tried disabling all filters (uMatrix/uBlock) and allowed Firefox to store all cookies it encounters. Still got the same error.

**Comment by Worble** [comment]
I've tried it on both Chrome and Firefox, both are failing for me. Chrome is allowing the cookies and does not have umatrix installed.

**Comment by instagramtest** [comment]
Another user actually found a temporary fix. 

`QR.req = $.ajax("https://sys.4chan.org/" + g.BOARD + "/post", options, extra);`

If you don't post on NSFW boards then changing 4chan to 4channel will fix it for now. If you post on both boards you could use two versions of 4chan X I guess. One for 4chan (default) and one for 4channel (modified).

**Comment by tannutuva** [comment]
@instagramtest weird, pass was working fine for me but all I was getting was a connection error which is how I found that sys.chan line was unchanged.  I'd rather write a switch/case statement on the hostname to fix it, but I know nothing about js.

**Comment by bakugo** [comment]
This fix should work for all boards.

`QR.req = $.ajax("https://sys."+(location.hostname.split('.')[1])+".org/"+g.BOARD+"/post", options, extra);`

**Comment by Amon-Hen** [comment]
@bakugo Yep, that did the trick.

**Comment by ccd0** [comment]
v1.14.4.6 should fix this. Let me know if it works for you.

**Comment by Amon-Hen** [comment]
Yeah, it works now. Thanks.
