### ISSUE TITLE
URL for boards not reflective of domain in Thread Watcher

### ISSUE THREAD

**Issue by saxamaphone69** [ccd0/4chan-x#2143]
When on `4chan.org`, the links in the thread watcher all link to `4chan.org` regardless, which then redirects the SFW boards.

When on `4channel.org`, the links in the thread watcher all link to `4channel.org` regardless, which then redirects the NSFW boards.

**Comment by ccd0** [comment]
Should be fixed as of v1.14.4.6. Thanks for reporting.

**Comment by saxamaphone69** [comment]
Yep, fixed! Thanks!
