### ISSUE TITLE
"Filter" crashed on node Post No.106372314 (tv).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2144]
Submitter: Oscar
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.14.4.5 userscript
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
URL: https://boards.4channel.org/tv/thread/106355925

TypeError: link.href is undefined
postDataFromLink@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:9410:9
allQuotelinksLinkingTo/<@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:9450:16
allQuotelinksLinkingTo@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:9448:14
hide@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:8518:13
apply/<@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:8631:18
tms_a6371607_a55a_4c67_8b57_e86b1dbf079b/</SimpleDict</SimpleDict</SimpleDict.prototype.forEach@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:7114:9
apply@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:8629:14
hide@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:8515:9
node@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:8085:11
tms_a6371607_a55a_4c67_8b57_e86b1dbf079b/</Callbacks</Callbacks</Callbacks.prototype.execute@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:5621:13
fn@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:25343:9
softTask@moz-extension://e6e14054-0443-4c9d-a995-79d4f6c0585f/userscript.html?id=a6371607-a55a-4c67-8b57-e86b1dbf079b:25347:16
g</<@eval:2:479
ja/c[d]@eval line 1 > Function:52:483

`<div class="postContainer replyContainer" id="pc106372314" data-full-i-d="tv.106372314"><div class="sideArrows" id="sa106372314">&gt;&gt;</div><div id="p106372314" class="post reply"><div class="postInfoM mobile" id="pim106372314"> <span class="nameBlock"><span class="name">Anonymous</span><br></span><span class="dateTime postNum" data-utc="1543004657">11/23/18(Fri)15:24:17 <a href="#p106372314" title="Link to this post">No.</a><a href="javascript:quote('106372314');" title="Reply to this post">106372314</a></span></div><div class="postInfo desktop" id="pi106372314"><input type="checkbox" name="106372314" value="delete"> <span class="nameBlock"><span class="name">Anonymous</span> </span> <span class="dateTime" data-utc="1543004657">11/23/18(Fri)15:24:17</span> <span class="postNum desktop"><a href="#p106372314" title="Link to this post">No.</a><a href="javascript:quote('106372314');" title="Reply to this post">106372314</a></span><a href="#" class="postMenuBtn" title="Post menu" data-cmd="post-menu">▶</a><div id="bl_106372314" class="backlink"><span><a href="#p106372584" class="quotelink">&gt;&gt;106372584</a> </span></div></div><blockquote class="postMessage" id="m106372314"><a href="#p106366440" class="quotelink">&gt;&gt;106366440</a><br><span class="quote">&gt;He sold Star Wars to Disney cause he wanted them to destroy it, but now, to late, he realizes his mistake.</span><br>Goofy fanfiction from retarded RLMers. Lucas doesn't give a shit about any of this, you morons asked for banal slop and he was accomodating enough to sell it to a company which would give you exactly that.</blockquote></div></div>`

**Comment by saxamaphone69** [comment]
I think you've got the 4chan Extension running too, you'll need to disable that for 4chan X to work as intended.
