### ISSUE TITLE
connection error when posting on 4channel

### ISSUE THREAD

**Issue by alidan** [ccd0/4chan-x#2145]
getting errors on all 4channel pages when trying to post from the extensions quick reply, using original form works, not sure if this is a me problem or if its a more widespread problem looking at the recent issue threads.

**Comment by anonymossy** [comment]
Having the same issue the original reply form works, quick reply gives an error

**Comment by shindante** [comment]
I'm unable to post on 4channel pages with quick reply or the original reply form. The 4chan pages work fine with either method.

**Comment by tannutuva** [comment]
search for sys.4chan in the script and you can update this line for QR to 4channel vs. 4chan and it'll work until they fix it, but you'll need to change it back to post on 4chan
![screenshot 2018-11-24 11 38 52](https://user-images.githubusercontent.com/41525296/48971339-c4996c00-efdd-11e8-8319-7bf24bc96327.png)

**Comment by ccd0** [comment]
merging into #2145 since it has more information
