### ISSUE TITLE
4channel X connection error

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2149]
Submitter: Sebastian
4channel X had a connection error problem with the Privacy Badger add-on, much like uBlock Origin. Didn't happen with 4chan X, but now I have to add boards.4channel.org/ to the excludes  of Privacy Badger or else I can't use quick reply.

**Comment by tannutuva** [comment]
for me this issue was the script, there's no switch/case for the hostname on QR:
`QR.req = $.ajax("https://sys.4chan.org/" + g.BOARD + "/post", options, extra);`

**Comment by beriah** [comment]
> 
> 
> for me this issue was the script, there's no switch/case for the hostname on QR:
> `QR.req = $.ajax("https://sys.4chan.org/" + g.BOARD + "/post", options, extra);`

This fixes it for me, thanks. What's the best way to implement this without breaking it on 4chan.org boards?

**Comment by tannutuva** [comment]
> > for me this issue was the script, there's no switch/case for the hostname on QR:
> > `QR.req = $.ajax("https://sys.4chan.org/" + g.BOARD + "/post", options, extra);`
> 
> This fixes it for me, thanks. What's the best way to implement this without breaking it on 4chan.org boards?

normal reply switches the hostname but I don't have the js knowledge to do this right
![screenshot 2018-11-24 12 09 13](https://user-images.githubusercontent.com/41525296/48971633-e5fc5700-efe1-11e8-9ccb-c07ca90840fa.png)

**Comment by tannutuva** [comment]
@beriah another user solved this in #2140 
`QR.req = $.ajax("https://sys."+(location.hostname.split('.')[1])+".org/"+g.BOARD+"/post", options, extra);`

**Comment by ccd0** [comment]
v1.14.4.6 should fix this. Let me know if it works for you.
