### ISSUE TITLE
Embeds no longer working?

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2150]
Hello, 
Embeds stopped working after yesterday's update. YouTube and Vocaroo works fine, but other embeds such as Twitter and media(.webm, .mp4 etc) doesn't.

**Comment by ccd0** [comment]
Can't reproduce. Can you post a link to one that's not working?

**Comment by knasen88** [comment]
i get this whenever a twitter embed is trying to load
https://i.imgur.com/d3jYh6K.png
firefox windows 10

**Comment by ccd0** [comment]
For me, it shows that message for a second and then loads. Maybe you're blocking something?

**Comment by knasen88** [comment]
seems to be any kind of twitter embed not loading, my case doesn't seem to be related to 4chanx
did some googling and it was firefox's tracking protection that broke it
