### ISSUE TITLE
Changing hover quote position

### ISSUE THREAD

**Issue by CorWilson** [ccd0/4chan-x#2160]
Is there a way, or a feature request, to be able to position quoted posts in hovering without them going off screen like below? I have it opened on a vertical screen and part of the post ends up going offscreen.

![4chanx-screen](https://user-images.githubusercontent.com/2097189/49118916-df811000-f26b-11e8-9d5f-00fb5c55d4e9.png)

**Comment by CorWilson** [comment]
Strangely it's correctly lining up with the west border of my screen. Odd. It just magically started working.

**Comment by ccd0** [comment]
Looks like this happens when the file description line is nearly as large as your browser width.
