### ISSUE TITLE
Settings not saving?

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2165]
No matter how many times I untoggle it "Catalog Hover Expand" keeps coming back.

**Comment by Zabalba** [comment]
So I had the same issue with settings not saving after closing chrome/site.

What worked for me was killing all instances of Chrome, launching it as admin, go to a chan and update the settings you want, then close all instances of chrome.

See if the settings keep.

**Comment by saxamaphone69** [comment]
It turns on/off on click. Turn off "Catalog Hover Toggle" if you don't want that.
