### ISSUE TITLE
/adv/ doesn't load

### ISSUE THREAD

**Issue by maxwell5** [ccd0/4chan-x#217]
Index refresh failed. Error (0) message that soon disappear.

**Comment by ccd0** [comment]
reported again in #479, #348

**Comment by ccd0** [comment]
and #705

**Comment by ccd0** [comment]
The workaround until EasyList fixes this is to add

    @@||4chan.org/adv/
    @@||4cdn.org/adv/

to your filters. This does not unblock any ads.

**Comment by ccd0** [comment]
And you can re-report it at
https://forums.lanik.us/viewforum.php?f=64

**Comment by ccd0** [comment]
I've worked around the issue for now. It should now be possible to use /adv/ without making any exceptions. Let me know if you still encounter any problems there.
