### ISSUE TITLE
non-java captcha not working correctly in opera

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2175]
Submitter: Anon
Email: ymous@yahoo.ru
clicking anywhere on box doesn't work and code isn't auto-copied, tested on new install of opera for confirmation

**Comment by ccd0** [comment]
Probably an issue with the userscript manager not running 4chan X on frames. What userscript manager are you using?

**Comment by Tororu** [comment]
Been having the same issue for months. Running Opera 60.0.3255.170 with Tampermonkey
