### ISSUE TITLE
Duplicate replies

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2177]
Happens randomly when I first open a thread, all reply links get duplicated on all posts that got quoted. Every time it happens one reply link or quote is bigger than the other duplicate. It goes away when the page is refreshed. 

4chan X 1.14.5.5, stock Firefox no add-ons

**Comment by kroblorg** [comment]
> Does it look like [this](https://imgur.com/e8Sjxmw)?

I have also have this issue and it does look like that.
