### ISSUE TITLE
Webm bug?

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2186]
Submitter: fxy0
I've updated 4chan x to ver  2.40.76 along with oneechan (beacuse of that 4channel thing) and now when I expand a webm the progress slider won't show.

**Comment by CharAznableLoNZ** [comment]
If this is on Chrome, it's a Chrome thing due to a change in the way Chrome deals with embedded videos.  I had to change it a awhile back under the flags to get the old UI back.

**Comment by ubone** [comment]
can confirm there is no issue on firefox

**Comment by CharAznableLoNZ** [comment]
In Chrome://flags set New Media Controls to disabled.
