### ISSUE TITLE
Thread updater takes longer than time set

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2189]
I've noticed that even though my thread updater is set for 5 seconds, it really only works about every 30 seconds or so. It'll show the countdown from 5 to 1 to updating and nothing happens. It'll keep doing this until it actually pulls up new posts from about 30 seconds ago. Is this just me? Is this a limitation on 4chan's end? Anything I can do about it?

**Comment by builderheg** [comment]
I'm getting this too. The number next to the icon that shows the number of unread posts doesn't update either.

**Comment by broski93** [comment]
Might be because of
https://boards.4channel.org/qa/thread/2512112

**Comment by beriah** [comment]
Also happening here.
