### ISSUE TITLE
Tab icon doesn't refresh

### ISSUE THREAD

**Issue by instagramtest** [ccd0/4chan-x#2190]
If a thread is archived the tab icon fails to indicate it (by changing colors to red). I've tested most of the recent versions and as fas as I can tell this issue was introduced with .5.2

Using Firefox 64

**Comment by TwilightSkyline** [comment]
similar issue here. for me, it's only the blue read favicon. i checked in the advanced settings and the image for it seems to be missing or broken. this is the same for all favicon themes. see if you have similar results.

**Comment by AirplaneRandy** [comment]
Same here. I shitpost all the time and I always have to check the thread to see if it was deleted. It was faster previously to just see if the icon turned red.

**Comment by beriah** [comment]
https://github.com/ccd0/4chan-x/issues/2039

**Comment by ccd0** [comment]
Confirmed, will fix. #2039 appears to be unrelated.
