### ISSUE TITLE
hope page images not working

### ISSUE THREAD

**Issue by alidan** [ccd0/4chan-x#2199]
![chrome_2019-01-09_03-37-15](https://user-images.githubusercontent.com/2681758/50890525-fd3faa00-13bf-11e9-97c7-dc48370606ad.png)

The site it self works, everything on there works, however these images do not load and havent for quite a while. at first I thought it was hiroshimoot fucking with the site, but then I saw my little brothers laptop and there is no issue. 
disabling adblock and umatrix doesn't fix this, but an incognito window does, and at that point I think the only thing tied to 4chan is 4chan-x

Is there something stupid I did that blocks them in 4chan x or is this a known problem?

**Comment by ccd0** [comment]
This seems unlikely to be related to 4chan X. Try checking what happens when you disable your other extensions.

**Comment by alidan** [comment]
I think I found out what was happening, but it still doesn't make much sense to me. 
incognito only has adblock+ and this is used as the more or less clean browser. 

normally, I have 2 4chan bookmarks
4chan.org
www.4chan.org
both of these default to a non https version, with the 4chan.org one doing it every time, this one regardless of what it does, will not display any images incog or normal. 
www.4chan.org also won't display images at all, either incog or on 4chan
however if you go to the frontpage from somewhere in 4chan, for me it will default over to an https version of the page, and it will display images, even going back to forcing a non https version though
http://www.4chan.org/ will display images for a time, and then it will stop. I have no idea why this is though, and this may not be correct, it's just what i'm seeing.
