### ISSUE TITLE
favicon is not updated when thead archives

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2206]
Latest Firefox Developer Edition and violent monkey, 4chanx 1.14.5.7
When a thread is archived it is properly marked as archived in the thread stats, but the favicon is not updated to be red until I refresh the page.

**Comment by beriah** [comment]
https://github.com/ccd0/4chan-x/issues/2039

**Comment by TwilightSkyline** [comment]
https://s.4cdn.org/image/favicon-ws.ico
does this display for you?

**Comment by ccd0** [comment]
duplicate of #2190
