### ISSUE TITLE
Keybinds seem to have stopped working

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2216]
Submitter: Anon
Email: anon@gmail.com
I reset the settings after I discovered the error, and keybinds still don't seem to work.

**Comment by ccd0** [comment]
They're working for me. What version, browser, and userscript engine are you on?

**Comment by Bebop79** [comment]
Same issue on Firefox Quantum 64.0.2 with the latest version of Tampermonkey

**Comment by ccd0** [comment]
Try going to your uBlock Origin settings under Filter Lists, then clicking "Purge all caches" and "Update now"

**Comment by ccd0** [comment]
Can you reproduce the problem without any other extensions running?

**Comment by philfry** [comment]
No. I created a new firefox profile, installed violentmonkey and 4chan-x only, and everything works fine.
I'll add the other extensions and try to figure out what kills 4chan-x' keybindings.

**Comment by philfry** [comment]
I think the problem is in the ublock filters around line 1870:
```
4chan.org##+js(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)
```
When adding a custom filter overriding this one the keybindings work again:
```
4chan.org##+js(abort-current-inline-script.js, String.fromCharCode, /\/\*[0-9a-f]{40}\*\//)$badfilter
```

**Comment by ccd0** [comment]
That filter should have been removed.
https://github.com/uBlockOrigin/uAssets/commit/a1eeaa31dfb44061024f3681b1cb107f690e946e
Are you sure your filter list is up to date?

**Comment by philfry** [comment]
I purged the cache and did an update. The filter at line 1870 is still present. The patch you're referring to regards a different filter.
