### ISSUE TITLE
what the hell are you guys doing

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2230]
Submitter: What The
Email: mgoplzplzplz@gmail.com
>"4chan X" has requested additional permissions.

>It could:

>Read and change all your data on the websites you visit

what the fuck

**Comment by chiemduyan** [comment]
What was that for anyway?

**Comment by ccd0** [comment]
It should normally ask this when you use the "Post from URL" feature.

**Comment by v1tal** [comment]
this keeps happening when i try to download images + reverse image search

**Comment by ccd0** [comment]
Apologies for the bug and thanks for helping diagnose it. As of v1.14.5.13 this should be fixed.
