### ISSUE TITLE
Failed to load board configuration. Invalid Data

### ISSUE THREAD

**Issue by CharAznableLoNZ** [ccd0/4chan-x#2234]
1.14.5.12
Threads load, posting works, however the auto updated does not work and every page has the following error pop up.

Failed to load board configuration. Invalid Data

In the Chrome console we see below.  Looks like the updater is getting broken.

script.js:4551 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://a.4cdn.org/g/thread/69918146.json?s=ThreadUpdater&t=1551086493351 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
(anonymous) @ script.js:4551
update @ script.js:19445
timeout @ script.js:19434
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setTimeout (async)
timeout @ script.js:19431
setInterval @ script.js:19410
node @ script.js:19265
Callbacks.execute @ script.js:5380
callbackNodes @ script.js:25472
initThread @ script.js:25333
initReady @ script.js:25306
cb @ script.js:4464

script.js:19466 Uncaught TypeError: Cannot read property 'posts' of null
    at Object.parse (script.js:19466)
    at XMLHttpRequest.load (script.js:19325)

**Comment by CharAznableLoNZ** [comment]
![screenshot_20190226_014458](https://user-images.githubusercontent.com/2172796/53403345-4cd63700-3968-11e9-9b51-aa29dea33ff3.png)

**Comment by CharAznableLoNZ** [comment]
Switching from the Chrome extension to running 4chanX in tampermonkey seems to have fixed it.

**Comment by ccd0** [comment]
Not exactly a fix from my perspective but this seems to be a duplicate of #2228 so marking it as such.
