### ISSUE TITLE
MAJOR loading speed issues in chrome

### ISSUE THREAD

**Issue by skidrv42** [ccd0/4chan-x#2241]
so im using google chrome with the 4chan x app and the images, webms and gif load very slow not only on 4chan but on a different cloudflare based chan aswell. however whenever i enter incognito mode everything opens up fast yet again on both chan's. i had only ublock origin running in both normal chrome and incognito and it didint affect anything.

**Comment by ccd0** [comment]
Do you have loading speed issues if that's the only tab you have open? What version of Chrome are you on?

**Comment by skidrv42** [comment]
version Version 72.0.3626.121 (Official Build) (64-bit) and and yes issues still even if its the only tab, i think it might have something to do with the permissions towards the google capatcha things

**Comment by Tenome** [comment]
I have the same issue but figured it was 4chan's image servers being garbage. Going incognito does seem to make it load faster.
