### ISSUE TITLE
Unable to update threads

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2249]
Submitter: Joseph
Email: karatejoe103@gmail.com
I am on version 1.14.5.13 and have been getting a message on 4chan that reads "Failed to load board configuration. Invalid Data" in a yellow box whenever Ioad a board or thread. It seems like this has disallowed me from updating threads and boards altogether. I believe I'm on the most recent version so I doubt that's the issue. I've also tried uninstalling and reinstalling with no success. Is there a fix for this currently?

**Comment by strotee** [comment]
Joseph,

See this thread https://github.com/ccd0/4chan-x/issues/2246 for the fix.
