### ISSUE TITLE
[Feature Request] ID Jumper

### ISSUE THREAD

**Issue by ebinBuddha** [ccd0/4chan-x#2252]
It would be cool to have an ID jumper functionality like this here already included in 4chanX:
https://github.com/ebinBuddha/ID-Jumper-for-4chan

**Comment by ccd0** [comment]
Looks useful and I'd accept a pull request for this. Posts with capcodes could use a similar treatment.

Have you thought about having the next post move to the the position of the post you clicked on instead of to the top? Then you wouldn't have to move the mouse as much.

**Comment by ebinBuddha** [comment]
I've thought about it but never felt the urge to do it.
I'll try and come up with some coffescript code
