### ISSUE TITLE
"Error loading https://a.4cdn.org/boards.json; try going to chrome://flags/#network-service and disabling the network service flag."

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2257]
Submitter: Kyle Vallade
Email: kylearmykid@gmail.com
Not entirely sure what this means or what to do

**Comment by Dayus9** [comment]
Same messages here. This is causing auto updates to not work I have to hit F5 now and when I post quick replies I get no response saying my post is successfull. Screenshot attached. 

![Clipboard01](https://user-images.githubusercontent.com/49004306/55110492-0b07f000-50d0-11e9-84a1-eaed08b69dd9.jpg)

**Comment by bakugo** [comment]
Type chrome://flags/#network-service into your URL bar and disable the network service option that comes up, then restart the browser.

**Comment by nefariousbear** [comment]
Disabling the network service option and restarting the browser did not fix the issue. This is still occurring for me.

**Comment by AGSPhoenix** [comment]
Can confirm that disabling the network service works.

It seems like the network service [isn't going away anytime soon](https://9to5google.com/2019/02/19/chrome-72-extensions-bug/), and asking users to go modify browser flags isn't a great workaround. Are there any plans for a more long term fix for this?

**Comment by ccd0** [comment]
#2228
