### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ponboo** [ccd0/4chan-x#2262]

**Comment by ccd0** [comment]
Most likely an issue with your filters, not 4chan X or uBlock Origin itself. Make sure your filters are up to date (purge cache and update). If it still happens, use the logger to find out what filter is blocking it, then either add an exception rule or don't use the filter list it's from.

**Comment by bathroomjuuler** [comment]
![adv](https://user-images.githubusercontent.com/49004905/55291162-4b6ab500-53d3-11e9-828e-475e9db568c8.png)
I always have original form hidden and I just opened it there and I noticed this. Sorry for wasting your time
