### ISSUE TITLE
Style won't change in NSFW boards anymore

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2265]
I was browsing /int/ and opened 4chan X settings to change the favicon to Original and the thread updater interval to 15 seconds. After refreshing I opened /wg/ in other tab and went to the bottom of the page in order to change the style to Tomorrow but it won't change, I tried refreshing and restarting the browser with no results. If I refresh the page after changing the option to Tomorrow while on the Catalog it keeps displaying Tomorrow in the box even though the style didn't change. But if I do that in a thread it changes back to Yotsuba and obviously the style doesn't change either. 

I could reproduce this in other NSFW boards aside from /wg/.

**Comment by Anonymous583** [comment]
Happens to me too.

**Comment by Poilaucul** [comment]
Concerned too, when I pause AdBlock selected style is back.

**Comment by ccd0** [comment]
Ad filter issue, force an update and you should be fine, at least if you use "uBlock filters – Unbreak"

**Comment by Addest3** [comment]
And what about those of us who use adblock?

**Comment by ccd0** [comment]
@Addest3
add
`@@||4cdn.org^$script,domain=4chan.org`
to your filters
https://github.com/uBlockOrigin/uAssets/commit/92aa3ea19b5c5d0445a7c51aab536ca7ac551205

**Comment by BondiBear** [comment]
All had to do to fix this was disable '_Enhanced Ad Blocking_' in **Ghostery**.

I changed **nothing** in uBO or 4chanx.

**Comment by phillycheeseteak** [comment]
> 
> 
> @Addest3
> add
> `@@||4cdn.org^$script,domain=4chan.org`
> to your filters
> [uBlockOrigin/uAssets@92aa3ea](https://github.com/uBlockOrigin/uAssets/commit/92aa3ea19b5c5d0445a7c51aab536ca7ac551205)

OP here, made an account just to thank you. Works like a charm.

**Comment by Poilaucul** [comment]
> @Addest3
> add
> `@@||4cdn.org^$script,domain=4chan.org`
> to your filters
> [uBlockOrigin/uAssets@92aa3ea](https://github.com/uBlockOrigin/uAssets/commit/92aa3ea19b5c5d0445a7c51aab536ca7ac551205)

Working good on adblock
