### ISSUE TITLE
connection error while posting/ failed to load board configuration

### ISSUE THREAD

**Issue by DankMickey** [ccd0/4chan-x#2268]
![image](https://user-images.githubusercontent.com/11018009/55408368-dfe92a80-552d-11e9-953a-4e2f8b05fe5b.png)
April Fools seems to have broken 4chan X even after the event.

**Comment by DankMickey** [comment]
![image](https://user-images.githubusercontent.com/11018009/55408486-145ce680-552e-11e9-9775-b3021eaed720.png)
It fails to load the board configuration

**Comment by Poilaucul** [comment]
chrome://flags/#network-service
Disable "network service"

Don't know the drawbacks tho.

**Comment by gonrhcp** [comment]
I am having the same problem, can't post in some boards like /adv/ 
Using Firefox and 4chanX 1.14.6.7

**Comment by miniwa** [comment]
Same issue.
Chrome: 73.0.3683.103
4chan-x: 1.14.6.8

**Comment by ccd0** [comment]
Are you on Chrome; if so; did disabling the network service flag help? Have you tried temporarily disabling your ad blocker and other extensions to see if your issue is related to them? (If it's your ad blocker, you should try updating your filter lists.)

**Comment by blixnood** [comment]
Yes, disabling the option in the browser removes the error message, but that isn't a fix.

Disabling ad blocking does nothing since there are only a few things required to view 4chan in the first place.

Unless we somehow all share the same extension(s), that isn't the issue.

**Comment by AuroraZero** [comment]
Try allowing the extension access to all sites, seemed to fix it for me

Settings > Extensions > 4chan X > Allow access to all sites
