### ISSUE TITLE
Catalog hover expand turning on after right click.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2269]
Submitter: Anonymous
Email: anonm371@gmail.com
Exactly as the title says. I set the option off and if I right click it turns back on. It doesn't seem to happen if I click above the threads in the catalog, but if I right click somewhere in the middle of the catalog and click away somewhere else on the catalog happens just about every time. Using chrome store version 1.14.5.16 on Chrome version 73.0.3683.86. I do have oneechan installed however it still happens when turned off. No errors in the console. Tried with a settings reset, still the same.

**Comment by ccd0** [comment]
It should happen on left click; this behavior can be turned off by unchecking "Catalog Hover Toggle". I can't reproduce it happening on right click. Is there anything in particular about your setup that might cause it to confuse a right click for a left click?

**Comment by saxamaphone69** [comment]
It turns on/off on click. Turn off "Catalog Hover Toggle" if you don't want that.
