### ISSUE TITLE
Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error on firefox

### ISSUE THREAD

**Issue by niconeitor** [ccd0/4chan-x#2270]
I've seen people on chrome get this error and im getting it on firefox now, i tried tampermonkey and violentmonkey but still get the error
https://i.imgur.com/BquZp43.png
Image related

**Comment by the-nothingman** [comment]
If you're using an ad blocker then certain easylist rules cause it. If you're using uBlock, go to My filters and add:

@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'
@@|blob:$image,media,domain=4chan.org
@@||boards.4chan.org^$csp
@@||4channel.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'
@@|blob:$image,media,domain=4channel.org
@@||boards.4channel.org^$csp

**Comment by ccd0** [comment]
What version of everything are you using? Are you using an ad blocker, and if so, did the suggested filters help?

**Comment by niconeitor** [comment]
problem solved, i had to make a rule exception for "https://mayhemydg.github.io/archives.json/archives.json" on ublock
