### ISSUE TITLE
Thread watcher bug?

### ISSUE THREAD

**Issue by akdrkzkzkfhxm** [ccd0/4chan-x#2274]
Is it me or that my thread watcher turns red whenever any reply is posted on the thread I replied to? Yes, I know this is exactly what is said on the thread watcher menu. 

But before few days ago, my thread watcher turned red only when (1)The thread that I started gets a reply, and (2)The reply I posted gets another replies. Now I have one more case, which is (3)When the thread I replied to gets replies to some other replies other than mine. So, basically I get notified every time they talk each other. I want check something only sent to me. I don't want this watcher button trips whenever a reply that's not related to my things is posted.

Before this happened, I haven't even checked what are in the thread watcher menu, and haven't touched anything. Something went wrong I'm sure. 

The only thing I did was disabling "chrome://flags/#network-service" that this 4chan-X suggested for the updating issues. Of course if I turn this thing back on, then I get none of updates from any.

**Comment by ccd0** [comment]
What version of 4chan X are you on? Can you export and post your settings, especially if you can do it just after the bug happens but before you open the thread?

**Comment by ccd0** [comment]
Also, in a thread where it happens, can you check whether either (1) the OP or (2) the post that gets a reply are recorded as yours? You can check by looking in the post menu to see whether "You" is checked. This would tell us whether this is an issue with the thread watcher or with the mechanism recording which posts you made.

**Comment by akdrkzkzkfhxm** [comment]
Sorry for the all the fuss. But it somehow went back to normal. Maybe me turning on and off the 'Auto Watch Reply' button did work? And I rarely start my own thread so it was clearly from the thread of others. My version is 1.14.5.16, and I didn't 'export' the setting because it was my first issue for 4chanX. I didn't even know you can export a thing. Well thank you for the attention.
