### ISSUE TITLE
Webm contact

### ISSUE THREAD

**Issue by InstallGentoo11** [ccd0/4chan-x#228]
![button](https://cloud.githubusercontent.com/assets/6108677/5383206/f6da803a-80b7-11e4-8783-c4655b71701a.jpg)
I find the webm contact button (for after expanding it) being on a pretty annoying place. Maybe it highly preferential, but putting a button like this on the top left side of the webm, under the tick box for post deletion/report, might be a lot better place.

**Comment by ccd0** [comment]
I kind of like the link because it's larger.  But do you still care about this now that click to contract is the default?

**Comment by InstallGentoo11** [comment]
I personally don't care at this point, it is fine the way it is now, but feel free to do whatever you want. Someone else might like it, or not care himself.
