### ISSUE TITLE
Webms not closing on click (firefox)

### ISSUE THREAD

**Issue by niconeitor** [ccd0/4chan-x#2280]
using stable version of 4chan x with firefox and my webms dont close when i click on them, or when i drag them to the left (with click pass through enabled of course) instead, i have to click a small text above the webm that says "contract" in order to close the webms. Shit is driving me insane and i have no idea how to fix this.

**Comment by kakhulu31** [comment]
>can't reproduce 
Really? Tested on latest and 2 years old firefox with violent and tampermonkey. Same behavior

**Comment by saxamaphone69** [comment]
There's existing issues outlining the same problem, apologies.

**Comment by kakhulu31** [comment]
>drag them to the left

This works, swipe has to be really long though.

**Comment by niconeitor** [comment]
Well, im glad to see im not the only one that ever had this problem, i thought it was me just being cursed, i just eventually defaulted to using chrome instead, i was never able to fix this problem.
