### ISSUE TITLE
Failed to load board configuration. Invalid Data.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2291]
Submitter: Lucas
Email: scorpio1994@gmail.com
4chan X version 1.14.7.3
Chrome Version 74.0.3729.108 (Official Build) (64-bit)
Error messages: https://gyazo.com/fdecf3352de53fddf5ace03769853c95

Error pops up when opening board or any thread within it. Won't auto-update threads. Doesn't happen when 4chan X is disabled.

**Comment by AuroraZero** [comment]
I found that allowing 4chan X access to data on all sites it loaded properly
Settings > Extensions > 4chan X > Allow access to all sites

**Comment by blixnood** [comment]
Dupe https://github.com/ccd0/4chan-x/issues/2228
