### ISSUE TITLE
All 4channel tabs crashing with Aw Snap every 10 minutes.

### ISSUE THREAD

**Issue by CharAznableLoNZ** [ccd0/4chan-x#2304]
Open a few dozen tabs on different boards.
All 4channel tabs crash at once.  4chan tabs are not affected.
Latest Chrome, 4chanx and tampermonkey.

This is annoying as fuck since you have to reload every tab again and again.

**Comment by CharAznableLoNZ** [comment]
They also go unresponsive quite often.  Taking 30+ seconds to display a tab, all the while Chrome is asking to kill the tab.

**Comment by CharAznableLoNZ** [comment]
Since this post has been made, it's crashed 3 times.

**Comment by CharAznableLoNZ** [comment]
Clearing caches and what not has helped however Chrome is still convinced the tabs are unresponsive and brings up the kill it box.

**Comment by CharAznableLoNZ** [comment]
Caches fixed the performance issues, the tabs still crashed though.

**Comment by CharAznableLoNZ** [comment]
And again.

**Comment by CharAznableLoNZ** [comment]
Going to try switch from the script to the extension, we'll see how that goes.

**Comment by CharAznableLoNZ** [comment]
The extension is doing the invalid data issue #2228.  Guess that means manual refreshing is in order.

**Comment by CharAznableLoNZ** [comment]
While it is more stable, it still crashes eventually.

**Comment by ccd0** [comment]
Are you using any other extensions? Does this happen with settings reset to default? Have you tried turning features off to see if any particular feature is causing this?

**Comment by CharAznableLoNZ** [comment]
I haven't tried a reset yet.  I was going to try that this weekend once I got some time to look into it again.  Three other extensions, ublock origin, umatrix, and tampermonkey with oneechan for rice.

**Comment by CharAznableLoNZ** [comment]
Tried the rest, still got a crash.  I'm starting to wonder if it's just too many tabs for the extension to handle.

**Comment by bakugo** [comment]
Have you tried with other extensions disabled? If it really only happens on 4channel.org and not 4chan.org, it could be an issue with a blocker extension since 4chan and 4channel have different ads.

>just too many tabs for the extension to handle.

I've had literally hundreds of 4chan tabs open at once with the same setup (chrome+tampermonkey) with no tab crashes so that can't be it. I do have hardware acceleration enabled though.

Also, maybe looking at the [browser debug log](https://support.google.com/chrome/a/answer/6271282) could help?

**Comment by CharAznableLoNZ** [comment]
It's possible ublock could be doing it, however don't really feel comfortable letting mootwo's ad networks run unblocked.  Looking over ublock's settings I can see this line added at the end from last time mootwo fucked something up.

@@||4chan.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'
I've added one to reflect 4channel.  We'll see if that does anything.
@@||4channel.org^*$csp=default-src 'self' * data: 'unsafe-inline' 'unsafe-eval'

**Comment by CharAznableLoNZ** [comment]
That didn't work.  I've moved Chrome's directory to a HDD and enabled debugging.  Didn't want the debug logs to eat an SSD.  Next crash I'll grab the logs.

**Comment by bakugo** [comment]
>Didn't want the debug logs to eat an SSD

The act of loading a single page in a browser on an SSD probably uses more writes than any form of logging...

**Comment by CharAznableLoNZ** [comment]
The logs are being written to the log file on top of all the usual stuff.  It's something I've wanted to move for some time just haven't gotten around to it.

Still waiting on a crash however see this pop up some times when I switch between 4channel tabs.

`[32039:32039:0519/035202.144658:INFO:CONSOLE(0)] "Error in event handler: TypeError: callbacks[response.id] is not a function
    at chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5237:29", source: https://www.google.com/recaptcha/api/fallback?k=6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc (0)
[32039:32039:0519/035208.334566:INFO:CONSOLE(0)] "Error in event handler: TypeError: callbacks[response.id] is not a function
    at chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:5237:29", source: https://www.google.com/recaptcha/api/fallback?k=6Ldp2bsSAAAAAAJ5uyx_lx34lJeEpTLVkP5k04qc (0)
`

**Comment by CharAznableLoNZ** [comment]
Unfortunately instead of generating a log file it just uploaded the dmp file to google.  I've requested the file from them however I doubt that'll happen.

Console spit out this while it did it.
--2019-05-20 03:40:47--  https://clients2.google.com/cr/report
Resolving clients2.google.com (clients2.google.com)... 216.58.206.78, 2a00:1450:4009:815::200e
Connecting to clients2.google.com (clients2.google.com)|216.58.206.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/fd/4’

Crash dump id: 98615c68a6a2cf6b

     0K                                                         950K=0s

2019-05-20 03:40:49 (950 KB/s) - ‘/dev/fd/4’ saved [16]

--2019-05-20 03:40:49--  https://clients2.google.com/cr/report
Resolving clients2.google.com (clients2.google.com)... 216.58.206.78, 2a00:1450:4009:815::200e
Connecting to clients2.google.com (clients2.google.com)|216.58.206.78|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘/dev/fd/4’

**Comment by CharAznableLoNZ** [comment]
Well I'm surprised, they pasted the crash.

`Thread 0 (id: 0x00007e62) CRASHED [SIGTRAP @ 0x00000000 ] MAGIC SIGNATURE THREAD
Stack Quality100%Show frame trust levels
0x0000557d480818bc	(chrome -heap_page.cc:677 )	blink::NormalPageArena::AllocatePage()
0x0000557d48082471	(chrome -heap_page.cc:929 )	blink::NormalPageArena::OutOfLineAllocate(unsigned long, unsigned long)
0x0000557d4b6bd4ff	(chrome -heap_page.h:1056 )	WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >* blink::HeapAllocator::AllocateHashTableBacking<WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::HashTable<WTF::AtomicString, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::KeyValuePairKeyExtractor, WTF::AtomicStringHash, WTF::HashMapValueTraits<WTF::HashTraits<WTF::AtomicString>, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::HashTraits<WTF::AtomicString>, blink::HeapAllocator> >(unsigned long)
0x0000557d4b6bd011	(chrome -heap_allocator.h:126 )	WTF::HashTable<WTF::AtomicString, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::KeyValuePairKeyExtractor, WTF::AtomicStringHash, WTF::HashMapValueTraits<WTF::HashTraits<WTF::AtomicString>, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::HashTraits<WTF::AtomicString>, blink::HeapAllocator>::Expand(WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >*)
0x0000557d4b6bcf33	(chrome -hash_table.h:1357 )	WTF::HashTableAddResult<WTF::HashTable<WTF::AtomicString, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::KeyValuePairKeyExtractor, WTF::AtomicStringHash, WTF::HashMapValueTraits<WTF::HashTraits<WTF::AtomicString>, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::HashTraits<WTF::AtomicString>, blink::HeapAllocator>, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > > WTF::HashTable<WTF::AtomicString, WTF::KeyValuePair<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > >, WTF::KeyValuePairKeyExtractor, WTF::AtomicStringHash, WTF::HashMapValueTraits<WTF::HashTraits<WTF::AtomicString>, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::HashTraits<WTF::AtomicString>, blink::HeapAllocator>::insert<WTF::HashMapTranslator<WTF::HashMapValueTraits<WTF::HashTraits<WTF::AtomicString>, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >, WTF::AtomicStringHash, blink::HeapAllocator>, WTF::AtomicString const&, std::nullptr_t>(WTF::AtomicString const&, std::nullptr_t&&)
0x0000557d4b6b9705	(chrome -hash_map.h:542 )	blink::RuleSet::AddToRuleSet(WTF::AtomicString const&, blink::HeapHashMap<WTF::AtomicString, blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > >, WTF::AtomicStringHash, WTF::HashTraits<WTF::AtomicString>, WTF::HashTraits<blink::Member<blink::HeapLinkedStack<blink::Member<blink::RuleData const> > > > >&, blink::RuleData const*)
0x0000557d4b6b9cf6	(chrome -rule_set.cc )	blink::RuleSet::AddRule(blink::StyleRule*, unsigned int, blink::AddRuleFlags)
0x0000557d4b6ba70a	(chrome -rule_set.cc:311 )	blink::RuleSet::AddChildRules(blink::HeapVector<blink::Member<blink::StyleRuleBase>, 0u> const&, blink::MediaQueryEvaluator const&, blink::AddRuleFlags)
0x0000557d4b6ba9d4	(chrome -rule_set.cc:355 )	blink::RuleSet::AddRulesFromSheet(blink::StyleSheetContents*, blink::MediaQueryEvaluator const&, blink::AddRuleFlags)
0x0000557d4b6e9afc	(chrome -style_sheet_contents.cc:605 )	blink::StyleSheetContents::EnsureRuleSet(blink::MediaQueryEvaluator const&, blink::AddRuleFlags)
0x0000557d4b6c88ff	(chrome -style_engine.cc:576 )	blink::StyleEngine::RuleSetForSheet(blink::CSSStyleSheet&)
0x0000557d4b6d9704	(chrome -document_style_sheet_collection.cc:89 )	blink::DocumentStyleSheetCollection::CollectStyleSheets(blink::StyleEngine&, blink::DocumentStyleSheetCollector&)
0x0000557d4b6d993b	(chrome -document_style_sheet_collection.cc:129 )	blink::DocumentStyleSheetCollection::UpdateActiveStyleSheets(blink::StyleEngine&)
0x0000557d4b6c89c8	(chrome -style_engine.cc:458 )	blink::StyleEngine::UpdateActiveStyleSheets()
0x0000557d4b6c7325	(chrome -style_engine.cc:497 )	blink::StyleEngine::UpdateActiveStyle()
0x0000557d4b7096e3	(chrome -document.cc:2284 )	blink::Document::UpdateActiveStyle()
0x0000557d4b707560	(chrome -document.cc:2237 )	blink::Document::UpdateStyleAndLayoutTree()
0x0000557d4b947297	(chrome -local_frame_view.cc:659 )	blink::LocalFrameView::UpdateLayout()
0x0000557d4b947c49	(chrome -local_frame_view.cc:916 )	blink::LocalFrameView::UpdateLayout()
0x0000557d4b94e0cc	(chrome -local_frame_view.cc:2867 )	blink::LocalFrameView::UpdateStyleAndLayoutIfNeededRecursive()
0x0000557d4b94cb61	(chrome -local_frame_view.cc:2298 )	blink::LocalFrameView::UpdateLifecyclePhases(blink::DocumentLifecycle::LifecycleState, blink::DocumentLifecycle::LifecycleUpdateReason)
0x0000557d4be570bf	(chrome -page_animator.cc:108 )	blink::PageAnimator::UpdateAllLifecyclePhases(blink::LocalFrame&, blink::DocumentLifecycle::LifecycleUpdateReason)
0x0000557d4b8a1159	(chrome -web_view_impl.cc:1594 )	blink::WebViewImpl::UpdateLifecycle(blink::WebWidget::LifecycleUpdate, blink::WebWidget::LifecycleUpdateReason)
0x0000557d4b8a00e1	(chrome -web_widget.h:146 )	blink::WebViewImpl::ResizeViewWhileAnchored(float, float, bool)
0x0000557d4b8a0327	(chrome -web_view_impl.cc:1444 )	blink::WebViewImpl::ResizeWithBrowserControls(blink::WebSize const&, float, float, bool)
0x0000557d4cb195e2	(chrome -render_view_impl.cc:1195 )	non-virtual thunk to content::RenderViewImpl::ResizeWebWidgetForWidget(gfx::Size const&, float, float, bool)
0x0000557d4cb29991	(chrome -render_widget.cc:1563 )	content::RenderWidget::SynchronizeVisualProperties(content::VisualProperties const&)
0x0000557d4cb24d28	(chrome -render_widget.cc:889 )	content::RenderWidget::OnSynchronizeVisualProperties(content::VisualProperties const&)
0x0000557d4cb20bc7	(chrome -tuple.h:52 )	content::RenderWidget::OnMessageReceived(IPC::Message const&)
0x0000557d48e4c209	(chrome -ipc_channel_proxy.cc:324 )	IPC::ChannelProxy::Context::OnDispatchMessage(IPC::Message const&)
0x0000557d488d99da	(chrome -callback.h:97 )	base::TaskAnnotator::RunTask(char const*, base::PendingTask*)
0x0000557d488da595	(chrome -thread_controller_with_message_pump_impl.cc:363 )	base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*)
0x0000557d488da374	(chrome -thread_controller_with_message_pump_impl.cc:214 )	base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoSomeWork()
0x0000557d48899525	(chrome -message_pump_default.cc:39 )	base::MessagePumpDefault::Run(base::MessagePump::Delegate*)
0x0000557d488dadc4	(chrome -thread_controller_with_message_pump_impl.cc:448 )	base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta)
0x0000557d488b76ae	(chrome -run_loop.cc:161 )	base::RunLoop::RunWithTimeout(base::TimeDelta)
0x0000557d4cb5d746	(chrome -renderer_main.cc:223 )	content::RendererMain(content::MainFunctionParams const&)
0x0000557d4848d222	(chrome -content_main_runner_impl.cc:513 )	content::ContentMainRunnerImpl::Run(bool)
0x0000557d484c36ba	(chrome -main.cc:415 )	service_manager::Main(service_manager::MainParams const&)
0x0000557d4848b1b0	(chrome -content_main.cc:19 )	content::ContentMain(content::ContentMainParams const&)
0x0000557d464645b2	(chrome -chrome_main.cc:103 )	ChromeMain
0x00007f2b54035b96	(libc-2.27.so -libc-start.c:310 )	__libc_start_main
0x0000557d461a7029	(chrome + 0x0199f029 )	_start
0x00007ffe7a665b47		

`

**Comment by bakugo** [comment]
According to the crash log, the browser is crashing because it's [failing to allocate memory while updating stylesheets](https://chromium.googlesource.com/chromium/src/third_party/+/99a08965609253056ae690580586161109bfa4ac/blink/renderer/platform/heap/heap_page.cc#677).

So either your computer is just really low on memory, or something in the page is causing a major leak (if this is the case it's probably oneechan). It also explains why tabs might go unresponsive, that's normal when memory is being paged out. You'll have to look at your computer's and chrome's task managers to see what's actually causing it.

**Comment by CharAznableLoNZ** [comment]
The machine has 32GB of RAM.  At the time of the last crash, the machine had 8GB of free RAM.  Feels like Chrome is limiting the RAM usage artificially if the process ran out.

**Comment by CharAznableLoNZ** [comment]
I've updated to the latest oneechan that, so far, it seems stable.  I'll probably close it at the end of the weekend if it stays stable.

**Comment by CharAznableLoNZ** [comment]
Well it still crashes but it's much less common.  Can live with it for now.
