### ISSUE TITLE
Quote Highlight works only for OP

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2313]
The Quote Highlight feature only seems to work for the OP now. Any post afterwards isn't highlighted, it's just previewed. Tested it with fresh profile and reset settings, same problem happens.

Running it thrrough Violentmonkey 2.10.5 and Firefox 67.0

**Comment by GMLW** [comment]
I'm having mostly the same problem. For some reason, I'll very occasionally find a post that actually will highlight. But 99% of the time, highlight doesn't work.
