### ISSUE TITLE
4chan X won't export settings.

### ISSUE THREAD

**Issue by HISAFUMI** [ccd0/4chan-x#2320]
I've been having this issue for a while.

Whenever I click on "Export" in the settings menu, nothing happens. Everytime my browser crashes, I end up losing all my settings, which is why I'd like to export them...

**Comment by ccd0** [comment]
Does it work if you temporarily disable your ad blocker?

**Comment by HISAFUMI** [comment]
> Does it work if you temporarily disable your ad blocker?

I'm afraid not, I've tried disabling all other extensions and then exporting, but it still doesn't work for some reason.

**Comment by ccd0** [comment]
Do you get any error messages in the console when you try to do it? What browser are you using?

**Comment by blixnood** [comment]
Export works for me on 1.14.8.0 in Vivaldi 2.6.1566.44.
