### ISSUE TITLE
Connection error only on /r/ board

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2325]
Submitter: blah
Email: blah@blah.com
I get the "Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error" error but only on /r/, and when checking the 4chan X settings, the version number on /r/ is different to the one I currently have installed, instead of showing version 1.14.7.4 like all other boards, /r/ shows version  1.13.15.10 regardless of whether I have adblock/ublock origin installed or not, and regardless of whether I upgrade or downgrade 4chan X.

**Comment by blixnood** [comment]
I can't reproduce this.
