### ISSUE TITLE
Disable thread preview option

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#2326]
![Untitled](https://user-images.githubusercontent.com/5096684/59155045-1362ab00-8ac3-11e9-81c1-4491f5136376.png)

How do I disable the popup thread preview? I can't find it in the Settings list.

**Comment by Vulgaris-Viridis** [comment]
Disable JSON Index.

**Comment by ccd0** [comment]
The specific options are "Catalog Hover Expand" and "Catalog Hover Toggle" (which are suboptions of "JSON Index".)
