### ISSUE TITLE
Yandex Reverse Image Search 400 Error

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2330]
Reverse image searching with Yandex now yields a 400 Bad Request error. I figured out the problem was that they updated their url so that it's always without the www now. It was a simple fix of just removing the "www." from the Yandex option under the sauce menu, but I just wanted to throw this out there in case anyone else was having this issue and maybe 4chanX could get an update that automatically updates Yandex's sauce url for those not in the know.

**Comment by ccd0** [comment]
also reported in #2338, merging here

**Comment by NaturalHarmonia** [comment]
I've also been getting this error.

**Comment by ccd0** [comment]
Update 4chan X, it should be fixed now.
