### ISSUE TITLE
Catalogue problems. 

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#2339]
Disabled Catalogue Hover Expand but now pictures posted by OPs don't expand unless I open the thread and hover the mouse over it. I've got Image Expansion and Image Hover in Catalogue on also by the way.

**Comment by jimmyrustles** [comment]
I've got Image Expansion on also by the way.

**Comment by ccd0** [comment]
What browser is this in? Did you make sure to reload the page after changing settings?

**Comment by jimmyrustles** [comment]
Oh shit, yeah it works now. 
My mistake, thanks heaps.
