### ISSUE TITLE
[Feature Request] When hovering over a quoted response, highlight the quoted number when there are multiple replies to other anons

### ISSUE THREAD

**Issue by ponboo** [ccd0/4chan-x#2348]
I don't think I worded it well in my title so here is a pic of what I mean.
![image](https://user-images.githubusercontent.com/49004905/60431791-86f66480-9bf8-11e9-854d-58a435a9bc0c.png)

**Comment by saxamaphone69** [comment]
Not on my computer, but if I remember correctly, `.forwardlink` is the class you’re looking for.
