### ISSUE TITLE
Filters in native catalog

### ISSUE THREAD

**Issue by Badum-Tiss** [ccd0/4chan-x#2351]
Any chance you could incorporate my script in your project?

https://pastebin.com/Mx8KSDyh

This is a much needed functionality for a chaotic and trollsome board like /pol/.

**Comment by ccd0** [comment]
Can't you already do this by putting adding all the meme flags to the filter under flags?

**Comment by blixnood** [comment]
Yes, and there's no reason to add some other function to do it.

**Comment by BondiBear** [comment]
Totally unnecessary. If flags trigger you this much, the stay off certain boards.

**Comment by Badum-Tiss** [comment]
@ccd0 ?

**Comment by blixnood** [comment]
So that's completely different. This is new functionality and it would be useful, yes.

**Comment by ccd0** [comment]
Flag filters already work in the 4chan X catalog. Adding flag filters to the native catalog would be possible but might slow things down because you'd have to load the catalog info twice, reducing the advantage of using the native catalog in the first place.

**Comment by Badum-Tiss** [comment]
@ccd0 Nonetheless, it would be an option for people that would prefer to get rid of spam memeflag OPs.

Please try the script on your end and let me know what's missing.

**Comment by ccd0** [comment]
Just looking at the script, the main issues I can see are:

- loads the JSON of every thread when it could just load catalog.json
- no way to look at what threads you've hidden as exists for other filters (but it might be worthwhile even without this)

If we added a feature to do extra filters in the native catalog, it would probably be worth applying all the filters the user has set up. Doing it that way would also alleviate the second issue I mentioned above because people could check what was hidden if they wanted with stubs in the index or via the 4chan X catalog.

**Comment by ccd0** [comment]
vichan sites similarly have native catalogs that don't show flags but do have the information in catalog.json. Might be worthwhile there too, especially because the 4chan X catalog isn't working on those sites yet.

**Comment by Badum-Tiss** [comment]
@ccd0 catalog.json doesn't have the flag information thus it would be impossible to filter particular threads based on flag information.

**Comment by ccd0** [comment]
![2019-07-18-101748_656x770_scrot](https://user-images.githubusercontent.com/5894749/61477958-5e36d480-a945-11e9-818f-fd4d3a3b86d0.png)
It's right here. Flag filters wouldn't work in the 4chan X catalog if it wasn't there.

**Comment by Badum-Tiss** [comment]
@ccd0 I see. Since I was specifically looking for a flag tag, I've must've missed this information.

These are all the `country_name` values associated with flags in the troll folder:

```javascript
const memeflags = ["Anarcho-Capitalist", "Anarchist", "Black Nationalist", "Confederate", "Communist", "Catalonia", "Democrat", "European", "Fascist", "Gadsden", "Gay", "Jihadi", "Kekistani", "Muslim", "National Bolshevik", "Nazi", "Hippie", "Pirate", "Republican", "Templar", "Tree Hugger", "United Nations", "White Supremacist", "LGBT", "Black Lives Matter", "Commie", "DEUS VULT"];
```

**Comment by ccd0** [comment]
Added an option to the beta to apply 4chan X filters to the native catalog by loading catalog.json.

**Comment by Badum-Tiss** [comment]
Hey @ccd0, I modified the script. https://pastebin.com/GXMRsmpV

Also, I have a question about this section of my script:

```js
  while(thread_nodes.length < 150) {
    await sleep(500);
    thread_nodes = [...document.querySelectorAll("div.thread")];
  }
```

As you can see, the script is shooting in the dark to find the right time to execute the function after a page load, since native catalog relies on AJAX to fill up the page. Is there a better way to do this with surety of knowing that everything has loaded in the catalog and thus to finally execute the function at that time?

**Comment by ccd0** [comment]
You can use a MutationObserver to listen for threads being inserted into the catalog.

**Comment by nick-s-b** [comment]
@ccd0 , is there a way to block all the posts with memeflags? I see the `const memeflags` above but I'm not sure if this is available as a variable in `4chan-x`.
I currently block all the memeflags with ` /^Catalonia$/i;` etc for all flags. Is there a better way? Thanks!

**Comment by ccd0** [comment]
Nothing that's implemented in 4chan X yet.

**Comment by gogvale** [comment]
> @ccd0 , is there a way to block all the posts with memeflags? I see the `const memeflags` above but I'm not sure if this is available as a variable in `4chan-x`.
> I currently block all the memeflags with ` /^Catalonia$/i;` etc for all flags. Is there a better way? Thanks!
```js
console.log(memeflags.map(e=>`/${e}/`).join("\n"))
```

Or, the compiled list:
```
/Anarcho-Capitalist/
/Anarchist/
/Black Nationalist/
/Confederate/
/Communist/
/Catalonia/
/Democrat/
/European/
/Fascist/
/Gadsden/
/Gay/
/Jihadi/
/Israel/
/Kekistani/
/Muslim/
/National Bolshevik/
/Nazi/
/Hippie/
/Pirate/
/Republican/
/Templar/
/Tree Hugger/
/United Nations/
/White Supremacist/
/LGBT/
/Black Lives Matter/
/Commie/
/DEUS VULT/
```
