### ISSUE TITLE
is Autoupdate broken?

### ISSUE THREAD

**Issue by BondiBear** [ccd0/4chan-x#2358]
I've noticed that autoupdates are no longer working. I'm still stuck on 1.14.8.0, although you released 2 new updates.

I've had to force-install 1.14.9.1 - it won't do it through an update check.

**Comment by ccd0** [comment]
1.14.8.0 is the current stable version, 1.14.9.1 is only on the beta channel.

**Comment by BondiBear** [comment]
oh ok.
