### ISSUE TITLE
"Filter" crashed on node Post No.21175557 (adv).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2366]
Submitter: Louise
Email: EdenFinite@hotmail.com
I haven't done anything except for going to the /adv/ board and posting. I have linkify urls set to on and replied with a username. Anything beyond that, I have no idea.

Script: 4chan X ccd0 v1.14.10.3 userscript
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
URL: https://boards.4channel.org/adv/thread/21175553

TypeError: link.href is undefined
postDataFromLink@user-script:4chan-X/4chan%20X:10697:9
allQuotelinksLinkingTo/<@user-script:4chan-X/4chan%20X:10737:20
allQuotelinksLinkingTo@user-script:4chan-X/4chan%20X:10735:25
hide@user-script:4chan-X/4chan%20X:10109:17
apply/<@user-script:4chan-X/4chan%20X:10222:28
userScript/</SimpleDict</SimpleDict</SimpleDict.prototype.forEach@user-script:4chan-X/4chan%20X:7980:9
apply@user-script:4chan-X/4chan%20X:10220:22
hide@user-script:4chan-X/4chan%20X:10106:19
node@user-script:4chan-X/4chan%20X:9577:22
userScript/</Callbacks</Callbacks</Callbacks.prototype.execute@user-script:4chan-X/4chan%20X:6350:17
fn@user-script:4chan-X/4chan%20X:27957:13
softTask@user-script:4chan-X/4chan%20X:27961:16
callbackNodesDB@user-script:4chan-X/4chan%20X:27972:14
initThread@user-script:4chan-X/4chan%20X:27745:21
initReady@user-script:4chan-X/4chan%20X:27717:21
execTask@user-script:4chan-X/4chan%20X:5646:19

`<div class="postContainer replyContainer" id="pc21175557" data-full-i-d="adv.21175557"><div class="sideArrows" id="sa21175557">&gt;&gt;</div><div id="p21175557" class="post reply"><div class="postInfoM mobile" id="pim21175557"> <span class="nameBlock"><span class="name">Nero</span><br></span><span class="dateTime postNum" data-utc="1564178628">07/26/19(Fri)18:03:48 <a href="#p21175557" title="Link to this post">No.</a><a href="javascript:quote('21175557');" title="Reply to this post">21175557</a></span></div><div class="postInfo desktop" id="pi21175557"><input type="checkbox" name="21175557" value="delete"> <span class="nameBlock"><span class="name">Nero</span> </span> <span class="dateTime" data-utc="1564178628">07/26/19(Fri)18:03:48</span> <span class="postNum desktop"><a href="#p21175557" title="Link to this post">No.</a><a href="javascript:quote('21175557');" title="Reply to this post">21175557</a></span><a href="#" class="postMenuBtn" title="Post menu" data-cmd="post-menu">▶</a><div id="bl_21175557" class="backlink"><span><a href="#p21175563" class="quotelink">&gt;&gt;21175563</a> </span></div></div><blockquote class="postMessage" id="m21175557"><a href="#p21175553" class="quotelink">&gt;&gt;21175553 (OP)</a><br>I have none now.</blockquote></div></div>`

**Comment by saxamaphone69** [comment]
Potentially something blocking /adv/ links, in addition to (what appears to be) the native extension running and interfering.
