### ISSUE TITLE
2captcha API not working

### ISSUE THREAD

**Issue by bobmcdouble3** [ccd0/4chan-x#2375]
I've seen absolutely nothing about this, besides for the option. I put in my API key, and 2captcha.com. No options pop up, and the captcha is not being solved. 

Was this something implemented a while out, that you don't care to maintain? Or have I done something wrong?

**Comment by ccd0** [comment]
For the domain put in exactly
`https://2captcha.com`

You may have to wait up to a minute after pressing submit for it to work. In the future I might add an option that requests the captcha when you start typing.

>Was this something implemented a while out, that you don't care to maintain?

Opposite, it's fairly new and will probably have some issues to work out and bad UI to fix.

**Comment by bobmcdouble3** [comment]
Ah. Thanks. I was half way into making a script to do it automatically. Haha

**Comment by bobmcdouble3** [comment]
@ccd0 Uhh. I just checked out the code. I'm not really a JS guy, but it appears like the feature is hard coded to /v/ on 4channel.org.

`    url = "#{Conf['captchaServiceDomain']}/in.php?key=#{encodeURIComponent key}&method=userrecaptcha&googlekey=<%= meta.recaptchaKey %>&pageurl=https://boards.4channel.org/v/"
`

**Comment by ccd0** [comment]
It just needs something to send as the referrer; the captchas you get from that will work on any board. I picked /v/ because it's the fastest worksafe board. I wouldn't want to send the actual URL people are visiting unless it was needed.

**Comment by bobmcdouble3** [comment]
Ah, I understand. I assumed it was required. Sorry for the unnecessary pull req

**Comment by bobmcdouble3** [comment]
By the way, is the chrome extension not updated? The 2cap feature simply doesn't work on my end

**Comment by ccd0** [comment]
Can you give more detail? What happens when you try to submit a post?

**Comment by bobmcdouble3** [comment]
Captcha failed to connect

**Comment by ccd0** [comment]
Is that the exact error message? If not, can you copy the exact error message?

**Comment by bobmcdouble3** [comment]
The shit is using my balance, but doesn't actually do anything. I'll get you the exact msg in a min

**Comment by ccd0** [comment]
I think it might be a permissions issue in the Chrome extension. Try clicking the link button, then clicking "Allow." That might make it work.

**Comment by ccd0** [comment]
![bbb89753-bfe8-4b91-a1e8-d66718c54243](https://user-images.githubusercontent.com/5894749/62183709-184c1a00-b310-11e9-95e4-f1ed5d47b9c8.png)
By "link button" I mean this button in the Quick Reply.

**Comment by ccd0** [comment]
![2019-07-30-212259_462x216_scrot](https://user-images.githubusercontent.com/5894749/62183757-429dd780-b310-11e9-877a-83cc5e5e9390.png)
Which will bring up this popup.

**Comment by ccd0** [comment]
Does the workaround work? Soon I'll fix this to have submitting the form trigger an appropriate permissions request (and if possible only for the site you need to connect to).

**Comment by bobmcdouble3** [comment]
I'll test it out. 1 min

**Comment by ccd0** [comment]
Thanks for reporting. This should be fixed now.
