### ISSUE TITLE
1.14.11.1 broke custom css

### ISSUE THREAD

**Issue by fgsfdss** [ccd0/4chan-x#2386]
A couple years ago I added this and a few more similar lines in custom css:
```
.tomorrow.highlight-own:root .yourPost > .reply {
  border-left: 3px solid rgba(10,11,12,0.7);
}
```
With today's auto-update, the highlights have reset to their defaults. I saw that the documentation for styling was updated recently, but as it's been a very long time since I made these changes I couldn't figure out how to get them to work again.
What changed in the syntax for these lines to stop working after many years?

**Comment by ccd0** [comment]
An `!important` was added to override one in 4chan's CSS.
You'll need to add an `!important` as well:
```
.tomorrow.highlight-own:root .yourPost > .reply {
  border-left: 3px solid rgba(10,11,12,0.7) !important;
}
```

**Comment by fgsfdss** [comment]
Solved, thanks.
