### ISSUE TITLE
Support catalog link search

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#239]
Example:
.>>>/vg/vita, which becomes https://boards.4chan.org/vg/catalog#s=vita

Also, there is rule linking, like >>>/v/rules/1 (>>>/global/rules/1 is also a thing). http://puu.sh/dwae4/93cb5a0830.png Hover support when?

Sorry if it's a duplicate request, I'm tired.

**Comment by ccd0** [comment]
This feature has been added, should be working in v1.9.19.0 forward.

**Comment by unknown--** [comment]
Searches still take me to the native catalog rather than 4chan X's.
For example, I have the following linked in the Custom Board Navigation:
`external-text:"/gtag/","http://boards.4chan.org/vg/catalog#s=gtag"`
or just using this URL:
`http://boards.4chan.org/vg/gtag`

**Comment by ccd0** [comment]
http://boards.4chan.org/vg/#s=gtag
will search the 4chan X index.

I haven't put in a way to specify the search string and catalog mode at the same time, but that's on the to-do list.

**Comment by ccd0** [comment]
>I haven't put in a way to specify the search string and catalog mode at the same time, but that's on the to-do list.

Once it's released, 784ba8e39dbf96cc4cee8aab61c75fb5b362f8a4 will allow choosing the index mode while specifying a search string via
http://boards.4chan.org/vg/#catalog/s=gtag

**Comment by ccd0** [comment]
I think this is done. Moving rule links to a new issue: #1096
