### ISSUE TITLE
saucenao bug

### ISSUE THREAD

**Issue by darkred3** [ccd0/4chan-x#2392]
Using saucenao will result in a link like this: https://sys.4chan.org/a/thread/saucenao.com/search.php?url=https%3A%2F%2Fi.4cdn.org%2Fa%2F1565183924029.png
The "https://sys.4chan.org/a/thread/" part is unnecessary and results in an error message "File not found. " being given.

**Comment by ccd0** [comment]
The suggested line in Sauce settings is

```//saucenao.com/search.php?url=%IMG```

Make sure what you're using matches that, particularly the two /s at the beginning (you may have accidentally deleted one or both of them).

**Comment by darkred3** [comment]
Indeed, it seems like I deleted both. Thank you.
