### ISSUE TITLE
opening a picture or webm moves posts to the left on hover

### ISSUE THREAD

**Issue by chrome68issues** [ccd0/4chan-x#2397]
So, opening/clicking on a picture or a webm moves all the posts you hover above it to the left, below the margin.

When you close the picture or the webm and then hover again over those same posts they move to the right where they are supposed to be.

I've no idea what's causing this or why. 

Here's a video demonstrating the issue. It's small but annoying

https://streamable.com/7pntu

Using the latest version of 4chan X and using the tampermonkey script. Happening on Edgemium dev channel (Chrome 77)

edit: Upon disabling the oneechan and using a pure installation of chrome beta, the issue persists although in a bit different way

https://streamable.com/pe7iw

Some posts are moved (usually the first two to the left), and when you open a webm, that posts moves to the left and never goes back until you just go near the - (hide sign, don't need to click it). Sometimes the post you opened goes left, sometimes the one below goes left.

On Chome 76 with 4chan X 1.14.10.4 this does not happen. So it will become a future issue when Chrome 77 becomes stable, it appears that Chrome 77 is causing the issue. 

This issue further is caused by Chrome further switching to LayoutNG in Chrome 77.  Disabling it via chrome flags fixes the issue.

**Comment by ccd0** [comment]
Not seeing this as of 77.0.3865.35. Perhaps fixed on Chrome's end?

**Comment by ccd0** [comment]
>Not seeing this

Never mind, had to enable the LayoutNG flag manually to reproduce.

**Comment by ccd0** [comment]
Probably an issue on Chrome's end, but found a quick workaround.

**Comment by ccd0** [comment]
Should be fixed now. Let me know if it isn't.
