### ISSUE TITLE
"Relative post date" unreliable on kissu.moe

### ISSUE THREAD

**Issue by lc-guy** [ccd0/4chan-x#2420]
Feature is enabled, yet rarely works. Hovering over the date shows the relative time even though that sub-option isn't enabled. Notably, refreshing breaks it on the rare occasion it's working.

Latest Firefox on Windows and Linux. 4chanX v1.14.13.0

**Comment by ccd0** [comment]
Confirmed, thanks for reporting. Will look into it.

**Comment by ccd0** [comment]
Same issue with Time Formatting. Looks like a race condition between 4chan X's code and the native code.
Going to have to think about how to fix this, but in the meantime, a good workaround is to enable "Show relative time" in the native options (upper right corner) also.
