### ISSUE TITLE
How do I enable the "Captcha Solving Service"

### ISSUE THREAD

**Issue by Spangonagornomb** [ccd0/4chan-x#2430]
Hey there, first thank you for keeping this fork active, I was wondering how do you enable the "Captcha Solving Service"

I seen the changes you added to the fork and I was wondering how do you enable it

**Comment by saxamaphone69** [comment]
Refer to [this section](https://github.com/ccd0/4chan-x/wiki/Captcha-FAQ#-what-alternatives-are-available-if-i-dont-want-to-or-cant-solve-the-captcha-or-buy-a-pass) of the Wiki.

Go to `Advanced > Captcha Solving Service` in the settings to set things up.
