### ISSUE TITLE
Failure to download images via Save Link As

### ISSUE THREAD

**Issue by Gigabeef** [ccd0/4chan-x#2442]
Started having this issue a few days ago. Right-clicking on an image or its filename link then selecting Save Link As gives me a download error before even getting to the filename dialog. Opening the link then saving the image from there works fine though.

**Comment by ccd0** [comment]
I'm not seeing this myself, but it seems likely to be an issue on 4chan's end. You might try seeing if it helps to change `Advanced > Override 4chan Image Host` from i.4cdn.org to is2.4chan.org

**Comment by Gigabeef** [comment]
I see. I tried your workaround, it didn't work, still getting the error.

**Comment by ccd0** [comment]
Other things you can check are whether you blocking / forging referrers, whether it happens with other extensions disabled / in a clean profile, and whether it happens with 4chan X disabled.

**Comment by Gigabeef** [comment]
Thanks for the suggestions, it was uMatrix. hiro must have been mucking with how images load. I set "other" for i.4cdn.org to green in uMatrix and it's working again.

Thanks again for the help, it wasn't 4chan X causing the issue after all.
