### ISSUE TITLE
4chan-x only works on blue boards (domain 4channel.org)

### ISSUE THREAD

**Issue by dejavecue** [ccd0/4chan-x#2444]
Is this behaviour intended? The script includes the 4chan.org domain, but it simply doesn't work.

Using Firefox (latest) with ViolentMonkey.
Have reinstalled the script multiple times from github, to same effect.

**Comment by saxamaphone69** [comment]
Have you tried disabling all other extensions? My first thought is that perhaps an ad block filter is blocking JS on the 4chan domain.

**Comment by amantereale** [comment]
Exact opposite for me, also on Firefox. Works on /ic/ (https://boards.4chan.org/ic/), but not on /co/ (https://boards.4channel.org/co/).

I have tried disabling Privacy Badger, Decentraleyes _and_ uBlock Origin; still having this problem.

![image](https://user-images.githubusercontent.com/26056582/65492538-66fdd680-deb1-11e9-96c0-b87312428aa8.png)

![image](https://user-images.githubusercontent.com/26056582/65492595-7a10a680-deb1-11e9-9eec-bf19fa1c0990.png)

No errors in console.

**Comment by dejavecue** [comment]
It was apparently a bug in µBlock Origin - all was set to "allowed", but on disabling the extension, it works. I uninstalled it, reinstalled it fresh, and now it works again.
