### ISSUE TITLE
Youtube API key expired

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2479]
Title. Embedded Youtube URLs just return 'Forbidden or Private'. Someone in /sqt/ said this means 4chan X's Youtube API key expired, or something. I assume you know what that means better than I do.

https://s1.desu-usergeneratedcontent.xyz/g/image/1573/71/1573714209267.jpg

**Comment by ionenwks** [comment]
I've started seeing titles again instead of the 'Forbidden or Private' I had for a while, so I guess it's fixed?
