### ISSUE TITLE
Tabbing (captcha and upload)

### ISSUE THREAD

**Issue by fgsfdss** [ccd0/4chan-x#250]
Suggest changing the index order so tabbing doesn't focus on the captcha window first and goes straight for the checkbox (text field to captcha requires two tabs now).

Also, tabbing (once) after completing the captcha to upload a file would be great. You can tab to it before completing the captcha with five tabs, but that's not very efficient, and even when you reach it you get an error sound when you press enter or space because it treats it as a pop-up I assume. 
Mayhem's fork did this fine, you could check that.

Basically what I suggest is:
type post > tab > enter (captcha) > tab > enter (upload image) > tab > enter (post)

Another minor thing that really isn't worth its own topic, consider making post highlighting and the unread line not red by default, because it's awfully hideous. I use these for Tomorrow:
```
#unread-line{
  border-color: #282A2E;
}

:root.highlight-own .yourPost > .reply {
  border-left: 3px solid rgba(10,10,10,0.7);
}

:root.highlight-you .quotesYou > .reply {
  border-left: 3px solid rgba(129,162,190,0.7);
}
```

I can't find the highlighting around threads in the catalog though, I would change that to the blue as well.

**Comment by ccd0** [comment]
> Another minor thing that really isn't worth its own topic

For future reference, even if something is a small issue, it's better to put it in its own topic.  Otherwise it gets lost easily.

Anyway, I think most of this stuff should be taken care of now except the part about tabbing to the file.  Probably the best way to handle that would be to add a keybind to open the file input field.

> even when you reach it you get an error sound when you press enter or space because it treats it as a pop-up I assume.

This isn't happening for me.  If it's still happening for you, can you check whether it's specific to certain browsers / settings / add-on combinations you're using?

**Comment by fgsfdss** [comment]
Still happening, yes. I'm using FF35, with a bunch of other addons yes, though none that should interfere. Greasemonkey is up-to-date, Adblock isn't a culprit, I don't use noscript or the likes, ...
I don't even have Chrome installed. Maybe it'd work with that but that's kind of a hassle, and I wouldn't ever use Chrome anyway.
Does it work on Firefox for you? Because then it's clearly on my end.

**Comment by ccd0** [comment]
On further investigation, it seems I had added boards.4chan.org as an exception to my pop-up blocking for some reason.  After removing the exception, I'm seeing the same issue.

**Comment by ccd0** [comment]
Probably the best way to handle this pop-up issue would be for me switch out the file picker interface with the one from Mayhem/ihavenoface, as you suggested.  This was already planned (for #288) but this makes it a little more urgent.  As a temporary workaround, you can allow popups on boards.4chan.org.

Unfortunately the Firefox popup issue gets in the way of the "keybind to open the file picker" idea.  Although I suppose I could add a little "(requires allowing popups in Firefox)" note to the keybind description.

**Comment by ccd0** [comment]
Enter on the file selector button should work as of v1.10.3.0 (currently the beta version).

**Comment by fgsfdss** [comment]
Can confirm, it works now. 
Do suggest changing the tab index from the files button directly to submit, rather than going over rename, spoiler and remove file first.
Maybe having to shift-tab to files after captcha is a little inconvenient, but going to files rather than submit after captcha by default is probably not better.

**Comment by ccd0** [comment]
> Do suggest changing the tab index from the files button directly to submit (after file selection), rather than going over rename, spoiler and remove file first.

Pressing enter from the filename field should submit the post.  I'm not sure I want to make the spoiler and remove file buttons keyboard-inaccessible.  Although we could replace them with keybinds.

**Comment by fgsfdss** [comment]
You could still have them after submit (wouldn't make much sense visually though). Would have to shift-tab back to submit, but they aren't used all that often compared to just selecting an image and submitting the post.

**Comment by ccd0** [comment]
> You could still have them after submit (wouldn't make much sense visually though).

I considered that, but I don't think I want to do that.
