### ISSUE TITLE
Force noscript captcha stopped working

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2501]
Submitter: Brazen
If I have the "force noscript captcha" option enabled then I get this message: 
"Could not connect to the reCAPTCHA service.
Please check your internet connection and reload to get a reCAPTCHA challenge."
If I disable it then it works with the normal captcha. It was working fine until recently but then it suddenly started giving me this error message.

**Comment by Confrade** [comment]
Having the same issue atm.
