### ISSUE TITLE
Youtube link Titles not working

### ISSUE THREAD

**Issue by Nusharik** [ccd0/4chan-x#2505]
The link titles on youtube are not working, It's not a "Forbidden or Private" message, it simply does not show any text, just the link. I'm using Tampermonkey and my version is up to date, as well as my 4chanx and firefox versions.  My console shows no errors related to it. 
![link title](https://user-images.githubusercontent.com/21247411/70877144-50d05580-1f8a-11ea-96ac-2972645ff6e6.png)

**Comment by Nusharik** [comment]
The problem also seems to replicate on chrome.

**Comment by mrtbonex** [comment]
Not working on chrome for me either. I think hiroshimoot fucked this up along with the captcha thing.

**Comment by DimensioX1** [comment]
same problem here.

**Comment by Janaue** [comment]
same

**Comment by BondiBear** [comment]
sometimes works, sometimes doesn't

**Comment by phasetri** [comment]
The problem is that by default, 4chan x uses the same youtube API key to fetch the titles. Frequently, the quota gets exceeded. You can get a new API key by going to 4chan x Options > Advanced > Youtube API Key

**Comment by BondiBear** [comment]
now doesn't even show titles occasionally any more, it's completely broken.

**Comment by ccd0** [comment]
merging into #2327
