### ISSUE TITLE
Force Noscript Captcha

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2506]
Using 4chan X (1.14.14.5) with Tampermonkey 4.5, Adblock 4.0.2, AdblockPlus 3.7 and uBlock Origin 1.23.0 in Chrome
Turning "Force Noscript Captha" on results in "Could not connect to the reCAPTCHA service.

Please check your internet connection and reload to get a reCAPTCHA challenge."

Captcha works if I disable this option and reload page

**Comment by valued-customer** [comment]
I have the identical problem, except that there is no captcha at all if I don't force noscript captcha.  I can no longer post at all on 4chan, with or without 4chanx.

**Comment by ccd0** [comment]
merged into #2500
