### ISSUE TITLE
please help me! 4chan-x captcha stopped working in firefox 38 esr, 45, 52, 60, 68, latest esr, can't get 4chan-x to work in firefox 72 latest. please help me! 

### ISSUE THREAD

**Issue by anontests** [ccd0/4chan-x#2508]
![a](https://www.dropbox.com/s/xjidwx4lw1qxb8i/please%20help%20me%21.png?raw=1)

![a](https://www.dropbox.com/s/3t8s3xlvre0wt9r/PLEASE%20HELP%20ME%21%21%20CAPTCHA%20STOPPED%20WORKING%20IN%20FIREFOX%2038%20ESR%2C%20THEN%20DOESN%27T%20WORK%20IN%2045%2C%2052%2C%2060%2C%2068%20LATEST%20ESR%21%21%20CAN%27T%20INSTALL%20USER-SCRIPTS%20IN%20FIREFOX%2072%20LATEST%21%21%20PLEASE%20HELP%20ME%21%21.PNG?raw=1)

![a](https://www.dropbox.com/s/8p9n467ii782mdh/20191217161803%20127928%20_g_%20-%20Technology%20-%204chan.png?raw=1)

![a](https://www.dropbox.com/s/beglsrsum1nls7u/20191217170928%20127942%20_g_%20-%20Technology%20-%204chan.png?raw=1)

![a](https://www.dropbox.com/s/6yeteh2vygczacz/20191217184244%20127944%20_g_%20-%20Technology%20-%204chan.png?raw=1)

![a](https://www.dropbox.com/s/izbsa4agis3vejf/20191217223458%20127945%20_g_%20-%20Technology%20-%204chan.png?raw=1)

![a](https://www.dropbox.com/s/bf6g5jayuth0l95/panic.gif%201497811942620.gif?raw=1)

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

![a](https://www.dropbox.com/s/xjidwx4lw1qxb8i/please%20help%20me%21.png?raw=1)

please help me! 4chan-x captcha stopped working in firefox 38 esr, 45, 52, 60, 68, latest esr, can't get 4chan-x to work in firefox 72 latest. please help me! 

i've been hanging onto firefox 1, 2, 3, 4, 10 esr, 17 esr, 18, 24 esr, 28 for years. for a number of reasons. hanging onto firefox 38 esr portable as a devoted image-board web-browser without opening links, and stuff. the captcha said something like "upgrade toa  supported browser". so i do 45; it can't connect. so i try 52 esr, 60 esr, 68 esr, 72 latest; all can't connect. 

i was sort of hoping to have a technology discussion about it on the image-boards but i only got berated and my thread deleted; while infinite /reddit/ threads are up. anyway. 

so i'm sort of completely stuck at this point and not able to do anything with 4chan-x at all; since i can't post with 4chan-x. 

please help me! 

also i can't get 4chan-x to work with firefox 72 latest because i download greasemonkey, then i can't seem to install the script. i just gives me plain-text. but it works in 68 esr. i don't know what to do. so. 

also. i'd appreciate it if the issue was left up until i confirm it's fixed. 

for me it's fixed if i can get any firefox portable with 4chan-x working, 2nd plan use chromium portable, 3rd plan use chrome portable, 4th plan use some sort of portable web-browser, 5th plan use firefox non-portable, 6th plan chromium non-portable, 7th plan chrome non-portable, 8th plan any web-browser. 9th plan anything. 10th plan panic. and. done. 

i want to confirm it's fixed because i don't like the idea of having my issue closed if the issue isn't solved. or "issue solved and locked and don't talk about it". you know. also i don't like keeping things up for a long time anyway. if i could -- i would just keep threads up as long as i want and just delete them when i'm done with them. so i'll keep this up until the issue is solved, then lock this myself, or request it to be locked if i have to. but if it's like 12 months have passed and it's obviously fixed and i'm not coming back then or something then it can be locked. but whatever you wanna do is fine ... 

also thank you to Anonymous, Anon, aeosynth, Mayhem, ihavenoface, Zixaphir, Seaweed, and Spittie; and ccd0. i really do appreciate you. yoully help me out a lot. thank you. 
 really help me out a lot. thank you. 

also if it's not obvious my goal is to get 4chan-x captcha working so i can post with anything; including latest firefox esr, latest firefox, even latest chromium; but having it work again with esr 38, or 45, 52, 60, 68 would be nice, too. again it's a devoted portable web-browser that i only use for a few certain image-boards and don't open links and i have an anti-virus and am up to date otherwise so i'm probably all right. 

also if it's not obvious my goal is to get 4chan-x captcha working so i can post. 

too long; didn't read: 

i can't get 4chan-x captcha and thus posting to work in anything and i'd appreciate if i don't have my thread locked until i say it's fixed for me or lock it myself but whatever you wanna do is fine. thank you. 

please help me! 

![a](https://www.dropbox.com/s/xjidwx4lw1qxb8i/please%20help%20me%21.png?raw=1)

**Comment by charisti5676** [comment]
Jennies disabled the fallback on 4chan, ))((jewz)

turn on the noscript

**Comment by ccd0** [comment]
Better idea: Keep the browser you like and try one of the hundreds of other imageboards that don't require proprietary software to post.

**Comment by anontests** [comment]
i appreciate you. thank you. 


TOO LONG; DIDN'T READ: I FIXED IT. 

YOU CAN STOP READING HERE. 

THANK YOU. 

read on if you want details and context below. thank you. 


also i don't want this closed right now. i'll see where this goes. if it goes nowhere with no replies then that's fine too. then i'll close it. if i'm obviously apparently gone and it's been like 2~12 months then close it. but whatever you wanna do is fine. thank you. 


i was sort of hoping that there would be an update, everything would be fixed, and i wouldn't have to do anything ... 


i think it's because i have the following enabled. 

> [v] Force Noscript Captcha: Use the non-Javascript fallback captcha even if Javascript is enabled.

however. i'm still getting the following message in firefox 38. 

> Please upgrade to a supported browser to get a reCAPTCHA challenge.
>
> Why is this happening to me?

so this is still apparently the end of firefox 38 esr portable no-opening-links image-board only usage. 

but. it does work in firefox 45 esr. so. i'm going to use firefox 45 esr to do it. 

i wanted to upgrade firefox 38 esr to firefox 48 esr. but. upgrading 38 upgrades to 45.3.0. "check for updates" again and you only get an option to "update to 60.9.0esr". so it makes more sensed for me to just use the more up-to-date 45.8.0esr. it'd be nice if i could upgrade 38 toesr to 45.80esr. ah well whatever ... 

also. please do not remove that feature. maybe make a note of "not working as of x" or "not working anymore" or "not working anymore. but try anyway". i don't know. they may have their reasons. either that or have an "advanced" or "misc settings". i don't know. i just don't want it removed entirely. i don't know. 

i appreciate you. thank you. 


> Jennies disabled the fallback on 4chan, ))((jewz)
> 
> turn off the noscript and use chrome for easiser captchas

oh. i see. i wonder why. thank you for keeping me up to date. 

i disabled noscript and i still get this issue. do you think it's because of another add-on or something? i disabled everything else too. i don't get why it's not connecting? apparently? worked all the time before. 1 day it works. next day it doesn't. 

thank you. 


> Better idea: Keep the browser you like and try one of the hundreds of other imageboards that don't require proprietary software to post.

oh, ccd0... 

well. you helped firefox 38esr stay compatible with 4chan-x. apparently now firefox 45esr is "needed" or artificially "needed" to work with google captcha. 

i guess the solution wasn't obvious. 

i'm surprised to hear you say that after all this time. 

we hung on to 4chan a lot. didn't we. to the point where the creator left after messing it up constantly, and the new owner doesn't fix anything. 

we really are somethingawful at this point for sticking around with it for this long despite everything aren't we. 

to be honest. i get banned from image-boards quickly a lot. i'm actually less likely to be banned from 4chan because there's so much stuff on there all the time. it's more likely to blend it with the rest of the crap that gets posted on there. whereas if i post on an image-board, i stick out like a sore thumb, get little to no replies, and mods ban me. like everywhere else. every time. to be honest. 

as for 8 and master or cc or whatever it's calling itself nowadays. and whatever. i don't like how i can't delete posts and threads on those boars at any time. and i also don't even like how posts don't get deleted. you end up with a bunh of /general/ cancer threads that i always feel ruins the point of image boards. it just makes it like /reddit/ and everything else. to me image boards were always best when they were image boards. not some wannabe /reddit/ and be like every other website ripoff. 

so. i just feel really uncomfortable not having my threads and posts deleted at all and not being able to delete my own threads and posts. yeah there are archives -- and yeah there's a lot of trash that comes with archives -- spies, people pointing out you posted something similar before that's obvious public information and making it like they're a great detective and this is some sort of huge revolution or "exposed" trash. but. it doesn't get the same attention, replies, and they get deleted at some point. so. i would rather use 4 right now; in that context. 

also i don't want to have to make my own board on there. for a number of reasons. for example i remember hearing something like "if you're banning a lot or banning over 50% of the users on the board; then we'll ban you and you'll lose control of the board". well i guess it's unlikely i'd do that; to me right now. but maybe the situation would change and i'd be actually spammed, have actual trash, or even want to have a lot of "old" style threads that most wouldn't even be familiar with. so i'm worried about the what-if's and more forced acceptance anyway. i mean it's almost like me seeing good threads and posts being deleted and banned while trash posts are not deleted and banned and even apparently enjoyed and loved. so. i'd also have to maintain it, possibly promote everyone going to 8 and other boards, and would rather just stick to my small temporary threads on 4 right now. 

so i may agree with some image-boards; but it doesn't work in mechanics. 

otherwise my experience on 8 and master and the like has been rather surprisingly good. but. i can't use it. 

i'd like to consider myself sort of of a jolly, playful, fun person. even a laid back person. even just a person that exists in life. but i get so many to feels like all fighting with me and bans for no reason at all. and now i have to deal with more problems. feels like i have to choose between an ignorant bliss or continue to actually try to have stuff better. but i keep being forced to edge to something. and i keep edging to actually try to have stuff better. ... it'd be nice if things were like they were before and i wasn't forced to deal with all these problems. but. you know. that's not an option. apparently. .... 

ccd0. i'm surprised that i have more tolerance for 4 than you do at this point. you seemed to tolerate everything. not saying it's wrong. just. surprised. hope you're able to tolerate my tolerance. lel ... so. it's gotten to the point where i am tolerated more than 4. that's sad. so ... 

thank you for always helping me, tolerating me, putting in updates for me here and there, and even keeping stuff compatible with older stuff. even when i was apparently the only 1 asking for it; and others didn't seem to like it or actually fight against it. again. i'm sure there's lots of users out there that want it. but just don't want to deal with asking like this and all that. like 99%. so maybe we helped over 99% more than me. i don't know. anyway. we don't really talk. but. in that context. and as others treat you. you're a good friend. thank you. 

also. you don't have to reply to any of this. it's cool. i'm just putting it out there. i already know you get the message and listen and understand. 

i need to post on 4 right now. 

i'm actually planning and even working towards making a site and possibly an image-board. but i've had various problems. and sort of regret talking about it. so i try to avoid talking about it. i'd rather talk about it when it's done and i can show it. but. so many bad things like this happen. so. i talk about it. and i'm doing this. right now. 

please understand. 


i appreciate you. thank you.

**Comment by ethereal-derealization** [comment]
Was your problem ever fixed? I'd recommend uninstalling all versions of firefox you currently have and then grab the latest verson of firefox (72.0.2) from the official website.
https://www.mozilla.org/en-US/firefox/new/
After that I'd recommend not downloading  the add ons adp or ghostery and instead opt to use only ublock orgin. You only need one adblocker; it doesn't do you any good to use multiple as they do the same thing. Also ghostery is botnet. NoScript can be really annoying so I'd recommend not using that.
The only add ons I'd recommend would be Decentraleyes, HTTPS Everywhere, Privacy Badger, uBlock Orgin, and Violentmonkey for userscripts. They don't contradict each other and work great together.
Tell me how it goes friend
