### ISSUE TITLE
[FEATURE REQUEST] Add option to disable annoying santa stocking caps.

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [ccd0/4chan-x#2517]
I feel i need to elaborate, it's not me being Grinch, I can usually get all the relevant info from the image just as it is, but these oversized caps are covering large part of the image forcing me to expand almost every image that contains text which is otherwise unreadable (see pic. related).

![Untitled - Copy](https://user-images.githubusercontent.com/17363930/71534481-6c7b1a80-28ff-11ea-8872-4a6c195e5842.png)

**Comment by bakugo** [comment]
This is what the custom CSS field is there for.

`.party-hat { display: none; }`

**Comment by Vulgaris-Viridis** [comment]
Thanks @bakugo, much appreciated!
