### ISSUE TITLE
4chan X not actually working on 4chan, only 4channel

### ISSUE THREAD

**Issue by bugjuicer** [ccd0/4chan-x#2518]
After the update, 4chan X no longer works on 4chan, only 4channel. I don't know how this happened. There's not much else I can say. Toggling the native extension does nothing and pink boards have no 4chan X.

**Comment by Kotters** [comment]
4chanx isn't working on 4chan or 4channel anymore, for me.

**Comment by ethereal-derealization** [comment]
It works perfectly fine for me, try uninstalling and reinstalling 4chan-x

**Comment by bugjuicer** [comment]
> try uninstalling and reinstalling 4chan-x

That worked
