### ISSUE TITLE
Archive Error

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2522]
Submitter: Alex
Email: Alex24356@gmail.com
I get the error "Error fetching archive data from
https://mayhemydg.github.io/archives.json/archives.json
Connection Error" on every page. The github link goes to a 404 now.

**Comment by utsuroibanana** [comment]
I'm also having the same issue on Firefox v72.0b11. I've disabled all add-ons and userscripts except 4chan X and the issue still persists (obviously since the link goes to 404?).

**Comment by ccd0** [comment]
already fixed, update the script #2500
