### ISSUE TITLE
captcha loading never completes when script is active

### ISSUE THREAD

**Issue by LawRon** [ccd0/4chan-x#2531]
What it says on the tin.
The blue wheel keeps spinning with no puzzle or whatever to complete.
Captcha only begins working again upon disabling the script.

I've tried reinstalling the script. Didn't help.

**Comment by Zalwis** [comment]
I'm also experiencing this issue. Using Firefox 72.0.1 combined with the latest Greasemonkey if it matters. Captcha just continually spins and nothing else happens. Forced to disable script in order to post anything.

**Comment by frankspace** [comment]
Same problem here.  Latest Tampermonkey and Firefox 73.0.1.  I also use various addons like uBlock Origin, but the captcha was working fine until just recently and to the best of my knowledge I haven't changed anything.

**Comment by bakugo** [comment]
I was having this problem too and it puzzled me for a while but today I looked into it and finally realized that it was being caused by the "captcha language" option being broken. Clearing that option made the captcha work again for me.

Something changed with the captcha recently and 4chan X is trying to apply the language to an iframe that doesn't have any URL.

**Comment by Brawl345** [comment]
Clearing the "captcha language" option worked, thanks. <s>Time to shitpost again!</s>

**Comment by ccd0** [comment]
@bakugo
Can you show me the iframe in question? I haven't been able to reproduce this on my machine.

**Comment by bakugo** [comment]
@ccd0 It's this frame, right under the captcha. Normally it has no `src` but 4chan X thinks it's the captcha iframe and sets one if the language option is set.

![image](https://user-images.githubusercontent.com/6014513/79698162-e7858980-827e-11ea-9cbc-42116da0949d.png)

Tried this in Firefox with the same 4chan X settings and it does not happen (the language gets added to the correct iframe at the bottom of the page instead) so this may be a Chrome-only issue.

**Comment by Brawl345** [comment]
FYI I had this issue with Firefox, too. Mine was set to "de" and didn't work. Clearing it worked.

**Comment by ccd0** [comment]
It's probably Google pushing new code to some users but not to others; they do this a lot with Recaptcha. I still can't reproduce in any browser, but I'm pushing a change that should fix it based on the info I've got.

**Comment by bakugo** [comment]
The fix worked for me.
