### ISSUE TITLE
Save All Images

### ISSUE THREAD

**Issue by ethereal-derealization** [ccd0/4chan-x#2537]
Add an option/button to download all file formats in a thread. It's quite the  annoyance and unneeded hassle to press right click and save every image one by one when it could be implemented into 4chan-x. I'm suprised it hasn't been done yet. There has been a few similar requests but they are quite old. I know there are programs and extensions that already let you do this but they are complicated and confusing, it would be nice to have it in the script. Thank you

**Comment by ncaos** [comment]
-"Download All Images" extension. It badly needs to be forked and modified for all file types though.
-"ripme" program.

Sure, it would be nice to have the functionality of either in the extension but why add more stuff that can potentially break?

**Comment by Vulgaris-Viridis** [comment]
Not sure how the _4chan_ would look at that as most of the sites discourage bots and scrapers. It would be a nice addition but i wouldn't be surprised if it never gets implemented. 

In the mean time, there are simple scripts like this one that you can use, just download and install python, (check _'add to path'_ during installation) and run _Scrape.py_. It will prompt you for the link and automatically create _imgs_ folder and start downloading. 

This is as easy as it gets. Once again, not sure how 4ch staff looks at that, you might get banned if they think you're a bot.

_https://github.com/LewisDick/4chan-Image-Scraper_

**Comment by ethereal-derealization** [comment]
It's already been implemented in dashchan, clover, omnichan, mimi, etc for android, I don't see how it could be a problem. ccd0 already implemented "expand all images" so if you tried to mass download images/videoos with an add-on or program it doesn't just download the thumbnails but the whole thing. I don't think it would be much work besides a few lines of code. This feature has been asked for since 2015.

Thank you though, I'll try and look at the different scripts already available on github.

**Comment by ethereal-derealization** [comment]
I finally found something I was happy with
https://github.com/mhetralla/YChan

though these are also good
https://github.com/Exceen/4chan-downloader
https://github.com/pboardman/4scanner

**Comment by JackJohnJoe** [comment]
I use Download Star.

**Comment by duanemoody** [comment]
Bookmarklet this: 
`javascript:let p=$$("a.download-button"), i=0, v=setInterval(() => {p[i++].click(); (i>p.length) && clearInterval(v);}, 1000);`
It's in a counter loop with 1 second `setInterval()` pauses because `forEach()`-type iterators are synchronous and 4chan will throttle more than 20-30 concurrent requests, dropping several in the process. 
I only fire `click()` because I'm still trying to figure out how to directly call `ImageCommon`'s download method.

**Comment by saxamaphone69** [comment]
https://web.dev/browser-fs-access/

Perhaps this could be useful in the future when it's better supported?

**Comment by saxamaphone69** [comment]
#1187

**Comment by rjy7wb** [comment]
have it download all the media in a thread and save it into a folder with the threads title as its name, the excuse that other extensions have isn't a good one, this should be the one-stop shop. 

hell tie it into the watcher for full integration.
