### ISSUE TITLE
[Question] Is it possible to use @import rule in 4chanX custom CSS?

### ISSUE THREAD

**Issue by leewdch** [ccd0/4chan-x#2545]
I was having an headache editing custom css in that small settings window so I thought I could just import css from a remote host and apply it but it looks like changes aren't imported at all. I checked the `<head></head>` and `@import` is indeed at the very top of the custom css `<style>` tag but it still doesn't get loaded at all. Am I misunderstanding the use of `@import` meaning I can only import css files from within the same server or maybe it has to do with how css is applied on demand via javascript?
For instance, the css is hosted on a public gitlab profile

**Comment by ccd0** [comment]
I tried

```@import url("https://files.catbox.moe/9r7sac.css");```

and it worked for me.

**Comment by leewdch** [comment]
Same here. For some reason it refuses to import if I use a raw link from gitlab.
I'm gonna test it some more with permalinks or something like that.
As long as it works with other links I know this isn't 4chanX's fault. Thanks

**Comment by leewdch** [comment]
For future reference, raw links from git are parsed as txt files. @import only accepts css files so you need to use GitHub Pages or GitLab Pages to host the file as an actual css file for @import to accept it
