### ISSUE TITLE
[enhancement] Please add a view option to allign threads to the center of the screen 

### ISSUE THREAD

**Issue by mikeloeven** [ccd0/4chan-x#2549]
Please add viewing optimizations for large widescreen monitors One of the main issues with the site is it was always designed for smaller square displays and on wider monitors everything gets smashed against the left side of the screen and does not properly scale in size. A centered scalable alignment for the threads would be optimal in this situation. If this feature exists I apologize but I was not able to find alignment in the FAQ's and am not good enough with code to tweak this myself

**Comment by madmadman** [comment]
This, come on. give it to us. Why is this addon such a downgrade compared to the built-in 4chan extension features?

**Comment by saxamaphone69** [comment]
Could always add `.board { max-width: 960px; margin auto; }` to Custom CSS.

**Comment by racofer** [comment]
If anyone still needs this, I have managed to achieve a good layout using Custom CSS with `.postContainer { max-width: 960px; margin-left: auto; margin-right: auto }:`
