### ISSUE TITLE
CSS fails to load with noscript 

### ISSUE THREAD

**Issue by Goldoche** [ccd0/4chan-x#2553]
This started happening one to two months ago. Once in a while, CSS won't load. As you can see in the screenshot, all scripts are allowed.

![4chanx css](https://user-images.githubusercontent.com/16695806/74801170-d7175980-52a3-11ea-8e79-57184f160d7a.png)

I'm not sure if it's an issue with noscript or 4chanX but I thought I'd report it here since it's a pretty popular browser add-on.

**Comment by F0kT** [comment]
Same problem here. Don't know what troubleshoot information is useful. I deleted the cookies, allowed all scripts, and yet I have to refresh a few times so the CSS loads.

**Comment by Goldoche** [comment]
it went away
