### ISSUE TITLE
Captcha Malfunction

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2570]
Submitter: Robert
captcha malfunctioned

**Comment by ccd0** [comment]
Captcha issues should be submitted to 4chan unless you've found them to be 4chan X specific.

**Comment by isfttr** [comment]
I have found that when I restore the default configuration, captcha resumes working as intended. I don't know what in my configuration has caused the error. I created a gist with the json file.

https://gist.github.com/isfttr/bd0c1d2deacb4aaced9c7475abe5fe8a

**Comment by ccd0** [comment]
Probably "Auto-load captcha". It could be related to #2531, so could you test again in v1.14.17.3 and see if it's fixed?

**Comment by isfttr** [comment]
How I got it working:
```
    "Auto-load captcha": false,
    "Post on Captcha Completion": false,
    "Captcha Fixes": true,
    "Force Noscript Captcha": false,
```

**Comment by ccd0** [comment]
Does your old config still not work as of v1.14.17.3 or later?

**Comment by isfttr** [comment]
It works fine now.

**Comment by ccd0** [comment]
Good to hear. I would recommend turning "Auto-load captcha" off anyway because the additional number of requests it makes for the captcha may adversely impact your Google score.
