### ISSUE TITLE
ID Filter seemingly broken

### ISSUE THREAD

**Issue by RaylaLe100** [ccd0/4chan-x#2573]
Hi  !
I use the following filter on /bant/ to filter out imptrash : `/undefined/;boards:bant;`
The problem is, somehow, only about half of the imptrash gets filtered. There are threads whose first post has no ID in my "hidden" category, but also threads with no ID in the catalog. I didn't manage to figure out any difference between filtered and not filtered threads, and it's what's bugging me.
Also another anon told me that with the exact same filter they had no problem, so I really don't know why this is happening.
version : 1.14.16.7

**Comment by ccd0** [comment]
Use this instead:
//;boards:bant;
