### ISSUE TITLE
Image saving issue

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2579]
Submitter: Karol W.
Greetings!

Really enjoy 4chanX, good job!

I have one minor issue though. I used to be able to save individual images from the Gallery using CTRL+S. Now it just saves the entire gallery as a website. Is there a way to save individual images without right-clicking on them? Preferably through keyboard. 

Thank you, and have a good day.

**Comment by saxamaphone69** [comment]
`Shift+j` is the current default Keybind I believe.
