### ISSUE TITLE
Image opens instead of simply expanding (when used together with Opensubtitles.org extension)

### ISSUE THREAD

**Issue by Tony3rd** [ccd0/4chan-x#258]
When I click a image to expand it, instead of expanding it, it opens.
using the chrome version 1.9.17.10

edit: Did some testing here, and apparently, this behaviour only happens when Opensubtitles.org extension (https://chrome.google.com/webstore/detail/opensubtitles-button/feeemcdfphbigikbeoedeppjeiheddim) is also active. 

I don't know if you guys can do anything about it... but here is a heads up any case someone else has to deal with the same thing.

**Comment by ccd0** [comment]
It might be helpful if, when the bug happens, you do Inspect Element on the thumbnail and post a screenshot or copy of the HTML in that area, like this:

![screenshot from 2014-12-31 20 03 22](https://cloud.githubusercontent.com/assets/5894749/5591647/a85c066e-9128-11e4-814d-6b16c5dc5b00.png)

Often conflicts like these are the result of other extensions modifying the HTML in a way that 4chan X can't parse anymore, and if I know what it's doing, I may be able to work around it.

Also, if there are any messages in the error console, particularly from "script.js", posting them would help too.

**Comment by ccd0** [comment]
This can also happen if you simply click an thumbnail in a large thread before 4chan X has had time to process the thread to that point.
