### ISSUE TITLE
Error : upload failed on one specific webm

### ISSUE THREAD

**Issue by Question2** [ccd0/4chan-x#2583]
When trying to upload a specific webm that I downloaded from : https://gelbooru.com/index.php?page=post&s=view&id=2783677&tags=fate/kaleid_liner_prisma_illya%20animated%20yuri , 4chanX keeps giving me this message. I have tried re-downloading the file to make sure its not corrupted, but it keeps giving me the message for this one specific webm. Other webms seem fine.

Whats going on?

**Comment by ccd0** [comment]
Can you upload it without 4chan X?

**Comment by Question2** [comment]
Nope, just says error : upload failed. Does it work for you?

**Comment by ccd0** [comment]
4chan has a lot of strange filters. I don't see anything wrong with the file, so you should be able to upload it without problems elsewhere.

**Comment by Question2** [comment]
@ccd0 : did you try uplaoding the file to see if it worked for you?

**Comment by saxamaphone69** [comment]
@Question2 FWIW when I tried it, I got `Error: Upload failed.` too. I'd say it's the file itself, if everything else works normally - in addition to the fact it doesn't upload with or without 4chan X enabled.
