### ISSUE TITLE
hCaptcha won't show with X enabled

### ISSUE THREAD

**Issue by fgsfds** [ccd0/4chan-x#2584]
With 4chan-X
![image](https://user-images.githubusercontent.com/4870330/79422501-6efc9f80-7fd6-11ea-8c00-00625775845d.png)

Without
![image](https://user-images.githubusercontent.com/4870330/79422521-77ed7100-7fd6-11ea-8446-55b584aa69af.png)

**Comment by saxamaphone69** [comment]
Interesting, I still get reCAPTCHA both on 4chan and 4channel.

**Comment by ccd0** [comment]
Thanks for the report, should be fixed in the latest version. Please let me know if it isn't.

@saxamaphone69
Not the captcha for posting, the captcha on Cloudflare's verification page.
