### ISSUE TITLE
Reloading media instead of using prefetched media

### ISSUE THREAD

**Issue by nilfoer** [ccd0/4chan-x#2601]
Greasemonkey 4.9
4chan-x 1.14.19.1
Firefox 76.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0)
Tested on https://boards.4channel.org/wsg/thread/3436778 and https://boards.4channel.org/wsg/thread/3460867

I don't know if this really is a problem with 4chan-x or e.g. Firefox.

Steps:
1. Visit 4chan thread
2. Turn on prefetch images and wait till everything is loaded
3. Hover over/Click thumbnail and you can see (in most cases) the new GET request in the browser's network tool (see below) instead of the browser using the cached prefetched image/webm. 
![2e](https://user-images.githubusercontent.com/60221153/82464377-4dec0a80-9abe-11ea-9e93-2c2190188e64.png)

**Comment by ccd0** [comment]
I've pushed a change that should improve things.
