### ISSUE TITLE
Remove Samachan.org -> Sushigirl.us redirect

### ISSUE THREAD

**Issue by seisatsu** [ccd0/4chan-x#2603]
Yuno (owner of Samachan.org) has posted on Sushichan and is offended by the redirect. They have responded by redirecting Samachan.org to 4chan.org/a/. I will see if I can get Yuno to talk to me about it. Until then, it is probably best to remove the Sushigirl link because they might at least undo the 4chan redirect and let users go back to seeing their parting message.

**Comment by ccd0** [comment]
It is done.
