### ISSUE TITLE
Reconsider Samachan/Sushichan Notification

### ISSUE THREAD

**Issue by seisatsu** [ccd0/4chan-x#2608]
So, no response from the Admin, and the 4chan redirect is still up. I think at this point it would be fair to implement the notification you mentioned earlier since they seem to have washed their hands of the whole thing, and it wouldn't be a message on their site. It's best if at least some of the users can reconnect.

**Comment by ccd0** [comment]
Rather than check watched threads and (You)s it will probably be easier to keep it simple and show the one-time notification for everyone with site configuration data from Samachan (which would mean they visited with 4chan X enabled at least once). Is that okay?

**Comment by seisatsu** [comment]
Yeah that's fine with me.

**Comment by ccd0** [comment]
Alright, I've added it.
