### ISSUE TITLE
"Force noscript captcha" doesn't work on report or /banned (edit: or original post form)

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#262]
I still get the new captcha when reporting posts or checking by ban status. Only works on quick reply.

**Comment by usernamestring** [comment]
I'm having the same problem. Reporting posts with food captcha is impossible unless I manually disable all 4chan scripts.
Can this be fixed?

**Comment by ccd0** [comment]
@usernamestring
Can you elaborate on your problem?  Although you'll get the food captchas in the report form at the moment (assuming you have Javascript enabled), they should work unless you're blocking something.
