### ISSUE TITLE
[code] tags not shown in 4chanX catalog

### ISSUE THREAD

**Issue by hotdogman** [ccd0/4chan-x#263]
![screenshot-6](https://cloud.githubusercontent.com/assets/4343306/5584936/f98d0dac-9061-11e4-87e4-5fe990ed1541.png)
![screenshot-7](https://cloud.githubusercontent.com/assets/4343306/5584937/f9902abe-9061-11e4-8d43-f2e4021dd5fc.png)
It doesn't work in the native catalog either, but then again, neither does greentext/quoting, which does work in the 4chanX catalog.

**Comment by ccd0** [comment]
The newest beta (v1.9.19.0) adds the background color, and the newlines are fixed.

**Comment by hotdogman** [comment]
Fixed in 1.9.19.0. Thanks.
