### ISSUE TITLE
Feature request : hide all posts in a thread that don't have an image (toggle)

### ISSUE THREAD

**Issue by JackJohnJoe** [ccd0/4chan-x#2641]
An option, like those in the top right, to hide all the posts within a thread that don't contain an image (just that, doesn't expand them). And clicking again acts as a toggle.
Maybe it can also be a permanent option in the preferences, although personally I'm not interested in that.

**Comment by saxamaphone69** [comment]
`Fappe Time` is what you're after.

**Comment by JackJohnJoe** [comment]
Alright, my bad.
