### ISSUE TITLE
"Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error"

### ISSUE THREAD

**Issue by Solaywri** [ccd0/4chan-x#2642]
I keep getting this error. The only extension I have is tampermonkey (I removed ublock origin to see if that would help but it didn't). It works on /lit/ but on /pol/ I get this error. I don't get the error on chrome either. I am on firefox.
![error](https://user-images.githubusercontent.com/67982592/86848580-41c30900-c07c-11ea-8532-da3e98d1671f.PNG)

**Comment by saxamaphone69** [comment]
Make sure 4chan X is updated, #2520.

**Comment by Solaywri** [comment]
It is updated. I reinstalled Firefox but I keep getting the issue.

**Comment by saxamaphone69** [comment]
So you're running 4chan X 1.14.20.0?

Then, go to the Settings > Advanced and update the archive list to `https://nstepien.github.io/archives.json/archives.json` instead.

**Comment by longestmt** [comment]
> So you're running 4chan X 1.14.20.0?
> 
> Then, go to the Settings > Advanced and update the archive list to `https://nstepien.github.io/archives.json/archives.json` instead.

I'm having the same issue as OP. Where should I look for `Settings>Advanced` I don't see it anywhere in Firefox settings or the 4chanX add-on section.

**Comment by saxamaphone69** [comment]
![image](https://user-images.githubusercontent.com/877480/105944535-9a5d0080-60b7-11eb-977a-030d90b9bc2e.png)

Should be the first thing you see.

Although, now the link is `https://4chenz.github.io/archives.json/archives.json`.

Make sure you don't have any blocking scripts like NoScript that may be blocking certain network requests.

**Comment by saxamaphone69** [comment]
Just keep 4chan X updated, and be mindful of other conflicts within extensions. Mayhem doesn't maintain any 4chan-related things anymore, so nobody to ask to update. The default was changed to 4chenz back in 2020.
