### ISSUE TITLE
"Mistyped captcha" forcing NoScript captcha

### ISSUE THREAD

**Issue by qorg11** [ccd0/4chan-x#2658]
4chan allowed noscript captcha, so i force it using the 4chan x option. When i paste the code it won't let me post:

![Get "Mistyped captcha or the captcha malfuncionated"](https://lainsafe.delegao.moe/files/qYHAnIyV.png)

I also tried using the original form feature. But it didn't work either.
![](https://lainsafe.delegao.moe/files/mhzRwdYM.png)

Also: I use uMatrix, so maybe this could be causing an issue. But i allowed literally everything but still not working

**Comment by qorg11** [comment]
disabled umatrix in the browser and it worked, not a 4chan x bug

**Comment by defkev** [comment]
For some odd reason you have to disable referrer spoofing in uMatrix on boards.4chan.org for Noscript Captcha to work:

`referrer-spoof: boards.4chan.org false`
