### ISSUE TITLE
Highlight CSS clarification

### ISSUE THREAD

**Issue by DuendeInexistente** [ccd0/4chan-x#2662]
The filters page says that one can pick a css style to use when highlighting posts.

There is, however, no example I can see of what the css can or should contain, and the inspect element tool isn't helping. How do I change the edge color? Can I set background/text properties in the css or just that color? I've tried to do that and it doesn't work.

Could an example be added to the filters' guide page?

**Comment by saxamaphone69** [comment]
>Highlight instead of hiding. You can specify a class name to use with a userstyle.
>For example: highlight; or highlight:wallpaper;.

It says you can specify the class name, nothing about CSS. It is assuming (rightfully so), that if you're knowledgeable enough to be using a userstyle, you would be aware of what happens and how to style custom classes.

By default, `highlight` puts a `.filter-highlight` on `.postContainer` (which you would see from inspecting an element). If you want "custom CSS", that is, the default filter is a different colour, you would change whatever 4chan X applies in the Custom CSS section of the settings, or override it within a userstyle.

If you want a customised highlight filter, `highlight:hello` for example, then in, again, the Custom CSS or your userstyle, you'd add `.hello { box-shadow: whatever; }` - which would be different to default highlighted filters.
