### ISSUE TITLE
auto-watch threads you're reply to

### ISSUE THREAD

**Issue by shagel** [ccd0/4chan-x#267]
hello ccd0 i am like your script its very best thank you for all but why did u remove this featuring?
i can not comprehend, please incorporate it again
many thanks

**Comment by ccd0** [comment]
It's not removed; go to the settings in the thread watcher menu and turn it on.  Along with Auto Watch Reply if you want it.

**Comment by shagel** [comment]
damn... i swear to my mom it used to be in the configuration menu thanks m8 keep up the good work
