### ISSUE TITLE
Images/webms not loading

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2670]
Submitter: trae warren
hello. im using 4chan and 4chan X on chrome and none of the images (both OP and other posters) images are not loading or showing the thumbnail and only the 4chan banners are showing up. whats the problem here? it opens when i click on it and it opens in a new tab

**Comment by an94baller** [comment]
I can replicate this issue, not sure what's causing it. Have tried to disable all add-ons and even tried a clean firefox portable.

**Comment by ccd0** [comment]
That looks like Werk Tyme (a feature to hide images) is turned on. Click the W in the header bar or press shift+W to turn it off.
