### ISSUE TITLE
regex.info abandoned?

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2673]
The site hasn't worked for quite a while now, any plans to replace it with another EXIF viewer?

**Comment by ParrotParrot** [comment]
Site underwent renovation and the resource was moved, multiple times
Currently at http://exif.regex.info/exif.cgi

**Comment by ccd0** [comment]
That's the URL used as the example in 4chan X right now. If anyone is having a problem with the regex info link, update the entry in your Sauce settings manually to

http://exif.regex.info/exif.cgi?imgurl=%URL
