### ISSUE TITLE
Convert days to months

### ISSUE THREAD

**Issue by hotdogman** [ccd0/4chan-x#268]
![screenshot-10](https://cloud.githubusercontent.com/assets/4343306/5594736/c7f3b3fe-921e-11e4-93db-5b4389b4aafa.png)
![screenshot-9](https://cloud.githubusercontent.com/assets/4343306/5594737/cae430ca-921e-11e4-922b-488308837421.png)
Shouldn't 340 days be converted to months?

**Comment by ccd0** [comment]
Newest beta (v1.9.19.0) should fix this.

**Comment by hotdogman** [comment]
Confirming fixed in 1.9.19.0. Thanks again.
