### ISSUE TITLE
Minor request regarding hide buttons etc

### ISSUE THREAD

**Issue by PixelEater** [ccd0/4chan-x#269]
Hello, I have a basic request I hope you'll consider. It's nothing major, just an aesthetics thing. I remember when Mayhem dug up those fancy web fonts to achieve the look of the new hide button and some other things. I noticed in this fork by comparison it's gotten a bit darker and perhaps the minus sign is smudgier somehow. Would you consider just reverting the color and size to what 4chan X 3.20.15 had? Further I wish for coordinating colors on non-worksafe boards again. I don't really understand the look of the blue buttons going on there.

One more thing I wish I could control is I want the original look of the board titles' font. I do sort of get the narrow-is-in look, but happen to like 4chan's default there.

Small details, but for me they would make this fork perfect. Definitely I noticed some appreciated new features when finally switching over again. I would be open to advice on how to modify these things myself. Either way, thanks for maintaining this.

**Comment by ccd0** [comment]
This would be easier if you could propose the CSS you'd like.
