### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by misakabestgirl** [ccd0/4chan-x#270]
http://puu.sh/e0VH5/36dbee480f.png 
just updated to the new version on the chrome store and on firefox. in both of the browser picture aren't showing on both the catalog and normal view. the only way to see them is mouse over or expanding them. Tried resetting the options to default and some of the picture appeared but only some of them without following a criteria

**Comment by bakugo** [comment]
4chan was down a few hours ago and it's still not completely back up, image uploads are broken and images sometimes fail to load at all. I doubt it's related to 4chan X.

**Comment by misakabestgirl** [comment]
3 hours passed and now some of the images are visible, but only the ones that where posted before 4chan went down, all the new ones are not visible, and also, it gives me an error every time I try to post. I'll keep you updated

**Comment by misakabestgirl** [comment]
ok, a few minutes ago the problem fixed itself. thank you for inorming me 4chan going down :)
