### ISSUE TITLE
Persistent storage maximum size reached

### ISSUE THREAD

**Issue by Papaie** [ccd0/4chan-x#272]
With  1.9.19.2 on firefox 35, I have the errors on every catalog pages :  

"Quick Reply" initialization crashed.
NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached
"Thread Watcher" initialization crashed.
NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached

**Comment by Papaie** [comment]
Also this one in a thread I participate in : 
"Unread" initialization crashed.
NS_ERROR_DOM_QUOTA_REACHED: Persistent storage maximum size reached

**Comment by ccd0** [comment]
If you export your settings, how large are they?

**Comment by ccd0** [comment]
You should be able to fix this with `localStorage.clear()` in the Javascript console, but that will clear any native extension settings you have, and possibly settings from other scripts.  Your 4chan X settings won't be affected.

Alternatively you can increase `dom.storage.default_quota` in `about:config`, but that will likely just kick the problem down the road.

You should probably check `localStorage` in the Javascript console to find out what's taking up all that space.

**Comment by Papaie** [comment]
My settings weighed 17 kB but now they are at 14kB. When I changed my theme for 4chan, the thread watcher appeared anew (it and the QR were absent) and I pruned all the threads. I no longer have the errors.


for info, my dom.storage.default_quota is set to 11

**Comment by hotdogman** [comment]
>for info, my dom.storage.default_quota is set to 11

That doesn't seem right.
>http://kb.mozillazine.org/Dom.storage.default_quota
>Amount of data a site may use, in kilobytes. Default value is 5120 (5 MB). 
>Default value is 5120

**Comment by ccd0** [comment]
> for info, my dom.storage.default_quota is set to 11

Is there a reason you have it set that low?  If not, setting it to the default should fix your problem.  It can be improved if necessary, but for the current version of 4chan X, that's not an unusually large amount of local storage space for it to entirely consume.

**Comment by Papaie** [comment]
THe three messages appeared anew and resetting the value dom.storage.default_quota permitted to make the QR and TW appear. I do not know what changes the value of dom.storage.default_quota but all is well now.
