### ISSUE TITLE
Board fuckery

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#273]
Is it possible to enable the scripting moot put on /pol/? (and other boards in the future)
If not, can you add an option?

Sorry if duplicate.

**Comment by ccd0** [comment]
You mean the scrolling stuff?  If you really want it, you can display it with

    marquee, .postMessage marquee + br, .postMessage marquee + br + br {
      display: inline;
    }

in custom CSS.

**Comment by ididntknowicoulddothatXD** [comment]
Thanks.
