### ISSUE TITLE
Internal archives

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#274]
https://boards.4chan.org/vr/archive

>"Index Generator" initialization crashed.
>TypeError: Cannot read property 'parentNode' of null

Also, please add internal archive-only links, like "current-archive". Thanks in advance.

**Comment by ccd0** [comment]
Just did an update for the archived threads list.  Let me know if anything's broken/missing.

One thing known to be missing on the archived threads list is filtering.  That may take some work to implement.

> Also, please add internal archive-only links, like "current-archive". Thanks in advance.

That's taken; how about `current-intarchive` or `current-archived` or `current-expired`?

**Comment by ididntknowicoulddothatXD** [comment]
current-expired sounds nice.

**Comment by ccd0** [comment]
OK, `current-expired` is in the beta (v1.9.19.5) now.

**Comment by ididntknowicoulddothatXD** [comment]
Thanks.

**Comment by ididntknowicoulddothatXD** [comment]
Beep, including the search function would be great.

**Comment by ccd0** [comment]
There isn't really a good way to search them other than what you can already do with Control+F.  You'd have to load the JSON for every thread on the archives page.  Fortunately the external archives have great search support.
