### ISSUE TITLE
Apply green-ish color to quoted text in archived page

### ISSUE THREAD

**Issue by hotdogman** [ccd0/4chan-x#275]
I figured (if it's possible) that 4chanX should apply the green color to quoted text in the archived page because it also does so in the catalog.
![screenshot--g- - technology - archive - mozilla firefox-1](https://cloud.githubusercontent.com/assets/4343306/5607624/f51eb9b8-9427-11e4-8db7-48b3aa2eee90.png)
![screenshot--g- - technology - mozilla firefox](https://cloud.githubusercontent.com/assets/4343306/5607619/bde7b9f4-9427-11e4-8b02-766e3b552fc4.png)

**Comment by ccd0** [comment]
Added to the beta (v1.9.19.5).

**Comment by hotdogman** [comment]
Neat. Thanks.
