### ISSUE TITLE
4chan's native catalog is overriding 4chan X's catalog.

### ISSUE THREAD

**Issue by placeholderaccount** [ccd0/4chan-x#276]
boards.4chan.org/[letter]/catalog

The 4chan X catalog loads for a second, and is then refreshed and replaced with the native catalog (paged, index, etc).

**Comment by ccd0** [comment]
That's the 4chan X catalog overriding the native catalog.

**Comment by ccd0** [comment]
I've removed the redirect, but if you want to use the native catalog you should uncheck "Use 4chan X Catalog" in your settings.
