### ISSUE TITLE
Weird spacing in the catalog

### ISSUE THREAD

**Issue by ColonelBlues** [ccd0/4chan-x#278]
Here is an example:
![](http://i.imgur.com/FxGITHL.jpg)

Everything is perfectly fine in threads, but the catalog seems to be funky with spaces (they still only count as one space). Importing my settings will replicate the problem. Tested on Chromium and Firefox.
ccd0's 4chan X: http://puu.sh/e8s2H/6dc6695b76.json
OneeChan: http://puu.sh/e8s4d/e257d1f0d5.json
(These are the only two extensions I use.)

**Comment by ccd0** [comment]
OneeChan justifies the text in the catalog.  If you don't like it that way, you can override it with

    .comment {
        text-align: center !important;
    }

or

    .comment {
        text-align: left !important;
    }

in custom CSS.

**Comment by ColonelBlues** [comment]
Thank you very much, that works perfectly.

**Comment by ColonelBlues** [comment]
Okay so sometimes when I go back to the catalog the spacing messed up again and requires me to manually refresh the entire page to temporarily fix it. Any ideas on that?

**Comment by ccd0** [comment]
Probably an issue with the order in which stylesheets are appended.  Try adding the custom CSS in OneeChan instead of in 4chan X.

**Comment by ColonelBlues** [comment]
Problem seems to have resurfaced after one of the recent updates (not sure which one). I have both 4chan X and Oneechan with the custom CSS still.

**Comment by ccd0** [comment]
It looks like there's a "Justified Text" option in OneeChan now.  Try turning that off.  If that doesn't work, open an issue on the OneeChan bug tracker.

**Comment by ccd0** [comment]
> now

Actually, I think it was there before this issue was opened.

**Comment by ColonelBlues** [comment]
Ah thanks for that, I didn't know Oneechan added something like that.
