### ISSUE TITLE
Increase 4chan-x popularity by adding a watermark on pictures people upload

### ISSUE THREAD

**Issue by jksfsfjk23h4** [ccd0/4chan-x#2781]
Increase 4chan-x popularity by adding a watermark on pictures people upload.
Have a 4chan logo on each photo above 200x200 photo that is uploaded via 4chan x

**Comment by jksfsfjk23h4** [comment]
![image](https://user-images.githubusercontent.com/70487576/92316864-5f700880-f002-11ea-96b1-1cabb94cbd56.png)

**Comment by ccd0** [comment]
lol
