### ISSUE TITLE
the word 'discord' is being filtered

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2784]
Submitter: ColdFusion
Using version 1.14.4.5 
when I try to post anything with the word 'discord' it pretends to put the post through, but then the post never appears. I have made sure by posting the exact same post but with 'd*scord' and that went through. In the case of a new thread, it definitely doesn't appear, I try making a new thread with the same image, and I don't get a duplicate image error, so it definitely doesn't exist.
I tried on another computer that doesn't have the extension, and it's not happening there, so I've narrowed it down to 4chanX causing this.

**Comment by fgsfdss** [comment]
based

**Comment by ccd0** [comment]
Discord links (I believe has to be a link and not just the word) are known to be filtered on many but not all 4chan boards, but this is something 4chan does. 4chan X does not filter your posts, regardless of how shitty they may be.
