### ISSUE TITLE
Keep the board links on top from collapsing every time I switch boards.

### ISSUE THREAD

**Issue by ethan0lx** [ccd0/4chan-x#2788]
This is a extremely annoying "feature". Every time I click on a board, the links collapse and I have to click the [ + ] again to see them again. Is there a way to have the links always open or even better yet to choose which boards I want links to?

https://i.imgur.com/xi70L47.png

**Comment by saxamaphone69** [comment]
Settings > Advanced > scroll down to "Custom Board Navigation"

**Comment by ethan0lx** [comment]
> Settings > Advanced > scroll down to "Custom Board Navigation"
> Also ensure that in the Header bar settings (the dropdown arrow menu), that "Custom Board Navigation" is enabled.

Thank you very much.  Solved it for me!
