### ISSUE TITLE
Can't highlight own threads?

### ISSUE THREAD

**Issue by 720905** [ccd0/4chan-x#2789]
For some reason catalog filtering doesn't work on my own threads. Is this feature intended or am I doing something wrong?   
The filter works, I'm 100% sure but when it matches a thread I made it doesn't highlight it or bump it to the top.

However, when I click said thread (the thread I made) the red halo appears around the OP , so it means the filtering worked.
So what's up? Am I just retarded?

**Comment by 720905** [comment]
Okay, from what I see I only get this problem when using the native 4chan catalog. 4chan X's catalog filters and highlights my threads properly. I like the native catalog more, unfortunate.

**Comment by ccd0** [comment]
You can turn on filters in the native catalog with the option "Filter in Native Catalog."
