### ISSUE TITLE
Enabling Captcha Fixes breaks noscript captcha

### ISSUE THREAD

**Issue by BlackPowerade** [ccd0/4chan-x#2797]
With "captcha fixes" enabled the text box to paste the verification code does not appear. This renders the captcha impossible to solve.
![image](https://user-images.githubusercontent.com/21957509/93841305-c45d6c80-fc58-11ea-8284-0d26e7d4b259.png)
Where as this problem is not present when "captcha fixes" are not enabled.
![image](https://user-images.githubusercontent.com/21957509/93841392-0dadbc00-fc59-11ea-93a6-e6214c6c9934.png)
I have verified it is not oneechan or any other css affecting this.

**Comment by ccd0** [comment]
It's supposed to paste it into that box for you. Is it not working?

**Comment by BlackPowerade** [comment]
No, it does not.

**Comment by ccd0** [comment]
Works for me, what browser and userscript manager are you using?

**Comment by BlackPowerade** [comment]
Edge chromium and tampermonkey

**Comment by ExoticMatter** [comment]
This also happens to me in Firefox 78.10-esr + Greasemonkey 4.11 with 4chanX 1.14.21.3. The div containing textarea under `.captcha-container` is hidden; I can unhide it with inspect element, allowing me to paste the code, although disabling captcha fixes is a more effective workaround.
