### ISSUE TITLE
Archives.json repository has been archived

### ISSUE THREAD

**Issue by Adamantcheese** [ccd0/4chan-x#2799]
https://github.com/nstepien/archives.json
It was already out-of-date, but I guess it's probably good to let everyone know that it won't be updated in the future either. Probably needs a new maintainer, or for it to be moved into 4chan-x itself.

**Comment by CANADIANPIG** [comment]
Yeah i am receiving an error for this as well. oh well

**Comment by Bexa2** [comment]
In case it's needed.
https://web.archive.org/web/20200917173424/https://nstepien.github.io/archives.json/archives.json

**Comment by Adamantcheese** [comment]
Closed as of 2040b9489529df708ac98cc1e5dba474a43947c3.
