### ISSUE TITLE
Search doesn't get unselected when selecting a thread

### ISSUE THREAD

**Issue by hotdogman** [ccd0/4chan-x#280]
http://a.pomf.se/pnjxbc.webm
Not sure if this a bug, or a feature request, or something else, but when you search for something with CTRL+ALT+S, and then navigate to a thread using CTRL+Up or CTRL+Down, and try to open it with Shift+O, the search doesn't get unselected, so the thread doesn't get opened, because it tries to search for it.
If it's possible, could you make it so that when CTRL+Up/CTRL+Down is pressed (or whatever the keybind for navigating between threads is,) the search gets unselected?

**Comment by ccd0** [comment]
Should be fixed in v1.9.19.6.

**Comment by hotdogman** [comment]
Thanks.
