### ISSUE TITLE
NSFW boards captcha is buggy on Opera browser

### ISSUE THREAD

**Issue by chanmioo** [ccd0/4chan-x#2804]
Recently the captcha checkbox area has been buggy on Opera for nsfw boards but works fine on sfw blue boards. The captcha checkbox is missing and has the wrong font. When clicked on, the captcha puzzle shows repeating images and is not solvable.

images showing the issue:
https://files.catbox.moe/43gjcd.png
https://files.catbox.moe/78a8t0.png

**Comment by chanmioo** [comment]
I have default Captcha settings as whenever I install 4chx and change the settings I never have touched the Captcha settings. They've always worked fine up until now.

**Comment by WorkerDrone16** [comment]
I'm just here to say i'm having the same exact issues, on OperaGx
![opera_2pGRLlKc2s](https://user-images.githubusercontent.com/73368920/97060698-ca958000-1559-11eb-8348-17c839207a0c.png)
![opera_xUFOSnihss](https://user-images.githubusercontent.com/73368920/97060718-d84b0580-1559-11eb-8c70-6b9aa7f61f0d.png)

**Comment by chanmioo** [comment]
> I'm just here to say i'm having the same exact issues, on OperaGx
> 
> ![opera_2pGRLlKc2s](https://user-images.githubusercontent.com/73368920/97060698-ca958000-1559-11eb-8348-17c839207a0c.png)
> 
> ![opera_xUFOSnihss](https://user-images.githubusercontent.com/73368920/97060718-d84b0580-1559-11eb-8c70-6b9aa7f61f0d.png)
> 
> 
> 
> 

I figured it out. In extensions there is a native Opera adblocker, disabling it worked for me.

**Comment by chanmioo** [comment]
I figured it out. In extensions there is a native Opera adblocker, disabling it worked for me (using non-GX Opera).
