### ISSUE TITLE
Error fetching archive data from https://nstepien.github.io/archives.json/archives.json Connection Error

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#2809]

**Comment by toniz4** [comment]
having the same error here

**Comment by Micronetic** [comment]
> having the same error here

But it looks as everything is working though, I am getting replies to show up in the Thread Watcher, can post etc. 

Would like to know what archive data this is needing to fetch?

**Comment by fgsfds** [comment]
Same

**Comment by saxamaphone69** [comment]
Either update 4chan X or use the new archive list `https://4chenz.github.io/archives.json/archives.json`
