### ISSUE TITLE
Add .se and .dance to linkified domains

### ISSUE THREAD

**Issue by hotdogman** [ccd0/4chan-x#281]
pomf.se doesn't get linkified
loli.dance doesn't get linkified
I added dance and se to https://github.com/ccd0/4chan-x/blob/master/src/Linkification/Linkify.coffee#L82. loli.dance got linkified, but pomf.se didn't, dunno why.

**Comment by ccd0** [comment]
> pomf.se doesn't get linkified
Works for me.  `se` should already be included in the `[a-z]{2}` option.

**Comment by hotdogman** [comment]
https://boards.4chan.org/g/thread/45979244
![screenshot-9](https://cloud.githubusercontent.com/assets/4343306/5654639/a3d598e6-968a-11e4-9487-a9f8255bc018.png)
>Works for me

It doesn't for me.

**Comment by ccd0** [comment]
It's probably failing in the case where it's followed by the comma.

**Comment by hotdogman** [comment]
That's probably it. Sorry for bothering you with something simple like that.

**Comment by ccd0** [comment]
Even though it's minor, it should still be fixed.
