### ISSUE TITLE
Not able to start threads on non blue boards and can't post on boards with geo location

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2825]
As the title suggests. I'm using chrome and can post just fine with 4chan X off, and i also tried turning off other extensions (which are just adblockers), but those didn't change anything. Two errors appear in the console both of which look like:
Refused to load the script 'https://cdn2.lockerdomecdn.com/_js/ajs.js' because it violates the following Content Security Policy directive: "script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://cdnjs.cloudflare.com https://hcaptcha.com https://*.hcaptcha.com 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
They don't appear with 4chan X off

**Comment by ParrotParrot** [comment]
Started happening to me a couple of hours ago. Posting would report a success but not actually post, only on 4chan domain.
It seems to have fixed itself after a DNS cache flush by `ipconfig /flushdns`
