### ISSUE TITLE
Ads/Banners

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2830]
There doesn't seem to be an option to unhide ads and banners. 4chan recently added user submitted ads and banners, and I would like to see them. But there isn't an option in the settings to view them. Can you add a button enabling them?

**Comment by huglovefan** [comment]
make sure your ad blocker isn't blocking them

i was able to make them seeable by whitelisting `bid.glass` in umatrix (i don't use ublock) and adding `https://bid.glass` `https://s.4cdn.org` to the javascript whitelist in 4chan-x advanced settings
