### ISSUE TITLE
4chan Pass Captcha 

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2840]
Submitter: rhine
As a 4chan Pass user, I'm still prompted to complete the captcha in the quick reply form. Is there something in the pipeline to address this? Thanks

**Comment by saxamaphone69** [comment]
I would say make sure you're [signed into your 4chan Pass](https://sys.4channel.org/auth) account.
If you disable 4chan X, does it recognise your 4chan Pass?
Do you have anything that might be blocking the request to check for the Pass?
