### ISSUE TITLE
'Hide bottom board list' doesn't work

### ISSUE THREAD

**Issue by esgwpl** [ccd0/4chan-x#285]
I'm running the script on Pale Moon, OS is Xubuntu.

![screenshot - 01122015 - 03 28 11 am](https://cloud.githubusercontent.com/assets/10489620/5696725/6cfe6fb6-9a0c-11e4-8998-002a8cfecf5b.png)

**Comment by ccd0** [comment]
Moot removed the bottom board list from the page and now generates it with Javascript instead.  It should be fixed now.
