### ISSUE TITLE
Is there a way to not scroll down to the last post?

### ISSUE THREAD

**Issue by Shikianon** [ccd0/4chan-x#2862]
When I click update, the thread scroll downs to the last post, like I update, there are 20 new posts and the thread scrolls to the very last post, so I have to scroll up to read the other new posts, this is pretty annoying, is there a way to update a thread and not scroll all the way down automatically?

**Comment by duanemoody** [comment]
Use the Thread Updater preference instead of manually updating. It doesn't affect scrolling and puts a simple horizontal line above the new posts.

**Comment by saxamaphone69** [comment]
![image](https://user-images.githubusercontent.com/877480/236819579-38a84b16-888b-4b5c-bdf2-33a3c4e7b712.png)
Also ensure these are off, just in case.
