### ISSUE TITLE
[Feature Request] Allow setting of styles outside of cookies

### ISSUE THREAD

**Issue by johnch18** [ccd0/4chan-x#2865]
I clear my cookies to ban evade pretty frequently, and the annoying thing is that it changes me back to the default styles for SFW and NSFW boards. I just want to use tomorrow god damnit. Could you add a way to let us set our current theme that bypasses cookies? Also please make it override holiday themes.

**Comment by duanemoody** [comment]
Export settings then after you do your thing, import them again.

Holiday and prank themes have a habit of changing their backend code for reasons which include providing a disincentive to easily disable them.
