### ISSUE TITLE
Auto refresh doesn't work, shows Offline instead.

### ISSUE THREAD

**Issue by anon2847** [ccd0/4chan-x#287]
Threads are not auto-refreshing and instead of an auto-refresh countdown it simply displays, "Offline" http://puu.sh/epr8R/3d8b741642.png I also just get a blank page when trying to view any board both in paged and catalog view. However if someone links me to a thread I can manually refresh it to get new posts, so 4chan doesn't appear to be down or anything. All other functions of the extension seem to be working fine. 

I've made no changes to my browser, system, or anything in a while. I just woke up, 4chan x updated, and now it's doing this. I disabled all other extensions and it still happens. I'm using 4chan x version 1.9.19.10 on the current version of chrome on windows 8.1. Here are my settings: http://pastebin.com/m8L1WQb1

**Comment by ccd0** [comment]
This is most likely a problem with your Internet connection.

**Comment by anon2847** [comment]
I honestly cannot remember the last time I have had a problem with my connection, and I don't appear to have one now. I have a very stable and consistent connection. Is there anything I can do to confirm that this isn't the case?

**Comment by ccd0** [comment]
If it's showing "Offline", that means that Chrome is setting `navigator.onLine` to false, which should only happen if it thinks you aren't connected to the Internet.  So either you have something going on between your browser and the Internet or a browser bug.

**Comment by anon2847** [comment]
Yes it appears to be a browser bug. For whatever reason it seems to have been stuck like that no matter what. Disconnecting and reconnecting my connection fixed it right away. Thanks for the info and help.
