### ISSUE TITLE
Filename change

### ISSUE THREAD

**Issue by InstallGentoo11** [ccd0/4chan-x#288]
In a previous 4chan X I was using, in the QR box you could click on the filename of a file you have already selected for posting and change the name with witch it would be posted. it was a pretty cool feature to have.

**Comment by ccd0** [comment]
You can edit the filename with Control+click.  That said, I do think the other UI is better and I plan to change it when I get around to it.

**Comment by InstallGentoo11** [comment]
I see, good to know, at least until when you change it.

Anyway, thanks for keep on working on 4chan X.

**Comment by ccd0** [comment]
As of v1.10.3.0 (the current beta), you no longer have to control+click to edit the filename.
