### ISSUE TITLE
Thread Watcher fills itself up with old threads when refreshing /r9k/

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2882]
Submitter: Anon
Not exactly sure how to report this properly, as I'm sure /r9k/ itself isn't the problem. Basically Thread Watcher refreshes itself with an outdated list of threads to follow every time I refresh /r9k/. I can delete everything on the watcher, go to any other board(s), but when I come back to /r9k/, all my old threads come back on the watcher for no reason.

In fact, being on /r9k/ turns the Thread Watcher on entirely. I unchecked the option in the settings, went to some other boards, no Watcher. Go to /r9k/, Watcher turns itself on AND populates itself with a bunch of old threads.

https://cdn.discordapp.com/attachments/721772222058070048/793933403547369492/4chan_X_v1.14.20.4-1609358856634.json
^ my 4chan X settings.

Will help w/any troubleshooting on my end that is needed, if needed.

**Comment by Jalopyy** [comment]
Worth noting that even when I reset 4chan X's settings to default, then go to /r9k/, it somehow brings back up all my old settings even though they should be gone. Have already deleted 4chan's cookies in entirety, so not sure what to think of next.

https://pastebin.com/WQTMPyCD

Pastebin mirror of .json file in case you don't want to download the real one.

**Comment by Jalopyy** [comment]
Nix this ticket. Somehow, restarting my browser fixed it. Who'd have guessed.

**Comment by Nutjob** [comment]
I'm getting this same bug, keep happening since a week or two.
I very rarely go to /r9k/, the bug just happened few minutes ago and the last time I went there was 3 or 4 days ago.

**Comment by Nutjob** [comment]
Duplicate of #2884

**Comment by ccd0** [comment]
merging into #2884
