### ISSUE TITLE
4chan x refusing to upload from pixiv urls

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2899]
Submitter: ruckus
I'm not sure entirely if this is a 4chanx issue, or just a Pixiv/website issue.
But when I try to post an image from a Pixiv URL, I only get the "Can't load file" message. It does this only for Pixiv URLs, and will do it regardless of whether the URL is a full image, thumbnail, what have you.
I don't know if maybe Pixiv changed their URL formatting, but I also only get this error with 4chanx, not other extensions or sites that allow URL uploads.

**Comment by Corridor89** [comment]
Oops. Sorry for the double post.

**Comment by ccd0** [comment]
dupe of #2898
