### ISSUE TITLE
Retain board name on body element

### ISSUE THREAD

**Issue by saxamaphone69** [ccd0/4chan-x#290]
Normally `body` has a `.board_g` or `.board_pol` class on it. On this fork, it seems to be removed.

I am going to assume it has something to do with [this](https://github.com/ccd0/4chan-x/blob/d189e1beedab7e8159d025abc2996165f63d25fe/src/General/Header.coffee#L357).

I only ask because on my userstyle I rely on that to serve different header images to different boards.

**Comment by ccd0** [comment]
I've removed the offending code (which was obsolete anyway) as of v1.9.20.2 (currently the beta).

**Comment by saxamaphone69** [comment]
Beautiful. Works perfectly, thanks!
