### ISSUE TITLE
Annoying persistent image that appears on the right hand side.

### ISSUE THREAD

**Issue by Zalgo97** [ccd0/4chan-x#2904]
Whenever you click the download button this annoying persistent image appears on the right hand side and stays until you refresh the browser. How do I get rid of this I've played with all the settings nothing works.

**Comment by saxamaphone69** [comment]
What browser, what version of 4chan X, how have you installed 4chan X, disable all your other add-ons and see if it still happens, attach a screenshot, does it happen on a fresh set of settings for 4chan X?

**Comment by Zalgo97** [comment]
Brave,1.14.20.4,standalone,ok it's violentmonkey causing the problem time to figure out which script. will update

**Comment by Zalgo97** [comment]
It was thread media viewer sorry for the false alarm guys I'm a retard.

**Comment by saxamaphone69** [comment]
Glad you worked it out.
