### ISSUE TITLE
Images open in Gallery with Expansion disabled

### ISSUE THREAD

**Issue by saxamaphone69** [ccd0/4chan-x#2912]
Small bug? At the least, I wouldn't say it's expected behaviour.

Turn off `Image Expansion`, but leave `Gallery` on.
Click thumbnail of an image, Gallery opens.

Turn off `Image Expansion` **and** `Gallery`.
Click thumbnail, full image opens in new tab.

**Comment by ccd0** [comment]
It was definitely intentional when Zixaphir implemented it, but at that time the Gallery didn't automatically seek to the image you had scrolled to. If it's a problem, that functionality could probably be removed.

**Comment by saxamaphone69** [comment]
Doesn't bother me, I just noticed it when checking for compatibility when enabling/disabling certain options for my userstyle.
