### ISSUE TITLE
Thread Watcher Keeps Reloading pruned threads

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2918]
Submitter: Andrew A Brenton
When I click on the thread watcher "eye" icon, it will have the same five pruned threads from a week ago, and will not update with threads that I have replied to. When I manually delete the pruned threads, and reload the page, the same five threads will reappear. When I click the "prune dead threads" box and reload, the box will still be unchecked.

**Comment by gitdine** [comment]
I've also been experiencing for the past month or so. 
It has been accompanied by the unread reply favicon often failing to update properly when I scroll down, forcing me to reload the tab for it to be marked as read.

**Comment by ccd0** [comment]
merging into #2884
