### ISSUE TITLE
images playing up

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#292]
This only seems to happen with certain images but now when I mouse over them so they expand, it will load only half of the top of the image, then the rest. And if I move the mouse anywhere in front of it, the bottom disappears and it will only show the top of it, while the mouse is moving. If I stop moving the mouse while on the image it loads the rest of it. I'm using 1.9.19.12.
Pic related.
![untitled](https://cloud.githubusercontent.com/assets/5096684/5773512/25edbcfc-9daf-11e4-94e4-0a70bdb36bec.png)

**Comment by owais95** [comment]
THIS^^
I'm having the same problem and it's been driving me insane now!!
Using newest version of firefox and of 4chan-x i guess there's a bug between the plugin interaction or perhaps the source of the problem is a change in the 4chan website
Please fix it's so frustrating

**Comment by nebukazar** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1083113

It's a Firefox bug introduced in 35. If it doesn't go away by disabling hardware acceleration in the options then you should probably downgrade to 34.0.5 if it gets too annoying.

**Comment by poewpoerw123** [comment]
Downgrading to 34 fixes the problem, but now webm files go out of sync every time. I guess I'll just wait for 36 and hope they fix the image loading.
