### ISSUE TITLE
Clicking the (embed) button doesn't load the video, have to open the clip in a new tab

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#2922]
![Screenshot_2021-02-01 (107) fit - Connor Murphy is Muslim now - Fitness - 4chan](https://user-images.githubusercontent.com/5096684/106415267-63f9f980-649a-11eb-951c-c077e2bf1713.png)

**Comment by ccd0** [comment]
It works for me. Maybe check that you're not blocking it with another extension?

**Comment by ccd0** [comment]
I assume you fixed your issue?

**Comment by jimmyrustles** [comment]
I thought it was fixed because it started working again on a video, but I'm still getting the same error with every video now.

**Comment by jimmyrustles** [comment]
It seems to have fixed itself for now.
