### ISSUE TITLE
When I right click on threads on the catalog theres no option to report or hide the thread

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2924]
Submitter: cock stamper
When right clicking on threads on the catalog it used to give you option to report or hide above the options to open the thead in a new tab or window etc. I think it disappeared when i updated firefox. im on ff85. v1.14.20.6.
poo poo piss penis

**Comment by saxamaphone69** [comment]
I saw this in a previous thread, the newest version of Firefox has disabled the ability to add items to the right click context menu. Can't find the exact reference though.

**Comment by ccd0** [comment]
Sad, I much preferred that design to the right-click hijacking some sites do.
This was never part of 4chan X, though. It was a feature of the native catalog.
