### ISSUE TITLE
How do i enable "go to reply"

### ISSUE THREAD

**Issue by qvimxyz** [ccd0/4chan-x#2934]
in normal 4chan when i click on the number of the reply i go there, but using 4chanX when u click the number, reply just appears  either hovering or over (see image) , and that's not what i want. so how do i enable this option?

![picrelated](https://user-images.githubusercontent.com/44214566/107151938-1d961600-6944-11eb-9672-72db99044355.png)
)

**Comment by saxamaphone69** [comment]
The `No.` is what you want to click on.
