### ISSUE TITLE
Submit post after passing captcha automatically.

### ISSUE THREAD

**Issue by ferongr** [ccd0/4chan-x#294]
Assuming that SHIFT-Clicking still works to cache multiple captchas. Right now keyboard users have to Tab multiple times to the submit button. If this happens you could also only show the Submit button when there are cached captchas. Also issue #250 would be neat to be fixed.

**Comment by ccd0** [comment]
The script already has this option; look at your settings.

**Comment by ferongr** [comment]
Thanks. Now all it takes is #250 and I'm a happy camper.
