### ISSUE TITLE
It looks like 4chan X doesn't work on 4channel on Firefox.

### ISSUE THREAD

**Issue by Rattle33** [ccd0/4chan-x#2946]
Title. Firefox 86.0 and 4chan X 1.13.15.10

**Comment by saxamaphone69** [comment]
Try updating 4chan X; 1.13.15 came out in 2018.

**Comment by Rattle33** [comment]
thats pretty funny

i couldn't figure out how to update the damn thing. i only just started using firefox, but when searching for Addons, there's one called 4chan X (which I installed, has ~5,000 users) but then there's another underneath it called 4chan X - Unofficial Port, and only has like 250 users. I installed that one and it's working fine now. strange. thanks for the help
