### ISSUE TITLE
Looking for a help setting up 4chanx on /v/

### ISSUE THREAD

**Issue by SSRISunshine** [ccd0/4chan-x#2948]
So I've mostly just used 4chanx for boards like /pol/ and /b/ and /gif/ but I was wondering how to set it up for other boards that it does not automatically just work for. Is there some setting I can change?
I use the firefox extension and I understand there may be some other way to install the script. Would that resolve the issue? If so, is there installation instructions I can find? 

Thanks again for any help or guidance. o7

**Comment by saxamaphone69** [comment]
4chan X applies to all boards, not just specific ones.

There is [no Firefox extension](https://github.com/ccd0/4chan-x#firefox), so check that.

**Comment by SSRISunshine** [comment]
Interesting, it was working before. Maybe I just had the chrome extension installed? Meh, its fine. Thanks so much though. I did it through tampermonkey now. Its working. 

o7
