### ISSUE TITLE
Exceeded Watched Threads

### ISSUE THREAD

**Issue by ZeroDrako** [ccd0/4chan-x#295]
I get an error if i mark "Watch Thread"...Console code:
<code>
QUOTA_BYTES_PER_ITEM quota exceeded  ----- script.js:904
</code>
<code>
QUOTA_BYTES_PER_ITEM quota exceeded watchedThreads Object {boards: Object, lastChecked: 1421638246446} ----- script.js:911
</code>

right now I have 40 threads, is the limit?

**Comment by ccd0** [comment]
It's the most Chrome will let you sync between devices.

**Comment by ccd0** [comment]
At some point, I need to set it up so that if you go over the limit that you can sync, sync will fail, but saving the setting locally will still work.

**Comment by ZeroDrako** [comment]
I forget to mention that I do not use Chrome ... use SRWare Iron (I hate tracking Chrome) ...
The problem is a solved, thanks !!!
Unlink my google account of Chrome, and now the extension works on SRWareIron !!

**Comment by ccd0** [comment]
> At some point, I need to set it up so that if you go over the limit that you can sync, sync will fail, but saving the setting locally will still work.

As of v1.10.1 it should work this way.
