### ISSUE TITLE
help me with blocking the native extension with ublock origin

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#2952]
Hey guys, can someone please help me with blocking the native extension on 4chan with ublock origin? I have no clue what I need to do and googling it leads me nowhere. Thanks.

![Capture](https://user-images.githubusercontent.com/5096684/111229472-b13cbf80-8631-11eb-836c-fb4307f7e1bf.PNG)

**Comment by saxamaphone69** [comment]
Browser? Userscript manager? Does this happen on a fresh profile?

Did you follow the instructions in the notification? You can click "block it" and it takes you to the FAQ.
https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions#im-seeing-multiple-images-when-i-expand-an-image-andor-getting-an-error-message-saying-failed-to-disable-the-native-extension-how-do-i-fix-it

**Comment by jimmyrustles** [comment]
I'm using Firefox 86.0.1 and using the Ublock Origin add-on, yeah, I did follow that link but I don't really know how to edit the settings in the Ublock Origin add-on.

**Comment by saxamaphone69** [comment]
I'm assuming Firefox still has some "extensions" page where you can see all your extensions. Get into the uBlock settings from there.
Alternatively, when you're on 4chan, click the uBlock icon in the chrome/address bar-area and open the uBlock pop-up and keep clicking "more" until you see 3 cogs (these are the settings). Open that.

Go to the "My filters" tab along the top, add the line `||s.4cdn.org/js/extension.min.*.js$important`, apply changes, hard refresh 4chan, and see if the error persists.

**Comment by jimmyrustles** [comment]
> Alternatively, when you're on 4chan, click the uBlock icon in the chrome/address bar-area and open the uBlock pop-up and keep clicking "more" until you see 3 cogs (these are the settings). Open that.
> 
> Go to the "My filters" tab along the top, add the line `||s.4cdn.org/js/extension.min.*.js$important`, apply changes, hard refresh 4chan, and see if the error persists.

Thanks, I figured it out.
