### ISSUE TITLE
NoScript captcha doesn't work on Greasemonkey 4

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2959]
Submitter: anon
It's as simple as installing Greasemonkey on a new Firefox profile, enabling NoScript captcha and trying to post. You can only click exactly on the small checkboxes at the corner of the images instead of on the images themselves, the option to automatically post upon completion doesn't work, and trying to submit a post results in "no valid captcha".

**Comment by ottersarecool** [comment]
I also get the same using Violentmonkeyv2.12.12 and 4chan-X 1.14.20.6
