### ISSUE TITLE
Desktop Notifications not working.

### ISSUE THREAD

**Issue by ZachArani** [ccd0/4chan-x#296]
Im running 1.9.19.12 and I have desktop notifications turned on and nothing ever happens with it. I also have permissions set to allow desktop notifications on Firefox. Is there an additional setting I'm missing or is this an actual issue?

**Comment by ccd0** [comment]
Working now?

**Comment by ZachArani** [comment]
Yes, sorry for making the issue.

**Comment by ccd0** [comment]
No problem.
