### ISSUE TITLE
Why don't you update the firefox addon version?

### ISSUE THREAD

**Issue by All3xJ** [ccd0/4chan-x#2965]
Here: https://addons.mozilla.org/it/firefox/addon/4chanx/
the last update is in 2018

**Comment by saxamaphone69** [comment]
To my knowledge, there is no official Firefox Addon of 4chan X.

Someone else has uploaded that and could have potentially included malicious code.

The only way to use 4chan X on [Firefox](https://github.com/ccd0/4chan-x#firefox) is through a userscript manager.
