### ISSUE TITLE
m5d filter - op:no and highlight:test don't work together

### ISSUE THREAD

**Issue by GitGondola** [ccd0/4chan-x#2968]
When used together op:no works but highlight:test doesn't add the class to the post.
eg.  /asdf==/;op:no;highlight:test;
There's some images I'd like to filter unless they're used to start a thread, and with highlight:test I can blur them out if they do start a thread with it.

**Comment by saxamaphone69** [comment]
If I understand correctly, you'd want `op:yes;`, then use `.opContainer.test .fileThumb { filter: blur(10px); }`, which would only blur OP images matching that filter, and replies/posts would be left as is.

**Comment by GitGondola** [comment]
Hmmm how to explain it.
There's some images I don't want to see but could be used to start a good thread full of images I might want to see. = op:no
But when an image I don't want to see is used to start a thread I want the thread to appear but the op image to be blurred = highlight:test

They work independently but when combined if an image I don't want to see is used to make a thread the thread shows up but it doesn't have the .test class where it should

**Comment by saxamaphone69** [comment]
I'm still struggling a bit to understand. Do you have a specific example in an active thread or two along with the relevant filters you're using and would be willing to share?

Otherwise, you could maybe create two filters, `highlight:okay-to-see` and `highlight:not-okay-to-see`?

Then play around with the classes available and maybe even `:not()`?

`.opContainer.okay-to-see:not(.replyContainer) .fileThumb { filter: blur(10px); }` or something? `.opContainer.okay-to-see.not-okay-to-see .fileThumb...`?

>but it doesn't have .test

`op:no` just means that the OP won't be filtered/highlighted, but any replies that match the Regex will be. That means it's working as intended.

**Comment by GitGondola** [comment]
![47088438](https://user-images.githubusercontent.com/68796479/114326891-2ab8c680-9b7a-11eb-92a8-eaaf4d645823.png)
![47088437](https://user-images.githubusercontent.com/68796479/114326894-2c828a00-9b7a-11eb-82e9-c617ee537ce7.png)
Hopefully this thread stays up for a while:
https://boards.4channel.org/an/thread/3757205
/d+eVKW34F4Na3lWjjPa0+g==/;op:no;highlight:test;

Add that filter yourself, ctrl + f the thread list for "sure eat a lot", inspect it and see that it doesn't have the .test class like you would expect it to because of the "highlight:test"

**Comment by saxamaphone69** [comment]
Yes, because you use `op:no`, which won't give it to the OP.

**Comment by GitGondola** [comment]
op:no - hides things unless they're the OP
highlight:test - adds a class to matched things
There's no reason they can't work in tandem.

**Comment by ccd0** [comment]
You need two filters, one to hide replies and one to add the class to OPs.

**Comment by saxamaphone69** [comment]
`/d+eVKW34F4Na3lWjjPa0+g==/;highlight:test;` - this is your filter.
`.test:not(.opContainer) .fileThumb { filter: blur(10px); }` - this in your Custom CSS.

Isn't what you're after?

Anything that matches the filter will be blurred, unless it's an OP, in which case it will be ignored.

**Comment by GitGondola** [comment]
> 
> 
> You need two filters, one to hide replies and one to add the class to OPs.

Thank you
