### ISSUE TITLE
No html in board title/subtitle

### ISSUE THREAD

**Issue by bakugo** [ccd0/4chan-x#297]
Don't know if this is intended, but 4chan X removes html tags from board titles/subtitles.

Without 4chan X:
![image](https://cloud.githubusercontent.com/assets/6014513/5847220/c12a737e-a1c2-11e4-9bce-bcabfe7dc5c2.png)

With 4chan X:
![image](https://cloud.githubusercontent.com/assets/6014513/5847225/d45824b4-a1c2-11e4-9db5-4b38c30578e4.png)

**Comment by hotdogman** [comment]
works on my machine
:^)
![screenshot](https://cloud.githubusercontent.com/assets/4343306/5847593/7b99bcb2-a194-11e4-9e0f-5a7bd8eac4b5.png)
Shitposting aside, this is probably related to the release of https://github.com/ccd0/4chan-x/blob/master/CHANGELOG.md#v1737
>Disable HTML both in custom board titles and file info formatting. This shuts down a means for a malicious script injected into the page to permanently install itself, to be run each time you browse 4chan. I expect few or no people were actually using their own HTML in these fields; if you want it back, make a request on the issues page, and I will consider working on a secure implementation.

**Comment by hotdogman** [comment]
Disregard that, I suck cocks. It looks normal in the index, but I get the same thing you do in threads.

**Comment by bakugo** [comment]
Yeah, I guessed it was for security purposes, but it would be nice to be able to keep html tags even if only for non-custom titles since moot sometimes fucks around with it (rip).

**Comment by hotdogman** [comment]
I'm pretty sure these are the related commits.
https://github.com/ccd0/4chan-x/commit/6ce8bef70945d7ef8bcbbd9a0fa7053c41158cb9
https://github.com/ccd0/4chan-x/commit/0415828e271476e201b883d5054e6ca55ed74444

**Comment by hotdogman** [comment]
That was fast.

**Comment by bakugo** [comment]
Yep. Thanks.
