### ISSUE TITLE
4chanx says I'm banned

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2971]
attempting to post with 4chanx says
Error: Ban evasion. Your original ban expires on April 27th, 2021 at 12:04 ET.
but https://www.4chan.org/banned says I'm not banned and when I go in a private window or turn off 4chanx I can post just fine
I have 4chan pass but same results whether I'm authorized or not

**Comment by ow-mahlayg** [comment]
This can be closed, 4channel.org/banned had the banned information I was looking for
