### ISSUE TITLE
IQDB is down, add a saucenao option to images

### ISSUE THREAD

**Issue by kargaroc** [ccd0/4chan-x#2972]
Since IQDB is down, the link for it that is added to all image posts by default doesn't work.
If it doesn't come back eventually it should be removed.
SauceNao works, but you have to use it manually.
It would be nice if a saucenao option could be added directly to the default image menu.

The URL format for saucenao would be something like
```
https://saucenao.com/search.php?url=https://i.4cdn.org/vp/1619340743906.png
```

**Comment by saxamaphone69** [comment]
`//saucenao.com/search.php?url=%IMG;text:sauce`

You can already add it in the Settings, under the Sauce tab.
