### ISSUE TITLE
where does 4chan-x keep its settings in firefox?

### ISSUE THREAD

**Issue by toimine** [ccd0/4chan-x#2976]
had to do a reset because the browser was acting up, then realised that i've forgot to export my settings, so now my watched threads and a ton of filters are lost
i assume it's somewhere in the old profile folder, but i've got no idea where exactly

**Comment by saxamaphone69** [comment]
It's probably too late now, but these might help others:

- https://groups.google.com/g/greasemonkey-dev/c/UaHjiVLgeRI
- https://stackoverflow.com/questions/11850460/where-are-chrome-tampermonkey-userscripts-stored-on-the-filesystem
- https://stackoverflow.com/questions/56918239/where-is-tampermonkeys-storage-tab-to-edit-the-storage-content
