### ISSUE TITLE
Flag support on /mlp/

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2977]
Submitter: Anonymous
I know it's a retarded change and I'm not a fan of it either but /mlp/ has flags now. 4chan X should at least support what the native site/extension does

Thanks for your time and general development, you're doing a great job.

**Comment by bakugo** [comment]
This change also broke troll flags on /pol/ since the API field was changed (it's now `board_flag` and `flag_name` instead of `troll_country` and `country_name`)

**Comment by bakugo** [comment]
Also boards.json was updated with a new flag format:

https://github.com/Floens/ChanTracking/commit/f241acf72cdc5c0ef3b4dcc68515c7ab274e82e9

**Comment by ccd0** [comment]
Thanks for reporting. It's fixed in the latest version.
dupes: #3003 #3005 #3017 #3027
