### ISSUE TITLE
Captcha fails on first load

### ISSUE THREAD

**Issue by EroticSpork** [ccd0/4chan-x#298]
Captcha has been failing on first load, the whole captcha needs to be minimized then reopened to work. It either spins forever if you're supposed to get a free one, or if you need to enter the captcha it won't let you submit it.

**Comment by ccd0** [comment]
What browser are you using, and what version?  Does it happen with all extensions other than 4chan X and Greasemonkey (if applicable) disabled?  Can you export a copy of your settings and post them somewhere?

**Comment by EroticSpork** [comment]
Issue seems to be fixed now. May have been an issue with Captcha itself.
