### ISSUE TITLE
Flag change option not appearing on quick reply form in /pol/ board

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2980]
as title suggests i am not getting the option to change my flag from the quick reply form box when replying to posts in the /pol/ board, it disappeared all of a sudden. I tried reinstalling 4chanx a couple of times on default settings to no avail, i am using google chrome.

**Comment by saxamaphone69** [comment]
4chan X has not been updated for the newest flag changes on 4chan yet.
