### ISSUE TITLE
About script stopping part-way through threads

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#2983]
This only happens to me on /g/, and 2 other anons confirmed this. For me personally, neither clearing the cache nor restarting the browser and staying in a single tab resolves the issue.
I do get the following error message in the browser console: "Promise resolved after context unloaded", "GM_getValue user-script:4chan-X/4chan X:28234" with 133 repeats.
Firefox 78.10.0-esr + Greasemonkey 4.11 + 4chan X 1.14.21.0

**Comment by CorWilson** [comment]
Adding to this that it's an solely a /g/ related event.

**Comment by planetar09** [comment]
/sci/ too
