### ISSUE TITLE
webm with controls and close on click

### ISSUE THREAD

**Issue by xehozq** [ccd0/4chan-x#299]
Right now to close a webm I have to click a additional link, which is super annoying.

In this 4chanx version (https://github.com/loadletter/4chan-x/) I can close the webm by just clicking on it and with some light modding of the script (just add "controls" after "loop") it also shows me controls. So I would have controls + I can close by clicking the webm instead of a link somewhere over it.

I hope you will implement this into your extension as well.

**Comment by InstallGentoo11** [comment]
You can contract it by dragging it to the left.

**Comment by ccd0** [comment]
> with some light modding of the script (just add "controls" after "loop") it also shows me controls

Now try operating those controls.

**Comment by xehozq** [comment]
>Now try operating those controls.
Works fine. https://drive.google.com/file/d/0B-janXwEl5hISVVLUDBVeUtGYlU/view?usp=sharing

**Comment by ccd0** [comment]
That's good news.  That didn't work in either at the time .webm was added to 4chan.  But Chromium has been fixed so that will now work:

https://code.google.com/p/chromium/issues/detail?id=390186

And Chromium's new behavior agrees with the standard, so it should eventually be fixed in Firefox.

I'll change them to contract on click by default (only on Chromium-based browsers for now) and put in an option for the old behavior for people using old versions or forks that need it.

**Comment by ccd0** [comment]
On the other hand, maybe it would be easier to just ignore clicks on the area where the controls are expected to be.  And I could remove the ignore-clicks code when enough people's browsers are compliant.

**Comment by xehozq** [comment]
>On the other hand, maybe it would be easier to just ignore clicks on the area where the controls are expected to be

I tried that before and I had trouble getting it to work properly. But it might just be because I suck at coding.

Anyways, thank you. I am very happy that you will implement this feature.

**Comment by ccd0** [comment]
> I tried that before and I had trouble getting it to work properly.

Any particular problems you had with it?

**Comment by xehozq** [comment]
>Any particular problems you had with it?

I don't remember it too well, but the more I think about it I think i actually got it to work in the end.

**Comment by ccd0** [comment]
This is now implemented in the beta version (v1.9.21.0).

**Comment by xehozq** [comment]
awesome
