### ISSUE TITLE
"Reply Hiding" crashed on node Post, settings not saving

### ISSUE THREAD

**Issue by Waffletoaster** [ccd0/4chan-x#301]
Never posted here before so if you need any information then please say so.
I am using Firefox 35.0.1 and was using 35.0 since the 15th of January but had no issues then, the issues started since this weekend when I updated 4chanX to 1.9.20.8.
I am using Greasemonkey 2.3

What I tried so far: remove the script entirely, reboot and reinstall it from this site. So a clean sheet with clean settings. It has no effect. Resting the settings also doesn't help the issues.

Problems I am having are as following:

"Reply Hiding" crashed on node Post No.280887434 (v).
TypeError: sideArrows is null

This message displays whenever I get into a thread and shows for every reply made in the thread. 
In my settings I tried turning off the reply hiding function but it has no effect. The message appears every time. I also had a similar one for the persistent quick reply but the menu seems to work though.

Another issue I have is with the settings: I turned image load on hoover off but it still happens.
Also I have my header as [toggle-all] but it displays the default header you get when first installing the script.

I also have 4 massive reply to thread buttons stacked at the top of the page.

My exported settings can be found here: https://mega.co.nz/#!TVRhRBrb!QhDwgEKsW8rXegv4lDcFYTGCSZvTH9FWtkmAWX8Ntf8

Screenshots of errors and header.

![header](https://cloud.githubusercontent.com/assets/10716081/5909782/e2ccdd4c-a5b3-11e4-8d62-4362cd0d4164.PNG)
![reply hiding error](https://cloud.githubusercontent.com/assets/10716081/5909781/e2cb5e04-a5b3-11e4-83b5-bfdb1559afb1.PNG)

**Comment by ccd0** [comment]
> I also have 4 massive reply to thread buttons stacked at the top of the page.

This is generally caused by having multiple copies or versions of 4chan X enabled at once.  Go through the list of user scripts in your add-ons tab and make sure only one 4chan X script is enabled.

**Comment by Waffletoaster** [comment]
That isn't right because that is the only script for 4chan I am running.

![scripts](https://cloud.githubusercontent.com/assets/10716081/5914094/4a29c820-a5ef-11e4-976b-74884ab69ec8.PNG)

**Comment by ccd0** [comment]
Do you have any other extensions installed?
Does it happen in a clean Firefox profile?  Maybe you have multiple copies installed and there's a glitch where one's not showing up.

**Comment by Waffletoaster** [comment]
I will check for certain when I get back from work, as far as I know I don't have any other extensions installed except for this one.

**Comment by Waffletoaster** [comment]
Okay here with an update. The problem is resolved and I would like to thank you for your help. While looking through my extensions I tried disabling several that might be able to interfere with the 4chan x script. After turning off Scriptish 0.1.11 my header returned to normal and I get no more errors when going into threads, basically every listed malfunction is now gone.
