### ISSUE TITLE
Updater options not appearing

### ISSUE THREAD

**Issue by hotdogman** [ccd0/4chan-x#303]
So, I may just be crazy, but 4chanX's settings say that the thread updater has more options in it's own dialog, but it isn't working for me.
It looks like the code for it is there, https://github.com/ccd0/4chan-x/blob/master/src/General/Config.coffee#L875-901, but the options never show up for me.
When I hover over the thread updater, the dialog never appears, it just asks if I want to update the thread.
![2015-01-26_23-15-57](https://cloud.githubusercontent.com/assets/4343306/5913946/52c74b16-a5b2-11e4-8ded-cf65f4533a41.png)

Tested with a fresh install on Google Chrome, default settings, except I unticked Updater and Stats in Header.
Exported settings: http://a.pomf.se/lqipuv.json

**Comment by ccd0** [comment]
The options are in the header menu and the advanced tab.  I'll fix the description.

Although the right way to do it would be nesting them underneath (#186).

**Comment by hotdogman** [comment]
Oh, woops. Sorry about that. I had just read that it had it's own dialog, so I thought it was something to do with the updater, not the header menu. My fault for not looking more. I apologize.

**Comment by ccd0** [comment]
Don't apologize, documentation bugs are still bugs.
