### ISSUE TITLE
Going to board catalog from thread crashes tab on firefox

### ISSUE THREAD

**Issue by d3athrow** [ccd0/4chan-x#3035]
I'm on Firefox 89.0b9 and going to a board catalog from a thread causes the tab to crash 9/10 times. Refreshing the page allows it to load properly though.

**Comment by recordcrash** [comment]
Can confirm

**Comment by DocHobo** [comment]
also having the same problem

**Comment by owataww** [comment]
Confirmed

**Comment by ccd0** [comment]
Didn't see this in FF 88.0.1 with Violentmonkey. Is this something happening only in the beta, or is it just hard to reproduce?

**Comment by d3athrow** [comment]
@ccd0 I think it may have been that particular beta. It still happens with 89.0b13 but ***much*** less frequently. Maybe once out of every 50 catalog loads

**Comment by DocHobo** [comment]
> 
> 
> Didn't see this in FF 88.0.1 with Violentmonkey. Is this something happening only in the beta, or is it just hard to reproduce?

I didn't realize the version in the op was a beta.  I'm on ff 88.0 and I've frequently had the issue of tab crashing when directly opening a new tab to https://boards.4chan.org/v/

**Comment by lpatrizio** [comment]
I'm on 88.0.1, can confirm I've had this happen more than a few times now.

**Comment by saxamaphone69** [comment]
I'm going to assume that most people here had this issue stop over the last 2 years.
