### ISSUE TITLE
How do I get rid of this?

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#304]
![capture](https://cloud.githubusercontent.com/assets/5096684/5919245/b55ddfbc-a67d-11e4-8cef-dbe322b2dfe5.PNG)

**Comment by ccd0** [comment]
That's not from 4chan X.  It looks like aeosynth's old standalone filter.  Check the userscripts you have active.

**Comment by jimmyrustles** [comment]
Thanks, your work is appreciated, dude.
