### ISSUE TITLE
twitframe isn't resizable in chrome 

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3049]
Chrome: Version 91.0.4472.77 (Official Build) (64-bit)
4chanx: Version 1.14.21.3

The scrollbar in the chrome window gets in the way of the resize corner icon.
Example: https://i.imgur.com/eeUhami.png
Normal Scrollbar (this message box): https://i.imgur.com/eIrf8wj.png

Error messages when expando is opened:

syndication.twitter.com/i/jot?l=%7B%22_category_%22%3A%22tfw_client_event%22%2C%22triggered_on%22%3A1622163181055%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22page%22%3A%22tweet%22%2C%22action%22%3A%22results%22%2C%22section%22%3A%22main%22%7D%2C%22context%22%3A%22horizon%22%2C%22client_version%22%3A%2282e1070%3A1619632193066%22%2C%22dnt%22%3Afalse%2C%22widget_id%22%3A%22twitter-widget-0%22%2C%22widget_origin%22%3A%22https%3A%2F%2Ftwitframe.com%2Fshow%3Furl%3Dhttps%3A%2F%2Ftwitter.com%2FNateSilver538%2Fstatus%2F1397876974434066432%22%2C%22widget_frame%22%3A%22false%22%2C%22widget_partner%22%3A%22%22%2C%22widget_site_screen_name%22%3A%22%22%2C%22widget_site_user_id%22%3A%22%22%2C%22widget_creator_screen_name%22%3A%22%22%2C%22widget_creator_user_id%22%3A%22%22%2C%22widget_iframe_version%22%3A%22c9f63d0%3A1622057477919%22%2C%22item_ids%22%3A%5B%221397876974434066432%22%5D%2C%22item_details%22%3A%7B%221397876974434066432%22%3A%7B%22item_type%22%3A0%7D%7D%7D:1 GET https://syndication.twitter.com/i/jot?l=%7B%22_category_%22%3A%22tfw_client_event%22%2C%22triggered_on%22%3A1622163181055%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22page%22%3A%22tweet%22%2C%22action%22%3A%22results%22%2C%22section%22%3A%22main%22%7D%2C%22context%22%3A%22horizon%22%2C%22client_version%22%3A%2282e1070%3A1619632193066%22%2C%22dnt%22%3Afalse%2C%22widget_id%22%3A%22twitter-widget-0%22%2C%22widget_origin%22%3A%22https%3A%2F%2Ftwitframe.com%2Fshow%3Furl%3Dhttps%3A%2F%2Ftwitter.com%2FNateSilver538%2Fstatus%2F1397876974434066432%22%2C%22widget_frame%22%3A%22false%22%2C%22widget_partner%22%3A%22%22%2C%22widget_site_screen_name%22%3A%22%22%2C%22widget_site_user_id%22%3A%22%22%2C%22widget_creator_screen_name%22%3A%22%22%2C%22widget_creator_user_id%22%3A%22%22%2C%22widget_iframe_version%22%3A%22c9f63d0%3A1622057477919%22%2C%22item_ids%22%3A%5B%221397876974434066432%22%5D%2C%22item_details%22%3A%7B%221397876974434066432%22%3A%7B%22item_type%22%3A0%7D%7D%7D net::ERR_BLOCKED_BY_CLIENT
Image (async)
(anonymous) @ embed.Tweet.2118a07d737bc8e3ebad.js:1
(anonymous) @ embed.Tweet.2118a07d737bc8e3ebad.js:1
n._log @ embed.Tweet.2118a07d737bc8e3ebad.js:1
n.log @ embed.Tweet.2118a07d737bc8e3ebad.js:1
t.scribe @ embed.Tweet.2118a07d737bc8e3ebad.js:1
(anonymous) @ embed.ondemand.Tweet.bc6daaaa574fc153adfc.js:1
(anonymous) @ embed.ondemand.Tweet.bc6daaaa574fc153adfc.js:1
Promise.then (async)
(anonymous) @ embed.ondemand.Tweet.bc6daaaa574fc153adfc.js:1
n.componentDidMount @ embed.ondemand.Tweet.bc6daaaa574fc153adfc.js:1
iu @ embed.modules.fdf619f0ab7b0d65a156.js:42
pc @ embed.modules.fdf619f0ab7b0d65a156.js:42
t.unstable_runWithPriority @ embed.modules.fdf619f0ab7b0d65a156.js:50
Wo @ embed.modules.fdf619f0ab7b0d65a156.js:42
dc @ embed.modules.fdf619f0ab7b0d65a156.js:42
Ju @ embed.modules.fdf619f0ab7b0d65a156.js:42
(anonymous) @ embed.modules.fdf619f0ab7b0d65a156.js:42
t.unstable_runWithPriority @ embed.modules.fdf619f0ab7b0d65a156.js:50
Wo @ embed.modules.fdf619f0ab7b0d65a156.js:42
qo @ embed.modules.fdf619f0ab7b0d65a156.js:42
z @ embed.modules.fdf619f0ab7b0d65a156.js:50
S.port1.onmessage @ embed.modules.fdf619f0ab7b0d65a156.js:50

syndication.twitter.com/i/jot?l=%7B%22_category_%22%3A%22tfw_client_event%22%2C%22triggered_on%22%3A1622163181224%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22page%22%3A%22tweet%22%2C%22action%22%3A%22FCP%22%2C%22component%22%3A%22performance%22%2C%22section%22%3A%22main%22%7D%2C%22context%22%3A%22horizon%22%2C%22client_version%22%3A%2282e1070%3A1619632193066%22%2C%22dnt%22%3Afalse%2C%22widget_id%22%3A%22twitter-widget-0%22%2C%22widget_origin%22%3A%22https%3A%2F%2Ftwitframe.com%2Fshow%3Furl%3Dhttps%3A%2F%2Ftwitter.com%2FNateSilver538%2Fstatus%2F1397876974434066432%22%2C%22widget_frame%22%3A%22false%22%2C%22widget_partner%22%3A%22%22%2C%22widget_site_screen_name%22%3A%22%22%2C%22widget_site_user_id%22%3A%22%22%2C%22widget_creator_screen_name%22%3A%22%22%2C%22widget_creator_user_id%22%3A%22%22%2C%22widget_iframe_version%22%3A%22c9f63d0%3A1622057477919%22%2C%22item_ids%22%3A%5B%221397876974434066432%22%5D%2C%22item_details%22%3A%7B%221397876974434066432%22%3A%7B%22item_type%22%3A0%7D%7D%2C%22duration_ms%22%3A310.39999997615814%7D:1 GET https://syndication.twitter.com/i/jot?l=%7B%22_category_%22%3A%22tfw_client_event%22%2C%22triggered_on%22%3A1622163181224%2C%22event_namespace%22%3A%7B%22client%22%3A%22tfw%22%2C%22page%22%3A%22tweet%22%2C%22action%22%3A%22FCP%22%2C%22component%22%3A%22performance%22%2C%22section%22%3A%22main%22%7D%2C%22context%22%3A%22horizon%22%2C%22client_version%22%3A%2282e1070%3A1619632193066%22%2C%22dnt%22%3Afalse%2C%22widget_id%22%3A%22twitter-widget-0%22%2C%22widget_origin%22%3A%22https%3A%2F%2Ftwitframe.com%2Fshow%3Furl%3Dhttps%3A%2F%2Ftwitter.com%2FNateSilver538%2Fstatus%2F1397876974434066432%22%2C%22widget_frame%22%3A%22false%22%2C%22widget_partner%22%3A%22%22%2C%22widget_site_screen_name%22%3A%22%22%2C%22widget_site_user_id%22%3A%22%22%2C%22widget_creator_screen_name%22%3A%22%22%2C%22widget_creator_user_id%22%3A%22%22%2C%22widget_iframe_version%22%3A%22c9f63d0%3A1622057477919%22%2C%22item_ids%22%3A%5B%221397876974434066432%22%5D%2C%22item_details%22%3A%7B%221397876974434066432%22%3A%7B%22item_type%22%3A0%7D%7D%2C%22duration_ms%22%3A310.39999997615814%7D net::ERR_BLOCKED_BY_CLIENT
Image (async)
(anonymous) @ embed.Tweet.2118a07d737bc8e3ebad.js:1
(anonymous) @ embed.Tweet.2118a07d737bc8e3ebad.js:1
n._log @ embed.Tweet.2118a07d737bc8e3ebad.js:1
n.log @ embed.Tweet.2118a07d737bc8e3ebad.js:1
t.scribe @ embed.Tweet.2118a07d737bc8e3ebad.js:1
d @ embed.ondemand.Tweet.bc6daaaa574fc153adfc.js:1
(anonymous) @ embed.vendors~ondemand.Tweet.8880cab60bc9ee2a25e9.js:1
(anonymous) @ embed.vendors~ondemand.Tweet.8880cab60bc9ee2a25e9.js:1
(anonymous) @ embed.vendors~ondemand.Tweet.8880cab60bc9ee2a25e9.js:1

**Comment by rudolphos** [comment]
Same problem. Can't resize.
![image](https://user-images.githubusercontent.com/4366810/156052845-b515b085-c1dc-4125-a856-8390b8303a1a.png)

**Comment by saxamaphone69** [comment]
Closing in favour of #3037.
