### ISSUE TITLE
Linkify not working properly.

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#305]
![capture](https://cloud.githubusercontent.com/assets/5096684/5931970/f133d4ce-a6f0-11e4-948d-08d6dfe76d5a.PNG)

**Comment by ccd0** [comment]
Working for me.  Check that you have it enabled?

**Comment by jimmyrustles** [comment]
![capture](https://cloud.githubusercontent.com/assets/5096684/5932495/61ee7ea4-a6fa-11e4-9389-8057591f20f8.PNG)

Yeah.

**Comment by ccd0** [comment]
Are there any errors in the console?  (Make sure you check the browser console (Control+Shift+J), not the Javascript console.)

Have you tried turning off other extensions temporarily to check for a conflict?

**Comment by jimmyrustles** [comment]
All good, it's seemed to fix itself somehow.
