### ISSUE TITLE
.hide-reply-button disappears under posts with #unread-line

### ISSUE THREAD

**Issue by sanitysama** [ccd0/4chan-x#3051]
![2021-05-30 21_20_32-](https://user-images.githubusercontent.com/4107753/120128092-3ba3b280-c18f-11eb-83d8-3858613c465d.png)
sometimes hide reply links don't load in after posts where the #unread-line horizontal rule is inserted. this only happens while browsing /g/ for me for some reason. my custom filters and CSS don't seem to be causing the issue. i only use release builds of firefox with ublock origin.

**Comment by saxamaphone69** [comment]
Not sure in what instance that `#unread-line` gets given `[hidden]`, because it seems that any posts beyond that aren't getting their ">>" replaced.

Any errors? If you disable your filters/CSS does it work? If you disable uBlock does it work?

**Comment by sanitysama** [comment]
there were no relevant errors in the console, and the issue persisted with uBlock and custom CSS disabled. i may have just pinpointed the problem however. i always forget i have NoScript installed. there's a default blocked entry for a "bid.glass" website, a self-serve advertising domain. i guess it tries to inject an ad under the #unread-line, which fucks up the for loop or whatever it is that 4chanx uses to replace the double dashes. it's always after the 49th post so including the OP, self-serve ads are meant to be injected after the 50th post i presume.

setting bid.glass to trusted has fixed the issue. not sure if i like that, but as long as the ads are being blocked by ublock it's fine.

**Comment by saxamaphone69** [comment]
![image](https://user-images.githubusercontent.com/877480/120283033-184b4580-c2fe-11eb-99ad-7757158f1fea.png)

I mean, I have `bid.glass` blocked and don't have the issue. You shouldn't have to allow/trust it for it to work after 50 posts. It would only add ads at the top and bottom of threads, never in between.

Try again with both uBlock and NoScript disabled, then one of each, then both. Also try a fresh profile and fresh install.

**Comment by sanitysama** [comment]
guess i have to reopen this because it's still happening, this time after 100 posts, sometimes still after 50 posts. tried what you suggested, issue still happens with ublock origin and noscript both disabled as add-ons. the issue does not happen at all on a fresh profile/install and everything works as intended. i get the same console errors from bid.glass on a fresh or old profile, so it's suggesting it's nothing to do with the bid.glass domain at all, but maybe a first-party script i'm blocking on 4chan unintentionally?
![2021-06-01 15_21_36-](https://user-images.githubusercontent.com/4107753/120379288-8e937c00-c2ed-11eb-902e-c7b5655ef6d7.png)
now i'm pointing all fingers at ublock origin. i'm subscribed to every list there is, but the only things being blocked on any page are a couple of class elements and the bid.glass domain by rules.
![2021-06-01 15_31_56-general - Discord](https://user-images.githubusercontent.com/4107753/120380057-ab7c7f00-c2ee-11eb-80e2-08149fab2d0f.png)
at this point i'm out of ideas once again. it's definitely something i have misconfigured, likely with ublock origin, and not an issue with 4chanx.

**Comment by saxamaphone69** [comment]
None of those errors show why you lose `.hide-reply-button` after every `#unread-line` - it's the fact that 4chan X does not even render the HTML after that point that is strange.

So on the fresh profile, with a fresh install of (I assume) Greasemonkey and 4chan X and *no* uBlock, it works.

Now, install uBlock on the new profile and see what happens. If it works, then something has happened to your profile/4chan X.

You could try to find this out by uninstalling 4chan X on your original profile (back up any important settings) and try installing it again.

**Comment by sanitysama** [comment]
curious as i was about trying to figure out what was causing this insanely specific issue that only occurs on one board, i couldn't find a single clue. maybe one of my unicode characters corrupted my profile during an update? i exported settings one time years ago and they corrupted within the JSON file such that it couldn't be imported back in. this no longer happens fortunately, and back then luckily i could fix them in notepad++ so i never lost my settings. for the record it's these characters specifically i use them for custom link texts to make the layout look cleaner:
`❖☼⋟◆🔎ⅈ◕
http://www.unicode-symbol.com/u/FE0E.html`
none of these are really that wild, but the one at the end is a weird one. it's the emoji-escape character, but i've had the reply link issue for much much longer than i've been using that. so who knows what happened.

nonsense rambling aside i followed your advice and reinstalled 4chanx, still don't know what happened but my issue is gone. really appreciate the help and following up, sax.

**Comment by saxamaphone69** [comment]
I can't say for certain that's the case, but maybe something to do when escaping unicode didn't go over so well and corrupted something at some point.

Glad to hear it's all working now!
