### ISSUE TITLE
/trash/ enabled name fields

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3067]
Currently only the Options post field is available as of 2021-06-14. Please add the Name field, too

**Comment by Smooshy30** [comment]
This seems to be due to !!config.forced-anon being called for /trash/.
Setting QR.forcedAnon = 0; on line 24204 in Tampermonkey shows the Name field again, as a temporary workaround.

**Comment by Smooshy30** [comment]
Found the problem
https://a.4cdn.org/boards.json
It's an issue on the end of this link here. /trash/ is still listed as _forced_anon_ when searching for that string. It's a site-wide issue and isn't fixable in the script, besides the hack I mentioned. Only /b/ remains a forced anon board as far as I'm aware.

**Comment by Smooshy30** [comment]
https://a.4cdn.org/boards.json has been updated and no longer references /trash/ as a forced anon board.
The script should now work normally without modifications.
