### ISSUE TITLE
Catalog image hover doesn't load all images fully

### ISSUE THREAD

**Issue by Icarus77** [ccd0/4chan-x#308]
I've noticed that the catalog sometime only loads a portion of the top part of some images image when using this option and putting your mouse over it.  It's been happening with me since a few updates ago, and I've done things like clearing cache, history, updating browser, and the like, but nothing's fixed it.  I'm using Firefox.

Anybody else experiencing this issue?

**Comment by hotdogman** [comment]
It's probably related to https://bugzilla.mozilla.org/show_bug.cgi?id=1083113. Try upgrading to FF36 and see if that solves your issue.
