### ISSUE TITLE
New 4chan Captcha breaks Quick Reply

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3082]
New 4chan captcha being tested causes captcha to not work
repeatedly states that the captcha is either malfunctioning, or not entered correctly.
Posting with the original form works.

**Comment by MooseZM** [comment]
i don't have the original form, any way i can get it back?

**Comment by MooseZM** [comment]
> i don't have the original form, any way i can get it back?

nvm just disable quick reply from 4chanx settings and delete cookies (atleast on opera i had to clear cookies for it to work properly)
