### ISSUE TITLE
Allow for /qa/ to be added to the navbar

### ISSUE THREAD

**Issue by PolarManne** [ccd0/4chan-x#309]
It's looking more and more likely that /qa/ is going to be a permanent board, so it'd be nice to properly add the link to it in the navbar. Currently you can have it there by using an external link that leads to boards.4chan.org/qa/, however it makes a few features unavailable when using that (such ass having the name be bolded when on that board).

**Comment by hotdogman** [comment]
/qa/ is not listed in https://a.4cdn.org/boards.json
Also note that /qa/ is not on the 4chan board list

**Comment by ccd0** [comment]
Alright, as of the newest beta (v1.9.23.2), unlisted boards should work in the header. The disadvantage is that some text you had in the header may now be interpreted as board links.  If that's a problem for anyone, let me know, and I'll see what we can do about it.
