### ISSUE TITLE
new captcha has broken the extension (chrome)

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3095]
Submitter: Ashley Blackwater
Title says it all really. Can't use the quick reply, so can't use the dump list, or load the new captcha in it. Threads also aren't saving to the thread watcher. Probably more issues, but these are all I've encountered since the 4chan update.

Godspeed~

**Comment by Serphentas** [comment]
Seconded, a new type of captcha is being deployed across boards and it simply doesn't load using 4CX.
