### ISSUE TITLE
Wemb sound volume default

### ISSUE THREAD

**Issue by InstallGentoo11** [ccd0/4chan-x#310]
It would be could if we can somehow change the default volume of webms, so they don't start always at 100%.

**Comment by ccd0** [comment]
I'm working on that and a mouse wheel interface for changing the volume.

**Comment by ccd0** [comment]
As of v1.9.22.0 (currently the beta), newly opened WebMs use the volume you selected for the last one you adjusted.  Also there is a control in the header menu.
