### ISSUE TITLE
Reply function/captcha not working from Index page

### ISSUE THREAD

**Issue by DannyDelusion** [ccd0/4chan-x#3111]
Captcha malfunctions when trying to reply to a post from index page, previously it would reply and open the thread in a new tab, however now, you need to manually open the thread and reply from within.

**Comment by daniells** [comment]
This is due to a change to 4chan's captcha API on 07/05/2021.  4channel no longer uses Google, but now uses an internally-served captcha widget.

**Comment by daniells** [comment]
Okay it's working now.  Almost certainly due to incremental site updates in the past 24 hours.

**Comment by Tororu** [comment]
Still doesn't work for me

**Comment by ccd0** [comment]
Thanks for reporting. Latest update (1.14.21.5) should fix it.

**Comment by DannyDelusion** [comment]
> 
> 
> Thanks for reporting. Latest update (1.14.21.5) should fix it.

Confirmed working now
