### ISSUE TITLE
QR window doesn't clear after posting

### ISSUE THREAD

**Issue by gitmage** [ccd0/4chan-x#3115]
After posting in any thread on both sfw and nsfw boards the persistent QR window doesn't clear. I'm on version 1.14.21.4 and using Firefox 88.0.1.

**Comment by ccd0** [comment]
What do you specifically mean by not clearing?

**Comment by gitmage** [comment]
After typing up a post, hitting the "post" button, the post gets submitted and shows up in the thread, but the quick reply window doesn't refresh/empty/clear itself. The post I just submitted stays in the quick reply window until I highlight and delete it, or until I road the page.

**Comment by synak** [comment]
I'm having the same issue, Firefox 89.0.2, 1.14.21.4.

**Comment by JippC** [comment]
Same. Basically you hit the post button, but your contents stay in the QR box, your post isn't marked as (You), and the QR box stays open

**Comment by synak** [comment]
I just manually updated to the latest (1.14.21.5) and the issues have gone away.  Thanks for your work on this!

**Comment by gitmage** [comment]
After updating to 1.14.21.5 the issue appears to be resolved. Thanks!
