### ISSUE TITLE
captcha doesnt show up

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3117]
Submitter: Allan
new 4chan captcha doesnt show up with 4chan x

**Comment by moneybags-cloud** [comment]
> Submitter: Allan
> new 4chan captcha doesnt show up with 4chan x

I have the same problem. All of my Captcha boxes are ticked off too under settings. I just get one big giant text box when I want to reply in a thread, and no Captcha shows up for me, so I can't post.

**Comment by pixelslate** [comment]
I'm having the same problem

**Comment by Kein** [comment]
Because it is not implemented
