### ISSUE TITLE
Fix yo shiet nigga

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3127]
Submitter: Nigga
Ayo, fam the captcha be sayn verification not required, then when I press submit It says to the top in da orange bar "No valid captcha". Also when I finna be tryna download a pic or one of dem WEBUMS with da download button, it says I can't download dat shit, so I gots to right click on da shit and then select save image/video as...

**Comment by RealDolos** [comment]
True, But smart people can figure out that as a workaround you can just put whatever you please into the captcha field.
