### ISSUE TITLE
Minimize webm button

### ISSUE THREAD

**Issue by evilagram** [ccd0/4chan-x#313]
There's no way to both have a control bar and minimize a webm after it has been expanded. Please add a minimize webm button once it has been expanded, or have it as a preference.

**Comment by ccd0** [comment]
Is clicking the video not working for you?  What browser are you using, and what version of it?

**Comment by evilagram** [comment]
Clicking the video works fine for me when the webm has the control bar disabled in options. This should have been a feature request but I made a mistake in filing it. I am saying having a minimize button would allow people to use the control bar while also being able to minimize the video when they are done watching it.

**Comment by ccd0** [comment]
Clicking the video should work as long as you're not in the bottom strip where the control bar typically is.  What browser are you using, and what version, and do you get any error messages in the console (Control+Shift+J) when you try to contract a video?

**Comment by evilagram** [comment]
Ah, when I click a video, it pauses it, it does not contract the video.
I'm using Firefox 34.0.5

Wait, I just went to go test this and it worked fine. I had disabled the control bar feature previously and enabled it again to test it.
