### ISSUE TITLE
This is still broken on some boards

### ISSUE THREAD

**Issue by IlskaZ** [ccd0/4chan-x#3136]
![firefox_WGtU7pNvwb](https://user-images.githubusercontent.com/35906893/125070974-9692c880-e0b0-11eb-8a88-2976a3819c63.png)
There is no captcha box in the qr at all

**Comment by texyak** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/87224407/125156797-fa5ad700-e12c-11eb-9bb2-2cd8fb2caac3.png)
same for me

**Comment by texyak** [comment]
![Screenshot (12)](https://user-images.githubusercontent.com/87224407/125156837-32621a00-e12d-11eb-9ab8-e1c0789b7cd9.png)
same for me as well
