### ISSUE TITLE
"The contract button and dragging to the left have been removed."

### ISSUE THREAD

**Issue by DAT-SQUAZZ** [ccd0/4chan-x#314]
Why? Please give this back

**Comment by ccd0** [comment]
You can click to contract now even with the controls shown.

**Comment by DAT-SQUAZZ** [comment]
I don't want to click to contract, I want to click to pause, and I want to be able to change the volume with out contracting

**Comment by ccd0** [comment]
I'll add an option to bring the old behavior back.

**Comment by DAT-SQUAZZ** [comment]
Thank you

**Comment by ccd0** [comment]
You should now get more or less the old behavior with the `Click Passthrough` option. Let me know if there are any problems.
