### ISSUE TITLE
[request] opt to remove "open all threads"

### ISSUE THREAD

**Issue by horusra** [ccd0/4chan-x#3152]
![image](https://user-images.githubusercontent.com/17074394/125822385-ea513f0c-87b1-488c-957d-a7feb9d46186.png)
please add an option to remove this button; the only time I ever use it is by accident and then without warning a billion tabs are opened.

**Comment by saxamaphone69** [comment]
`#thread-watcher #menu > a:first-child { display: none; }` in the Custom CSS section.

**Comment by horusra** [comment]
> `#thread-watcher #menu > a:first-child { display: none; }` in the Custom CSS section.

thank you!
