### ISSUE TITLE
Unable to use hyphens in filter highlighting

### ISSUE THREAD

**Issue by saxamaphone69** [ccd0/4chan-x#316]
I was using `/.webm$/i;highlight:video-file;` on Mayhem's 4chan X so that I could style the thumbnails of videos to have a play button over them to easily discern them from images.

On this version however, post containers only receive the `video` class name, as opposed to the full `video-file`. Unsure if intentional or not, but "m-muh CSS class naming conventions".

**Comment by ccd0** [comment]
Fixed in the newest beta version (v1.9.23.1).
