### ISSUE TITLE
Rendering Font Order Issue

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3160]
Submitter: what da font
Something has been changing by firefox and/or 4chan, where the bitmap fonts render in the toolbar (where I can see the posts/pages in bitmap font) and in the blotter, but the rest of the page won't follow.

**Comment by saxamaphone69** [comment]
Nothing specific to 4chan X that would cause this. Could be an OneeChan thing, or another userstyle/userscript.
