### ISSUE TITLE
[Feature Request] Hide  "X hidden threads [Show]"

### ISSUE THREAD

**Issue by B0ngert** [ccd0/4chan-x#3173]
Hiding threads is very important to improve a lot of boards quality, but constantly being shown how many threads are hidden and being only one click away from being exposed to them again isn't helpful. Sure i could just *not* click to show them but my curiosity always gets the better of me, knowing that the things i shouldn't or don't want to look at are right there at the top of the catalog. I just tell myself that I'm looking to check for false positives but i just end up looking at all the threads i specifically don't want to see instead. Call me weak willed but I'm sure I'm not the only one that has trouble with this. I would like an option to move the [Show] button ideally inside the settings menu under the filters tab. Simply by putting them somewhere were you're not exposed to them constantly you'll not be tempted to go there. Out of sight, out of mind so to say.

**Comment by saxamaphone69** [comment]
```css
#hidden-label { display: none !important; }
```
in your Advanced > Custom CSS settings.
