### ISSUE TITLE
Gallery mode on other sites

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#3188]
Submitter: Tristan
This isn't a bug I believe, but I can't get 4chan x to display in archived.moe and some other sites. Some do work and I see it on the allowed websites list, which I haven't changed. The toolbar at the top just doesn't appear. Am I missing something? Version updated to 1.14.21.3 in firefox using tampermonkey. Thankful for any response, sorry to waste time. Couldn't find anywhere else to ask.

**Comment by saxamaphone69** [comment]
#2171
