### ISSUE TITLE
Expanding images: limiting size

### ISSUE THREAD

**Issue by kilmer009** [ccd0/4chan-x#319]
This was a feature in another fork currently no longer updated.
Expanded images could be limited to such options as: Screen width, length, or both.

Really useful as people love posting massive high res images.

**Comment by hotdogman** [comment]
![jrxblb 1](https://cloud.githubusercontent.com/assets/4343306/6094408/8189fb48-aeee-11e4-99db-fba5c92dbba2.png)

**Comment by kilmer009** [comment]
Oh shit. I didn't even know about that little pull down menu. I figured all options would be in the main settings menu.  My bad!  Thanks hotdog.

**Comment by hotdogman** [comment]
>I didn't even know about that little pull down menu.

Most people don't either, don't worry about it. It's on the list of things to be added/fixed.
#186
