### ISSUE TITLE
[Feature Request] Add end of linkify processing event to 4chan X API

### ISSUE THREAD

**Issue by steponmepls** [ccd0/4chan-x#3191]
I'd like to have the API tell me when the linkify processing of links within a threads has finished so that I can safely filter invalid/dead/private links from all the others. Right now I use `4chanXInitFinished` to receive the first processing of a thread but that isn't enough time to process all the links in a page when hundreds are posted. Depending on the amount of links and performances of the client, adding an hard-coded timer isn't always enough to catch all the valid links. Having 4chan X API itself telling me it is now safe to access the DOM knowing for sure it has finished processing all the links would be a great help.

If I understand correctly by the time `4chanXInitFinished` event fires all the links in a page should be linkified but once that is done an additional check happens adding video titles to all the valid links and setting the `data-original` attribute to the linkified links. It is this particular attribute that I use right now to figure out if a link is valid or not but this attribute additions is only performed after the `4chanXInitFinished` event, therefore the need for an additional API event..

**Comment by saxamaphone69** [comment]
Have you experimented with setting up `MutationObservers` to watch for changes in the interim?
