### ISSUE TITLE
Filters suddenly not working?

### ISSUE THREAD

**Issue by blastermaster11** [ccd0/4chan-x#3199]
Issue: Filters no longer working
Program Version: 4chan X 1.14.19.3
Browser: Brave 1.30.87
Userscript Manager: Tampermonkey v4.13
No errors noted in console (other than content security policy)
Issue persists through a settings reset, a cache clearing, and a restart
Example of non-operational filter: /ntr/i;op:only;boards:4:*;

pls halp

**Comment by saxamaphone69** [comment]
Does this still occur/did you work out what went wrong? `/ntr/i;op:only;boards:4:*;` hides threads for me.
