### ISSUE TITLE
Detected JavaScript + cookies + blocked referer. Your post looks like spam this way, so either enable referers or disable JavaScript and cookies

### ISSUE THREAD

**Issue by qbb** [ccd0/4chan-x#321]
Can 4chan X somehow circumvent this?
I can't post otherwise.

**Comment by ccd0** [comment]
You can use an extension like https://addons.mozilla.org/en-US/firefox/addon/refcontrol/ to enable/forge referers on a per-site basis.

**Comment by ccd0** [comment]
I personally have network.http.referer.XOriginPolicy set to 1 in about:config which means the referer is sent only when the base domains match (e.g. from boards.4chan.org to sys.4chan.org, but not from boards.4chan.org to www.youtube.com).

**Comment by qbb** [comment]
Just changed to 1 too instead of 0.
Too bad 4chan is getting worse and worse and not even scripts can fix it anymore.
