### ISSUE TITLE
Cannot preview images from Catalog view on certain boards.

### ISSUE THREAD

**Issue by Commander-Snek** [ccd0/4chan-x#3211]
As the title states, I cannot preview images from the Catalog view on certain boards. This happened two days ago, completely on its own and out of nowhere, and no matter what settings I change, I cannot seem to revert it to the way it was before.
For example, in the attached pic, I was hovering my mouse over the thread/picture on the left, and all I got was a box saying when the thread was created and when the last post was.

![Screenshot 2021-10-19 233323](https://user-images.githubusercontent.com/92829718/138000604-71f03a5c-1544-49df-af0f-15b7aa3c86ca.png)

Any and all help would be very appreciated.

**Comment by saxamaphone69** [comment]
This is the native catalogue, not the 4chan X one. Check your URLs end in `https://boards.4channel.org/board/#catalog`, not `https://boards.4channel.org/board/catalog`.
