### ISSUE TITLE
webm expansion breaking quick reply

### ISSUE THREAD

**Issue by cimris** [ccd0/4chan-x#3225]
When viewing a thread the quick reply will work as normal until expanding a webm. After doing so, quick reply (when clicking on post number) will cease to work until either page reload or opening the regular post reply form.

Issues occurs on both Firefox Developer Edition (95.0b12) and Firefox (94.0.2). Issues does not occur on native Chrome extension with exact same settings. No other extension running. No errors in the console, and this was with a fresh profile.

4chan X v.1.14.21.7
Violentmonkey v.2.13.0

**Comment by ryanrms** [comment]
I can confirm this issue is happening, with Firefox v95.0 (flatpak) and Violentmonkey v2.13.0

I became aware of it from someone screaming about it in a Firefox thread, thanks to them I guess.

**Comment by saxamaphone69** [comment]
Seems to have fixed itself, this is on Firefox 113 with Violentmonkey 2.14.0
https://github.com/ccd0/4chan-x/assets/877480/542ff1f8-a282-4f15-a965-225686a8330f
