### ISSUE TITLE
Import settings fails systematically

### ISSUE THREAD

**Issue by Janaue** [ccd0/4chan-x#323]
Hello,

I have firefox 36 b8 on the latest greasemonkey and a stock firefox profile with Release 4chan X v1.10.0.2.
When I start with the stock settings and save them, to import them just after, I get an error in red
                       Import failed due to an error.
here is the CP for my default settings http://pastebin.com/F4TS725y modulo "External Catalog": false, to test the importation of the settings.

the size of my saved default settings is 9KB

**Comment by Janaue** [comment]
This what I have in the console  after an attempt to import the settings
"$.clear@file:///C:/Documents%20and%20Settings/aaa/My%20Documents/FirefoxPortable/Data/profile/gm_scripts/4chan_X-1/4chan-X-noupdate.user.js:957:17
Settings.loadSettings@file:///C:/Documents%20and%20Settings/aaa/My%20Documents/FirefoxPortable/Data/profile/gm_scripts/4chan_X-1/4chan-X-noupdate.user.js:15526:1
Settings.onImport/reader.onload@file:///C:/Documents%20and%20Settings/aaa/My%20Documents/FirefoxPortable/Data/profile/gm_scripts/4chan_X-1/4chan-X-noupdate.user.js:15414:1

**Comment by ccd0** [comment]
I'll see what I can do to work around the problem, but in the meantime you can try the [nightly version](https://arantius.com/misc/gm-nightly/) of Greasemonkey.

**Comment by Janaue** [comment]
I precise that the '4chan_X-1' comes from  the rewritting from GM because I have the original 4 chan X module (but disabled). The original module takes the name 4chan_x in my GM script folder.

**Comment by Janaue** [comment]
I tried the night version of GM on the same stock settings for firefox and 4 chan X v1.10.0.3  : the importation woks perfectly, either with my personal settings or the default ones.

**Comment by Janaue** [comment]
And the importation works well with my personal profile of firefox with the night version of GM.

**Comment by ccd0** [comment]
Changes in Firefox 35 apparently broke Greasemonkey's `GM_listValues` function:
https://github.com/greasemonkey/greasemonkey/issues/2033

I've added a workaround for the stable version of Greasemonkey (and older versions).

**Comment by Janaue** [comment]
thank you !
