### ISSUE TITLE
4chan x work like shit om firefox

### ISSUE THREAD

**Issue by wrigsted** [ccd0/4chan-x#3233]
you get this shit again:
Error fetching archive data from
https://mayhemydg.github.io/archives.json/archives.json
Connection Error

or something like it. No fun!

**Comment by saxamaphone69** [comment]
Are you on the most up to date version of 4chan X?

![image](https://user-images.githubusercontent.com/877480/150908207-543f2054-1008-44e3-b5c7-69b1dfa4482a.png)

Otherwise, go to Settings > Advanced and in the Archive section type in `https://4chenz.github.io/archives.json/archives.json`.

**Comment by wrigsted** [comment]
Thanks, that help! And sorry for the tone in my first tread, I had really tried everything I could think of to also change the archive address, but obviously not to the right one, as well as read various issue reports.
I may not be the sharpest knife in the drawer, but I can usually figure these things out. Maybe make a sticky for us not to smart firefox users?
And again, thank you so much for the help Johnny and in such a good tone after the way I presented my problem!

**Comment by wrigsted** [comment]
One more thing, why don't Captha work on /pol/ and other NSFW pages in Firefox's  4chan x anymore. No problems in Chrome with 4chan x and NSFW pages. Something I missed again?

**Comment by saxamaphone69** [comment]
Do you have an adblocker like uBlock Origin? Or certain scripts on your whitelist? With the Captcha now, it requires `core.js` to run, and so I know I was caught out by not having it disabled for both `4chan` AND `4channel` domains.

With a 4chan X update, it should have replaced the old archive link with the new one, though it appears it hasn't. I'd check you're running `v1.14.21.7`.
