### ISSUE TITLE
[Feature Request] Randomize Filename toggle on Quick Reply

### ISSUE THREAD

**Issue by Red-AM** [ccd0/4chan-x#3245]
Feature:
It'd go where the "S" for spoiler toggle would be when you select an image to upload. Checking it would randomize the filename and unchecking it would return it to the original filename.

Reason:
I usually keep the Randomize Filename option in the settings checked but there are many occasions when I want to use the original filename (ex. soundposts). It's inconvenient having to copy the filename and paste it in each time. I think a simple toggle in the quick reply window would be a big improvement to QoL.

**Comment by gir489** [comment]
Soundposters get the rope.

**Comment by vt-idiot** [comment]
There's already a PR #2927 and many many many similar requests: #473, #1409, #1574, #1573, #1848, #2200, #2660, #2890

You're not alone.
