### ISSUE TITLE
Captcha have dissapeared

### ISSUE THREAD

**Issue by anonimnaya** [ccd0/4chan-x#3250]
Hello! For some reason I don't have Captcha window when I browse 4chan. I can't post because of that. Also for some reason 4chan-x can't connect to something. I use Firefox browser. I'll try "reinstalling" it again through violentmonkey and will update if it gets fixed. Also I do not have any other extensions.

**Comment by anonimnaya** [comment]
Yep, the problem with 
Error fetching archive data from
https://mayhemydg.github.io/archives.json/archives.json
Connection Error
still same.

**Comment by gir489returns** [comment]
I don't have this issue. Are you blocking their Captcha API server? Can you post the developer logs? I don't know furfox works, but in Chrome there's a network activity log you can monitor requests. My bet is the CAPTCHA request is being rejected by your gateway(router).

**Comment by saxamaphone69** [comment]
Double check you're not blocking the 4chan JS, `*//s.4cdn.org/js/core.min.*.js`

As for the archive, that link is now dead, please go to Settings > Advanced and for the archive use `https://4chenz.github.io/archives.json/archives.json`.

**Comment by FuckOBS** [comment]
> Double check you're not blocking the 4chan JS, `*//s.4cdn.org/js/core.min.*.js`
> 
> As for the archive, that link is now dead, please go to Settings > Advanced and for the archive use `https://4chenz.github.io/archives.json/archives.json`.

Thanks, your advice helped me regain my caption
