### ISSUE TITLE
How to click on replies like regular 4chan?

### ISSUE THREAD

**Issue by filminghub** [ccd0/4chan-x#3251]
With 4chanX when you click on the reply it embed the reply on on top of the post, how do you change it so that it takes you to where the replies is instead like the regular version?

**Comment by jumper323213** [comment]
4chanX settings (wrench at the top right OR Alt+O) > scroll down to "Quote Links" > uncheck "Quote Inlining".

**Comment by filminghub** [comment]
> 4chanX settings (wrench at the top right OR Alt+O) > scroll down to "Quote Links" > uncheck "Quote Inlining".

Thank you so much. Another thing, can you also change the update button to work like before? Now when you click update thread, there's no response only a small "javscript;:" pop on the bottom left corner on the screen.

**Comment by jumper323213** [comment]
Not sure if I understand what you mean. 4chanX has thread auto update on by default and it updates every 5 seconds, the number of unread posts is displayed in the browser's tab name: `(number of unread posts) /board name/ - Thread Title`
If you're asking if clicking update works, the answer is yes.
If you want to change how fast it auto updates: 4chanX settings > Advanced > Scroll to "Thread Updater" and change the interval.
If you want to disable thread auto update: Open any thread > Click the the small arrow at the top right next to the wrench > Updater > Uncheck "Auto Update".
