### ISSUE TITLE
(Feature) saved catalog search

### ISSUE THREAD

**Issue by clawwwie** [ccd0/4chan-x#3253]
4chan natively keeps whatever you search in the catalog and has it input when you return to the catalog from a thread, and you then get to clear it to see all threads. I find this useful for jumping to the next version of a general or ongoing topic, but I can't find an option for that in 4chan X, if it exists.
I'm using the latest release (v1.14.21.7) if that matters at all

**Comment by jumper323213** [comment]
Use highlight filters
Example: '/hello/i;boards:pol;highlight'
This will pin threads with the word "hello" at the top of the catalog on /pol/.

**Comment by saxamaphone69** [comment]
Another thing you can do is add a custom board link, `external-text:"/dg/","//boards.4channel.org/vg/#s=destiny"` and whenever you click it, will prefill the catalogue search field with that search.
