### ISSUE TITLE
voca.ro links have embed option but it's broken

### ISSUE THREAD

**Issue by Hamahaki** [ccd0/4chan-x#3255]
The embed button opens up a menu but the play button is greyed out and timestamp is 0:00 / 0:00
![image](https://user-images.githubusercontent.com/49539004/162840229-89574e88-e81d-403d-9645-34093de95cbc.png)

**Comment by Hamahaki** [comment]
> Unfortunately, it looks like ccd0 is no longer active, as this has been the case for a while now (with a fix ready: #3235) but if you really want, you can change the code yourself.

I looked at the source code of 4chanX on tampermonkey and the vocaroo embed code looks different from Pinkcat's code in the fix

**Comment by Jorge9811** [comment]
> That's because the PR is written in `.coffee`, and the userscript is in `.js`. It's converted during the build process.
> 
> I _think_ this is what the conversion would be. The `a.dataset...` in `el.src` might not need the wrapped brackets, I haven't tested it.
> 
> ```js
> key: 'Vocaroo',
>         regExp: /^\w+:\/\/(?:(?:www\.|old\.)?vocaroo\.com|voca\.ro)\/((?:i\/)?\w+)/,
>         style: '',
>         el: function(a) {
>           var el;
>           el = $.el('iframe');
>           el.width = 300;
>           el.height = 60;
>           el.setAtttribute("frameborder", 0);
>           el.src = "https://vocaroo.com/embed/" + (a.dataset.uid.replace(/^i\//, '')) + "?autoplay=0";
>           return el;
> ```

doesnt work the embed button doesnt do anything now the bar with the audio controls neveer appears

**Comment by RikisX** [comment]
Fixed:
```JS
key: 'Vocaroo',
        regExp: /^\w+:\/\/(?:(?:www\.|old\.)?vocaroo\.com|voca\.ro)\/((?:i\/)?\w+)/,
        style: '',
        el: function(a) {
          var el;
          el = $.el('iframe');
          el.width = 300;
          el.height = 60;
          el.setAttribute("frameborder", 0);
          el.src = "https://vocaroo.com/embed/" + (a.dataset.uid.replace(/^i\//, '')) + "?autoplay=0";
          return el;
```

**Comment by Zipdox** [comment]
If you're super autistic and don't want an embed:
```javascript
key: 'Vocaroo',
regExp: /^\w+:\/\/(?:(?:www\.|old\.)?vocaroo\.com|voca\.ro)\/((?:i\/)?\w+)/,
style: '',
el: function(a) {
  var el;
  el = $.el('audio', {
    controls: true,
    preload: 'auto'
  });
  let audioSrc = /^i\//.test(a.dataset.uid) ? "https://old.vocaroo.com/media_command.php?media=" + (a.dataset.uid.replace('i/', '')) + "&command=download_mp3" : "https://media1.vocaroo.com/mp3/" + a.dataset.uid;
  (typeof GM_xmlhttpRequest != 'undefined' ? GM_xmlhttpRequest : (GM ? GM.xmlHttpRequest : GM_xmlhttpRequest))({
    method: "GET",
    url: audioSrc,
    responseType: 'blob',
    headers: {
      'Referer': 'https://vocaroo.com/'
    },
    onload: function(response) {
      el.src = URL.createObjectURL(response.response);
    }
  });
  return el;
}
```
