### ISSUE TITLE
Youtube Embed

### ISSUE THREAD

**Issue by supersaiyandoyle** [ccd0/4chan-x#3265]
Don't know if it's just me, but I think youtube imbeds are broken.
It'll imbed the video and load the name etc, but clicking play causes it to load for about 10 seconds before giving a "An error occurred. Please try again later" error, forcing me to click on the title of the video to go to youtube to watch it.

**Comment by saxamaphone69** [comment]
Does this issue still occur or did the problem go away?

**Comment by supersaiyandoyle** [comment]
> Does this issue still occur or did the problem go away?

This question is from a year ago and I've changed browsers since then.
