### ISSUE TITLE
Unread Count is off and webm pausing when it shouldn't

### ISSUE THREAD

**Issue by leveechan** [ccd0/4chan-x#327]
When I expand a webm it pauses if I scroll even a little, as if it thinks the entire webm is off screen, but it does play when I click again. 
The unread count does not change to zero when I scroll all the way down, it only updates the number of posts read when they reach the top of the browser, but if I do shorten the browser window all the way and scroll all the way down it does veiw all as read. see pictures
![more whack shit](https://cloud.githubusercontent.com/assets/2664770/6243482/6a95c208-b710-11e4-8140-5bc3db5b6c99.png)
![shits whack yo](https://cloud.githubusercontent.com/assets/2664770/6243448/79a7d282-b70f-11e4-9ffb-e124ad6ff8e1.png)

I honestly think the same bug is related to both issues.
This doesn't happen with 4chan's native extension and all other extensions are disabled right now

I am using 4chan 1.10.0.5 (but the problems have been going on for weeks and I'm just bothering to report it now) and vanilla chrome which is updated to Version "40.0.2214.111 m" as of today, so I can't get the latest 4chan x version from the chrome store

http://pastebin.com/cb1BanBx

I know the issue isn't urgent but it's just annoying on several levels

**Comment by ccd0** [comment]
Thanks, should be fixed as of 1.10.0.6.

**Comment by leveechan** [comment]
I love you

thanks
