### ISSUE TITLE
[Feature Request] Have a way to tell which filter was matched on hidden posts.

### ISSUE THREAD

**Issue by Inkerlink** [ccd0/4chan-x#3272]
It would be very handy to have a way to tell which filter was matched when looking at my filtered posts, whether it's visually or otherwise. It would help in order to make it easier when fine tuning personal filters. Right now there is no way to tell 'why' a post was filtered. Maybe have it so any matching terms etc are highlighted, or just list matched filters below the hidden post or something.

**Comment by saxamaphone69** [comment]
#126 Long standing issue, was present in Mayhem's version but never made it over.
