### ISSUE TITLE
Feature Request: Button to randomize filename on the fly in the quik reply box

### ISSUE THREAD

**Issue by Jorge9811** [ccd0/4chan-x#3276]
having to toggle on and off the global setting for randomize filename is annoying
it would be faster if there was a toggle to do it on the reply box in a case bycse basis as an option

**Comment by vt-idiot** [comment]
There's already a PR #2927 and many many many similar requests: #473, #1409, #1574, #1573, #1848, #2200, #2660, #2890

You're not alone.
