### ISSUE TITLE
Quick Reply Doesn't Work on Firefox

### ISSUE THREAD

**Issue by Mavrickindigo** [ccd0/4chan-x#3277]
4chan.org boards don't work with 4chan x. Quick Reply windows do not have a space for captcha at all. 4channel.org works perfectly fine.

**Comment by OPROSVOs** [comment]
Also works on my end on FF91esr with 4chanX 1.14.22.1
Any script blocker / adblocker? Maybe check your console for errors.

**Comment by uNderdog101** [comment]
Also does not work for me with Firefox 103.0.2 and 4chanX 1.14.22.1.  Deactivating Ublock Origin (the only thing I have that alter the page) does nothing.

**Comment by gpfn** [comment]
Firefox (firefox-bin) 104.0.2 on Gentoo, still ocurring.  Maybe there's some minor difference between the 4channel and 4chan sites somewhere?
