### ISSUE TITLE
Oekaki Replay feature now working unless 4chan X is disabled

### ISSUE THREAD

**Issue by kensolano** [ccd0/4chan-x#3280]
Oekaki (/i/ board) has a replay feature that allows to replay your drawing in Tegaki. This doesn't work when 4chan X is enabled. To make it work properly I had to disable 4chan X

**Comment by saxamaphone69** [comment]
Works for me on Firefox and Chrome, Greasemonkey and Tampermonkey, with uBlock enabled. You should check if you have anything else blocking the `tegaki.js` file.
