### ISSUE TITLE
4chan not loading on Firefox

### ISSUE THREAD

**Issue by AgentGuig** [ccd0/4chan-x#3294]
its forever refreshing the index. I tried importing the settings I use on chroim and that didn't work.
I've tried resetting the settings and disabling my adblocker, Ublock Origin
![Screenshot 2022-08-31 171213](https://user-images.githubusercontent.com/112587791/187787693-0c822a51-3aaa-4178-a8d9-baa1edf8bdd0.png)
![Screenshot 2022-08-31 171239](https://user-images.githubusercontent.com/112587791/187787703-a50e5a1b-6b66-4cd0-ada1-40aba067b588.png)

**Comment by saxamaphone69** [comment]
Does this still occur?
