### ISSUE TITLE
Replies and threads collapsed by default

### ISSUE THREAD

**Issue by rando09** [ccd0/4chan-x#3299]
![image](https://user-images.githubusercontent.com/114412384/192286110-a1743924-055d-4d77-b413-149a70b969bf.png)

So, for some reason, despite changing nothing and doing nothing, all replies are by default collapsed like this and i have to open them manually one by one. Threads when I load up a board are also completely missing, but there's a show all button that opens them. However, no show all button for these collapsed replies. I didn't do anything in my settings, and checking them I see no option that would cause this. Please help, thanks

**Comment by saxamaphone69** [comment]
Check your filters, probably something going rogue.

**Comment by asdf8dfafjk** [comment]
On that note, is there a way to "show all replies" without clicking them one by one ...
