### ISSUE TITLE
noscript captcha reloads periodically even when tab is backgrounded.

### ISSUE THREAD

**Issue by the8472** [ccd0/4chan-x#330]
I think it would make sense to only refresh the captcha when the tab [is visible](https://developer.mozilla.org/en-US/docs/Web/Guide/User_experience/Using_the_Page_Visibility_API).

With several 4chan tabs open it could mean loading a handful of captchas every minute, which might trigger some of google's heuristics to present harsher captchas?

**Comment by ccd0** [comment]
Should be fixed as of v1.10.2.0 (the current beta).

**Comment by the8472** [comment]
Looks good, getting easier captchas too.
