### ISSUE TITLE
[Feature Request] Button in "Quick Reply" for Randomizing Filename

### ISSUE THREAD

**Issue by mywifechino** [ccd0/4chan-x#3302]
Hello. Sometimes I find myself wanting specific files have their names randomized but it's not always the case, therefore I have to constantly enter the menu and check/uncheck the randomizing filename option. It would be great if a shortcut could be added to the "quick reply" mode. Thank you.

![image](https://user-images.githubusercontent.com/78307321/193477234-36f70b12-4849-4228-aa8b-82dc0b0193d9.png)

**Comment by Jorge9811** [comment]
#3276
