### ISSUE TITLE
[Feature Request] Option to always display full image filename

### ISSUE THREAD

**Issue by KonaKona7** [ccd0/4chan-x#3305]
It would make readability in certain threads easier. It would also make saving the image with its original name easier as that download button (after the filename) would remain in a fixed position, and not change every time you hover over part of the filename.

The functionality already exists, this is just to make it always on rather than only on hover.

**Comment by saxamaphone69** [comment]
Change it yourself in the Settings:

![image](https://user-images.githubusercontent.com/877480/196861968-b54046a2-4b9d-4ef7-8033-5c14f40582f0.png)

**Comment by KonaKona7** [comment]
Thanks for the quick reply, works great!
