### ISSUE TITLE
site support

### ISSUE THREAD

**Issue by trollogyadherent** [ccd0/4chan-x#3306]
Hello, would it be possible to get support for soyjak.party and frenschan.org?

**Comment by brsk93** [comment]
> Hello, would it be possible to get support for [soyjak.party](http://soyjak.party) and [frenschan.org](http://frenschan.org)?

They already work, you just have to manually add their url to your `@include` list in the userscript, either by manually editing the code, or by going into Violent/Grease/whatever monkey addon you use, looking for the script settings, and adding the urls there.

**Comment by trollogyadherent** [comment]
ok, thanks
