### ISSUE TITLE
Tabbing from the comment box to the captcha brings you to the top of the page

### ISSUE THREAD

**Issue by MisakaImoutoWaifu** [ccd0/4chan-x#331]
I'm on OS X 10.10 using Chromium 38 and the latest 4chan X.

-Try to tab from comment box to captcha

What should happen
-You go to the captcha

What happens
-You jump to the top of the page to some invisible element
-You need to press tab again to get to the captcha

**Comment by ccd0** [comment]
Can you post your settings?  (Use the "Export Settings" link in the settings panel, and post its contents on Pastebin or a similar site.)

**Comment by MisakaImoutoWaifu** [comment]
http://pastebin.com/6WY69BT8

There you are.

**Comment by MisakaImoutoWaifu** [comment]
As a note I reset 4chan X and the bug persists.
It doesn't seem to happen on Firefox.

**Comment by ccd0** [comment]
Has this happening for a while or did it just start happening?
I'm seeing it now, but I haven't seen this before today.
Might have been a change on Google's end.

**Comment by MisakaImoutoWaifu** [comment]
It only started about an hour or two ago at most. It was working fine before that.

**Comment by MisakaImoutoWaifu** [comment]
I've also noticed that in long threads it doesn't jump to the top, it jumps up about 50% of the page.

**Comment by ccd0** [comment]
For some reason Google is putting an element at (-10000px, -10000px) that just says "undefined" and is the first thing you focus on when you tab into the captcha frame.  I have no idea why they're doing this (probably just a strange bug), but I can work around it.

**Comment by ccd0** [comment]
Alright, the newest version (v1.10.1.12) should fix it.

**Comment by MisakaImoutoWaifu** [comment]
Have to click tab twice, but I don't find that to be an issue personally. Works fine other than that.
Thanks for the quick fix.
