### ISSUE TITLE
Is there a way to see the bump limit and how close a thread is to it?

### ISSUE THREAD

**Issue by Forbiddentwo** [ccd0/4chan-x#3315]
Apparently there should be...?

Ditto for seeing the # of unique IPs in a thread.

**Comment by gir489returns** [comment]
![image](https://user-images.githubusercontent.com/100792176/206358618-74fd6fb8-71e1-40cc-96cb-f8815e1b36d6.png)

In the top right corner, you have Posts / Files / IPs / Page. When the Posts number turns red, that means the thread is at the bump limit.
