### ISSUE TITLE
bolded text not applied in 4chanX catalog

### ISSUE THREAD

**Issue by hotdogman** [ccd0/4chan-x#332]
![ptbtme 1](https://cloud.githubusercontent.com/assets/4343306/6313199/ab6385b2-b964-11e4-8802-666d89a8a4ec.png)
![nzmjrp 1](https://cloud.githubusercontent.com/assets/4343306/6313204/c83e2bb0-b964-11e4-84d6-2cdbc28e7990.png)

**Comment by ccd0** [comment]
It's deliberate to keep rolls on /tg/ from blending in with the subject.  Unfortunately there doesn't seem to be a general way to distinguish rolls from stuff like this, but I could make it apply only on /tg/.

**Comment by ccd0** [comment]
> I could make it apply only on /tg/.

Done as of v1.10.3.0.
