### ISSUE TITLE
No more popups for (you)s since yesterday or the day before

### ISSUE THREAD

**Issue by Forbiddentwo** [ccd0/4chan-x#3320]
I originally used the Google Chrome version of 4chan-x and I would get a little popup in the bottom right corner whenever I got a (you).  That stopped a few days ago for no apparent reason.

I ended up switching to the tampermonkey script version, which seems to have some additional features, which is nice... but still no popups for (you)s.

???

**Comment by saxamaphone69** [comment]
If you were using [the Chrome version](https://chrome.google.com/webstore/detail/4chan-x/ohnjgmpcibpbafdlkimncjhflgedgpam) then that version is the exact same as the userscript version - no "additional features".

Ensure you have `Desktop Notifications` enabled and try again.
![image](https://user-images.githubusercontent.com/877480/209583730-7e98608e-f630-419c-ba1a-7e759d83e1f3.png)

**Comment by Forbiddentwo** [comment]
FWIW desktop notifications is checked.
