### ISSUE TITLE
[Feature Request] Highlight the threads where the OP has put a Gif or a Webm

### ISSUE THREAD

**Issue by eXo-Necro** [ccd0/4chan-x#3335]
I made this code: 
```
document.addEventListener("DOMContentLoaded", function() {

    const catalogThreads = document.getElementsByClassName('catalog-thread');
    for (let thread of catalogThreads) {
        const webms = thread.querySelectorAll('a[href$=".gif"]');
        if (webms.length > 0) {
            const catalogStats = thread.querySelector('.catalog-stats');
            catalogStats.style.backgroundColor = 'pink';
            catalogStats.style.color = '#ff3546';
        }
    }

})
```

but the change does not apply, you know why?

**Comment by saxamaphone69** [comment]
Option 1 is to add a filter to Filter > Filename:
`/.webm$/;highlight:file--video;top:no;`
`/.gif$/;highlight:file--gif;top:no;`

And then in your CSS `.file--video {}`.

Option 2 is to use the `:has()` selector in Custom CSS:
`.post:has(a[href$=".gif"]) {}` or whichever element you want to focus on.

**Comment by eXo-Necro** [comment]
Awesome! the first option works great.
I'm not at all familiar with this way of doing things, so there's one last thing I would like is that it doesn't apply when you're in a thread, only when you're on a page like boards.4chan.org/gif/
How can I do this?

**Comment by saxamaphone69** [comment]
`.is_index .file--video {}` would only apply on the index.

**Comment by eXo-Necro** [comment]
that's perfect, that's exactly what I wanted the script to do.
