### ISSUE TITLE
Can't load captcha

### ISSUE THREAD

**Issue by miu135** [ccd0/4chan-x#3343]
What do?

**Comment by saxamaphone69** [comment]
What browser?
What version?
Userscript or extension?
What version of 4chan X?
Have you tried posting without 4chan X?
Have you tried disabling all other extensions?

**Comment by miu135** [comment]
Browser: Chrome
Version: 110.0.5481.178
Extensions: adblock, pop-up blocker, minerblock, and Windscribe.
4chan X ver: 1.14.22.4
Can't post without it but that's normal. Also disabling all doesn't seem to do anything.
It also seems like the site's down currently.

**Comment by saxamaphone69** [comment]
I'm sure once it's back up, things will go back to normal.

**Comment by weefunker** [comment]
Same issue

**Comment by Zabrios** [comment]
Same here, Chrome + ublock origin + sponsorblock + ghostery + popup blocker
