### ISSUE TITLE
Thread Watcher always seems to be open upon switching boards 

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#3354]
The Thread Watcher always seems to be open whenever I switch boards.

**Comment by saxamaphone69** [comment]
![image](https://user-images.githubusercontent.com/877480/233919955-8edd186b-eade-4a67-bc8b-8c83dfcdbb4b.png)

You might have `Persistent Thread Watcher` enabled. Check that and report back.

**Comment by jimmyrustles** [comment]
Yeah, that was the problem, thanks.
