### ISSUE TITLE
Highlighting text in a post and then clicking the post number no longer quotes the highlighted text

### ISSUE THREAD

**Issue by anon90000** [ccd0/4chan-x#3355]
This was an extremely useful future that no longer works. 

![img](https://user-images.githubusercontent.com/131615242/233859997-23ac6740-ad74-4f0c-9c74-a3c38f5b330e.jpg)

**Comment by saxamaphone69** [comment]
Appears to be working here.

Browser and browser version? Extension or userscript/userscript manager? 4chan X version? Does it happen with your other extensions (like ad blocking) disabled? Fresh profile/fresh install of 4chan X?

![copytoreply](https://user-images.githubusercontent.com/877480/233919426-4a9f25a8-b438-4e51-b2e4-611bcaf1005b.gif)

**Comment by anon90000** [comment]
I went and tested it with all other extensions disabled and it worked. The culprit was an addon that adds highlighting to webpages that disable it. I don't know why I didn't take troubleshooting steps before posting this. My bad.
