### ISSUE TITLE
Ignore keyboard shortcuts when editing text

### ISSUE THREAD

**Issue by mgrabovsky** [ccd0/4chan-x#337]
When editing a text field on a page where shortcuts are enabled, the plugin overrides the default action.

For instance, editing the search input on the index/catalog page, pressing Ctrl-X would normally cut a chunk of selected text. While on this page, by default, it causes the sorting algorithm to cycle. As another example, when editing filters in the "Settings" window while being on the same page, the same happens.

This is kinda counter-productive.

**Comment by ccd0** [comment]
You can set it to Alt+X or anything you like in the keybinds section of the settings panel.  Alt+X is the default for this, although many people will have imported the Control+X setting from Mayhem's script.  Sometimes keybinds are wanted when editing text, so it's not a good idea to disable them entirely when doing so.  And keybinds without a modifier are disabled in text fields.

**Comment by mgrabovsky** [comment]
OK, consider this WONTFIX.

I only use two shortcuts, both of which lack modifiers, so it came as a surprise at first that Ctrl-X was usurped. You're probably right that one might want to use shortcuts while editing, although I've never felt this need myself.
