### ISSUE TITLE
Getting archive issues

### ISSUE THREAD

**Issue by devicemodder** [ccd0/4chan-x#3372]
Gettign issues connecting to archive.json

>Error fetching archive data from
>https://mayhemydg.github.io/archives.json/archives.json
>Connection Error

what's a working archive.json link? or can i use a locally saved one and put the filepath to my drive?

**Comment by saxamaphone69** [comment]
You might be using an old version of 4chan X, try updating first.

If not, head over to the `Advanced` section and make sure it says `https://4chenz.github.io/archives.json/archives.json` instead.

![image](https://github.com/ccd0/4chan-x/assets/877480/26591122-14f9-49f9-950f-c6e6da8d547b)
