### ISSUE TITLE
No longer functional as of today

### ISSUE THREAD

**Issue by Cerzel** [ccd0/4chan-x#3377]
Yeah. Was working fine yesterday but some backend update must've broken it. All functionality is completely busted. Tried with Violentmonkey in Waterfox and Tampermonkey in Opera. I haven't updated the browser; the same session has previously loaded tabs still working fine but new ones are broken.

**Comment by saxamaphone69** [comment]
>some backend update

4chan X hasn't been updated in a few months now, so not sure what you mean. What operating system; did that update recently? Have you got anything else running that might conflict? Disable those first and try again. Does 4chan work without 4chan X enabled?

When you say "all functionality is completely busted" - what does this mean? Do you still see the header? The QR?

**Comment by Cerzel** [comment]
That's weird, it suddenly broke overnight in the browser; I hadn't updated anything which is why I assumed it had been a backend update. Just did a restart of the computer and now it's working properly again.
Sorry for the trouble.
