### ISSUE TITLE
I want to filter OPs that contain only a period/fullstop

### ISSUE THREAD

**Issue by TikTikKobold** [ccd0/4chan-x#3381]
I want to filter those threads where the OP is just a picture with a period in the text field. How exactly can that be done? Any attempts I've tried filtered basically everything.

**Comment by saxamaphone69** [comment]
![image](https://github.com/ccd0/4chan-x/assets/877480/dbf920ff-5b48-4c24-8cb5-4b21214641f2)
`/^\.$/;op:only`
