### ISSUE TITLE
Captchas working on blue boards but not on green (nsfw) boards

### ISSUE THREAD

**Issue by Saffronette** [ccd0/4chan-x#3385]
Hello, I apologize in advance if this was brought up as an issue before, but I've been having some issues trying to load the captcha on green boards. On the blue boards it works fine, but they don't load at all on the green boards. I was wondering if there was a setting I missed to allow the captchas to work.

**Comment by saxamaphone69** [comment]
Green NSFW boards?

I'd say double check your adblocker isn't blocking `core.js`.

**Comment by Saffronette** [comment]
How do I check to see if it's blocking it or not? Where do I type it in? I'm using ublock origin by the way.

**Comment by saxamaphone69** [comment]
I believe if you open your browsers console, it will show a list of blocked resources.

Alternatively, disable all other extensions and see if you get the captcha.

**Comment by Saffronette** [comment]
It seems to be blocking it on chrome even when I turn off ublock. I originally installed 4chanX to even use the captcha at all. Prior to this it was working fine, unless a recent update messed something up. Is there a way to unblock the resources?

**Comment by saxamaphone69** [comment]
Use the Guest profile/make a new profile (that way nothing else is installed, including 4chan X), and navigate to 4chan and see if the captcha loads. A screenshot of your browser console or the network tab might help.

**Comment by Saffronette** [comment]
When I did sign in as a guest on chrome, the captcha did work on a green board. This is the error message I got when I check the console tab. I apologize if I'm asking a lot of questions, a lot of this is very confusing to me since I've never had this issue before.
![chrome_PrrQWrx3FS](https://github.com/ccd0/4chan-x/assets/139253941/01006102-6cef-4037-9a94-0e09f7574d0b)

**Comment by saxamaphone69** [comment]
Open your 4chan X Settings, click on Advanced, scroll down to `Javascript Whitelist`. I personally have this in the text field:
```
http://s.4cdn.org
https://s.4cdn.org
http://www.google.com
https://www.google.com
https://www.gstatic.com
http://cdn.mathjax.org
https://cdn.mathjax.org
https://cdnjs.cloudflare.com
https://hcaptcha.com
https://*.hcaptcha.com
'self'
'unsafe-inline'
'unsafe-eval'
```

Check yours to see.

**Comment by Saffronette** [comment]
I did copy and paste that into the whitelist, but it didn't seem to fix the issue. I refreshed the page and turned off my adblock, still didn't work. Is there anything else I need to put in the whitelist or console settings?

**Comment by Saffronette** [comment]
Alright after a bit of tweaking I had to get rid of some extensions that might have been causing problems. Now captchas are back and working on the green boards. Thank you for your help, I appreciate it very much.
