### ISSUE TITLE
Disabling 4chanX removes updater button

### ISSUE THREAD

**Issue by pinosmrime** [ccd0/4chan-x#3388]
I'm on a Windows 7 PC using Firefox.
Whenever I disable 4chanX it removes the [Update] button completely, making it only the only way to update a thread by a full page refresh or enabling 4chanX again.

**Comment by saxamaphone69** [comment]
Yes because it's 4chan X that adds that functionality, disable it and it goes.

If that's the case, what you need to do is click [Settings] at the top of default 4chan and enable the native extension.
