### ISSUE TITLE
Wrong item order in header's arrow menu (see pic)

### ISSUE THREAD

**Issue by crisalis** [ccd0/4chan-x#339]
"Index Navigation" appears before the "Prefetch Images" check-box item.
![image](https://cloud.githubusercontent.com/assets/10261623/6361041/19a62378-bc7f-11e4-9857-a4bd2c22864b.png)

**Comment by ccd0** [comment]
I think I'm also going to move `Prefetch Images` above `Threading`, if no one minds.

**Comment by ccd0** [comment]
This should be fixed as of v1.10.3.0 (currently the beta).
