### ISSUE TITLE
Index Refresh Error on LibreWolf

### ISSUE THREAD

**Issue by Renbuscus** [ccd0/4chan-x#3395]
This error occurred after I put my PC into sleep mode for around 14 hours, then booted it up and attempted to refresh the catalogue

![Screenshot 2023-08-05 235801](https://github.com/ccd0/4chan-x/assets/131457462/274566b7-51e4-4f58-b1f4-2850eaa4ddb2)
![Screenshot 2023-08-05 235813](https://github.com/ccd0/4chan-x/assets/131457462/20ed91a8-6f96-4826-8388-21616a693831)

I am using LibreWolf Version 114.0.1-2 on Windows 10 Build 19045

I've tried to remedy this in a number of ways:

- Resetting my settings and importing them back in
- Creating a new profile on my browser using "about:profiles" with only violentmonkey and 4chanx installed
- Disabling every extension except violentmonkey
- Cleaning out temporary files on my browser

None of these presented a solution, so I'm pretty stumped on how to fix it. Not even sure if it's a problem with my browser or 4chanx. This guy seemed to have the same problem though --> #3294

**Comment by saxamaphone69** [comment]
4chan itself is having issues. Just wait it out.

**Comment by NaturalHarmonia** [comment]
Same for me. I'm using Microsoft Edge on Windows 11. I'll wait it out like saxamaphone69 said.
