### ISSUE TITLE
Can't find the option to show IDs or Flags

### ISSUE THREAD

**Issue by Razwerkz** [ccd0/4chan-x#3398]
Maybe I'm blind, or just stupid, but I can't see a setting that shows IDs or enables Flags to be visible.  Am I mistaken, or are these features of 4chan X?

**Comment by saxamaphone69** [comment]
They're always shown unless you're using CSS to hide them. Is this on vanilla 4chan X?

**Comment by Razwerkz** [comment]
I believe so.  It's shows version 1.14.22.4.  There is some custom CSS filled in here:
```
/* Board title rice */
div.boardTitle {
  font-weight: 400 !important;
}
:root.yotsuba div.boardTitle {
  font-family: sans-serif !important;
  text-shadow: 1px 1px 1px rgba(100,0,0,0.6);
}
:root.yotsuba-b div.boardTitle {
  font-family: sans-serif !important;
  text-shadow: 1px 1px 1px rgba(105,10,15,0.6);
}
:root.photon div.boardTitle {
  font-family: sans-serif !important;
  text-shadow: 1px 1px 1px rgba(0,74,153,0.6);
}
:root.tomorrow div.boardTitle {
  font-family: sans-serif !important;
  text-shadow: 1px 1px 1px rgba(167,170,168,0.6);
}
```
I disabled the custom CSS checkbox, but nothing seems to be any different.  I think the above code only pertains to the style selection.

**Comment by saxamaphone69** [comment]
Are you on a board that has flags and IDs?

Can you right click the "Anonymous" and choose "Inspect Element" and take a screenshot of the HTML?

![image](https://github.com/ccd0/4chan-x/assets/877480/6d1f91d5-cf03-414c-aa12-292949cf14e9)

Just to see if the HTML is being rendered.

**Comment by Razwerkz** [comment]
![image](https://github.com/ccd0/4chan-x/assets/9700289/5367a8b4-01d2-4d6b-a7f7-e5b6f29f8932)

**Comment by saxamaphone69** [comment]
So far this is expected as /b/ doesn't have IDs or flags.

Does this happen on boards with them like /pol/?

**Comment by Razwerkz** [comment]
Ah, then that appears to be the cause of my issue.  Flags and IDs show up fine /pol/.

![image](https://github.com/ccd0/4chan-x/assets/9700289/93285225-a8d9-448c-84a3-5c207a012a11)
