### ISSUE TITLE
Make "Threading" check-box remember whether it is or it isn't checked

### ISSUE THREAD

**Issue by crisalis** [ccd0/4chan-x#340]
Currently, even if you uncheck it, it will be checked again automatically. So you see threaded conversations by default, and can temporarily unthread them. I'd actually want the opposite (unthreaded conversations by default, sometimes thread them). Making it remember whether it's checked or not is an intermediate solution, I think.

**Comment by hotdogman** [comment]
Quote threading should be disabled by default.
https://github.com/ccd0/4chan-x/blob/master/src/General/Config.coffee#L528-531

**Comment by crisalis** [comment]
@hotdogman 
Yes, I know. I should have clarified that.
I meant this "issue" to be a suggestion about how the quote threading check-box should work when the quote threading option is enabled in the settings and thus the check-box item appears.

**Comment by ccd0** [comment]
This is in the latest beta (v1.11.30.0).
