### ISSUE TITLE
Can you please tell me where 4chanx saves its data?

### ISSUE THREAD

**Issue by Maoman1** [ccd0/4chan-x#3404]
Specifically where it saves its settings and where it saves the list of links in your thread watcher. 

See, I recently upgraded my computer and had to reinstall windows, but I installed it on a new harddrive so I still have all my old data from my old install, so I just need to know where to go to fetch this info and where to copy it in my new install. I had a lot of posts "saved up" in my thread watcher that I could go back and reference via archive sites--reaction gif posts, noteworthy posts in time, stuff like that. Redoing my settings isn't that big of a deal (I know, I should have exported them and saved that file, sorry) but I'd really like to not lose that list of threads.

**Comment by Maoman1** [comment]
Alright, thanks.

**Comment by saxamaphone69** [comment]
OS? Browser? Userscript or extension? If userscript, which manager?

Surely you could have copied the old profile over, loaded it up temporarily, exported the settings, then copied them to your new profile.
https://stackoverflow.com/questions/11850460/where-are-chrome-tampermonkey-userscripts-stored-on-the-filesystem
https://www.reddit.com/r/GreaseMonkey/comments/804nab/where_are_tampermonkey_scripts_stored/

**Comment by saxamaphone69** [comment]
And also #2976 and #427.
