### ISSUE TITLE
Thread watcher crashed

### ISSUE THREAD

**Issue by thatguy46** [ccd0/4chan-x#341]
"Thread Watcher" initialization crashed.
TypeError: Cannot read property 'isDead' of null

Is the error that came up, is there anything I can do? I am currently running 1.10.1.15 in Chrome 40.0.2214.115 m, Google Store version

I have thread watcher currently turned on so I know that is not the issue at hand either.

Thanks!

**Comment by ccd0** [comment]
Can you check what it prints in the console (Control+Shift+J)?

**Comment by thatguy46** [comment]
"Thread Watcher" initialization crashed. TypeError: Cannot read property 'isDead' of null
    at Object.ThreadWatcher.fetchStatus (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:12658:15)
    at Object.ThreadWatcher.fetchAllStatus (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:12652:23)
    at Object.ThreadWatcher.fetchAuto (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:12635:23)
    at Object.ThreadWatcher.init (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:12426:21)
    at Main.initFeatures (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16088:19)
    at Function.$.asap (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:580:14)
    at chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16033:18
    at Object.callback (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:880:18)
    at safeCallbackApply (extensions::sendRequest:21:15)
    at handleResponse (extensions::sendRequest:73:7)chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:16313 Main.parseError
chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:12791 Uncaught TypeError: Cannot read property 'excerpt' of null
script.js:11382 'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).
3script.js:12791 Uncaught TypeError: Cannot read property 'excerpt' of null
3extensions::uncaught_exception_handler:8 Error in event handler for storage.onChanged: TypeError: Cannot read property 'excerpt' of null
    at Object.ThreadWatcher.makeLine (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:12791:20)
    at DataBoard.ThreadWatcher.refresh [as sync] (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:12832:34)
    at DataBoard.onSync (chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:1767:53)
    at chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:91:61
    at chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:848:9extensions::uncaught_exception_handler:8 handler
ados.js:293 1424978602672: loading flight:503880
3chrome-extension://ohnjgmpcibpbafdlkimncjhflgedgpam/script.js:6956 Uncaught TypeError: Cannot read property 'el' of undefined

**Comment by ccd0** [comment]
Can you export and post a copy of your settings?  You might have some corrupt data in there.  If that's the case, resetting your settings should fix it, but it would be useful to see what's happening.

**Comment by thatguy46** [comment]
{
  "version": "1.10.1.15",
  "date": 1424981295027,
  "Conf": {
    "JSON Navigation": true,
    "Use 4chan X Catalog": false,
    "External Catalog": false,
    "Catalog Links": false,
    "Announcement Hiding": true,
    "Desktop Notifications": false,
    "404 Redirect": true,
    "Except Archives from Encryption": true,
    "Keybinds": true,
    "Time Formatting": true,
    "Relative Post Dates": true,
    "Relative Date Title": false,
    "Comment Expansion": true,
    "File Info Formatting": true,
    "Thread Expansion": true,
    "Index Navigation": false,
    "Reply Navigation": false,
    "Custom Board Titles": false,
    "Persistent Custom Board Titles": false,
    "Show Updated Notifications": true,
    "Color User IDs": true,
    "Remove Spoilers": false,
    "Reveal Spoilers": false,
    "Show Support Message": true,
    "Normalize URL": true,
    "Disable Autoplaying Sounds": false,
    "Disable Native Extension": true,
    "Linkify": true,
    "Link Title": true,
    "Embedding": true,
    "Auto-embed": false,
    "Floating Embeds": false,
    "Anonymize": false,
    "Filter": true,
    "Filtered Backlinks": false,
    "Recursive Hiding": true,
    "Thread Hiding Buttons": true,
    "Reply Hiding Buttons": true,
    "Stubs": true,
    "Image Expansion": true,
    "Image Hover": true,
    "Image Hover in Catalog": true,
    "Gallery": true,
    "Fullscreen Gallery": false,
    "PDF in Gallery": false,
    "Sauce": true,
    "WEBM Metadata": true,
    "Reveal Spoiler Thumbnails": false,
    "Replace GIF": false,
    "Replace JPG": false,
    "Replace PNG": false,
    "Replace WEBM": false,
    "Image Prefetching": false,
    "Fappe Tyme": false,
    "Werk Tyme": false,
    "Autoplay": true,
    "Restart when Opened": false,
    "Show Controls": true,
    "Click Passthrough": false,
    "Allow Sound": true,
    "Mouse Wheel Volume": false,
    "Loop in New Tab": true,
    "Volume in New Tab": true,
    "Menu": true,
    "Report Link": true,
    "Thread Hiding Link": true,
    "Reply Hiding Link": true,
    "Delete Link": true,
    "Download Link": true,
    "Archive Link": true,
    "Thread Updater": true,
    "Unread Count": true,
    "Quoted Title": true,
    "Hide Unread Count at (0)": true,
    "Unread Favicon": true,
    "Unread Line": true,
    "Scroll to Last Read Post": true,
    "Thread Excerpt": true,
    "Remove Thread Excerpt": false,
    "Thread Stats": true,
    "IP Count in Stats": true,
    "Page Count in Stats": true,
    "Updater and Stats in Header": true,
    "Thread Watcher": true,
    "Toggleable Thread Watcher": false,
    "Mark New IPs": true,
    "Quick Reply": true,
    "QR Shortcut": true,
    "Persistent QR": false,
    "Auto Hide QR": true,
    "Open Post in New Tab": true,
    "Remember Spoiler": false,
    "Show New Thread Option in Threads": false,
    "Show Name and Subject": false,
    "Hide Original Post Form": true,
    "Cooldown": true,
    "Posting Success Notifications": true,
    "Force Noscript Captcha": false,
    "Captcha Warning Notifications": true,
    "Auto-load captcha": true,
    "Post on Captcha Completion": true,
    "Bottom QR Link": true,
    "Quote Backlinks": true,
    "OP Backlinks": true,
    "Quote Inlining": true,
    "Quote Hash Navigation": false,
    "Forward Hiding": true,
    "Quote Previewing": true,
    "Quote Highlighting": true,
    "Resurrect Quotes": true,
    "Mark Quotes of You": true,
    "Highlight Posts Quoting You": true,
    "Highlight Own Posts": true,
    "Mark OP Quotes": true,
    "Mark Cross-thread Quotes": true,
    "Quote Threading": false,
    "Fit width": true,
    "Fit height": false,
    "Scroll into view": true,
    "Expand spoilers": true,
    "Expand videos": true,
    "Expand from here": false,
    "Advance on contract": false,
    "Hide Thumbnails": false,
    "Fit Width": true,
    "Fit Height": true,
    "Scroll to Post": true,
    "Slide Delay": 6,
    "Default Volume": 1,
    "Current Board": false,
    "Auto Update Thread Watcher": true,
    "Auto Watch": false,
    "Auto Watch Reply": false,
    "Auto Prune": false,
    "Show Unread Count": true,
    "name": "# Filter any namefags:\n#/^(?!Anonymous$)/",
    "uniqueID": "# Filter a specific ID:\n#/Txhvk1Tl/",
    "tripcode": "# Filter any tripfag\n#/^!/",
    "capcode": "# Set a custom class for mods:\n#/Mod$/;highlight:mod;op:yes\n# Set a custom class for moot:\n#/Admin$/;highlight:moot;op:yes",
    "subject": "# Filter Generals on /v/:\n#/general/i;boards:v;op:only",
    "comment": "# Filter Stallman copypasta on /g/:\n#/what you're refer+ing to as linux/i;boards:g",
    "flag": "",
    "filename": "",
    "dimensions": "# Highlight potential wallpapers:\n#/1920x1080/;op:yes;highlight;top:no;boards:w,wg",
    "filesize": "",
    "MD5": "",
    "sauces": "https://www.google.com/searchbyimage?image_url=%TURL\nhttp://iqdb.org/?url=%TURL\n#//tineye.com/search?url=%TURL\n#//saucenao.com/search.php?url=%TURL\n#http://3d.iqdb.org/?url=%TURL\n#http://regex.info/exif.cgi?imgurl=%URL\n# uploaders:\n#//imgur.com/upload?url=%URL;text:Upload to imgur\n# \"View Same\" in archives:\n#https://archive.moe/_/search/image/%MD5/;text:View same on archive.moe\n#https://archive.moe/%board/search/image/%MD5/;text:View same on archive.moe/%board/;boards:a,biz,c,co,diy,gd,h,i,jp,k,m,mlp,po,qa,s4s,sci,tg,u,v,vg,vp,vr,wsg\n#https://rbt.asia/%board/image/%MD5;text:View same on RBT /%board/;boards:cgl,g,mu,qa,w\n# Search with full image only for image file types:\n#https://www.google.com/searchbyimage?image_url=%URL;types:gif,jpg,png\n#https://www.google.com/searchbyimage?image_url=%TURL;types:webm,pdf",
    "werk": false,
    "Custom CSS": false,
    "Index Mode": "paged",
    "Previous Index Mode": "paged",
    "Index Sort": "bump",
    "Index Size": "small",
    "Show Replies": true,
    "Pin Watched Threads": false,
    "Anchor Hidden Threads": true,
    "Refreshed Navigation": true,
    "Fixed Header": true,
    "Header auto-hide": false,
    "Header auto-hide on scroll": false,
    "Bottom Header": false,
    "Centered links": true,
    "Header catalog links": true,
    "Bottom Board List": true,
    "Shortcut Icons": true,
    "Custom Board Navigation": true,
    "boardnav": "[ toggle-all ]\na-replace\nc-replace\ng-replace\nk-replace\nv-replace\nvg-replace\nvr-replace\nbiz-replace\nco-replace\nfit-replace\njp-replace\nmu-replace\nsp-replace\ntv-replace\npol-replace\n[external-text:\"FAQ\",\"https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions\"]",
    "QR.personas": "#options:\"sage\";boards:jp;always",
    "time": "%m/%d/%y(%a)%H:%M:%S",
    "backlink": ">>%id",
    "fileInfo": "%l (%p%s, %r)",
    "favicon": "ferongr",
    "usercss": "",
    "Toggle board list": "Ctrl+b",
    "Toggle header": "Shift+h",
    "Open empty QR": "q",
    "Open QR": "Shift+q",
    "Open settings": "Alt+o",
    "Close": "Esc",
    "Spoiler tags": "Ctrl+s",
    "Code tags": "Alt+c",
    "Eqn tags": "Alt+e",
    "Math tags": "Alt+m",
    "Toggle sage": "Alt+s",
    "Submit QR": "Ctrl+Enter",
    "Watch": "w",
    "Update": "r",
    "Expand image": "Shift+e",
    "Expand images": "e",
    "Open Gallery": "g",
    "Pause": "p",
    "Slideshow": "s",
    "fappeTyme": "f",
    "werkTyme": "Shift+w",
    "Front page": "1",
    "Open front page": "Shift+1",
    "Next page": "Ctrl+Right",
    "Previous page": "Ctrl+Left",
    "Paged mode": "Alt+1",
    "Infinite scrolling mode": "Alt+2",
    "All pages mode": "Alt+3",
    "Open catalog": "Shift+c",
    "Search form": "Ctrl+Alt+s",
    "Cycle sort type": "Alt+x",
    "Next thread": "Ctrl+Down",
    "Previous thread": "Ctrl+Up",
    "Expand thread": "Ctrl+e",
    "Open thread": "o",
    "Open thread tab": "Shift+o",
    "Next reply": "j",
    "Previous reply": "k",
    "Deselect reply": "Shift+d",
    "Hide": "x",
    "Previous Post Quoting You": "Alt+Up",
    "Next Post Quoting You": "Alt+Down",
    "Beep": false,
    "Auto Scroll": false,
    "Bottom Scroll": false,
    "Scroll BG": false,
    "Auto Update": true,
    "Optional Increase": false,
    "Interval": "4",
    "hiddenThreads": {
      "boards": {
        "biz": {
          "1": true
        },
        "c": {
          "1990691": {}
        },
        "co": {
          "67431994": {}
        },
        "g": {
          "39894014": true
        },
        "gif": {
          "5871965": true,
          "6226033": true,
          "6755717": {},
          "6795287": {}
        },
        "int": {
          "13531746": {}
        },
        "k": {
          "23385784": true
        },
        "pol": {
          "40489590": true,
          "41712811": true,
          "41716986": true,
          "41721573": true,
          "41721807": true,
          "41723685": true,
          "41724127": true,
          "41724734": true,
          "41726576": true,
          "41726582": true,
          "41765741": true,
          "41771108": true,
          "41771139": true,
          "41773166": true,
          "41775076": true,
          "41821613": true,
          "41822061": true,
          "41826804": true,
          "41827890": true,
          "41849491": true,
          "41850359": true,
          "41854599": true,
          "41856595": true,
          "41857850": true,
          "41858644": true,
          "41862527": true,
          "41862586": true,
          "41863295": true,
          "41863394": true,
          "41863594": true,
          "41863738": true,
          "41863741": true,
          "41863865": true,
          "41864021": true,
          "41865165": true,
          "41865396": true,
          "41865805": true,
          "41865836": true,
          "41865866": true,
          "41866135": true,
          "41866231": true,
          "41866275": true,
          "41866359": true,
          "41866453": true,
          "41866485": true,
          "41866498": true,
          "41867119": true,
          "41867123": true,
          "41867190": true,
          "41867253": true,
          "41867307": true,
          "41895779": true,
          "41900759": true,
          "41902719": true,
          "41902923": true,
          "41930464": true,
          "41930687": true,
          "41930959": true,
          "41932058": true,
          "41933332": true,
          "41935465": true,
          "41935714": true,
          "41936465": true,
          "41936750": true,
          "41937236": true,
          "41937282": true,
          "41937411": true,
          "41937454": true,
          "41937745": true
        },
        "r9k": {
          "16644566": true,
          "16683343": true,
          "16684132": true,
          "16684941": true,
          "16686446": true,
          "16686506": true,
          "16686673": true
        },
        "v": {
          "284133896": true,
          "284156868": true,
          "284159186": true,
          "284160043": true,
          "284161743": true,
          "284162665": true,
          "284162709": true,
          "284163224": true,
          "284322798": true,
          "284353073": true,
          "284359375": true,
          "284364042": true,
          "284372860": true,
          "284375291": true,
          "284376057": true,
          "284460476": true,
          "284644626": true,
          "284649186": true
        },
        "vr": {
          "1392415": {}
        },
        "wg": {
          "4667225": true
        },
        "wsg": {
          "247727": {},
          "455445": {},
          "546969": {},
          "560659": {}
        }
      },
      "lastChecked": 1424978601891
    },
    "hiddenPosts": {
      "boards": {
        "pol": {
          "41862586": {
            "41866819": {
              "thisPost": true
            },
            "41866889": {
              "thisPost": true
            },
            "41867154": {
              "thisPost": true
            }
          }
        }
      },
      "lastChecked": 1424978601896
    },
    "lastReadPosts": {
      "boards": {
        "biz": {
          "656269": 656467,
          "656435": 656451,
          "657284": 658157
        },
        "gif": {
          "6793625": 6795359
        },
        "k": {
          "24806575": 24813693,
          "24813169": 24813585,
          "24829103": 24838547,
          "24833542": 24837914,
          "24842403": 24843004
        },
        "pol": {
          "41712364": 41725939,
          "41716327": 41729252,
          "41723685": 41724064,
          "41773792": 41775176,
          "41774409": 41774810,
          "41822061": 41828082,
          "41827053": 41828137,
          "41847100": 41847803,
          "41848114": 41849526,
          "41862586": 41867502,
          "41892682": 41895851,
          "41895397": 41898655,
          "41896854": 41905024,
          "41898094": 41899323,
          "41898322": 41904845,
          "41898610": 41899321,
          "41917488": 41932559,
          "41928713": 41938342,
          "41930464": 41933534,
          "41930618": 41932533,
          "41935964": 41937795,
          "41936738": 41937985,
          "41937006": 41937744,
          "41937282": 41937537,
          "41937464": 41937964
        },
        "r9k": {
          "16682833": 16687043,
          "16684132": 16686866,
          "16686446": 16686836
        },
        "v": {
          "283933493": 283967805,
          "283962937": 283967150,
          "283966871": 283968674,
          "284066650": 284072754,
          "284160043": 284163290,
          "284162947": 284163406,
          "284218176": 284222463,
          "284247158": 284251207,
          "284250449": 284260767,
          "284256369": 284256830,
          "284267819": 284293771,
          "284286587": 284292534,
          "284450639": 284455796,
          "284467802": 284473880,
          "284474365": 284482520,
          "284528510": 284534151,
          "284619326": 284622513,
          "284649186": 284659814,
          "284688925": 284690289,
          "284716902": 284720846,
          "284743482": 284747981,
          "284762217": 284774516,
          "284776745": 284778781,
          "284829560": 284832120
        },
        "vg": {
          "94850885": 95196438,
          "94960353": 95401141,
          "95196327": 95454052,
          "95400808": 95622429,
          "95459834": 95580167
        },
        "wsg": {
          "338176": 338465,
          "526438": 556978,
          "547007": 556875,
          "552205": 556829,
          "553737": 557020,
          "558549": 560437
        }
      },
      "lastChecked": 1424978601909
    },
    "yourPosts": {
      "boards": {
        "pol": {
          "41937006": {
            "41937616": true
          }
        },
        "v": {
          "283933493": {
            "283961451": true
          },
          "284250449": {
            "284251859": true,
            "284259717": true
          },
          "284649186": {
            "284659332": true,
            "284659474": true
          }
        },
        "vg": {
          "94850885": {
            "95011212": true
          },
          "94960353": {
            "94998226": true,
            "95010840": true,
            "95116862": true,
            "95213769": true,
            "95293482": true,
            "95293739": true
          },
          "95196327": {
            "95288428": true
          },
          "95400808": {
            "95574296": true,
            "95575902": true,
            "95622429": true,
            "95622557": true
          }
        }
      },
      "lastChecked": 1424978601896
    },
    "watchedThreads": {
      "boards": {
        "v": {
          "284688925": {
            "excerpt": "/v/ - Dead or Alive 5: Last Round - Do you shave? edition?",
            "isDead": true,
            "quotingYou": 0,
            "unread": 504
          },
          "284750152": {
            "excerpt": "/v/ - Zelda lore thread",
            "isDead": true,
            "quotingYou": 0,
            "unread": 566
          },
          "284766131": {
            "excerpt": "/v/ - >Bloodborne comes out next month // >\"Well I guess its time to g...",
            "isDead": true,
            "quotingYou": 0,
            "unread": 67
          },
          "284776868": {
            "excerpt": "/v/ - Is \"survival\" the worst thing to happen to gaming in the last 5 ...",
            "isDead": true,
            "quotingYou": 0,
            "unread": 36
          },
          "284777669": {
            "excerpt": "/v/ - Post vidya terms that are now virtually meaningless. // >metroid...",
            "isDead": true,
            "quotingYou": 0,
            "unread": 54
          }
        },
        "vg": {
          "95459834": {
            "excerpt": "/vg/ - /wgg/ Wargame General",
            "isDead": false,
            "quotingYou": 0,
            "unread": 87
          },
          "NaN": null,
          "isDead": true
        }
      },
      "lastChecked": 1424981247307
    },
    "customTitles": {
      "boards": {}
    },
    "selectedArchives": {}
  }
}

**Comment by thatguy46** [comment]
Also, resetting the settings worked, Thanks!

**Comment by ccd0** [comment]
If you want your old settings back, you should be able to re-import them by deleting this part:

    ,
    "NaN": null,
    "isDead": true

Still investigating to try to find out what might have caused this corruption.

**Comment by ccd0** [comment]
Alright, as of v1.10.1.16 this should be fixed, and you should even be able to import your old settings without editing if you want.  Thanks for reporting this.

**Comment by thatguy46** [comment]
No problem, thank you for making 4chanx, for the quick response, and being active in fixing it. I really appreciate it! Thank you!
