### ISSUE TITLE
How to make a custom board navigation while keeping the [+] expanding. 

### ISSUE THREAD

**Issue by HiddenMelonCat** [ccd0/4chan-x#3414]
I swear I remember you were able to be able to keep the expanding + sign while removing the boards you didn't want when it opened up and expanded. I can't figure out for the life of me how to do that anymore. The only way to keep the expanding + is to have the code: [toggle-all] but that enables all the boards, which I don't want.

**Comment by saxamaphone69** [comment]
1) Have custom board navigation enabled
![image](https://github.com/ccd0/4chan-x/assets/877480/72c3fd55-cb4a-4a37-86f0-dfb029aa28bf)

2) Go into the Settings > Advanced and type whichever boards you want, along with a toggle-all
e.g. `a b c d e f g toggle-all` - you'll see it being rendered in the background if the header is showing
![image](https://github.com/ccd0/4chan-x/assets/877480/56e0ad95-cc6e-45f8-9b44-04af40ef2f36)

**Comment by HiddenMelonCat** [comment]
> 1. Have custom board navigation enabled
>    ![image](https://user-images.githubusercontent.com/877480/275729622-72c3fd55-cb4a-4a37-86f0-dfb029aa28bf.png)
> 2. Go into the Settings > Advanced and type whichever boards you want, along with a toggle-all
>    e.g. `a b c d e f g toggle-all` - you'll see it being rendered in the background if the header is showing
>    ![image](https://user-images.githubusercontent.com/877480/275729792-56e0ad95-cc6e-45f8-9b44-04af40ef2f36.png)

Thank you for taking the time to explain with screenshots, and give a detailed rundown. I think you misunderstood what I meant. When click the + sign, as you can see I have done here. 
![image](https://github.com/ccd0/4chan-x/assets/108193614/27fe3ae0-a4d0-4745-9a0f-cfcdbc02cede)

For example I want to click the + sign and have it expand, but I want all of these in red gone. Is this possible? 
![image](https://github.com/ccd0/4chan-x/assets/108193614/4513e612-5722-4c55-bd4d-42386dc64062)

One a side note. That is a fantastic CSS. Is there a good 4chan CSS repository out there?

**Comment by saxamaphone69** [comment]
I would've thought if you only want some boards, you'd just put the boards you want.

Otherwise Custom CSS. If you only want to hide a few boards, manually pick which ones
```css
#full-board-list a[data-board-i-d="a"],
#full-board-list a[data-board-i-d="gif"] {
  display: none;
}
```
but you'll probably need to play with the extra `span`s in there.

Otherwise if you only want 5 boards in total (again, why not just only pick the ones you want), then you `:not` it instead.
```css
#full-board-list a:not([data-board-i-d="m"]):not([data-board-i-d="hr"]) {
  display: none;
}
```

Other than searching on GitHub or the threads of /g/ and /wg/, not really. [I've been making userstyles for 4chan, for way too long](https://github.com/saxamaphone69/ss21).

**Comment by HiddenMelonCat** [comment]
> I would've thought if you only want some boards, you'd just put the boards you want.
> 
> Otherwise Custom CSS. If you only want to hide a few boards, manually pick which ones
I have would have, but I would prefer to hid them in a collapse-able menu, aka, the [+]  
> 
> ```css
> #full-board-list a[data-board-i-d="a"],
> #full-board-list a[data-board-i-d="gif"] {
>   display: none;
> }
> ```
> 
> but you'll probably need to play with the extra `span`s in there.
> 
> Otherwise if you only want 5 boards in total (again, why not just only pick the ones you want), then you `:not` it instead.
> 
> ```css
> #full-board-list a:not([data-board-i-d="m"]):not([data-board-i-d="hr"]) {
>   display: none;
> }
> ```
> 
> Other than searching on GitHub or the threads of /g/ and /wg/, not really. [I've been making userstyles for 4chan, for way too long](https://github.com/saxamaphone69/ss21).

Thank you again. I would have written out the boards individually, but I would prefer to hid them in a collapse-able menu, aka, the [+]. While also organizing them how I want to.
