### ISSUE TITLE
404 Redirect not working

### ISSUE THREAD

**Issue by Dopebear** [ccd0/4chan-x#343]
Bascially the title. I try to access a 404'd link, and it brings me to the 404 page for a second then redirects me to the board (ie if I were to access a 404'd /k/ link, it'll bring me to /k/ itself)

This is the case on latest versions of Chrome and Firefox. The 4chan x version used is 1.10.1.15

**Comment by ccd0** [comment]
Does it happen in v1.10.1.16?

**Comment by Dopebear** [comment]
That's correct. Updating to 1.10.1.16 made no change to the issue.

**Comment by ccd0** [comment]
Are there any error messages in your console (Control+Shift+J)?

**Comment by ccd0** [comment]
Also, exporting your settings and posting them to pomf.se or pastebin might help.

**Comment by Dopebear** [comment]
Is there anything in particular I should be looking for in the console?

Exported settings: http://pastebin.com/Rxc00ucS

**Comment by ccd0** [comment]
Easiest way would be to just clear the log before opening a page that doesn't redirect, and copy everything.

Another thing to try is disabling your other extensions temporarily to check for a conflict.

Are those exported settings from Chrome or Firefox?

**Comment by Dopebear** [comment]
They're the settings from Firefox. Chrome settings are stock-standard (ie installing 4chan x and leaving it as it is)

**Comment by ccd0** [comment]
Can you give an example of a thread that doesn't redirect?

**Comment by Dopebear** [comment]
I've checked non-/b/ threads, and they all archive just fine (can view but not post)

Didn't know /b/ had some obscure rule like this. Oh well, I miss out I guess. Apologies for the hassle. No idea about /b/ being some exception.

**Comment by ccd0** [comment]
/b/ and /sp/ don't have public archives at the moment due to child porn issues.  https://fgts.jp/ has one for /b/, but they only let you use it while you're on their IRC channel, so it probably wouldn't work well for automatic redirects.
