### ISSUE TITLE
almost all threads in catalog and all replies colapsed

### ISSUE THREAD

**Issue by AshleyBlackwater** [ccd0/4chan-x#3434]
Woke up today and all threads now have every reply collapsed, and almost all threads are hidden in catalog.
Did I fumble a shortcut to do this or something? Can't find a button to uncollapse everything so the site is hell to use because of this.

Disabling all extensions this issue does not happen, so assuming its linked to this extension.
image as example, same for the catalog but like 6 random threads will be shown
![image](https://github.com/ccd0/4chan-x/assets/51403175/4b8b8666-2b15-4ba5-ab6f-e0a29ff73c5b)

**Comment by saxamaphone69** [comment]
Check your filters for a rogue one.

**Comment by AshleyBlackwater** [comment]
> Check your filters for a rogue one.

Never touched filters, no idea what it could have been but there was a filter set up for anonymous posts, very strange. Removed all text under all filters, Thanks :)
