### ISSUE TITLE
Youtube embeds broken

### ISSUE THREAD

**Issue by BondiBear** [ccd0/4chan-x#344]
Youtube embeds now show as a black box with no content. This worked fine before.

Unembedding and clicking the yt link opens the video fine in youtube, so it's not a region block thing.

**Comment by ccd0** [comment]
It's working fine for me.
https://boards.4chan.org/int/thread/38209022#p38214706

Can you link to an example that's not working?  There are some videos they don't let you embed.

**Comment by BondiBear** [comment]
On the above link, I get a black box.

I don't know why, I even re-installed the latest flash player and checked ADB+ isn't interfering etc.
