### ISSUE TITLE
Don't link back to posts with punctuation in them

### ISSUE THREAD

**Issue by hotdogman** [ccd0/4chan-x#345]
![gwulcb 1](https://cloud.githubusercontent.com/assets/4343306/6428681/0294c736-bf70-11e4-814c-4079d7298618.png)
Obviously, 3.16 is not a valid post number, but 46786266 is.

**Comment by ccd0** [comment]
This is mostly an issue on 4chan's end, but I'm not even sure if it's a good idea to fix.  What if someone ends their sentence with a post number, and forgets to put a space after the period?

**Comment by hotdogman** [comment]
>What if someone ends their sentence with a post number, and forgets to put a space after the period?

I was dumb and didn't think about this, whoops. Sorry.
