### ISSUE TITLE
"Image Hover in Catalog" not working

### ISSUE THREAD

**Issue by TwoDz** [ccd0/4chan-x#3477]
I have it enabled. it worked fine back when I used Chrome, but after switching to Firefox, this feature has stopped working.

**Comment by saxamaphone69** [comment]
Just double checking, are you using the `/g/catalog` URL or just `/g/` with Index Mode set to Catalog?

![image](https://github.com/user-attachments/assets/d5504bd3-887c-4285-ab94-0c0e425d3dba)

Works on my machine, Firefox 130 via userscript, with nothing else enabled.

**Comment by TwoDz** [comment]
/g/catalog
i switched to /g/ and hit catalog and it works now, thanks!
