### ISSUE TITLE
/adv/ board isn't loading, this appears when the page loads

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#348]
![untitled](https://cloud.githubusercontent.com/assets/5096684/6458603/1ec288b8-c1d1-11e4-9b63-e65a63fd9c7c.png)

**Comment by ccd0** [comment]
Probably this is either 4chan being down or your ad blocker blocking /adv/ as in https://github.com/ccd0/4chan-x/issues/217.
