### ISSUE TITLE
Links in the top board list no longer marked active on the 4channel.org domain boards

### ISSUE THREAD

**Issue by cercos** [ccd0/4chan-x#3482]
I believe the old url's used 4chan.org url's and they now have 4channel.org domain and it doesn't mark blue boards with the active CSS class.  Small issue but I have custom CSS that highlights the board and noticed it wasn't highlighting blue boards.

**Comment by cercos** [comment]
The URL in the top board list is 4channel.org but they have a redirect to the 4chan.org domain so maybe that's why the current class doesn't get marked on the blue boards.

**Comment by saxamaphone69** [comment]
You've already opened an issue #3439, which happened after they killed `4channel`.
My advice is to install the currently maintained fork, [4chan XT](https://github.com/TuxedoTako/4chan-xt).

**Comment by cercos** [comment]
Doesn't work on  4ChanXT either

**Comment by saxamaphone69** [comment]
What browser and OS
Userscript or extension
Disable all other extensions and scripts except for 4chan XT, does it work

**Comment by cercos** [comment]
Chromium on Arch llinux with KDE plasma 6 DE.   Using the chrome extension or TamperMonkey script has the same issue.  Are the top board-list anchors created by the script or 4chan?  

Not sure exactly how the current class gets added but if it uses the address bar URL and the matches it to anchor link in the board-list it won't match because of the 4channel.org domain being uses.

**Comment by saxamaphone69** [comment]
What version of XT are you using?
Is this in the custom board list or normal board list? All references to 4channel have been removed so it doesn't quite make sense how you still have 4channel appearing

**Comment by cercos** [comment]
Version 	1.14.22.4

I used the "click here to install 4chan X" in the section https://github.com/ccd0/4chan-x?tab=readme-ov-file#chromium

**Comment by saxamaphone69** [comment]
X is considered abandoned, I'm asking about XT, which I linked earlier and you said you had the same issue

**Comment by cercos** [comment]
Oh didn't realize it was different.  Why is there a link to install 4chan-x in the readme of xt?  bit confusing.

**Comment by cercos** [comment]
I got it now.  I just scrolled down on the readme and landed in the Chromium section of Original Readme.  Gonna npm build it.  They should ax that original read me section.

**Comment by saxamaphone69** [comment]
Build or, or grab it built: https://github.com/TuxedoTako/4chan-xt/releases/tag/XT2.16.0

**Comment by cercos** [comment]
Thanks for the help.
