### ISSUE TITLE
[question] How do I make the Index Sort of a board persist between every board?

### ISSUE THREAD

**Issue by Ze-da-cacimba** [ccd0/4chan-x#3489]

**Comment by saxamaphone69** [comment]
Assuming that you mean you want to set something like 'Sort by File Count' once and it does it for every subsequent board?
If so, open the Header menu, and untick this option.

![image](https://github.com/user-attachments/assets/00212cf0-8a3f-4154-9670-d77f92cce2a8)

**Comment by Ze-da-cacimba** [comment]
@saxamaphone69 That's exactly what I needed, thank you very much
