### ISSUE TITLE
Index refresh failed

### ISSUE THREAD

**Issue by shagel** [ccd0/4chan-x#349]
Hello I am using 4chanx beta version 1.10.3.5, Greasemonkey version 2.3 and Firefox version 39.0a1 (20150302030204) and when I try to open a board (so far only happens on /g/ and /pol/, didn't try all of the boards) I get an error.
Well to be honest I get a couple errors on the console but I think this one is the one:

"Index failure: pages[0] is undefined" "Index.parseThreadList@file:///C:/Users/_/AppData/Roaming/Mozilla/Firefox/Profiles/z46xv66m.default-1419996402513/gm_scripts/4chan_X_beta/4chan-X-beta.user.js:3655:7
Index.parse@file:///C:/Users/_/AppData/Roaming/Mozilla/Firefox/Profiles/z46xv66m.default-1419996402513/gm_scripts/4chan_X_beta/4chan-X-beta.user.js:3647:7
Index.load@file:///C:/Users/_/AppData/Roaming/Mozilla/Firefox/Profiles/z46xv66m.default-1419996402513/gm_scripts/4chan_X_beta/4chan-X-beta.user.js:3622:11
Index.update/Index.req<.onloadend@file:///C:/Users/_/AppData/Roaming/Mozilla/Firefox/Profiles/z46xv66m.default-1419996402513/gm_scripts/4chan_X_beta/4chan-X-beta.user.js:3587:18
"
If you don't support beta versions well sorry for bothering you my friend, feel free to close away this issue ;)
 btw edited the console error to block my name

**Comment by ccd0** [comment]
Not a 4chan X problem, the board is down.

**Comment by shagel** [comment]
yes i thought of that but status.4chan.org says boards are up

**Comment by bakugo** [comment]
Posting on 4chan is down. status.4chan.org is outdated and often shows incorrect information. Whenever you can't post, go look at a very active board and check the last post on the top of the page. If it was 2 hours ago, you know something's wrong.

**Comment by shagel** [comment]
nvm fixed it
