### ISSUE TITLE
Using Meta key+Click on the file field to rename opens file select window again on Mac

### ISSUE THREAD

**Issue by ompq** [ccd0/4chan-x#351]
Steps to reproduce:

1. On OS X, select file to post on the quick replay window.
2. Meta key (Command key on Mac) + Left click on the file name field.

Expected result:
Focus on the file name field to that user can edit the name to post file with.

Actual result:
File select window opens again. Focus is enabled on the file name field once the user closes the file select window.

Note:
Ctrl+click does not work as Ctrl+click is hard wired to simulate right click on OS X. This behavior cannot be turned off in the OS X settings.

**Comment by ccd0** [comment]
Thanks, should be fixed now.
