### ISSUE TITLE
Persistent "Offline" after briefly losing internet connection

### ISSUE THREAD

**Issue by mcbo** [ccd0/4chan-x#352]
First want to say thanks for all the great work!

I've noticed an issue where 4chan-x shows "Offline" and refuses to go back to normal after briefly losing internet connection for a few minutes.

http://i.imgbox.com/uqtJb2Dk.png

My modem/router occasionally loses connection but comes back after a reboot and internet works again. The problem is "Offline" remains in red in the 4chan-x navbar, threads wont update without manually refreshing the tab.

Can this be fixed? Is there a setting I need to change?

**Comment by ccd0** [comment]
What browser are you using?

**Comment by mcbo** [comment]
Sorry, Chromium 42.0.2308.0

**Comment by ccd0** [comment]
It's probably a bug in your browser where it falsely reports you're offline, but I suppose I could add a setting to ignore it.

**Comment by mcbo** [comment]
If you think that would work around the issue that would be great. I've had these lost connections before but I never noticed the red Offline sticking in the navbar after the connection comes back. Its very possibly the browser.

Also after this Offline happens, opening a new tab won't refresh the catalog index: http://i.imgbox.com/tnGbzjjy.png
Although it won't show the red Offine in the new tab's navbar, the catalog or index view will be blank. Clicking the refresh link has no effect and the refresh button in Chromium also won't show any threads. Is this consistent with the browser reporting falsely offline?

**Comment by ccd0** [comment]
No, that's consistent with the browser correctly reporting offline.

**Comment by ccd0** [comment]
To be more specific, if your catalog is blank, that has nothing to do with the browser reporting you as offline or online.  But it is likely happening because of your browser for whatever reason failing to connect to the Internet.

**Comment by mcbo** [comment]
Ok, which would be great if there really was no connection. But if I open a tab right next to the blank catalog one and load Google everything is working fine in the Google tab. Would a setting to ignore browser's online/offline solve whats going on here?

**Comment by ccd0** [comment]
Can you actually search?  It could just be cached.

> Would a setting to ignore browser's online/offline solve whats going on here?

No.  It wouldn't even fix the updater, as it would just try to fetch updates and not get anything.

**Comment by mcbo** [comment]
Yes search works and clicking on links load the external pages. This Github tab is working fine in the same Chromium window that will only gives blank /g/ catalog tabs.

**Comment by ccd0** [comment]
It could be another extension blocking it.  Do you get any messages like `net::ERR_BLOCKED_BY_CLIENT` in the Javascript console (Shift+Control+J) when you try to refresh the catalog?

**Comment by mcbo** [comment]
I just refreshed and got 2 messages but they seem to be about ads: http://i.imgbox.com/cIpNLWwz.png

I disabled all extensions and refreshed, now there are no messages but still no threads: http://i.imgbox.com/4jZULWT1.png

**Comment by ccd0** [comment]
What do you get in the network tab of the console when you refresh?

**Comment by mcbo** [comment]
A lot of stuff, it looks like thumbnails for the catalog download but aren't being displayed:
http://i.imgbox.com/eUspX63J.png
http://i.imgbox.com/6VypL6RO.png

It seems once this Offline condition happens the catalog is always blank.

Tabs opened before Offline happens will continue to show posts, they just wont update automatically, but the refresh button in the browser will work and load any new posts.

**Comment by ccd0** [comment]
Not with F5.  With the refresh icon in the header or the "Refresh" link.

**Comment by mcbo** [comment]
Oh, sorry. Clicking the "Refresh" link doesn't seem to do anything on the page and doesn't show any new activity in the network tab. But the "Archive" link next to it seems to work and loads its content normally. Clicking "Catalog" link again after being on the Archive page gives the same network activity as F5 but no threads displayed.

**Comment by ccd0** [comment]
> Clicking the "Refresh" link doesn't seem to do anything on the page and doesn't show any new activity in the network tab.

Is there any new activity in the console tab?
Also, can you check which version of 4chan X you're using?

**Comment by mcbo** [comment]
There is no console activity when clicking the Refresh link. But clicking Catalog link gives an uncaught type error cant read map of undefined, clicking Index link gives cant read slice of undefined: 
http://i.imgbox.com/CavGcFNN.png

4chan X version is 1.10.2.10

**Comment by ccd0** [comment]
Okay, after a double check, it seems 4chan X does check the offline status reported by the browser and doesn't try to refresh if you're offline.  So this is related to the false offline reporting after all.

**Comment by mcbo** [comment]
Ok, thanks for checking. So Chromium thinks its offline for some reason even though its clearly connecting.

I guess the workaround to add a setting for ignoring offline status would work, I'd appreciate if you could add one for this weirdness . It seems strange that the browser should think its offline but that would be a problem to take up with the Chromium devs I guess. Do you know if I could check the browser offline status directly?

**Comment by ccd0** [comment]
> Do you know if I could check the browser offline status directly?

Type `navigator.onLine` in the console.

**Comment by mcbo** [comment]
Thanks, so that returns false. Can I permanently set it to true? 

Does this look like a Chromium bug to you? This happens after losing internet connection for a few minutes then the browser is stuck in offline mode until its restarted.

**Comment by ccd0** [comment]
> Can I permanently set it to true?

Not that I'm aware of.  But I can add a setting in 4chan X to ignore it.  And yes, it is definitely a Chromium bug.  If you are online, `navigator.onLine` should be true.

**Comment by mcbo** [comment]
Well this Github tab has been connecting fine the whole time so navigator.online should be true. I'll try to see what Chromium devs can say about it. 

If you could add an ignore setting to 4chan X that would be great. I really appreciate the help with this issue.

**Comment by ccd0** [comment]
The ignore setting is in the newest beta version (v1.10.4.0).

**Comment by ccd0** [comment]
Is it working for you?
