### ISSUE TITLE
Gallery loading

### ISSUE THREAD

**Issue by fgsfdss** [ccd0/4chan-x#353]
Suggest an option (or default) to pre-fetch all images in a thread upon opening the gallery. 

Because when using that function you'll probably want to check out most of the images right? It makes sense.
Of course right now you can just click the expand all button and contract them again or activate and de-activate global pre-fetch, but this would just be a small QOL upgrade.

**Comment by fgsfdss** [comment]
Also, the bars / buttons to go to next and previous images are a bit thin (might be better on larger monitors, I use a 1440x900). You could try making them expand on hover, or just having them a little wider by default.

**Comment by ccd0** [comment]
> Suggest an option (or default) to pre-fetch all images in a thread upon opening the gallery.

Agreed, but I think it would be best to prefetch only the next image rather than all of them at once.

> Also, the bars / buttons to go to next and previous images are a bit thin (might be better on larger monitors, I use a 1440x900). You could try making them expand on hover, or just having them a little wider by default.

True.  I'll have to play with it to see what looks good.  Pull requests (or even just posting suggested CSS) welcome here.

**Comment by fgsfdss** [comment]
<blockquote>only the next image rather than all of them at once</blockquote>
In a dump you want to skip over reaction images and unrelated conversation though. Loading only the next image you would still have to wait for the one after the reaction image to load.
You could do both I guess, one as default, one as an extra option.

I'm quite busy with some work this week and the next, and I don't know much about CSS at all, but I'll see if I can figure something out for those next & prev buttons (seems like a simple ":hover", though I've never used those with animations). No promises though.

**Comment by fgsfdss** [comment]
Update: I've been using the gallery like I described (with expanding and contracting) for a while now, but it doesn't work very well. 
Even though I wait for all images to be loaded before contracting them again, sometimes half of them flub out. The images get broken, and even when going to the direct link they won't load at all. Refreshing does nothing, needs a browser restart (or cache clear I guess) to fix this. 
Quite frustrating in dumps, to be fair.

**Comment by ccd0** [comment]
> activate and de-activate global pre-fetch

BTW, you shouldn't have to deactivate it.  When you check the box in the header menu, it only turns prefetching on for that thread.

> it doesn't work very well.

I see these sort of issues too.  Also, loading all the images considerably slows down loading the one you want.  That's why I think it should just load the next image.  Well, that and not wrecking people's bandwidth.

> The images get broken, and even when going to the direct link they won't load at all. Refreshing does nothing, needs a browser restart (or cache clear I guess) to fix this.

I guess I need to take a look at the error handling to see if this can be improved by retrying from `http://imageurl.jpg?timestamp`.  This is something we already do, but only in image hovering I think.

**Comment by fgsfdss** [comment]
<blockquote>When you check the box in the header menu, it only turns prefetching on for that thread.</blockquote>
Neat, I didn't know that.
<blockquote>Well, that and not wrecking people's bandwidth.</blockquote>
Hence why I suggested a default-disabled option. I'm also assuming most people have the bandwidth to load 250 images these days. That's around 100 mb at worst (for average sized jpgs)? Becomes a different matter with webms, animated gifs and hi-res images I suppose, but if you mainly visit those kinds of threads and your bandwidth can't handle that you wouldn't have to use the option.

Well, just the next image is already a big improvement over none at all, but that still leaves the issue of reaction- and other unrelated images, and if you're going through them quite fast or selectively pre-fetching only the next one won't have much of an effect.

**Comment by fgsfdss** [comment]
I've also been playing around with the expanding buttons I suggested, but without success.
I thought it'd be a simple
<code>.gal-next{
  transition:width 0.5s;
}

.gal-next:hover{
  width:200%;
}</code>
...but it seems it is not. Well, that doesn't work anyway.

**Comment by ccd0** [comment]
The gallery preloads the next image now.  Splitting the previous/next button issue into a separate topic: #431.

**Comment by fgsfdss** [comment]
Awesome to hear. Thanks.
