### ISSUE TITLE
Fake deleted posts

### ISSUE THREAD

**Issue by bakugo** [ccd0/4chan-x#354]
Ever since 01af49fd5236c611ad1a4516295fba24064a6349 (I think) some posts are being marked as deleted when they aren't. This already happened before, but they would be "un-deleted" at the next thread update, now they stay marked as deleted until the page is refreshed.

**Comment by ccd0** [comment]
Are they being marked as deleted by the thread update or by something else?

**Comment by bakugo** [comment]
By the thread updater, yes.

**Comment by ccd0** [comment]
Is it happening often enough that you can reproduce it?  What are your updater settings like?

**Comment by bakugo** [comment]
Interval set to 5 seconds, auto-increment disabled.

It seems to happen in any thread moving fast enough, it's been happening at least once every 30 minutes today.

**Comment by ccd0** [comment]
What browser?

**Comment by bakugo** [comment]
Chrome 40.0.2214.115 m

**Comment by bakugo** [comment]
Managed to reproduce it with the devtools open: on one update the post is present in the JSON, 5 seconds later it updates again and the post is gone (last-modified header is 6 seconds later than the first request), then about 3 Not Modified requests, then another one where the post is back again (last-modified is about 30 seconds after the second request).

**Comment by ccd0** [comment]
What do the now/tim/time on the posts look like in the JSON?

**Comment by bakugo** [comment]
I noticed that it seems to happen when two posts are made almost at the same time, the last post to be posted gets marked as deleted.

In the post mentioned above, the tim value is 1426036971030 while the previous post is 1426036971009.

**Comment by ccd0** [comment]
> In the post mentioned above, the tim value is 1426036971030 while the previous post is 1426036971009.

What were the Last-Modified times?

**Comment by ccd0** [comment]
Also was
> This already happened before, but they would be "un-deleted" at the next thread update
still happening after v1.9.10.0 in November?

**Comment by bakugo** [comment]
`Wed, 11 Mar 2015 01:22:51 GMT` when it appeared, `Wed, 11 Mar 2015 01:22:56 GMT` when it disappeared and around `Wed, 11 Mar 2015 01:23:13 GMT` when it appeared again.

>still happening after v1.9.10.0 in November?  
I think so. It was rare but it happened.

**Comment by ccd0** [comment]
Thanks a lot.  I'm going to try rejecting updates that (1) decrease the last post number and (2) have last-modified times less than 30 seconds (half the deletion cooldown) after that of the post being deleted.  I'll probably have to bring back the post resurrecting thing anyway as whatever I do isn't going to be perfect.

**Comment by ccd0** [comment]
Does v1.10.4.3 fix it on your end?

**Comment by bakugo** [comment]
Seems to be fixed, it hasn't happened at all today. Thanks.
