### ISSUE TITLE
Disable popup error notification or increase cooldown?

### ISSUE THREAD

**Issue by gonridingonaneagle** [ccd0/4chan-x#355]
Is there a way to disable the popup message? Here's the situation:

1. Dump images (on pass)
2. The image somehow is sent a split second early
3. This stops the dump, and shows the message. If I close the message, the dump resumes as normal. However, I don't want to babysit it in case a popup interrupts it again.

Alternatively, can I just bump the cooldown to 61, etc.? I see "customcooldown" in the code, but I didn't see it in the GUI. So, naturally, I have no idea how to do it.

**Comment by ccd0** [comment]
> I see "customcooldown" in the code, but I didn't see it in the GUI.
It's near the bottom of the Advanced section.

But probably the right fix is to make the "please wait" error not abort autoposting.

**Comment by ccd0** [comment]
OK, I see the problem. The autoposting isn't being aborted, but the alert is pausing everything.  I'll have to fix that.

**Comment by ccd0** [comment]
Is this fixed for you now?
