### ISSUE TITLE
[code] tag duplicates itself

### ISSUE THREAD

**Issue by r3bify** [ccd0/4chan-x#357]
Unless inside a thread all of the instances of [code] tags will be identical. 
http://i.imgur.com/KIC7ijv.png
Windows 8.1, chrome 43.0.2327.5 dev-m (64-bit)

This issue has been present for a number of versions, regardless of what other scripts/extensions I have on/turn off.

**Comment by ccd0** [comment]
I've never seen it, but I can guess what might be causing it.  I've put some changes that might fix it in the latest beta version (v1.10.5.0).  Can you check if it works now?

**Comment by r3bify** [comment]
It works now.
