### ISSUE TITLE
Optional increase refresh rate limit the wrong way around

### ISSUE THREAD

**Issue by leuton** [ccd0/4chan-x#358]
Thread updater's optional increase max refresh rate limit is the wrong way around. Currently the limit is higher for visible tabs.

https://github.com/ccd0/4chan-x/blob/53e7478839d92c6602d2d6f830f2eb0e972de6d1/src/Monitoring/ThreadUpdater.coffee#L201

**Comment by ccd0** [comment]
Thanks, should be fixed now.
