### ISSUE TITLE
Threads opened via keybind "open thread in new tab" forgotten on restart

### ISSUE THREAD

**Issue by hejops** [ccd0/4chan-x#360]
Threads opened via manually clicking (both when 4chan-x is enabled and disabled), or via keybind "open thread in current tab" are unaffected, so I have a feeling 4chan-x is behind this.

4chan-x version: 1.10.4.8
Firefox version: 36.0, 36.0.1 (fresh)
OS: Mint 17.1, Windows 10 build 10036 (fresh)

**Comment by ccd0** [comment]
What version of Greasemonkey?

**Comment by hejops** [comment]
3.0

**Comment by ccd0** [comment]
Can you check if it still happens in 3.1beta1?

**Comment by hejops** [comment]
Yes, the bug still persists.

**Comment by ccd0** [comment]
I'm seeing it too.  It's a Greasemonkey bug:

https://github.com/greasemonkey/greasemonkey/issues/2107

**Comment by hejops** [comment]
Oh, that's interesting. Guess we'll have to wait and see. Should I close the thread?

**Comment by ccd0** [comment]
Might as well, there isn't any good way to work around this from the script side.
