### ISSUE TITLE
Indication of backlinks

### ISSUE THREAD

**Issue by noname4** [ccd0/4chan-x#361]
So let's say there is a post I want to read the opinions about.  I click on the backlink to one of the replies.  And it turns out this guy has quoted and replied to 30 other posts on the same post.  For example,

<<1234567
faggot
<<1234444
you suck
<<2123245
underrated post
<<2124032
I suck dicks

Is there a way to show which quotelink is the one I'm looking for?  What I'm thinking of is something like adding a (you)(OP)(Cross thread) next to the link or maybe change its colour to indicate the reply I'm looking for.

**Comment by bakugo** [comment]
The quotelink for the backlink you're hovering on for has a dotted underline. Same when you hover over a quotelink, the corresponding backlink has a dotted underline.

**Comment by noname4** [comment]
Is it possible to get the quote highlighting feature without the quote previewing feature?  I'm not much of a hovering fan.

**Comment by ccd0** [comment]
As of v1.11.21.0 (the current beta) this happens in inlined quotes also.
