### ISSUE TITLE
New Threads Open New Tab so Fast that Thread Hasn't Been Made Yet

### ISSUE THREAD

**Issue by polyjay** [ccd0/4chan-x#362]
I make a new thread, and the new tab pops up, but it gets immediately redirected to an empty archive page. I'm not sure if it's opening too fast that the thread hasn't even been made yet.

**Comment by ccd0** [comment]
Is this happening often?

**Comment by ccd0** [comment]
Sounds like a glitch on 4chan's end.  If it keeps happening, I'll work around it, but if it's a one-time thing, it's probably not worth worrying about.

**Comment by deadman3000** [comment]
New thread posts open with a 404 page. I want it to open my new thread like before. Any ideas?

**Comment by RocketLauncher2** [comment]
I'm getting this problem constantly as well.

**Comment by ccd0** [comment]
Can you check if the latest beta version (v1.10.6.6) fixes it?

**Comment by RocketLauncher2** [comment]
It hasn't been happening frequently but it just happened when making a thread on /pol/. I had it set to post while I had another tab open and noticed it just sent me straight to the archive. 98% of the time it seems to be fixed for me, though.

**Comment by hotdogman** [comment]
I don't know how important it is, or if it even matters, but I just noticed this issue resurface after creating a thread on /g/.

**Comment by ccd0** [comment]
@hotdogman 
Did it wait 10 seconds before opening the thread?  If the thread isn't there within 10 seconds, 4chan X stops testing and opens it anyway.  If it is waiting 10 seconds, there's not much I can do about it; I don't want to poll indefinitely.  If it's not, there's a problem.

**Comment by hotdogman** [comment]
I may just be bad at estimating, but I don't think it waited 10 seconds. I posted the thread, and (I think) it opened right away to the 404 page and re-directed to the index.

**Comment by ccd0** [comment]
@hotdogman
Next time you start a thread, can you check the HTTP requests?  It should make a few HEAD requests and open the page when it gets a 200.

Also, is there anything notable about your Internet connection?  Use of proxies, web filtering software, etc.?

**Comment by hotdogman** [comment]
>Next time you start a thread, can you check the HTTP requests? It should make a few HEAD requests and open the page when it gets a 200.
Are you referring to the network request logger in firefox/chromium? If so, yeah, I can do that. I don't make threads very often, though.

>Also, is there anything notable about your Internet connection? Use of proxies, web filtering software, etc.?
Besides the fact that (in my opinion) it's slow, no. I don't use any proxies and my internet connection is not being filtered by my ISP to my knowledge.

**Comment by ccd0** [comment]
> Are you referring to the network request logger in firefox/chromium?

Yes.

**Comment by RocketLauncher2** [comment]
It's been happening again pretty frequently on /pol/. I haven't noticed it on other boards.

**Comment by ccd0** [comment]
@RocketLauncher2
Is the 10 second wait period working?

**Comment by ccd0** [comment]
I think I'm going to extend the maximum wait to 15 seconds and then just close this issue again because with any wait time we'll have some small fraction of threads that take longer than that to create.

**Comment by ccd0** [comment]
Might as well leave this open while the problem still exists on 4chan's end.
