### ISSUE TITLE
Parsing of Post No failed. Post will be skipped. TypeError: link.nextSibling is null

### ISSUE THREAD

**Issue by mrrip** [ccd0/4chan-x#363]
I've been getting this error since a few versions back. It seems to only happen to posts with a youtube link on it.

**Comment by ccd0** [comment]
Are you using something like Youtube Link Title?

**Comment by ccd0** [comment]
Also, could you give me a link to a post that's not working?

**Comment by mrrip** [comment]
Checked the add-ons and I had something similar like the Youtube Link Title still on. Disabling it cleared up the errors. All good now. Thanks a lot.

**Comment by ccd0** [comment]
It would still be good to fix the conflict.  Can you tell me what extension it was and what post was not working?

**Comment by mrrip** [comment]
Had the 4chan imgur thumbnail (fix) script 1.12.3 on for the longest time, before 4chanX.
Examples on https://boards.4chan.org/v/thread/287893915
Posts 287899010, 287900041, 287909428, 287909840 have no embed support and 4chanX quotes backlink and preview stopped working on those posts. It doesn't happen to all the youtube links it seems (OP, 287896424, 287899595 work fine)

**Comment by mrrip** [comment]
If you need to find the 4chan imgur thumbnail 1.12.3 (the one on userscripts hasn't been updated for a while now), this is the link to it https://github.com/bakugo/4chan-imgur/raw/master/dist/4chan-imgur.user.js

**Comment by ccd0** [comment]
It seems to be adding its own fake file info which 4chan X understandably chokes on.  I've changed the beta version (v1.10.6.1) so that it skips file info not from 4chan.

**Comment by ccd0** [comment]
Can you check if the beta version works with 4chan imgur thumbnail on?

**Comment by mrrip** [comment]
Sorry for the late reply. Tested the beta build with the 4chan imgur thumbnail on, and no errors turned up.

**Comment by ccd0** [comment]
Thanks!

**Comment by bakugo** [comment]
Something I should probably point out: the script embeds 4chan image links (i.4cdn.org) as well, which still cause an error. Wouldn't it be easier to just filter files with the imgur_file class?

I should have probably noticed this earlier but it seems the execution order of 4chan X and the script is different on my browser and doesn't cause any errors.

**Comment by mrrip** [comment]
Not sure if it's related to the previous issue, but in 1.10.6.1, deleted posts' images that were quoted no longer have the Image Expansion and the Image Hover working on them like it did in 1.10.6.0. 

Example: https://boards.4chan.org/vg/thread/98009217#p98014146 quotes a deleted post

**Comment by ccd0** [comment]
@bakugo 
> Wouldn't it be easier to just filter files with the imgur_file class?

Maybe, but I'm hesitant to target specific scripts, as it will break if someone writes another script that does the same thing.

Do you have anything that fakes `.fileText > a:first-child`?

**Comment by ccd0** [comment]
> Do you have anything that fakes `.fileText > a:first-child`?

Never mind, I see you do.  I had only tested the version @mrrip linked to.  Going to try a more direct approach: ignoring files if we don't see a file size, which is the reason for these crashes.

**Comment by ccd0** [comment]
> Never mind, I see you do.

Oops, correction, I don't think your version does, but I found another version that does:
https://bitbucket.org/murkeli/userscripts/raw/master/4chanimgur.user.js

**Comment by ccd0** [comment]
@mrrip
> Not sure if it's related to the previous issue, but in 1.10.6.1, deleted posts' images that were quoted no longer have the Image Expansion and the Image Hover working on them like it did in 1.10.6.0.

I think it was related.  Could you try it in 1.10.6.2 (just pushed) and see if it's working again?

**Comment by mrrip** [comment]
Tested 1.10.6.2. The Image Expansion and the Image Hover now works on deleted posts and encountered no errors with the 4chan imgur thumbnail script on.

**Comment by ccd0** [comment]
Thanks.
