### ISSUE TITLE
Please Rework File Info Formatting

### ISSUE THREAD

**Issue by MrSeyker** [ccd0/4chan-x#364]
I used 4chan Grab to download pictures from threads, but 4chan changed the code too much, so it no longer works.

Using 4chan X with File Info Formatting and DownThemAll was a good alternative, but in its current format, it doesn't work like it should.

Long filenames show up as "short name(...) - long name" in the description field, and they download as just "short name(...)" when it should format to "long name" and ignore the first part.

There's also the issue of spoilered images. 4chan reworked the code so that if the image is a spoiler, the filename also is. That's cool for browsing, but it fucks up batch downloading pictures, as they will always be renamed "Spoiler Image" unless 4chan X is set to unspoil pictures by default.

The File Info Formatting code needs to be reworked so that the original filename is always sent properly to the DownThemAll description/text field.

**Comment by ccd0** [comment]
Have you tried changing the "File Info Formatting" setting on the "Advanced" settings tab?

**Comment by MrSeyker** [comment]
Yes, I use %L (link is the untruncated original filename), but the text description in DownThemAll shows the "short name - long name" format regardless, and like I said, only the first part (the short file name) is considered when this is the case.

**Comment by ccd0** [comment]
This is an issue that really needs to be fixed on DownThemAll's end:
https://bugs.downthemall.net/ticket/2534
But I can add an option to work around it.

**Comment by ccd0** [comment]
In the newest beta version (v1.10.6.2), if you turn on the `Remove Original Link` option, it should do what you want.

**Comment by MrSeyker** [comment]
It's not really an issue on DownThemAll, because earlier versions of 4chan X's File Info Formatting actually send proper filenames to DTA's description field.

I'm currently using a fork of 4chanX v2 as an alternative, and that formats the data correctly with the same settings (untruncated name as link, no spoilers, picture properties). It's most deffinitely an issue in the current code.

I'll test the new version to see how it behaves and report back.
