### ISSUE TITLE
Add an embed button for .webp links

### ISSUE THREAD

**Issue by iiiGerardoiii** [ccd0/4chan-x#365]
It would be nice to have the embed button on links that end with `.webp` so the image could be seen inside the thread.

**Comment by iiiGerardoiii** [comment]
I just realized that it would be useless in Firefox and Safari because they haven't implemented `webp` image support yet.

**Comment by ccd0** [comment]
No reason not to add it for browsers that do, though.  I'd just want to add some code that tests for webp support and only adds the embed link if it's there.
