### ISSUE TITLE
OP country flag visible through /int/ and /sp/ catalogs

### ISSUE THREAD

**Issue by Fapjack0** [ccd0/4chan-x#374]
Is it possible to make the thread creator's flag visible through the catalogs from boards that uses country flags, like /int/ or /sp/? Preferable right next the thread's post count or right before OP's message, in each thread. 

That would make easier to distinguish serious from bait threads, depending where the thread creator comes from.

**Comment by crisalis** [comment]
I also want this, specially because with vanilla 4chan, if you hover over a thread in the catalog, you can see OP's flag as well as some more info.

**Comment by Fapjack0** [comment]
I'm aware of that hovering information through 4chan's catalog. But it's really annoying having to hover over each image to check where the thread creators comes from. It'd be far more practical if we had that kind of information always visible. I think the ideal would be OP's flag and his name (Anonymous or Tripfag), between the thread posts count and his actual post.

**Comment by ccd0** [comment]
> I think the ideal would be OP's flag and his name (Anonymous or Tripfag), between the thread posts count and his actual post.

In the 4chan X catalog this CSS should now do that:

```
.nameBlock {
  display: block !important;
}
:root:not(.catalog-hover-expand) .catalog-container .nameBlock,
.catalog-container:not(:hover) .nameBlock {
  padding-top: 0;
}
```

**Comment by ccd0** [comment]
Now this is the only part needed:
```
.catalog-post > * > .nameBlock {
  display: inline-block !important;
}
```
