### ISSUE TITLE
Index refresh button tries to refresh twice

### ISSUE THREAD

**Issue by bakugo** [ccd0/4chan-x#375]
The "Last index refresh" button in the index [always tries to refresh twice](https://github.com/ccd0/4chan-x/blob/master/src/General/Index.coffee#L266) if the "Refreshed navigation" option is turned on, which causes an "index refresh failed" error to pop up every time it's clicked.

**Comment by ccd0** [comment]
Oops!  Thanks, will fix.

**Comment by ccd0** [comment]
Should be fixed now.  Working for you?

**Comment by bakugo** [comment]
Works fine. Thanks.
