### ISSUE TITLE
Webm does not play on hover in Firefox

### ISSUE THREAD

**Issue by CorWilson** [ccd0/4chan-x#376]
This seems to be an issue that has been around for me. Don't know if anyone else has it. On hover in Firefox, webms don't play, but gifs do. In Chrome, webms play on hover, however.

**Comment by ccd0** [comment]
Can't reproduce on my end.  Can you check some more details?
https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md

**Comment by CorWilson** [comment]
I first turned off all my extensions and addons. It still did not work with a restart, which meant it was likely a plugin or setting stopping it. Cause I did a hard reset and reinstalled only greasemonkey and 4chan x, and it started working again. I slowly added my add ons back on, checking each time, and the webm still plays. It could have been something that wasn't there before or changed.
