### ISSUE TITLE
Quick filtering images

### ISSUE THREAD

**Issue by alidan** [ccd0/4chan-x#377]
Sorry if this is already a thing, but could adding a quick filter md5 button be possible? There are manga/comics that get posted over and over again that are more or less troll images, not to mention the images made just to increase the post count and never anything else, and every time you have to go to the drop down filter md5... 

If possible could it be a setting you have to enable like image expansion, gallery mode, work time, fap time? While I would get tons of use out of it, having it there all the time could cause an accidental filtering.

On the topic of filtering, would it be possible to add a message to a filtered comment to tell you why it was filtered? Also, in this case looking at the md5 filter, see the board it was originally filtered from?

Sorry if this is long and has more than one request, really all I would like is a quick md5 filter and the rest would just be extras.

**Comment by ccd0** [comment]
Also requested in
https://boards.4chan.org/b/thread/623145275/#p623158884
https://boards.4chan.org/g/thread/51761944

**Comment by ccd0** [comment]
Another request:
https://boards.4chan.org/g/thread/57415525#p57419076

**Comment by alidan** [comment]
lol, someone else either remembers the request or wanted it too... sad this isn't part of the extension yet, but I'm in no hurry, boards and threads I go to these days are not nearly as infested with shit as the ones I was going to when I made the request.

**Comment by ccd0** [comment]
I've added this in the latest beta version (v1.13.1.2). To turn it on, go to `Advanced` > `File Info Formatting` in your settings and add a `%f` wherever you want the button. There's also a keybind for adding MD5 filters (`5` by default), which may be quicker if you have to do a lot of them.

**Comment by ccd0** [comment]
> On the topic of filtering, would it be possible to add a message to a filtered comment to tell you why it was filtered?

This is #126.

> Also, in this case looking at the md5 filter, see the board it was originally filtered from?

Might be a good idea to add a comment to this functionality showing the URL of the post in which the Quick Filter button was clicked. Re-opening for that bit.

**Comment by alidan** [comment]
Personally only filter 3 things not images, and one is a tripfag who has yet to once not shitpost/shill
The other two, it would be nice to have a quick bi line for why its filtered, same with images, I find myself clicking the hide post button off to check why something is filtered, only to remember why I filtered it in the first place a second later. 

On the topic of extra filtering options, is it possible to highlight a filtered post with specific colors? I already have one for webm so I know its not a gif im opening, but if there was a way to add a highlight color to differentiate 'its an image that's filtered' and 'its text that's filtered' it would make it easier to go through a thread knowing what each post is without needing to see it.

**Comment by ccd0** [comment]
> On the topic of extra filtering options, is it possible to highlight a filtered post with specific colors?

Not at the moment, but maybe it could be done as part of the fix for #1118.
