### ISSUE TITLE
"Catalog Links" setting ignored

### ISSUE THREAD

**Issue by aphirst** [ccd0/4chan-x#378]
Despite enabling the "Catalog Links" setting, and the checkbox's state seemingly persisting across refreshes or otherwise loading 4chan pages, the actual functionality does not. It does not return on page refresh - only a 4chan-x setting reset helps.

http://a.pomf.se/ocbicc.json for exported settings.

Using:
* Pale Moon `25.3.1`
* Greasemonkey `1.15` (newer versions not supported by Pale Moon; and Catalog Links worked fine with this version in the past)
* 4chan-x `1.10.7.7`
* oneechan `5.5.25`

I have "JSON Navigation" disabled but this behaviour seems to occur regardless (though of course the JSON navigation can be configured to give a 'catalog' page even without /catalog/ in the URL)

I'm happy to provide any other information, just ask. :smile:

**Comment by ccd0** [comment]
Working for me.  To be clear, are you checking the checkbox in the header menu?  It seems to be unchecked at the time you exported your settings.

![checkbox](https://cloud.githubusercontent.com/assets/5894749/7089956/823356ca-df54-11e4-9784-800c419cbd90.png)

If you have, are you using any other extensions?  Check if it works with all other extensions (including OneeChan) disabled, and if it does, turn them back on one by one until you find what's causing the problem.

**Comment by ccd0** [comment]
Is this still a problem?

**Comment by aphirst** [comment]
I can confirm that this is indeed no longer a problem. Frankly, if it ever was a problem, I now strongly suspect that it had been entirely my own fault. Feel free to close.
