### ISSUE TITLE
keeps autoscrolling to new open image?

### ISSUE THREAD

**Issue by throwaway666** [ccd0/4chan-x#379]
anytime a new image loads 4chanx seems to automatically scroll to the newly opened image which is pretty annoying. didn't see anything in the settings to turn this off. slower internet so i tend to open a couple of images, read a few posts and then go back to see what i opened but this makes that impossible, not to mention trying to do this with comics/manga and having my reading interrupted by a new image load.

using the "open all images" function doesn't do this, just individually loading images. why is this?

**Comment by ccd0** [comment]
In the header menu there's an "Image Expansion" menu.  Try turning off "Scroll into view."

**Comment by throwaway666** [comment]
i've looked through twice even ctrl+f 'scroll' and have no option like that anywhere
