### ISSUE TITLE
'Open thread in background tab' keybind removed

### ISSUE THREAD

**Issue by azazas** [ccd0/4chan-x#380]
Or at least I can't see it anywhere now. When I'm going through the catalog I usually open a few threads I want to read in background tabs, but now it switches right to the tab when I open it

**Comment by ccd0** [comment]
Check your browser preferences.  In Firefox it's "When I open a link in a new tab, switch to it immediately" on the General settings page.

**Comment by azazas** [comment]
Yes, I had that option turned off already (and turning it on then off didn't change the behaviour). I also tried disabling TabMixPlus and Classic Theme Restorer, the only things I can think might be interfering, and no change. New tabs opened any other way seem to behave fine, it's just 4chanX that's being weird. If you can't reproduce it I'll try starting a new profile, probably about due anyway.

**Comment by ccd0** [comment]
You never said what specifically you were clicking / pressing to open the threads.

**Comment by ccd0** [comment]
Sorry, I was a bit confused because you said "catalog" but the "open thread in new tab" doesn't work in catalog mode.  This is a Greasemonkey issue: https://github.com/greasemonkey/greasemonkey/issues/2105

**Comment by azazas** [comment]
Oh right yeah, index mode is what I meant. Thanks for clarifying, hopefully it gets fixed by the GM guys.
