### ISSUE TITLE
Index Refresh Failed (0)

### ISSUE THREAD

**Issue by ManofJupiter** [ccd0/4chan-x#382]
![index refresh failed error 0](https://cloud.githubusercontent.com/assets/11928802/7120746/49bc29c6-e1c4-11e4-8895-4d42322c47bd.png)

So I try to open up 4chan today from chrome and this is what happens, just that error appears and nothing seems to be working. I already tried disabling ADBLock, all the extensions, I already tried to access the site from different browsers and this still happens. 

Seems like it's not happening to other people since I can still see the threads in foolz going by.

Help?

**Comment by ccd0** [comment]
Sometimes https://a.4cdn.org/v/catalog.json is broken on 4chan's end.  When this happens, you can still browse 4chan by turning off the "JSON Navigation" option.

**Comment by ccd0** [comment]
Is this still happening, or was it just a temporary most-likely-network issue?

**Comment by Red-M** [comment]
I still get this issue but mine comes up as just the board with no threads at all. Same error.

**Comment by ccd0** [comment]
@Red-M

Every time or just occasionally?  It should happen occasionally when catalog.json fails to load, and you should be able to fix it by refreshing the index.

**Comment by Red-M** [comment]
@ccd0 https://db.tt/Sqz5OcUJ

**Comment by Red-M** [comment]
@ccd0 I believe the issue is my AV and someone posting something that looks like a mouse disable JS script. g, v and vr now work and the  others I tested. The reason for why I think this is now I can't get on 8chan's /meta/ and I got the same problem but all the other boards work.


So end of the story, pls ignore this was due to a troll.

**Comment by ccd0** [comment]
To be clear, do you mean some text someone posted apparently triggered a false positive in a web security product, and the problem goes away when you disable the security product?

**Comment by Red-M** [comment]
yes.
