### ISSUE TITLE
Posts read count not updating if I post ("Unread" crashed on node Post No.71208769 (co). NS_ERROR_FACTORY_NOT_REGISTERED: see console for details)

### ISSUE THREAD

**Issue by josereyes53** [ccd0/4chan-x#383]
If I post on a thread the script stops counting the posts I've read afterwards. If I refresh it takes me back to my post, and all subsequent posts in the thread appear as unread. I'm using SeaMonkey 2.33.1 and Greasemonkey 3.1. I realize that SeaMonkey isn't officially supported, but I thought to open an issue anyway, to see if it could be resolved somehow.

**Comment by ccd0** [comment]
Can you paste the error from the console?
If it's a compatibility issue, you might be able to get it to work in Greasemonkey 1.15 or 2.3.

**Comment by josereyes53** [comment]
I downgraded to 1.15 and still had the same issue.

![error console 2015-04-13 17 17 52](https://cloud.githubusercontent.com/assets/11931866/7125688/10816b48-e201-11e4-901d-e8dba1cdea00.png)

I also got a lot of those declaration dropped warnings. SeaMonkey's error console is quite different from Firefox's, I apologize if it isn't as helpful.

**Comment by ccd0** [comment]
Can you find where it says NS_ERROR_FACTORY_NOT_REGISTERED?

**Comment by ccd0** [comment]
Also, you might want to try this:
http://sourceforge.net/projects/gmport/

**Comment by josereyes53** [comment]
I in fact can't find NS_ERROR_FACTORY_NOT_REGISTERED in the console. The closest thing was what I found on the screenshot I posted, and it's not even appearing again. I still get the error, on 1.15, 2.3, 3.1, and even on the SeaMonkey port of Greasemonkey.

**Comment by ccd0** [comment]
I tried this on the Seamonkey port of Greasemonkey and wasn't able to reproduce.  Does it happen with default settings and all other add-ons disabled?

**Comment by josereyes53** [comment]
New Seamonkey profile + Greasemonkey port, and default 4chan x settings. Still got the same error, but it actually is updating the read count now

**Comment by ccd0** [comment]
Apparently Seamonkey doesn't support Javascript access to the console by default.  Can you turn on browser.dom.window.console.enabled in about:config and check the console for the error again?

**Comment by josereyes53** [comment]
This is what I get:
![error console 2015-04-15 00 54 02](https://cloud.githubusercontent.com/assets/11931866/7152447/26bfb7ca-e30a-11e4-8b14-529dc8151a34.png)
And this is what appears if I click on the errors:
![source of_ file](https://cloud.githubusercontent.com/assets/11931866/7152457/4a4d229a-e30a-11e4-8d31-b2d816f7c700.png)

**Comment by ccd0** [comment]
Ew.  Try editing the script and removing the

        try {

and

        } catch (_error) {
          err = _error;
          if (!errors) {
            errors = [];
          }
          errors.push({
            message: ['"', name, '" crashed on node ', this.type, ' No.', node.ID, ' (', node.board, ').'].join(''),
            error: err
          });
        }

from around line 1027 so you can see where it's crashing.

**Comment by josereyes53** [comment]
Error Console reports this:
![error console](https://cloud.githubusercontent.com/assets/11931866/7158621/fa12e892-e349-11e4-9b48-d6f729ed69b3.png)
Line 13273:
![source of_ file](https://cloud.githubusercontent.com/assets/11931866/7158625/097c16b4-e34a-11e4-83e4-bfc6cbf3bd7f.png)

**Comment by ccd0** [comment]
Turns out I wasn't reproducing it because I forgot to give 4chan X notification permissions.  I'm seeing this now.  Seems to be a known Seamonkey bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1130502.

**Comment by josereyes53** [comment]
Well alright, I can live without notifications for now. Thanks for the help

**Comment by ccd0** [comment]
I added a workaround anyway.  Crashes should no longer happen with desktop notifications enabled in v1.11.2.0+.
