### ISSUE TITLE
4chan X encountered an error while posting. 

### ISSUE THREAD

**Issue by sersh** [ccd0/4chan-x#390]
I've been getting that error for weeks so I checked the console and found the error below

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sys.4chan.org/int/post. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by ccd0** [comment]
To be clear, are the posts being made?

If you're using any other addons, or any proxies or web filtering software, try disabling them temporarily to see if they're causing the problem.

**Comment by sersh** [comment]
>To be clear, are the posts being made?
No, it makes me retype a captcha and then I have to submit it again

**Comment by ccd0** [comment]
Do the original post form or the native quick reply work?  Also, have you checked everything in
https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions#what-does-4chan-x-encountered-an-error-while-posting-please-try-again-mean
?

**Comment by sersh** [comment]
>Do the original post form or the native quick reply work?

Yes, this error seems to randomly appear every now and then and yeah I've also checked the FAQ

**Comment by ccd0** [comment]
It's not unexpected for 4chan to have intermittent network issues.  There isn't anything I can do about that.

**Comment by sersh** [comment]
It happens at least 10 times a day :c
