### ISSUE TITLE
Option to remove shadow behind board title

### ISSUE THREAD

**Issue by TwilightSkyline** [ccd0/4chan-x#393]
Personal problem. Also the font seems to be different, so a way to toggle both would be nice.

**Comment by ccd0** [comment]
You can revert to the default look with this in your custom CSS:

    div.boardTitle {
      font-family: Tahoma,sans-serif !important;
      font-weight: bold !important;
     text-shadow: none !important;
    }

Although I'm thinking about removing the shadow / font change and letting people who want them add them with custom CSS.

**Comment by ccd0** [comment]
Moved to custom CSS.
