### ISSUE TITLE
Filter fix

### ISSUE THREAD

**Issue by InstallGentoo11** [ccd0/4chan-x#398]
Can we have an option or something that makes the filter not pick up words inside of words? For example to not pick up fag in asjdfopisadjfag.

**Comment by bakugo** [comment]
You can use `\b` to match word boundaries. For example, `/\bfag\b/` will match "something fag" but not "somethingfag"

**Comment by InstallGentoo11** [comment]
Nice, it would good if it is included in the guide then. Seems like people with tons of filters, like myself, would appreciate to know about. Thanks for educating the stupid.

**Comment by ccd0** [comment]
There's a link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions in the guide, but I suppose it's easy to miss.  Maybe we could do something to make it stand out more?

**Comment by InstallGentoo11** [comment]
I have no idea where exactly you have linked, but it would be good to add a link on this page
![untitled](https://cloud.githubusercontent.com/assets/6108677/7444558/a50808fa-f190-11e4-81cf-f9cec00c4892.jpg)

Also add the \b thing among the others. I really think it is one of the more important ones to have, considering it helps a lot with decreasing the random stuff you pick up.

**Comment by InstallGentoo11** [comment]
I just realized on the pic the REGULAR EXPRESSIONS thing. Ha. Fucking hell. Maybe making it full caps will help.

**Comment by ccd0** [comment]
I underlined it.  Do you think that's enough, or would something like

Use regular expressions, one per line. See [this guide](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) for how to write.

would be better?

**Comment by InstallGentoo11** [comment]
It is probably enough. I guess I will close the thread?

Keep on the good work!
