### ISSUE TITLE
/fit/ archive change

### ISSUE THREAD

**Issue by prospektor** [ccd0/4chan-x#399]
Hi there, 
it'd be great if the archive for /fit/ could be changed to https://archive.moe/fit/ ; currently, only imcute.yt is an option to choose, and this seems to be dead (at least for me, at least right now). If there is any such option to add it myself I didn't find it and would be grateful an according instruction.

**Comment by ccd0** [comment]
You must be using an out-of-date version.  Updating 4chan X should fix your problem.

**Comment by ccd0** [comment]
Did that fix it?

**Comment by prospektor** [comment]
Oops, sorry, yes it did. For some reason I had to manually do that, but now it works fine. Thanks.
