### ISSUE TITLE
thread watcher request

### ISSUE THREAD

**Issue by ansamech** [ccd0/4chan-x#40]
would it be possible to get an option that makes the thread watched act as if in toggle mode, but never disappear when refreshing, and automatically be open when opening a new tab?

thanks

**Comment by ccd0** [comment]
In the newest beta (v1.10.8.0), the thread watcher will remember if you had it open or not.

**Comment by ccd0** [comment]
Update: I didn't like having to close the thread watcher after opening a thread, so I changed the way this works.  As of v1.10.8.4 `Fixed Thread Watcher` and `Toggleable Thread Watcher` are separate options.  Turning on `Fixed Thread Watcher` but not `Toggleable Thread Watcher` will do the same thing as @InstantHands's workaround.

**Comment by ansamech** [comment]
awesome work with the new fixes! one thing tho, when toggle is disabled, as in, when the watcher is always visible, it only shows current board, then on mouse over shows the others

**Comment by ccd0** [comment]
@ansamech
I changed the maximum height to apply when the thread watcher is non-fixed instead of when it's non-toggleable.

**Comment by ansamech** [comment]
perfect! thanks!
