### ISSUE TITLE
Does infinite scroll work?

### ISSUE THREAD

**Issue by Talcon** [ccd0/4chan-x#401]
I noticed there's an option for infinite scroll in the settings, with the default set to on, but infinite scroll doesn't seem to be working. Am I doing something wrong?

Firefox 37.0.2
4chan X version downloaded from here just today https://ccd0.github.io/4chan-x/
Greasemonkey 3.1

Infinite scroll worked when I used the native 4chan extension

**Comment by ccd0** [comment]
You need to select it from the drop-down menu at the top of the index.

![screenshot from 2015-05-05 13 19 51](https://cloud.githubusercontent.com/assets/5894749/7482090/bc233560-f329-11e4-83db-12153dc365d5.png)

**Comment by Talcon** [comment]
Thanks!
