### ISSUE TITLE
"Scroll to last read post" not working anymore

### ISSUE THREAD

**Issue by KragV** [ccd0/4chan-x#402]
It used to work but hasn't for like two weeks or so, reopening a thread just drops me at the OP, the Unread Line still works though.

Using version 1.10.11.12 on Chrome Version 43.0.2357.52 beta-m (64-bit)

**Comment by ccd0** [comment]
How are you opening the thread?

**Comment by KragV** [comment]
I usually let Chrome open the tabs from my last session automatically when it starts and it doesn't work that way. Now I'm wondering if it ever did.
Seems to work when opening them from the catalog.

**Comment by ccd0** [comment]
Tested this out.  It seems to be working for me.  Is it still not working for you?
