### ISSUE TITLE
Index refresh failed

### ISSUE THREAD

**Issue by ferongr** [ccd0/4chan-x#403]
Page spits this error trying to load the board normal index. Latest Nightly, Greasemonkey 3.1, latest 4chan-x

`14:42:29.181 Index failure: pages[0] is undefined Index.parseThreadList@file:///C:/Users/ferongr/AppData/Roaming/Mozilla/Firefox/Profiles/wg32mlmd.default/gm_scripts/4chan_X/4chan-X.user.js:3702:7
Index.parse@file:///C:/Users/ferongr/AppData/Roaming/Mozilla/Firefox/Profiles/wg32mlmd.default/gm_scripts/4chan_X/4chan-X.user.js:3694:7
Index.load@file:///C:/Users/ferongr/AppData/Roaming/Mozilla/Firefox/Profiles/wg32mlmd.default/gm_scripts/4chan_X/4chan-X.user.js:3660:11
Index.update/Index.req<.onloadend@file:///C:/Users/ferongr/AppData/Roaming/Mozilla/Firefox/Profiles/wg32mlmd.default/gm_scripts/4chan_X/4chan-X.user.js:3625:18
1 4chan-X.user.js:3666:9
Index.load() 4chan-X.user.js:3666
Index.update/Index.req<.onloadend() 4chan-X.user.js:3625`

**Comment by bakugo** [comment]
4chan is broken right now, some boards like /b/ have broken/empty indexes that cause that error, too.

**Comment by ferongr** [comment]
Werks now. Oh well.
