### ISSUE TITLE
Thread isn't loading, thread info is blank

### ISSUE THREAD

**Issue by oluapris** [ccd0/4chan-x#405]
https://a.pomf.se/mhzyct.png
Other threads work fine and this one loads if I disable 4chan X. What do?

**Comment by ccd0** [comment]
Hard to say what happened since it's deleted now.  Might have been an effect of whatever the mods did.  Let me know if you see it again.

**Comment by ccd0** [comment]
If this was one of the cases where a thread turns into a one-post stub instead of a 404 when it's deleted, these are recognized as deleted threads by 4chan X now and are redirected to the archive.
