### ISSUE TITLE
Resurrect quotes doesn't work in catalog mode

### ISSUE THREAD

**Issue by hotdogman** [ccd0/4chan-x#406]
Browser version: Firefox 38.0
4chan X version: 1.10.12.4 beta
Greasemonkey version: 3.1

Tested with a clean profile and default 4chan X settings.

Steps to reproduce:
1. Set index mode to paged
2. Go to a board where an OP links to a dead thread (/d/)
3. Hover over the dead thread, notice that it resurrects it from the archive
4. Set index mode to catalog
5. Hover over the dead thread, notice that it is not resurrected from the archive

Video/example test case (NSFW, /d/): https://a.pomf.se/varvfu.webm

**Comment by ccd0** [comment]
That's because it hasn't been implemented there yet.

**Comment by ccd0** [comment]
It's implemented now.
