### ISSUE TITLE
Large blank area at bottom of threads

### ISSUE THREAD

**Issue by deadman3000** [ccd0/4chan-x#409]
Since the last update I now have a large blank are at the bottom of threads underneath the last line of 4chan trademark/copyright notice. I made sure to disable any scripts and AdBlock but it persists.

**Comment by ccd0** [comment]
What browser are you using, and can you give an example of a page it's happening on?

**Comment by deadman3000** [comment]
Please delete. It's some plugin issue. I should have started the browser in safe mode before posting. Sorry to waste your time.

**Comment by ccd0** [comment]
I'll close the issue, but it might be useful to let other people know what plugin was the problem, at least once you figure it out.

**Comment by deadman3000** [comment]
On 23/05/2015 21:37, ccd0 wrote:
>
> I'll close the issue, but it might be useful to let other people know 
> what plugin was the problem, at least once you figure it out.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ccd0/4chan-x/issues/409#issuecomment-104943371>.
>
Video DownloadHelper was the culprit.
