### ISSUE TITLE
Comment field in QR can't be resized properly on chrome

### ISSUE THREAD

**Issue by bakugo** [ccd0/4chan-x#413]
When "Remember QR Size" is on, making the comment field bigger and refreshing the page makes it impossible to make it smaller.

This only seems to happen in chrome, in firefox it works normally.

**Comment by ccd0** [comment]
I take it you're using Tampermonkey?
That option has apparently never worked right in Chrome, so it's disabled in the Chrome extension.  I'll need to fix it so it's disabled in Tampermonkey as well.

**Comment by bakugo** [comment]
I am. I guess I'll just disable it, then. Thanks for the info.
