### ISSUE TITLE
Latest update killed 4chan X

### ISSUE THREAD

**Issue by Dopebear** [ccd0/4chan-x#414]
Latest update seemingly removed/killed 4chan X. No features are on anymore. What gives? I'll fiddle around and see if anything fixes it.

Disabling and enabling OneeChan works just fine with no change to 4chan x.

EDIT: Reinstalling it somehow resolved the issue. At least for now--can't see any issues. I'll keep this here in-case this happens to anyone else. This is the first time this has happened for me.

**Comment by ccd0** [comment]
Are you the same person as
https://rbt.asia/g/thread/S48324332#p48326758
https://rbt.asia/g/thread/S48324332#p48326809
?
My best guess is that something went wrong with downloading the update, leaving you with a corrupt file, and re-downloading it fixed it.

**Comment by matt31** [comment]
Same thing happened with me. Reinstalling it worked, thanks.
