### ISSUE TITLE
Firefox freezes whenever refreshing the page or opening an image. 

### ISSUE THREAD

**Issue by yankeeboy1865** [ccd0/4chan-x#416]
This has been happening since Firefox 38.0. Whenever I open a new page with more than 200 posts or open an image in a new tab, Firefox will freeze for about 30 seconds. After turning disabling all plug-ins and extensions, I figured out that this was only happening with 4chan-x. 

My 4chan-x is updated to 1.10.13.4

**Comment by ccd0** [comment]
Does it happen with 4chan X alone?  It could be an interaction with another plugin/extension.

Try the stuff in
https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by yankeeboy1865** [comment]
Hey thanks. After trying out the stuff you mentioned in that article, I saw that the issue was due to a conflict with DownloadHelper 5.3.1.1
