### ISSUE TITLE
Embedded videos

### ISSUE THREAD

**Issue by deadman3000** [ccd0/4chan-x#417]
So this has been going on for some time now but I thought I would mention it now because it's been going on for so long. Embedded video's end up not being embedded until I refresh the page (the auto refresh after each post thereafter does nothing). The links look broken and clicking on the 'embed' option does nothing. Only a physical full refresh embeds the video into the thread. When it does work I get a link with the embed option which when I click it opens up the video in the top right hand corner. Whereas a hard refresh causes video's to end up under the posting.

I am not sure what is going on here.

**Comment by ccd0** [comment]
>The links look broken

Can you post a screenshot?  And link to a post where this happened?

Also, I did a quick test of floating embedding of a Youtube video in a post added by the updater and I didn't see any problems, so try this stuff to isolate why it's happening in your case:
https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by deadman3000** [comment]
Here is a cap of when I post a Youtube URL

http://i.imgur.com/9F9Becy.jpg

If I don't do a full refresh it will stay like that (even as new posts arrive) and clicking on the embed option does nothing. If I do a full page refresh the video gets embedded into the thread like so.

http://i.imgur.com/S4Xwgfg.jpg

However if someone else makes a new post with a Youtube URL it has a line with the embed option which I can click on and the video plays in the upper right hand corner. BUT! When I hit escape  the video disappears and the line becomes like in the first cap above again. A hard refresh is then required and it ends up like in the second image again.

I shall have to try a profile copy and restart with all addons disabled except Greasemonkey and 4chan-x. If it still does it I will pass you my 4chan-x settings file.
