### ISSUE TITLE
Thread watcher menu cut off (was: Thread watcher not working)

### ISSUE THREAD

**Issue by jackbyo** [ccd0/4chan-x#418]
Default settings, latest version of chrome.

Thread watcher only works manually. Does not auto watch threads I have posted in

No other extensions (only have adblocker) seem to be interfering

What do?

**Comment by ccd0** [comment]
> Does not auto watch threads I have posted in
It doesn't do that under default settings; you have to turn it on in the thread watcher menu.

**Comment by jackbyo** [comment]
where is thread watcher menu?

Under settings > main > monitoring, there are three checkboxes for thread watcher. All are ticked (by default). Still does not auto follow threads

**Comment by saxamaphone69** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/877480/8120357/978712d2-10e1-11e5-9543-da710935305e.png)

**Comment by ccd0** [comment]
Working for you now?

**Comment by jackbyo** [comment]
![screen shot 2015-06-30 at 4 32 04 pm](https://cloud.githubusercontent.com/assets/12841225/8425088/a4878daa-1f45-11e5-9e8c-1672cbe48e7a.png)

Yeah it's working now, although you can see the issue I was having in this photo. The list of checkboxes under settings is hidden by the border of the thread watcher window. Only by minimizing font to 50% can I view enough of the checkboxes to tick the one I wanted.

4chan x 1.11.1.3
chrome 43.0.2357.130 64bit
os x 10.10.1

Thanks everyone

**Comment by ccd0** [comment]
> The list of checkboxes under settings is hidden by the border of the thread watcher window.

Well, it definitely shouldn't do that.  Mind posting your exported settings?

**Comment by jackbyo** [comment]
{
  "version": "1.11.1.3",
  "date": 1435646777958,
  "Conf": {
    "JSON Navigation": true,
    "Use 4chan X Catalog": true,
    "Index Refresh Notifications": false,
    "External Catalog": false,
    "Catalog Links": false,
    "Announcement Hiding": true,
    "Desktop Notifications": true,
    "404 Redirect": true,
    "Archive Report": true,
    "Except Archives from Encryption": false,
    "Keybinds": true,
    "Time Formatting": true,
    "Relative Post Dates": true,
    "Relative Date Title": true,
    "Comment Expansion": true,
    "File Info Formatting": true,
    "Thread Expansion": true,
    "Index Navigation": false,
    "Reply Navigation": false,
    "Custom Board Titles": true,
    "Persistent Custom Board Titles": false,
    "Show Updated Notifications": true,
    "Color User IDs": false,
    "Remove Spoilers": false,
    "Reveal Spoilers": false,
    "Show Support Message": true,
    "Normalize URL": true,
    "Disable Autoplaying Sounds": false,
    "Disable Native Extension": true,
    "Enable Native Flash Embedding": true,
    "Linkify": true,
    "Link Title": true,
    "Embedding": true,
    "Auto-embed": false,
    "Floating Embeds": false,
    "Anonymize": false,
    "Filter": true,
    "Filtered Backlinks": false,
    "Recursive Hiding": true,
    "Thread Hiding Buttons": true,
    "Reply Hiding Buttons": true,
    "Stubs": true,
    "Image Expansion": true,
    "Image Hover": true,
    "Image Hover in Catalog": false,
    "Gallery": true,
    "Fullscreen Gallery": false,
    "PDF in Gallery": false,
    "Sauce": true,
    "WEBM Metadata": true,
    "Reveal Spoiler Thumbnails": false,
    "Replace GIF": false,
    "Replace JPG": false,
    "Replace PNG": false,
    "Replace WEBM": false,
    "Image Prefetching": false,
    "Fappe Tyme": false,
    "Werk Tyme": false,
    "Autoplay": true,
    "Restart when Opened": true,
    "Show Controls": true,
    "Click Passthrough": false,
    "Allow Sound": true,
    "Mouse Wheel Volume": true,
    "Loop in New Tab": true,
    "Volume in New Tab": true,
    "Menu": true,
    "Report Link": true,
    "Thread Hiding Link": true,
    "Reply Hiding Link": true,
    "Delete Link": true,
    "Download Link": true,
    "Archive Link": true,
    "Thread Updater": true,
    "Unread Count": true,
    "Quoted Title": false,
    "Hide Unread Count at (0)": false,
    "Unread Favicon": true,
    "Unread Line": true,
    "Scroll to Last Read Post": true,
    "Thread Excerpt": true,
    "Remove Thread Excerpt": false,
    "Thread Stats": true,
    "IP Count in Stats": true,
    "Page Count in Stats": true,
    "Updater and Stats in Header": true,
    "Thread Watcher": true,
    "Fixed Thread Watcher": true,
    "Toggleable Thread Watcher": true,
    "Mark New IPs": false,
    "Quick Reply": true,
    "QR Shortcut": true,
    "Persistent QR": true,
    "Auto Hide QR": true,
    "Open Post in New Tab": true,
    "Remember QR Size": false,
    "Remember Spoiler": false,
    "Show New Thread Option in Threads": false,
    "Show Name and Subject": false,
    "Hide Original Post Form": true,
    "Cooldown": true,
    "Posting Success Notifications": true,
    "Use Recaptcha v1": false,
    "Force Noscript Captcha": false,
    "Auto-load captcha": false,
    "Post on Captcha Completion": false,
    "Bottom QR Link": true,
    "Captcha Fixes": true,
    "Use Recaptcha v2 in Reports": false,
    "Quote Backlinks": true,
    "OP Backlinks": true,
    "Quote Inlining": true,
    "Quote Hash Navigation": false,
    "Forward Hiding": true,
    "Quote Previewing": true,
    "Quote Highlighting": true,
    "Resurrect Quotes": true,
    "Mark Quotes of You": true,
    "Highlight Posts Quoting You": false,
    "Highlight Own Posts": false,
    "Mark OP Quotes": true,
    "Mark Cross-thread Quotes": true,
    "Quote Threading": false,
    "Fit width": true,
    "Fit height": false,
    "Scroll into view": true,
    "Expand spoilers": true,
    "Expand videos": true,
    "Expand from here": false,
    "Advance on contract": false,
    "Hide Thumbnails": false,
    "Fit Width": true,
    "Fit Height": true,
    "Stretch to Fit": false,
    "Scroll to Post": true,
    "Slide Delay": 6,
    "Default Volume": 1,
    "Current Board": false,
    "Auto Update Thread Watcher": true,
    "Auto Watch": true,
    "Auto Watch Reply": true,
    "Auto Prune": false,
    "Show Unread Count": true,
    "name": "# Filter any namefags:\n#/^(?!Anonymous$)/",
    "uniqueID": "# Filter a specific ID:\n#/Txhvk1Tl/",
    "tripcode": "# Filter any tripfag\n#/^!/",
    "capcode": "# Set a custom class for mods:\n#/Mod$/;highlight:mod;op:yes\n# Set a custom class for moot:\n#/Admin$/;highlight:moot;op:yes",
    "subject": "# Filter Generals on /v/:\n#/general/i;boards:v;op:only",
    "comment": "# Filter Stallman copypasta on /g/:\n#/what you're refer+ing to as linux/i;boards:g",
    "flag": "",
    "filename": "",
    "dimensions": "# Highlight potential wallpapers:\n#/1920x1080/;op:yes;highlight;top:no;boards:w,wg",
    "filesize": "",
    "MD5": "",
    "sauces": "https://www.google.com/searchbyimage?image_url=%IMG\nhttp://iqdb.org/?url=%IMG\nhttp://eye.swfchan.com/search/?q=%name;types:swf;sandbox\n#//tineye.com/search?url=%IMG\n#https://www.yandex.com/images/search?rpt=imageview&img_url=%IMG\n#//saucenao.com/search.php?url=%IMG\n#http://3d.iqdb.org/?url=%IMG\n# tools:\n#http://regex.info/exif.cgi?imgurl=%URL\n#//imgops.com/%URL;types:gif,jpg,png\n# uploaders:\n#//imgur.com/upload?url=%URL;types:gif,jpg,png,pdf;text:Upload to imgur\n# \"View Same\" in archives:\n#https://archive.moe/_/search/image/%MD5/;text:View same on archive.moe\n#https://archive.moe/%board/search/image/%MD5/;text:View same on archive.moe/%board/;boards:a,an,biz,c,co,diy,fit,gd,gif,h,i,int,jp,k,m,mlp,out,po,qa,r9k,s4s,sci,tg,u,v,vg,vp,vr,wsg\n#https://rbt.asia/%board/image/%MD5;text:View same on RBT /%board/;boards:cgl,g,mu,qa,w",
    "werk": false,
    "Custom CSS": false,
    "Index Mode": "catalog",
    "Previous Index Mode": "paged",
    "Index Sort": "bump",
    "Index Size": "small",
    "Show Replies": true,
    "Pin Watched Threads": false,
    "Anchor Hidden Threads": true,
    "Refreshed Navigation": false,
    "Fixed Header": true,
    "Header auto-hide": false,
    "Header auto-hide on scroll": false,
    "Bottom Header": false,
    "Centered links": false,
    "Header catalog links": false,
    "Bottom Board List": true,
    "Shortcut Icons": true,
    "Custom Board Navigation": true,
    "boardnav": "[ toggle-all ]\na-replace\nc-replace\ng-replace\nk-replace\nv-replace\nvg-replace\nvr-replace\nck-replace\nco-replace\nfit-replace\njp-replace\nmu-replace\nsp-replace\ntv-replace\nvp-replace\n[external-text:\"FAQ\",\"https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions\"]",
    "QR.personas": "#options:\"sage\";boards:jp;always",
    "captchaLanguage": "",
    "time": "%m/%d/%y(%a)%H:%M:%S",
    "backlink": ">>%id",
    "fileInfo": "%l (%p%s, %r%g)",
    "favicon": "ferongr",
    "usercss": "",
    "Toggle board list": "Ctrl+b",
    "Toggle header": "Shift+h",
    "Open empty QR": "q",
    "Open QR": "Shift+q",
    "Open settings": "Alt+o",
    "Close": "Esc",
    "Spoiler tags": "Ctrl+s",
    "Code tags": "Alt+c",
    "Eqn tags": "Alt+e",
    "Math tags": "Alt+m",
    "Toggle sage": "Alt+s",
    "Submit QR": "Ctrl+Enter",
    "Watch": "w",
    "Update": "r",
    "Expand image": "Shift+e",
    "Expand images": "e",
    "Open Gallery": "g",
    "Pause": "p",
    "Slideshow": "Ctrl+Right",
    "fappeTyme": "f",
    "werkTyme": "Shift+w",
    "Front page": "1",
    "Open front page": "Shift+1",
    "Next page": "Ctrl+Right",
    "Previous page": "Ctrl+Left",
    "Paged mode": "Alt+1",
    "Infinite scrolling mode": "Alt+2",
    "All pages mode": "Alt+3",
    "Open catalog": "Shift+c",
    "Search form": "Ctrl+Alt+s",
    "Cycle sort type": "Alt+x",
    "Next thread": "Ctrl+Down",
    "Previous thread": "Ctrl+Up",
    "Expand thread": "Ctrl+e",
    "Open thread": "o",
    "Open thread tab": "Shift+o",
    "Next reply": "j",
    "Previous reply": "k",
    "Deselect reply": "Shift+d",
    "Hide": "x",
    "Previous Post Quoting You": "Alt+Up",
    "Next Post Quoting You": "Alt+Down",
    "Beep": false,
    "Auto Scroll": false,
    "Bottom Scroll": false,
    "Scroll BG": false,
    "Auto Update": true,
    "Ignore Offline Status": false,
    "Optional Increase": false,
    "Interval": 30,
    "customCooldown": 0,
    "customCooldownEnabled": true,
    "hiddenThreads": {
      "boards": {}
    },
    "hiddenPosts": {
      "boards": {},
      "lastChecked": 1435638257072
    },
    "lastReadPosts": {
      "boards": {
        "adv": {
          "15857883": 15858024
        },
        "k": {
          "23385784": 23385784,
          "26336412": 26342155,
          "26343101": 26343352,
          "26343372": 26344866
        },
        "o": {
          "12880633": 12881597
        },
        "out": {
          "38571": 144777,
          "507426": 539923,
          "510912": 535484,
          "520386": 544716,
          "523955": 523955,
          "524800": 540834,
          "528315": 534610,
          "529720": 536428,
          "531636": 543686,
          "532116": 542183,
          "532478": 535482,
          "532754": 535710,
          "533016": 545083,
          "533519": 538385,
          "533711": 536257,
          "534310": 544728,
          "534881": 534998,
          "535075": 535558,
          "535367": 535445,
          "535448": 535483,
          "535522": 535522,
          "536231": 540856,
          "536407": 536447,
          "536498": 538363,
          "536537": 537626,
          "536576": 540363,
          "536628": 536867,
          "536876": 536895,
          "537129": 539734,
          "537163": 538958,
          "537224": 541124,
          "537225": 537229,
          "537317": 537661,
          "537403": 538431,
          "537508": 540929,
          "537640": 537662,
          "537736": 537996,
          "537928": 537965,
          "537970": 537987,
          "537997": 540126,
          "538061": 539647,
          "538233": 540420,
          "538255": 538262,
          "538365": 540893,
          "538367": 538382,
          "538390": 538391,
          "538403": 538409,
          "538405": 538421,
          "538427": 538433,
          "538437": 538437,
          "538438": 538459,
          "538475": 540426,
          "538586": 539724,
          "538761": 540412,
          "539039": 539048,
          "539266": 539733,
          "539349": 539387,
          "539418": 539689,
          "539438": 539515,
          "539450": 539472,
          "539453": 539574,
          "539488": 544371,
          "539656": 540209,
          "539669": 539678,
          "539815": 540860,
          "539844": 541795,
          "539869": 539906,
          "540113": 541060,
          "540135": 544157,
          "540191": 540263,
          "540241": 540349,
          "540339": 545104,
          "540367": 540367,
          "540568": 544543,
          "540595": 540922,
          "540676": 541101,
          "540734": 541065,
          "540767": 544941,
          "540791": 540823,
          "540871": 540902,
          "540935": 540939,
          "540952": 541080,
          "541104": 541776,
          "541146": 541151,
          "541785": 541796,
          "541797": 541797,
          "543004": 544356,
          "543316": 545012,
          "543806": 544368,
          "543893": 545000,
          "544097": 544104,
          "544158": 544229,
          "544329": 544436,
          "544516": 544779,
          "544771": 544959,
          "544958": 545036
        }
      },
      "lastChecked": 1435636892893
    },
    "yourPosts": {
      "boards": {
        "o": {
          "12880633": {
            "12881444": true
          }
        },
        "out": {
          "507426": {
            "536845": true
          },
          "520386": {
            "539602": true
          },
          "533016": {
            "541135": true
          },
          "533519": {
            "533622": true,
            "533623": true
          },
          "534310": {
            "536570": true
          },
          "536498": {
            "536559": true
          },
          "538438": {
            "538438": true
          },
          "538761": {
            "540412": true
          },
          "539844": {
            "540255": true
          },
          "540135": {
            "540199": true
          },
          "540339": {
            "540408": true,
            "545104": true
          },
          "540568": {
            "540933": true
          },
          "540767": {
            "541156": true
          },
          "544329": {
            "544372": true
          },
          "544958": {
            "545036": true
          }
        }
      },
      "lastChecked": 1435636892827
    },
    "watchedThreads": {
      "boards": {
        "out": {
          "520386": {
            "excerpt": "/out/ - God tier footwear",
            "isDead": false,
            "quotingYou": 0,
            "unread": 1
          },
          "531636": {
            "excerpt": "/out/ - gear recommendation thread",
            "isDead": false,
            "quotingYou": 0,
            "unread": 0
          },
          "532116": {
            "excerpt": "/out/ - Scourge of the woods",
            "isDead": true,
            "quotingYou": 0,
            "unread": 0
          },
          "533016": {
            "excerpt": "/out/ - Post your backpacking gear.",
            "isDead": false,
            "quotingYou": 0,
            "unread": 0
          },
          "534310": {
            "excerpt": "/out/ - Questions That Don't Deserve Their Own Thread, Thread",
            "isDead": false,
            "quotingYou": 0,
            "unread": 0
          },
          "540135": {
            "excerpt": "/out/ - Been on /out/ for quite a while. // Never seen a knot thread.",
            "isDead": false,
            "quotingYou": 0,
            "unread": 0
          },
          "540339": {
            "excerpt": "/out/ - Hammock camping",
            "isDead": false,
            "quotingYou": 0,
            "unread": 0
          },
          "540568": {
            "excerpt": "/out/ - But why do you hate hippies /out/? // Why can't you let the lo...",
            "isDead": false,
            "quotingYou": 0,
            "unread": 0
          },
          "540767": {
            "excerpt": "/out/ - ARCHERY THREAD",
            "isDead": false,
            "quotingYou": 0,
            "unread": 0
          },
          "544329": {
            "excerpt": "/out/ - Watching gear reccomendation videos, sticker is still on.",
            "isDead": false,
            "quotingYou": 0,
            "unread": 0
          },
          "544771": {
            "excerpt": "/out/ - Welcome to /mreg/, or Meal Ready-to-Eat General, post your fav...",
            "isDead": false,
            "quotingYou": 0,
            "unread": 2
          },
          "544958": {
            "excerpt": "/out/ - books.",
            "isDead": false,
            "quotingYou": 2,
            "unread": 7
          }
        }
      },
      "lastChecked": 1435646426242
    },
    "customTitles": {
      "boards": {}
    },
    "selectedArchives": {}
  }
}

**Comment by ccd0** [comment]
Can you test if putting this in custom CSS (on the advanced panel) fixes things?

    #thread-watcher, :root:not(.fixed-watcher) #thread-watcher:not(:hover) {
      max-height: initial;
      overflow: initial;
    }
    #watched-threads {
      overflow-x: hidden;
      overflow-y: auto;
      max-height: calc(100vh - 75px);
    }
    :root:not(.fixed-watcher) #watched-threads:not(:hover) {
      max-height: 210px;
      overflow-y: hidden;
    }

**Comment by ccd0** [comment]
Or better, don't add the custom CSS (remove it if you have), and see if the latest beta version (v1.11.2.1) works.

**Comment by jackbyo** [comment]
Latest beta works perfect.

thanks
