### ISSUE TITLE
Posting issue

### ISSUE THREAD

**Issue by Dopebear** [ccd0/4chan-x#419]
My posts sometimes doesn't get posted and this error pops up "4chan X encountered an error while posting. [Banned?] [More info]" and I'm not banned. This is a recent thing too and I can't find out what causes it. It's seemingly random. Say, every second/third post will have this. But I can post successfully after the second try. Meaning, this error doesn't pop up more than once per post.

Firefox: 38.0.5
Greasemonkey: 3.2
4chanX: 1.10.13.4
OneeChan: 5.5.25

**Comment by ccd0** [comment]
That's a connection error with 4chan, probably due to a problem with 4chan or your network connection.

**Comment by Dopebear** [comment]
Happens every day, every ~3 posts will get it. I can't see how it'd be my connection, it seems stable.

**Comment by ccd0** [comment]
Are you using any other browser extensions/plugins/userscripts, or any products like Avast Web Shield?  Try temporarily disabling them to see if there's a conflict.

Try disabling 4chan X and posting 10ish of the same images that gave you errors.  You'll probably have the same problem.

**Comment by Dopebear** [comment]
I'll install 4chan X on another browser, keep the default settings and try that.

You think I the error only occurs with image posts? I don't think that's the case. I'll keep a further eye out for it.

**Comment by ccd0** [comment]
Sorry, I meant testing without 4chan X under the same conditions (same or similar comment or image) that gives you errors with 4chan X.  If you can reliably get errors with 4chan X but not without, that might indicate a problem with 4chan X, but most likely this has nothing to do with 4chan X.

**Comment by Dopebear** [comment]
Seems to be fixed now that I've enabled the "Use Recaptcha v1" in 4chan x settings.
