### ISSUE TITLE
Shift+Click won't hide catalog threads in latest Nightly

### ISSUE THREAD

**Issue by sanitysama** [ccd0/4chan-x#420]
This is more of an issue with Nightly, but it would be nice to be able to change the hotkey to hide catalog threads since Nightly is now using the shift+click shortcut to open links in new windows. Shift+click still works as intended in Firefox stable.

**Comment by ccd0** [comment]
Shift+click has always opened links in new windows.  4chan X should be overriding this behavior in the catalog, and if it doesn't, it's a bug.  I'm not seeing the bug in the current Nightly, so hopefully it was just a bug in Nightly that got fixed?  Let me know if it's still happening, because if something like that hits stable, we'll need to work around it.

**Comment by sanitysama** [comment]
Really sorry but it turns out it's caused by the Tab Mix Plus extension. No idea why it's programmed to reinforce default shift+click behavior, but thread hiding works fine with TMP disabled.

**Comment by ccd0** [comment]
Can confirm.  Well, it doesn't seem to be preventing our events from being registered, so it's probably not something that can be worked around on 4chan X's end.

**Comment by Denveous** [comment]
> This is more of an issue with Nightly, but it would be nice to be able to change the hotkey to hide catalog threads since Nightly is now using the shift+click shortcut to open links in new windows. Shift+click still works as intended in Firefox stable.

Shift+click was never the default hotkey for firefox, chrome, IE, or any browser in windows for opening a new tab. It's been ctrl+click since the early 90s.

**Comment by Denveous** [comment]
> This is more of an issue with Nightly, but it would be nice to be able to change the hotkey to hide catalog threads since Nightly is now using the shift+click shortcut to open links in new windows. Shift+click still works as intended in Firefox stable.

Since Firefox introduced tabs back in the early 2000s the button combo for opening a new tab has always been ctrl+click not shift+click, the shift+click action opens a new window. (if you can't ctrl+click to open a new tab you had modified your settings)
