### ISSUE TITLE
Firefox Unrepsponsive script when opening image file with 4chanx

### ISSUE THREAD

**Issue by itbeely** [ccd0/4chan-x#422]
While using the 4chanx extension when I open an image/gif/webm in a new tab from a thread, Firefox will either hang, or give an unresponsive script error
(Script: resource://gre/modules/commonj…helper/data/gallery-content.js:121)

I tested by disabling greasemonkey and opening the same file in a new tab and there was no hanging.

**Comment by itbeely** [comment]
Sorry this can be closed. Figured it out. 
It was due to Video DownloadHelper Version 5.3.1.1-signed
Using Version 5.2.0.1-signed seems to work.

**Comment by tenkuu** [comment]
You can close the issue too.
