### ISSUE TITLE
Error dump, image error, etc

### ISSUE THREAD

**Issue by Xibster** [ccd0/4chan-x#424]
The first error is a full spam of errors retaining to opening up a tread from the index/catalog (clicking reply to open up whole tread).

             "File Info Formatting" crashed on node Post No.XXXXXXXX (Y).
              HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy

http://i.gyazo.com/f172403ab058f844a6e06af7b34ce4bd.png

Second clicking an image brings i to full size but clicking again doesn't minimize it and just showed both minimized and maximized versions of the image

http://i.gyazo.com/f7e1b29b9a07bfbef1249c3f5f65d035.png

Final error is double replies. It showed double the replies to a single post.

http://i.gyazo.com/137d4b9526b33dbbff37a5347506f2f7.png
(You can see the dups of user ids [one dubs])

**Comment by ccd0** [comment]
It looks like you are running two different versions of 4chan X at once.  Look in your add-on settings and disable the other one.

**Comment by ccd0** [comment]
Working now?

**Comment by Xibster** [comment]
Yes
