### ISSUE TITLE
builds/4chan-X.crx is still version 1.10.14.4

### ISSUE THREAD

**Issue by spaghetti2514** [ccd0/4chan-x#426]
Github says the file was last updated with the "Release 4chan X v1.11.0.8." commit, but the crx still installs version 1.10.14.4
Doesn't seem to just be mis-versioned as the latest features are missing too.

Edit: Is 1.11.0.8 only for the beta extension? Why does the release touch every build?

**Comment by hotdogman** [comment]
4chan-X.crx is the stable version.
4chan-X-beta.crx is the beta version.

**Comment by spaghetti2514** [comment]
But then why is the stable build being touched by the 1.11.0.9 release commit? Does the build script just rebuild stable without changes after every beta release?
![screen shot 2015-06-21 at 8 36 09 pm](https://cloud.githubusercontent.com/assets/1966861/8274337/7573654e-1855-11e5-8b2a-f352d809f616.png)

**Comment by ccd0** [comment]
@spaghetti2514
That file is the most recent version.  The main links on the front page point at these files:
https://github.com/ccd0/4chan-x/tree/gh-pages/builds
(They're all 1.11.0.9 now, but they weren't earlier.)
At each release, all of those files are built, and when I want to move a version to stable or beta, I copy the appropriate files to the gh-pages branch.

**Comment by spaghetti2514** [comment]
Oh, okay.
