### ISSUE TITLE
Where does Firefox store the watched threads data?

### ISSUE THREAD

**Issue by KingCuck** [ccd0/4chan-x#427]
Had an HDD failure and the only thing I could salvage was the AppData folder.

**Comment by ccd0** [comment]
They're stored with `GM_setValue`, which Greasemonkey stores in an SQLite database:
http://wiki.greasespot.net/GM_setValue

Look for something like `gm_scripts/4chan_X.db` in your Firefox profile directory.

**Comment by KingCuck** [comment]
Thank you. I wasn't able to just copy paste the `X.watchedThreads` string (it would just reset some of your settings) but copying over the entire file worked.
