### ISSUE TITLE
using Gm 3.2 in Pale moon

### ISSUE THREAD

**Issue by Janaue** [ccd0/4chan-x#429]
Hello,

is it possible to make the script compatible with GM 3.2 for pale moon too ?

I use lots of scripts in pale moon which work only with GM versions higher than 2.0

**Comment by ccd0** [comment]
> is it possible to make the script compatible with GM 3.2 for pale moon too ?
Greasemonkey 3.2 doesn't work well enough in Pale Moon to be usable for scripts making use of much of the GM_* API:
https://github.com/greasemonkey/greasemonkey/issues/2182
https://github.com/greasemonkey/greasemonkey/issues/2185
If you need a working GM2+ in Pale Moon, you may have to fork it.

If you just need it working personally, you should be able to get it to work by building Greasemonkey after merging
https://github.com/greasemonkey/greasemonkey/pull/2183
https://github.com/greasemonkey/greasemonkey/pull/2187
and building 4chan X after merging the `palemoon` branch.

**Comment by janekptacijarabaci** [comment]
See
https://github.com/greasemonkey/greasemonkey/pull/2183#issuecomment-132635977
https://github.com/greasemonkey/greasemonkey/pull/2187#issuecomment-132636033

The partial and temporary solution to the problem:
https://github.com/janekptacijarabaci/greasemonkey/releases/latest

**Comment by ccd0** [comment]
I've put out a release that should work with the above at:

https://github.com/ccd0/4chan-x/raw/1.11.10.0/builds/4chan-X.user.js
