### ISSUE TITLE
Thread function stopped working, or rarely works

### ISSUE THREAD

**Issue by Brottweiler** [ccd0/4chan-x#436]
Using the user script with Tampermonkey Beta (`3.12.4699`) on Chrome (`44.0.2403.61` beta (64-bit)
), the extension ([4chan X beta](https://github.com/ccd0/4chan-x/blob/master/builds/4chan-X-beta.user.js) `1.11.3.2`), using updated today. Now functions in threads will not work. Sometimes when I go into a thread, it works (cache?), but after a refresh it stops. Tampermonkey Beta also updated to that version, today, btw.

What I mean with "thread function", is that in a thread, I still have the top bar, and can go into the 4chan X settings, and such. But inside the thread, nothing works. It works like if I didn't have the extension installed. Hovering on images doesn't enlarge them, clicking on them opens in a new tab, even if I have `Image Expansion` and `Image Hover` enabled.

There's no "Menu: Add a drop-down menu to posts." next to the reply number. Happens even after resetting to default settings.

Anyone else experianced this?

**Edit**: Seems like the chrome extension at the store works.

**Comment by ccd0** [comment]
Any error messages, either on the page or in the console (Control+Shift+J), when this happens?

**Comment by Brottweiler** [comment]
If I have the script disabled, and I check the error log, then I enable the script and refresh, I see no new errors.

**Comment by ccd0** [comment]
Are you using any other userscripts on 4chan besides 4chan X or extensions besides Tampermonkey?  Try turning them off temporarily to see if one of them is causing a conflict.

**Comment by ccd0** [comment]
Never mind the bit about other extensions, I've managed to reproduce the issue.  Might be a Tampermonkey Beta bug.

**Comment by ccd0** [comment]
I've reported it upstream:
https://github.com/derjanb/tampermonkey/issues/223

**Comment by ccd0** [comment]
This should be fixed in the newest Tampermonkey Beta (3.12.4704).
