### ISSUE TITLE
Page style refuses to change

### ISSUE THREAD

**Issue by Garbledina** [ccd0/4chan-x#438]
I recently cleared my cookies for 4chan, and the page style keeps changing back to the default 'switch' (which looks like Yotsuba B) from what I want, 'Tomorrow'. I wouldn't have raised issue here, but the 4chanX UI stays as switch(YB), like so: 
![0339473a41](https://cloud.githubusercontent.com/assets/1735491/8636014/ae5d7e90-280d-11e5-8e5c-1adbe77ccccf.jpg)

I don't know precisely what I've done wrong here. Deleting cookies and reinstalling 4chanX doesn't work, I'm just assuming that maybe if I find the issue with 4chanX I'll figure out the solution.

**Comment by ccd0** [comment]
In order for 4chan X to detect the style you're using, you need to leave your browser's page style setting on `switch` and choose the style you want with the drop-down menu at the bottom of the page.

**Comment by Garbledina** [comment]
Thank you, I can't believe I forgot something like that.
