### ISSUE TITLE
request : auto sage indicator

### ISSUE THREAD

**Issue by ampersham** [ccd0/4chan-x#441]
would go in this section right here  http://i.imgur.com/GniQ9tv.png

something like a little sage icon or plain text indicating auto sage.

maybe a sage icon which is monochrome and damped normally but becomes full color and glowing when autosage is active

**Comment by bui** [comment]
autosage can mean two things:

- if you mean the bump limit, this is already indicated with the post count turning red once the bump limit has been reached for that thread;
- if you mean manually bumplocked by a mod, there's no way to know when this happens. one possibility used to be checking the thread's position on the board index, but that has a whole slew of problems of its own: you can't differentiate sage vs. bumplock, and it'd cause problems with fast threads/boards
