### ISSUE TITLE
Option to not change scroll position on image expand

### ISSUE THREAD

**Issue by boomie123** [ccd0/4chan-x#443]
Last versions of 4chanx made a change to switch scroll position to view most of the expanded image when you expand any image.
This does not work for me: 4chan contains a lot of creepy and disturbing images; in the past I used to expand those and sloooowly scroll down to view them in full with an option to bail out and collapse image back because I'm a little girl like that. Right now the behavior is that they just cover my entire fullhd screen with a mouse click.
Please make an option to leave old behavior back.

**Comment by ccd0** [comment]
Uncheck "Scroll Into View" in the "Image Expansion" submenu in the header.

![screenshot from 2015-07-18 09-44-31](https://cloud.githubusercontent.com/assets/5894749/8762565/ae241e6a-2d31-11e5-88fe-d13f18e84d44.png)

**Comment by boomie123** [comment]
Yes, that works, thank you. I always forget there are several different places with settings
