### ISSUE TITLE
option/keyboard shortcut for resetting the timer?

### ISSUE THREAD

**Issue by CouldBeWhat** [ccd0/4chan-x#445]
sometimes it gets messed up and i have to wait for it to end in order to post a thread/post. it would be nice to have a keyboard shortcut or a small button to reset it. 

thank you for your work by the way, i love it.

**Comment by ccd0** [comment]
In addition to bypassing the cooldown timer, there should probably be a mechanism to bypass all the other conditions where 4chan X will prevent you from posting.

**Comment by ccd0** [comment]
requested again: #2572

**Comment by paradox460** [comment]
Shift click submit to bypass cooldown timers
