### ISSUE TITLE
legacy text CAPTCHA

### ISSUE THREAD

**Issue by lazy-lemon** [ccd0/4chan-x#449]
I noticed that users can use the legacy captcha with the vanilla extension when making quick replies.  I'm not sure exactly how 4chan verifies when it's right to use or not use the old captcha, but it would be nice if 4chanX could take advantage of it somehow.  I'd imagine that if the regular extension can do it, 4chanX ought to be able to do it as well somehow.  I don't know.  I wouldn't switch to the regular extention just to see the old captcha again, but I'd much rather use the old one than the new one.

**Comment by ccd0** [comment]
Check "Use Recaptcha v1" in your settings.

**Comment by lazy-lemon** [comment]
I was looking in the settings before.  I'm not sure why I didn't notice that.
