### ISSUE TITLE
WebM click passthrough not working

### ISSUE THREAD

**Issue by AliceTertia** [ccd0/4chan-x#450]
On the last couple of days, the webm part of the extension has completely stopped working for me, they are all pretty much being treated as gifs, and enabling click passthrough doesn't work as well, (dragging to the left to close it also doesn't work, only clicking "contract). Using Firefox nightly x64 on windows 10 64-bit.

**Comment by ccd0** [comment]
This is, as you might expect, a Nightly bug.  I've reported it upstream:
https://bugzilla.mozilla.org/show_bug.cgi?id=1192302

**Comment by AliceTertia** [comment]
Oh, alright then.

**Comment by ccd0** [comment]
Re-opening since it looks like Firefox 42 is going to ship with this unfixed.

**Comment by ccd0** [comment]
I think I misinterpreted and they are planning to fix this in Firefox 42 after all.
