### ISSUE TITLE
Captcha doesn't seem to be working at all right now

### ISSUE THREAD

**Issue by Ghosthree3** [ccd0/4chan-x#451]
Clicking the tick box leaves it indefinitely spinning and never brings up images/confirms. Disabled script and it worked just fine.

EDIT: My version wouldn't auto update for some reason, which is weird because it's been working for months. Went and force updated and it's working again.

EDIT2: Started happening again after one post, not sure what's going on, need to disable script to post.

**Comment by Chromanin** [comment]
Same here didn't work, worked once, couldn't get it to work again. Captcha and posting works fine if I disable 4chan-x.

**Comment by ccd0** [comment]
Here is the known issue:  If you have the QR autohiding (it will do this by default if "Persistent QR" is on), make sure you don't click outside the QR and autohide it while the captcha is loading, as that can put the captcha in that state.  But you should be able to fix it by closing and re-opening the captcha section with the "Captchas: #" link.

Other than that, I'm not seeing any problem.  If that's not it, is it still happening?  What browser are you using?  Does it happen with default settings and all other extensions disabled, or only in particular circumstances?

**Comment by xzerio** [comment]
I am also having this problem, It worked fine until one of the recent updates for 4chan x happened. ever since the captcha just keeps spinning and doesn't give me any pictures or text to complete.

**Comment by Ghosthree3** [comment]
Ok so for me it happens no matter what, if I click a post to reply/bring up the box, then hit the check box and do absolutely nothing, not even move the mouse, it'll still happen.

Using Pale Moon so using GM 1.1.5, might be too out of date? Did you upgrade the script?

**Comment by ccd0** [comment]
@xzerio
You can try older versions from https://github.com/ccd0/4chan-x/blob/master/CHANGELOG.md although I doubt that's the problem.  If you find it does work in older versions, let me know at what point it stops working.

**Comment by ccd0** [comment]
@Ghosthree3
Are you sure it's working consistently with 4chan X disabled?  If it's randomly working and not working, you might sometimes see it work with 4chan X disabled.  Can you test a few more times?

Also if you have `Auto-load captcha` on, try turning it off as it may cause problems.  You can also try turning off `Captcha Fixes` temporarily, although that setting is helpful (adds the numpad stuff, gets rid of the extra tab press) and I'm not aware of it causing any issues.  And can you confirm that 4chan X is not autohiding the QR at any point in the process?

You can also test
https://www.google.com/recaptcha/api2/demo
If you have issues with it, it's probably on Google's end.

Another thing to try is if you're blocking referrers, forge them instead.

**Comment by ccd0** [comment]
@Ghosthree3
As for Pale Moon, there's nothing in 4chan X I'm aware of that wouldn't work in Pale Moon, but I don't know about the captcha.

**Comment by Ghosthree3** [comment]
Was able to load the captcha properly 5 times in a row on both the demo page and with the script off. Script still failing, tried turning off captcha fixes but it didn't help, auto-load captcha was already off. Definitely not autohiding but I disabled that option anyway to check and it didn't help.

Not sure what you mean by blocking referrers so I guess I'm not using that.

**Comment by ccd0** [comment]
Does it work in the native extension's quick reply?

**Comment by ccd0** [comment]
You might also want to test whether there's any difference between http://boards.4chan.org and https://boards.4chan.org.

**Comment by ccd0** [comment]
OK, got Pale Moon running, I am seeing this problem.  So I should be able to investigate from this end now.

**Comment by Ghosthree3** [comment]
Oh thank you. What was the issue, out of curiosity.

**Comment by ccd0** [comment]
Greasemonkey in Pale Moon is reporting the wrong location URL when it's running in an iframe, among other things.  This was triggering the 404 redirect code (recently changed to accommodate those occasional deleted threads with a stub left behind) in the captcha.  I'll push out a workaround shortly.

**Comment by ccd0** [comment]
Alright, can you see if the new version works?

**Comment by Ghosthree3** [comment]
Yep, working good now thanks!

**Comment by DAT-SQUAZZ** [comment]
Thanks, this was an exceptionally annoying issue
