### ISSUE TITLE
Randomize filename

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#452]
from https://rbt.asia/g/thread/49609560
>With all the 4chan archives available, is there a way to randomize the name of a file every time you post it?
>Like if I would upload "ayylmao1111.jpg" it automatically changes to "13921849213.jpg" or some shit so that you can't find all my posts containing "ayylmao1111.jpg" in the archives?

>Make an option so when you add an image it gives you a random 4chan filename from the last 3 years or so (if it's an older timestamp it will stand out more).
>It should randomize when you add the image, so you can still click on the filename and rename it to overwrite it if you want to, for including source etc.

**Comment by ccd0** [comment]
This is now in the latest beta version (v1.11.9.0).

**Comment by WitnessMe** [comment]
I like option but sometimes you don't want to randomize every picture you post (i.e. for funny filenames). Is it possible to have a button in the header, a keybind or somewhere else to enable and disable this on the fly?

**Comment by ccd0** [comment]
It only randomizes the default filename; you can still edit it.
