### ISSUE TITLE
hover/expansion doesn't always work with quoted posts even though it's enabled

### ISSUE THREAD

**Issue by rainbowdashie1** [ccd0/4chan-x#453]
same thing with embed links

Firefox v40
Greasemonkey v3.3
4chan X v1.11.8.5 and v1.11.7.5

**Comment by ccd0** [comment]
It could be a bug, or it could be an issue with your Internet connection.  Can you find a post where you can make it happen consistently, and if so, can you link it?  And if you're using any other extensions, try turning them off temporarily to check for a conflict.  And try looking at your network activity in the console (press F12) when this happens.

**Comment by rainbowdashie1** [comment]
it seems to only affect posts after the thread was loaded, but not every post
I disabled all other extensions
nothing in network activity except the thread updating
my internet is fine http://www.speedtest.net/result/4580516745.png
>\# ping -f -c 100 8.8.8.8
>PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
>
>--- 8.8.8.8 ping statistics ---
>100 packets transmitted, 100 received, 0% packet loss, time 997ms
>rtt min/avg/max/mdev = 9.541/10.067/15.183/0.648 ms, pipe 2, ipg/ewma 10.075/9.880 ms

**Comment by ccd0** [comment]
Well, it's not your Internet because it's happening with posts from the same thread.
Are there any errors in the console when you hover over a link and the post doesn't show?
Can you check if the hover event listeners are there?  Right click > Inspect Element on a link that's not working.  There should be a little black "ev"; click on it and check if the "mouseover" event is there.
![events](https://cloud.githubusercontent.com/assets/5894749/9264504/0752425a-41dc-11e5-9e12-96960b531f11.png)

**Comment by rainbowdashie1** [comment]
nothing in the console
not there on those links
![2015-08-14_01-06-44](https://cloud.githubusercontent.com/assets/13788103/9264673/d4311c1c-4220-11e5-86ea-9e2b8f81b625.png)

**Comment by ccd0** [comment]
What's the other userscript?  Did you remember to refresh the page after turning it off?

**Comment by rainbowdashie1** [comment]
[[s4s] Enhancer](https://greasyfork.org/en/scripts/3329-s4s-enhancer)
and yes

**Comment by ccd0** [comment]
> [[s4s] Enhancer](https://greasyfork.org/en/scripts/3329-s4s-enhancer)

That script is causing the problem.  To fix it, the script should be rewritten to use DOM methods instead of `innerHTML`.

**Comment by ccd0** [comment]
Are there any issues like this with [s4s] Enhancer disabled?

If so, could you try retesting the stuff in
> Well, it's not your Internet because it's happening with posts from the same thread.
Are there any errors in the console when you hover over a link and the post doesn't show?
Also, can you check whether the hover event listeners are there? Right click > Inspect Element on a link that's not working. There should be a little black "ev"; click on it and check if the "mouseover" event is there.

with  [s4s] Enhancer disabled?

**Comment by ccd0** [comment]
Reported here:
https://greasyfork.org/en/forum/discussion/6070/rewriting-the-comment-with-innerhtml-removes-event-listeners

**Comment by rainbowdashie1** [comment]
I'm pretty sure I already disabled it, but I tried again and that fixed it, so apparently I'm retarded
anyway, I removed the parts of the script I don't want and changed the other parts
