### ISSUE TITLE
captcha not loading in pale moon in versions after v1.11.7.1

### ISSUE THREAD

**Issue by Janaue** [ccd0/4chan-x#454]
I have pale moon 25.6.0 with GM 2.0.1 [or even GM 1.15.1] and any version of 4chan X after v1.11.7.1 [v1.11.7.1 not included], up to v1.11.8.6 does not show the images for the captchas.

when i click on I am not a robot, there is the little blue circle  to show that the images are loading, but they never load. I never see the images, not even the window of the captcha. It just loads forever.

**Comment by ccd0** [comment]
Make sure you're on v1.11.7.5+ or v1.11.8.4+ and that you have reloaded the page.  Try disabling any other extensions or userscripts to see if they're causing a conflict.  If it's still happening, could you try adding

    c.log(location.href, window === window.top, !!(d.body && !d.head.firstChild), !!d.body, !!d.head.firstChild, doc.innerHTML);

to the script just above the

    if (d.body && !d.head.firstChild) {

line, and tell me what gets printed in the console (F12) when you load the captcha?

**Comment by Janaue** [comment]
the problem came from some  dark theme for youtube which was loaded before your script. once the youtube theme is loaded after your theme, I get the captchas.

**Comment by ccd0** [comment]
I suspected it might be something like that.  This we can probably fix on our end, though.  Can you link to the script?

**Comment by ccd0** [comment]
Okay, it should work in v1.11.8.7 no matter which order the scripts run in.
