### ISSUE TITLE
Right click context for catalogue?

### ISSUE THREAD

**Issue by Davidj361** [ccd0/4chan-x#457]
Can we get a feature where instead of needing to click the tiny arrow below the thread, you can right click the thread's OP picture and have a context option for hiding, reporting, filtering, etc? I just find it exasperating to click such a small arrow in order to hide a thread.

**Comment by ccd0** [comment]
I assume you mean in the catalog?
The native catalog does that, although I think the way they do it is Firefox-only.
You can also hide threads with Shift+click (in both), but it's not very discoverable unfortunately.

**Comment by Davidj361** [comment]
>You can also hide threads with Shift+click (in both), but it's not very discoverable unfortunately.
+1

**Comment by ccd0** [comment]
Is this still needed now that it shows the Shift+click shortcut in the menu?

**Comment by ccd0** [comment]
Closing assuming mentioning "Shift+click" in the menu suffices.
