### ISSUE TITLE
captcha language not following selected language code

### ISSUE THREAD

**Issue by Ofunniku** [ccd0/4chan-x#458]
Fx Nightly, 4chan X v1.11.8.9, and Greasemonkey are all up-to-date.

I tried changing the language from [en] to [en-GB] to no avail, still reads in local gibberish.

**Comment by ccd0** [comment]
Can you export and post your settings?

**Comment by Ofunniku** [comment]
sorry, just got back.

this isn't exactly as exported, I just nuked everything in the file past last read/watched/visited or something.

https://mega.nz/#!pgFHEJbb!bWIfyV0Pcaa2lgDXsVzwPbAdj3FT8gNMAf-ZBM_9vMg

**Comment by ccd0** [comment]
I don't think Recaptcha v1 is localized other than instructions like "Type the text", which you'd only see on the reports page / original post form.  Right now 4chan X doesn't do anything with the captcha language setting for v1.

What are you seeing that's a problem?  It's common to get random letters as the captcha; changing language settings won't help there.

**Comment by Ofunniku** [comment]
Thread reporting or ban checking.

It's very strange because it used to apply the language code for recaptcha v1 just fine until recently, was this change deliberate?

**Comment by Ofunniku** [comment]
not sure what was changed recently, but this seems to be fixed on my end, going to clear all google related cookies and check again...

**Comment by Ofunniku** [comment]
Alright, across browsers, this seems to fixed on my end, I'll go ahead and close the issue, though it would be interesting to know what fixed this.

**Comment by Ofunniku** [comment]
Alright, across browsers, this seems to fixed on my end, I'll go ahead and close the issue, though it would be interesting to know what fixed this.

**Comment by ccd0** [comment]
The captcha language setting has never applied to (Javascript-based) Recaptcha v1.  If the language you're seeing has changed, it's due to a change on Google's end.

**Comment by ccd0** [comment]
The language setting is now supported for v1.
