### ISSUE TITLE
Post layout messed up

### ISSUE THREAD

**Issue by BondiBear** [ccd0/4chan-x#467]
Since today, the layout of long posts in a thread are messed up. The post is set further to the left than the other posts and there is a gap to the post above. See attached example.
Using FF40.0.3 and 4chanx 1.11.9.5.

![ff layout](https://cloud.githubusercontent.com/assets/2057221/9549129/b1984218-4da4-11e5-89c2-72c7bce2e9e0.PNG)

**Comment by whoknows22** [comment]
Having this issue as well, but (at least on my end) it's not related to 4chanx. Doesn't seem to be a browser issue either as it happens on all my browsers but none of my friends see it so I have no idea what's causing it.

For the record, you can fix it by switching to the Yotsuba theme.

**Comment by ccd0** [comment]
Can you check if this CSS fixes it?  If so, I can add it to 4chan X.

It will need to be coordinated with @nebukazar to avoid breaking OneeChan.

.replyContainer {
  display: -webkit-flex;
  display: flex;
  margin: 2px 0px 4px;
}
div.reply {
  display: block;
  margin: 0;
  overflow: visible;
}
div.thread > div:nth-of-type(2) > div.reply {
  margin-top: 0 !important;
}

**Comment by whoknows22** [comment]
Fixed it for me. Didn't break Yotsuba (which was the only theme where it didn't happen) or anything.

**Comment by BondiBear** [comment]
Left alignment seems fixed, but the spacing between posts seems larger than before.

Can this be corrected?

**Comment by ccd0** [comment]
@BondiBear
I'm not seeing any difference on my end.  Can you check in the element inspector what the margins/borders/paddings on the replyContainer/sideArrows/reply divs are working out to be on your end?  And maybe post another screenshot?

**Comment by BondiBear** [comment]
I've attached some screens, I hope they contain what you are looking for.

Compare these to the two screens ('4x before & after'), and you can see the gaps between posts are larger.

FYI I use the 'Tomorrow' (black theme) in 4chan.

![4x before](https://cloud.githubusercontent.com/assets/2057221/9567084/61c5fd4a-4f1e-11e5-8efa-82103589f543.PNG)

![4x after](https://cloud.githubusercontent.com/assets/2057221/9567082/5b38e10e-4f1e-11e5-8b41-30f267ed16c8.PNG)


![4x1](https://cloud.githubusercontent.com/assets/2057221/9567066/9f1160be-4f1d-11e5-8622-e137d40b4b80.PNG)

![4x2](https://cloud.githubusercontent.com/assets/2057221/9567067/9f11d3b4-4f1d-11e5-9198-5e391489d93f.PNG)

![4x3](https://cloud.githubusercontent.com/assets/2057221/9567065/9f105e1c-4f1d-11e5-91e7-0637151b6ed9.PNG)

**Comment by ccd0** [comment]
@BondiBear https://github.com/ccd0/4chan-x/issues/467#issuecomment-136130845
I don't see the `div.reply` part of the CSS showing up in the rules in the last image.  Could you double-check the CSS you entered?

**Comment by BondiBear** [comment]
I re-checked and get the same problem (also with all 4chan styles).
Maybe if nobody else has a problem with this fix, it's something to do with my particular configuration(?)

I say add it if it checks out for you.

**Comment by ccd0** [comment]
Are you adding the CSS with 4chan X's custom CSS field or some other way?  If it's some other way, that might be the problem.

On the other hand, if you're adding CSS rules with 4chan X's custom CSS setting, and the CSS rules aren't showing up, there's a bug that needs to be fixed, or at the very least a conflict that maybe we can possibly work around.  Maybe you can check whether the custom CSS is being added to `<head>` in the right place, and that the `<style>` element contains the right CSS?  It should be the last thing:

![screenshot from 2015-08-30 17-14-09](https://cloud.githubusercontent.com/assets/5894749/9570257/d7a4c9a8-4f3a-11e5-93b0-95af40b708d2.png)

**Comment by ccd0** [comment]
By the way, make sure you all report this to
https://www.4chan.org/feedback
because it would really be best fixed on 4chan's end.  It would be annoying to fix this one way, and have to redo everything when 4chan fixes it another way.

**Comment by BondiBear** [comment]
Oops, I did add it another way, but adding in 4chanx fixed the problem!
I'm sorry - I am not an expert.

Please add this fix to 4chanx. Great work!

**Comment by ccd0** [comment]
Working on a new version of the CSS using `display: table-cell` since it's more likely 4chan will fix it this way, when they get around to it (old IE versions don't support `display: flex`).  See if this still works for you.

    .replyContainer {
      display: table;
      margin: 2px 0px 4px;
    }
    .inline .replyContainer {
      margin: 0;
    }
    .replyContainer > div {
      display: table-cell;
    }
    .replyContainer > div:first-of-type {
      vertical-align: top;
    }
    div.sideArrows {
      float: none;
      padding: 0 2px;
    }
    .hide-reply-button {
      float: none;
      display: block;
    }

**Comment by BondiBear** [comment]
Yes, this works just as well as the previous code.

**Comment by ccd0** [comment]
Is this still happening to people?  (with custom CSS turned off)
Could anyone affected by this issue test whether it's still there with OneeChan installed and "Fit Width" turned on in the Oneechan options (under replies)?

**Comment by nebukazar** [comment]
I haven't encountered this on my end.

**Comment by whoknows22** [comment]
Doesn't happen with OneeChan installed and custom CSS turned off. Still does without OneeChan, though.

**Comment by ccd0** [comment]
@whoknows22
Does it happen with OneeChan with "Fit Width" turned off?  I think that's what makes the difference.

@nebukazar
Is there a reason for the `!important` at
https://github.com/nebukazar/OneeChan/blob/c20d5bfb5fe38a1296d55b39d97385d41f8cf63a/src/css/Original.css#L57
?
It seems to be making the CSS more complicated because you have to go back and re-hide hidden posts.
Similarly, do you know why the `#delform` part of the selector is there?

**Comment by nebukazar** [comment]
https://github.com/nebukazar/OneeChan/commit/a35391bbc252921213d0a142e23a169eb86aedc1

Checked the commit history but seaweed closed his issues page so I'm not sure what the original purpose was, although it seems to be working fine if you remove `#delform` and `!important`. Is it causing problems on your end?

**Comment by ccd0** [comment]
>Is it causing problems on your end?

Not currently but that part is going to have to be rewritten if I do the table-cell fix, so I want to make sure I'm not breaking anything.

**Comment by nebukazar** [comment]
Since this isn't happening for everyone it would be interesting to find out what is causing it for certain people before we do any changes.

**Comment by ccd0** [comment]
For anyone experiencing this, can you list the extensions you are using, and test with them disabled?  Especially ad blockers; someone updating a filter list could explain this happening across multiple browsers.

**Comment by whoknows22** [comment]
>Does it happen with OneeChan with "Fit Width" turned off?

Nope. I didn't mess around with OneeChan's settings too much but it doesn't seem to happen at all with it installed.

>For anyone experiencing this, can you list the extensions you are using, and test with them disabled?

I only use AdBlock Plus, NoScript and Greasemonkey, but it still happens with all of them turned off (and on browsers with no extensions installed at all). That's what makes it weird.

**Comment by ccd0** [comment]
@whoknows22
Can you give the version of one of the browsers with no extension and your operating system?
Do you have any plugins installed?

**Comment by whoknows22** [comment]
Fresh Chrome install, 45.0.2454.85 m. I'm on Windows 8.1.

Then again according to the most recent thread on /qa/ this fixed itself for some people so I don't know if anyone other than me is still getting it.

**Comment by BondiBear** [comment]
Tried it on vanilla FF 40.0.3 (no extensions, settings all default), and the issue still occurs.
This is FF 32bit running on Win 8.1 64bit.

**Comment by ccd0** [comment]
For anyone still seeing this, does a hard refresh (Control+F5) make it go away?  If not, could you check the CSS on the replies with Inspect Element?  Specifically whether `div.reply` has `display: table` or `display: inline-block`?

![screenshot](https://cloud.githubusercontent.com/assets/5894749/9977569/d76dceee-5ec1-11e5-8ab9-dc5a81aaab96.png)

**Comment by whoknows22** [comment]
Mine says inline-block.

**Comment by ccd0** [comment]
It looks like the problem here is that the 4chan admins have been updating the CSS without bumping the version number, causing Cloudflare to serve users old versions it has cached.

**Comment by ccd0** [comment]
Looks like they bumped the CSS version number, and it turns out it's the *new* CSS that's broken, and most people didn't notice because they were still getting the old version.

But it seems once everyone got the broken CSS, they noticed it pretty quick and reverted it.  So this should be fixed now.

**Comment by whoknows22** [comment]
Yeah, completely fixed for me.

**Comment by BondiBear** [comment]
Seems back to normal. Thanks for the support.
