### ISSUE TITLE
Tree Style Tab support

### ISSUE THREAD

**Issue by ldgbc** [ccd0/4chan-x#470]
When opening with keybind: Open thread in new tab. tab does not open as a child tab.
There is API available here: http://piro.sakura.ne.jp/xul/_treestyletab.html.en#api

**Comment by ccd0** [comment]
This would need to be fixed in Greasemonkey; 4chan X just calls `GM_openInTab`.

**Comment by ccd0** [comment]
https://github.com/greasemonkey/greasemonkey/issues/2055
