### ISSUE TITLE
Feature request: Anchored image hover

### ISSUE THREAD

**Issue by Swerving** [ccd0/4chan-x#471]
I'm sure you all are familiar how the image hover works by default without the plugin, How it opens to the upper-right corner of the screen instead of following the mouse cursor.

Its a preference thing.

**Comment by ccd0** [comment]
Also requested at
https://rbt.asia/g/thread/S53881761#p53886237

**Comment by zixaphir** [comment]
"Classic" is a misnomer -- we've done image hovering longer than 4chan.
Perhaps anchored? Or locked in place?

**Comment by ccd0** [comment]
I'm thinking of doing what 8chan does and having an option named "Follow Cursor", on by default, which you would uncheck to get this behavior.

**Comment by zixaphir** [comment]
Sounds great
