### ISSUE TITLE
Dynamic loading fails on some boards.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#479]
Submitter: ANON
Email: senkou@cock.li
Iceweasel 38.2.1
Greasemonkey 3.4
4chanX 1.11.10.4
This has been going on for a while but I couldn't be arsed to report it.

On some boards (tested: /g/, /t/, /a/) loading the catalog and auto updating threads works fine. On others (tested: /adv/) it doesn't.
When opening the board page I get "Index refresh failed. Error (0)" pretty much immediately. Thread refresh fails silently.
The error console shows an error "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://a.4cdn.org/adv/catalog.json. (Reason: CORS request failed)." on the affected boards and not the others.

**Comment by bakugo** [comment]
Using Firefox and uBlock causes this.

**Comment by ccd0** [comment]
This is a known problem caused by ad filter lists thinking anything on /adv/ is an advertisement.  You'll need to add an exception for *.4chan.org/adv/* and *.4cdn.org/adv/*.

**Comment by ccd0** [comment]
should be marked as duplicate of #217
