### ISSUE TITLE
Dead quotelinks re-open current thread in a new tab

### ISSUE THREAD

**Issue by bakugo** [ccd0/4chan-x#482]
If a post is added by the updater, marked as deleted, and a new post quoting the first is added (in that order), the dead quotelink in the second post re-opens the current thread in a new tab instead of scrolling to the post.

**Comment by ccd0** [comment]
Couldn't reproduce, but this might be settings dependent.  Could you post your current settings under which this happens?

**Comment by bakugo** [comment]
Just tested on a clean install of 4chan X, it only happens if Quote Inlining is disabled. My settings are [here](http://pastebin.com/raw.php?i=3FW8AURM) if they're still needed.
Seems like it's caused by [this line](https://github.com/ccd0/4chan-x/blob/master/src/Quotelinks/Quotify.coffee#L56).

**Comment by ccd0** [comment]
Thanks, I'm seeing it now.  Should be fixed as of v1.11.11.1+.

**Comment by bakugo** [comment]
Seems to be fixed. Thanks.
