### ISSUE TITLE
Trustable extension?

### ISSUE THREAD

**Issue by Fasmea** [ccd0/4chan-x#484]
Excuse me for asking this question. I recently bought a 4chan Pass and now I'm worried that this extension might send my data (4chan Pass password or even tripcode etc.) somewhere else.
Should I uninstall this extension or is it legit?
Please, this is a honest question and I've been paranoid about lots of things lately.
Thanks in advance.

**Comment by ccd0** [comment]
It doesn't do anything like that, but if you're paranoid, you should be reviewing the source code instead of asking me, shouldn't you?

**Comment by Fasmea** [comment]
Thanks for the response. I already did that.

**Comment by ccd0** [comment]
The one caveat I should mention is that if you use the Chrome extension version and have Chrome Sync enabled, your settings, which will include your tripcode and posting history, will be stored on Chrome Sync.  Same on Firefox if you enable the (experimental, undocumented, unsupported, and very buggy) feature of Greasemonkey to sync script data with Firefox Sync.  Other browsers and user script engines may do their own things with settings.

4chan X doesn't do anything with 4chan Pass credentials at all.

I'm going to write up a page documenting what data 4chan X stores, and what sites other than 4chan it communicates with.

**Comment by ccd0** [comment]
Added said documentation here:
https://github.com/ccd0/4chan-x/wiki/Privacy

**Comment by Fasmea** [comment]
That's great to hear, thanks!
