### ISSUE TITLE
Full comments in catalog

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#489]
Nothing urgent but I think the catalog mode should look like this:

![Image](http://i.imgur.com/7cvO1lJ.png)

`.catalog-thread {
display: inline-flex;
text-align: left;
flex-direction: column;
align-items: center;
margin: 0 2px 5px;
word-break: break-word;
vertical-align: top;
vertical-align: top;
margin: 5px 10px 10px;
text-align: center;
width: 165px;
padding: 5px;
background: #D6DAF0;
border: 2px solid #B7C5D9;
max-height: 275px;
}
.catalog-thread > .subject {
color: #0F0C5D;
}
.catalog-thread:hover{background: #CACEE4;}
`

NSFW Style:
`.catalog-thread {
display: inline-flex;
text-align: left;
flex-direction: column;
align-items: center;
margin: 0 2px 5px;
word-break: break-word;
vertical-align: top;
vertical-align: top;
margin: 5px 10px 10px;
text-align: center;
width: 165px;
padding: 5px;
background: #f0e0d6;
border: 2px solid #D9BFB7;
max-height: 275px;
}.catalog-thread > .subject {
color: #cc1105;
}.catalog-thread:hover{background: #E4D5CC;}
`

**Comment by ididntknowicoulddothatXD** [comment]
/* Tomorrow */
    .catalog-thread {
    display: inline-flex;
    text-align: left;
    flex-direction: column;
    align-items: center;
    margin: 0 2px 5px;
    word-break: break-word;
    vertical-align: top;
    vertical-align: top;
    margin: 5px 10px 10px;
    text-align: center;
    width: 165px;
    padding: 5px;
    background: #282a2e!important;
    border: 2px solid #111!important;
    max-height: 275px;
    }

.catalog-thread:hover {
    background: #1D1D21!important;
    }

.catalog-thread > .subject {
    color: #b294bb!important;
    }

/* Photon */

.catalog-thread {
    display: inline-flex;
    text-align: left;
    flex-direction: column;
    align-items: center;
    margin: 0 2px 5px;
    word-break: break-word;
    vertical-align: top;
    vertical-align: top;
    margin: 5px 10px 10px;
    text-align: center;
    width: 165px;
    padding: 5px;
    background: #DDD!important;
    border: 2px solid #BBB!important;
    max-height: 275px;
    }

.catalog-thread:hover {
    background: #CCC!important;
    }

.catalog-thread > .subject {
    color: #111!important;
    }

**Comment by ccd0** [comment]
I don't see scroll bars on the comment when I try it. Did you leave that out?
In my opinion, being able to view the full comment is one of the biggest things that need fixing in the catalog.

An alternate approach to scroll bars would be showing the full comment on hover:
https://github.com/ccd0/4chan-x/compare/catalog

    .catalog-thread:hover > .comment {
      overflow: visible;
      z-index: 1;
      background-color: inherit;
    }
    :root.burichan .catalog-thread:hover {
      background-color: #D6DAF0;
      outline: 1px solid #B7C5D9;
    }
    :root.futaba .catalog-thread:hover {
      background-color: #F0E0D6;
      outline: 1px solid #D9BFB7;
    }
    :root.photon .catalog-thread:hover {
      background-color: #DDD;
      outline: 1px solid #CCC;
    }
    :root.tomorrow .catalog-thread:hover {
      background-color: #282A2E;
      outline: 1px solid #111;
    }
    :root.yotsuba-b .catalog-thread:hover {
      background-color: #D6DAF0;
      outline: 1px solid #B7C5D9;
    }
    :root.yotsuba .catalog-thread:hover {
      background-color: #F0E0D6;
      outline: 1px solid #D9BFB7;
    }

![screenshot from 2015-11-22 14-21-47](https://cloud.githubusercontent.com/assets/5894749/11326689/72672ad2-9124-11e5-9089-4b84e4a19e47.png)

What do you think?

**Comment by ccd0** [comment]
![catalog-status](https://cloud.githubusercontent.com/assets/5894749/18756698/b5781cfc-80a5-11e6-9345-ef56bd1da337.png)
This is the status of the catalog right now. I'm thinking of adding file info on top and excerpts of replies on bottom, where if you hover over the excerpt, the post is shown.

**Comment by ididntknowicoulddothatXD** [comment]
>What do you think?
[...]

>This is the status of the catalog right now. I'm thinking of adding file info on top and excerpts of replies on bottom, where if you hover over the excerpt, the post is shown.

As long as I can still go back to the default styles and options I use in my OP, it's fine.
Sorry if this sounds demanding or anything but I wouldn't like to be unable to overwrite this new style.

**Comment by ccd0** [comment]
>As long as I can still go back to the default styles and options I use in my OP, it's fine. (Using the 4chan X catalog)

Of course, you may have to rewrite your custom catalog CSS when all the changes are done, but it will still be possible to make it look how you want.

**Comment by ccd0** [comment]
Do people think the default highlight color for watched threads in the Tomorrow theme should be changed? Currently it's blue, which doesn't stand out much. Would red, as #1101 suggests, be better?

**Comment by ididntknowicoulddothatXD** [comment]
>Of course, you may have to rewrite your custom catalog CSS when all the changes are done, but it will still be possible to make it look how you want.

That's great-- I just can't see myself becoming a fan of the way you implemented hovering, since I prefer the addition of scrollbars.

**Comment by ccd0** [comment]
Keeping open even though this is on stable since there are a few things still to be addressed:

- Should we get rid of the extra padding on `.board` and depend on https://github.com/ccd0/4chan-x/commit/0d09c63d7c677ca411e3e989652743527409460f to shift the thread on screen?
- Should the highlighting in the catalog in the Tomorrow style be switched to red? This should probably be a separate issue.
- See if we can do anything to improve performance while scrolling. A lot of stuff gets hovered/unhovered causing a bit of lag.
- Other complaints / feedback that I get after moving this to stable.

**Comment by ccd0** [comment]
From http://boards.4chan.org/qa/thread/817335#p824852:
> please remove the new thing that you have to click on the catalog to activate thread info hovering. I have to do it every time I refresh the page or change board, it's annoying. If I don't want threads to hover I can just uncheck the option from the menu.

I replied:
> How about making it so that it remembers it state? So if you refresh or change boards, it stays on, but you can turn it off easily by clicking?
but there was no response before thread died. Probably going to take this approach.
