### ISSUE TITLE
RECAPTCHA filling using keypad is returning "mistyped captcha" and can't be completed

### ISSUE THREAD

**Issue by HASJ** [ccd0/4chan-x#497]
Mouse clicking behaves normally.

**Comment by ccd0** [comment]
The keypad still works for me most of the time, although I also have seen an increase in bogus "mistyped captcha" errors.  Try it a few more times; it's probably not the keypad/mouse change that's making the difference.

**Comment by ccd0** [comment]
Is this still happening?

**Comment by HASJ** [comment]
No. I think it only happened for about two days after I posted the issue and it was fixed either by one of your updates, 4chan or google.
