### ISSUE TITLE
Console throws Uncaught TypeError: Illegal invocation When trying to export settings

### ISSUE THREAD

**Issue by ramenchef** [ccd0/4chan-x#498]
I am on Chrome Version 47.0.2522.0 dev-m (64-bit) running 4chan X through TamperMonkey BETA Version: 3.12.4812.

Uncaught TypeError: Illegal invocation
Settings.downloadExport @ VM87:16624
(anonymous function) @ VM87:16613
(anonymous function) @ VM87:1081
$.queueTask.execTask @ VM87:883

**Comment by ccd0** [comment]
Does the bug occur in stable Chrome and/or stable Tampermonkey?

**Comment by ramenchef** [comment]
Occurs in stable tampermonkey. Does not occur when using extension from webstore. I am not currently able to access a stable chrome installation. I will attempt to do so later on.

**Comment by ccd0** [comment]
Most likely due to
https://forum.tampermonkey.net/viewtopic.php?f=17&t=1324
same as #501.

**Comment by ccd0** [comment]
Does this happen in the latest TamperMonkey BETA? (3.12.4851)  It looks like it should be fixed:
https://tampermonkey.net/changelog.php?version=3.12.4851&show=gcal
