### ISSUE TITLE
Bottom-of-page board list present

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#500]
Submitter: Deckard
Email: doctorretro.4chan@gmail.com
Until recently, the script has been working fine for me. I didn't make any changes to the script or settings, but somehow it broke anyway. Now it's enabled the bottom-of-page board list and it's wiped my custom board navigation setup.

**Comment by ccd0** [comment]
It sounds like something caused your settings to become corrupt.  If you haven't reset them already, can you try exporting your settings so we can find out what happened and possibly recover them?

**Comment by DeckardEdward** [comment]
I imported an old settings pack that I saved from Noface's 4X a while ago -after- the corruption happened, but the corruption's still there. Will exporting my current settings still be useful?

Also, it might be worth noting that I've used several different versions of 4X, so I suppose bits and pieces of things that they saved might still be in places that I don't know about. I'm not exactly that well-versed in scripting...

**Comment by ccd0** [comment]
I tried importing those settings, and I see what appears to be your custom board list
`[+] [b / d / f / t / v / vg / vr] [i / ic] [y] [adv / an / ck / co / fit / int / lit / n / po / sci / tg / wsg] [aco] [Down?] [Banned?]`
with the bottom board list turned on.  Is this what you see also?  I don't see anything obviously wrong in the data.

What browser are you using?  If it's Firefox with Greasemonkey, do you have `extensions.greasemonkey.sync.values` turned on?  If you do, you should turn it off, because it's completely broken and could cause the sort of behavior you're describing.

Maybe starting over in a fresh profile would help?  (If you're using Firefox.)  It sounds like it might be a problem with your browser and/or the way it stores 4chan X's settings rather than with 4chan X itself.

**Comment by DeckardEdward** [comment]
Yeah, that's my board list how I've set it up after my other custom arrangement got wiped. The bottom board list is the full board list, uneditable and embedded at the very bottom of the page, not floating.

I'm using FIrefox, and I'll take a look at the sync setting as soon as I post this. I'm willing to bet that's probably switched on, if it's the likely cause.

**Comment by DeckardEdward** [comment]
Wait a minute. Would services.sync.prefs.sync.extensions.greasemonkey.sync.values;true have something to do with this?

**Comment by ccd0** [comment]
> Would services.sync.prefs.sync.extensions.greasemonkey.sync.values;true have something to do with this?

I don't think so.  That looks like it just says whether to sync the value of `extensions.greasemonkey.sync.values`.

**Comment by DeckardEdward** [comment]
Okay, I made a new profile and I have 4X set back up how I had it before. I'll drop a new comment here if my settings get reset again.

In the meantime, I have one last minor question. Is there a way to format the custom header tags on an external link to make it open in a new tab when clicked?

**Comment by ccd0** [comment]
> Is there a way to format the custom header tags on an external link to make it open in a new tab when clicked?

There's not a good way at the moment, but it would be easy to add.
Technically you could use `javascript:void(open('http://example.com/'))` and allow pop-ups on 4chan, but that's suboptimal (the link wouldn't work with anything but a plain left click).

**Comment by DeckardEdward** [comment]
I was dumb before and didn't realize that the bottom-of-page list was toggleable through an Oneechan setting. I turned off top links, and that gets rid of the board list for some reason, but it's also getting rid of my top-of-catalog controls (search, sort, thumbnail size, etc.).

I'm probably missing something here, but I can't figure it out on my own apparently. How do I shut off the board list without sacrificing my catalog controls?

**Comment by ccd0** [comment]
In vanilla 4chan X, you can turn off the bottom board list in the drop-down menu in the header under Header > Hide Bottom Board List.  I'm not sure how Oneechan changes things; you'd be better off asking @Nebukazar about that.

**Comment by DeckardEdward** [comment]
Thanks. I'll check the vanilla extension, and then I'll pop over to Neb's bug tracker if that doesn't work.

**Comment by DeckardEdward** [comment]
I never got any reply from Nebukazar. Instead, I saved my 4X and Oneechan settings, and I loaded the settings on my desktop. I loaded the 4X settings first, and that got rid of the bottom board list by itself.
