### ISSUE TITLE
'Report this post' button is broken

### ISSUE THREAD

**Issue by bui** [ccd0/4chan-x#501]
Uncaught TypeError: Illegal invocation
        ReportLink.report @ VM320:12699

Google Chrome 47.0.2522.0 on Windows 10
V8 4.7.74.1
Tampermonkey 3.11
4chan X 1.11.12.0

**Comment by ccd0** [comment]
Looks like it's this issue:
https://forum.tampermonkey.net/viewtopic.php?f=17&t=1324

**Comment by ccd0** [comment]
Can you check whether this still happens with the latest Tampermonkey BETA?
https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf
It should be fixed:
https://tampermonkey.net/changelog.php?version=3.12.4851&show=gcal

**Comment by bui** [comment]
Yep, fixed in Tampermonkey BETA.
