### ISSUE TITLE
scrolling is broke

### ISSUE THREAD

**Issue by ajloveslily14** [ccd0/4chan-x#508]
Things like the navigation buttons and the scroll to new posts are broke. aswell as the unread posts updating.

**Comment by ccd0** [comment]
4chan is down at the moment, and I only managed to test the navigation buttons before it happened, but they worked for me.  Could you give more detail about your setup (browser version, Greasemonkey version, exported settings, any other extensions)?

**Comment by ccd0** [comment]
All working for me.
Try the stuff in https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by ajloveslily14** [comment]
Uncaught TypeError: Illegal invocation$.event @ VM301:807

**Comment by ccd0** [comment]
Are you using Tampermonkey with Chrome 47+?  If so, this issue should be fixed in the next Tampermonkey release.  See:
 https://forum.tampermonkey.net/viewtopic.php?f=17&t=1324
#501

**Comment by ccd0** [comment]
Can you check whether this still happens with the latest Tampermonkey BETA?
https://chrome.google.com/webstore/detail/tampermonkey-beta/gcalenpjmijncebpfijmoaglllgpjagf
