### ISSUE TITLE
Infinite Scrolling Broken

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#515]
Submitter: Sam
Email: sam.l.miller@outlook.com
Using old versions of 4chan X doesn't seem to help.
Using Chromium Version 46.0.2487.0 (64-bit)

http://puu.sh/kDwp7/f0c3a20f14.png errors in console

Used to work a few days ago, then stopped. Can't really remember anything specific that might have happened.

**Comment by ccd0** [comment]
Is this on /adv/?

**Comment by Jalopyy** [comment]
The infinite scrolling seems broken on every board.

**Comment by ccd0** [comment]
Are you using 4chan X as an extension directly or through Tampermonkey?  Do you have any other extensions installed?  (Try temporarily disabling them.)

**Comment by Jalopyy** [comment]
Extension.

Still doesn't work even w/all addons disabled.

Will try w/Tampermonkey.

**Comment by ccd0** [comment]
Can you export and post your settings?

> Still doesn't work even w/all addons disabled.

Did you make sure to refresh the page after disabling them?

How exactly is it failing?  You have infinite scroll selected in the drop-down, and scroll to the bottom of the page and nothing happens?  Or something else?

**Comment by Jalopyy** [comment]
Apparently I never had 'infinite scrolling' selected in the drop-down. I guess it was added sorta recently, where before it was the default as long as option was ticked, and I never noticed.

Thanks though!
