### ISSUE TITLE
Ability to use street sign captcha

### ISSUE THREAD

**Issue by ivzaitsev** [ccd0/4chan-x#524]
It's possible to use it with the native extension, but in 4chanX its the unreadable word one. Is it possible to add it?
![image](https://cloud.githubusercontent.com/assets/1762220/10615118/a476124a-7766-11e5-9867-0464335eae8f.png)

**Comment by ccd0** [comment]
You can use either the word captcha or the image selection captcha in 4chan X.  To get image selection, turn off `Use Recaptcha v1` under `Posting and Captchas`.

**Comment by ivzaitsev** [comment]
Bummer:(

**Comment by ccd0** [comment]
I'm confused what you are trying to do.
Do you want the captcha where you type in something or the one where you pick an image?

**Comment by ccd0** [comment]
If you want what you're showing in the OP image, turn `Use Recaptcha v1` on, and make sure you have `Force Noscript Captcha` off.

**Comment by ivzaitsev** [comment]
Thats strange, I've tried using Recaptcha v1 and Force Noscript before, but all I got was the unreadable black and white text version. And now it uses the one I want. Oh well, thanks for the help.

**Comment by ivzaitsev** [comment]
Force Noscript should be on, by the way
http://i.imgur.com/sYtHWt2.png
![noscript on](https://cloud.githubusercontent.com/assets/1762220/10627164/e8ec6796-77be-11e5-91d7-7c781c55868b.png)
![noscript off](https://cloud.githubusercontent.com/assets/1762220/10627172/f3404834-77be-11e5-881f-ab69d8c6dcbd.png)

**Comment by ccd0** [comment]
You need to refresh the page after changing the settings.  If you have `Use Recaptcha v1` and `Force Noscript Captcha` on, it is going to give you unsolvable captchas after you refresh the page.

Whether you get words or street numbers to type is entirely up to Google, and you will likely get a mixture of both.
