### ISSUE TITLE
Detect whether math/code/sjis tags and oekaki are enabled instead of hardcoding the board list.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#525]

**Comment by ccd0** [comment]
Cases where boards are being treated specially by a hardcoded check in 4chan X:

- /f/ is different in lots of ways.  That special case is probably not going away.
- /f/, /b/ and now /trash/ (#576) have no internal archive.
- /b/ and /vg/ only show 3 replies in the index, and /t/ only shows 1.  Most boards show five.
- 4chan X does not run on /z/ or /fk/.  This can be removed as those pages no longer exist.
- /gif/ and /wsg/ allow WebM files with audio.
- /vg/ doesn't allow threads without a subject.
- /r9k/ doesn't allow empty comments or comments with just a quotelink.
- /g/ has [code] tags.
- /sci/ has [math] and [eqn] tags.
- /jp/ has [sjis] tags.
- Dice rolls are unbolded in the catalog in /tg/ only. This is /tg/-only to fix #332.  In general, we need to do better at identifying dice rolls. #577
- **(fixed)** At the time this bug was made, /i/ was treated specially for Oekaki, but this is now auto-detected.
- The list of boards archived by third parties is hard-coded and unchangeable except by script update: #517
- Simiarly, the list of boards on catalog.neet.tv is hard-coded and unchangeable: #570

**Comment by bui** [comment]
https://a.4cdn.org/boards.json has some settings defined
you could request missing ones at [4chan/4chan-API](https://github.com/4chan/4chan-API)

**Comment by ccd0** [comment]
I'll pull it from boards.json if necessary, but where possible, it's probably better to read it from the page itself, which will be more up to date.

**Comment by ccd0** [comment]
OTOH, I think maybe boards.json will be okay.  It just means that if the user hasn't visited 4chan in a while, the starting of features that need fresh boards.json data will have to be delayed until the request is complete.  That's probably not too much of a problem.

The bigger potential problem is that boards.json historically hasn't always been kept up to date.  They seem to be updating it manually, separate from the code that generates the HTML, which seems to get updates first.

**Comment by ccd0** [comment]
Have removed everything it's possible to remove.
