### ISSUE TITLE
Just a quick fix for the halloween theme

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#557]
of course  "s.4cdn.org/css/yotsubluenew.629.css" should be changed to the desired theme.

@import url("//s.4cdn.org/css/yotsubluenew.629.css");
a, a:visited {
    color: #34345C!important;
    text-decoration: none!important;
}
div.post div.postInfo span.postNum a {
    text-decoration: none!important;
    color: #000000!important;
}
#skellington { display: none; }

**Comment by Dragas** [comment]
Even though this fixes the terribad theme that was applied for this "special" occasion, the theme selector is still missing.
http://i.imgur.com/6DEpV8e.png

**Comment by ccd0** [comment]
It's easier to just block the spooky.css.

**Comment by ccd0** [comment]
||s.4cdn.org/css/spooky.*.css
    boards.4chan.org###skellington

**Comment by Dragas** [comment]
Fair enough.
