### ISSUE TITLE
Move "Edit in Tegaki" option to menu.

### ISSUE THREAD

**Issue by iiiGerardoiii** [ccd0/4chan-x#561]
e.g.:
![2015-11-01-01 35 25](https://cloud.githubusercontent.com/assets/6264194/10867967/4263ed02-8044-11e5-876c-06be31bdbffe.gif)
Having the option inside the menu will give the posts a cleaner look.

**Comment by ididntknowicoulddothatXD** [comment]
How did you get that sauce link in the menu?

**Comment by iiiGerardoiii** [comment]
Photoshop CC, based on #391

**Comment by spaghetti2514** [comment]
:+1:
