### ISSUE TITLE
Quick Reply dialog creation crashed

### ISSUE THREAD

**Issue by Question2** [ccd0/4chan-x#565]
Quick Reply dialog creation crashed. [report]
NS_ERROR_FILE_CORRUPTED: see console for details
(4chan X ccd0 v1.11.14.12 userscript on gecko at 983,1089,8919,8971,8815,8806,7600,7007,7192,7260)

I cant attach the console error file because it says i do not have permission, so here it is in text :

Expected ':' but found '/'.  Declaration dropped. 133045725
Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. yotsubluenew.635.css:1:27
Expected media feature name but found '-webkit-min-device-pixel-ratio'. yotsubluenew.635.css:1:10084
Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. yotsubluemobile.635.css:1:70
Unknown property 'user-select'.  Declaration dropped. yotsubluemobile.635.css:1:6327
Error in parsing value for 'max-width'.  Declaration dropped. yotsubluemobile.635.css:1:10407
Error in parsing value for 'max-height'.  Declaration dropped. yotsubluemobile.635.css:1:10433
Selector expected.  Ruleset ignored due to bad selector. 133045725:1:262
Unknown property 'user-select'.  Declaration dropped. 133045725:1:1073
Unknown property 'user-select'.  Declaration dropped. 133045725:1:3235
Unknown property 'user-select'.  Declaration dropped. 133045725:1:9487
Unknown property 'user-select'.  Declaration dropped. 133045725:1:14320
Unknown property 'speak'.  Declaration dropped. 133045725:17:7
Unknown pseudo-class or pseudo-element '-webkit-search-decoration'.  Ruleset ignored due to bad selector. 133045725:689:8
Error in parsing value for 'unicode-bidi'.  Declaration dropped. 133045725:748:16
Error in parsing value for 'display'.  Declaration dropped. 133045725:955:13
Error in parsing value for 'display'.  Declaration dropped. 133045725:965:13
Error in parsing value for 'display'.  Declaration dropped. 133045725:976:13
Error in parsing value for 'display'.  Declaration dropped. 133045725:1002:13
Unknown pseudo-class or pseudo-element '-webkit-search-cancel-button'.  Ruleset ignored due to bad selector. 133045725:1281:15
Error in parsing value for 'display'.  Declaration dropped. 133045725:1298:11
Error in parsing value for 'display'.  Declaration dropped. 133045725:1496:11
Unknown property '-moz-text-decoration-style'.  Declaration dropped. 133045725:1580:30
Error in parsing value for 'display'.  Declaration dropped. 133045725:1862:11
Error in parsing value for 'background-image'.  Declaration dropped. 133045725:1935:20
Error in parsing value for 'display'.  Declaration dropped. 133045725:1988:11
Error in parsing value for 'display'.  Declaration dropped. 133045725:2011:11
Error in parsing value for 'display'.  Declaration dropped. 133045725:2049:11
Error in parsing value for 'display'.  Declaration dropped. 133045725:2223:11
Error in parsing value for 'display'.  Declaration dropped. 133045725:2402:11
Error in parsing value for 'display'.  Declaration dropped. 133045725:2420:11
Error in parsing value for 'display'.  Declaration dropped. 133045725:2427:11
Error in parsing value for 'display'.  Declaration dropped. 133045725:2441:11
Error in parsing value for 'display'.  Declaration dropped. 133045725:2515:11
Expected identifier for pseudo-class or pseudo-element but found '.'.  Ruleset ignored due to bad selector. 133045725:2640:26
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. 133045725:2693:21
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. 133045725:2772:23
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. 133045725:2851:20
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. 133045725:2925:22
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. 133045725:3031:22
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. 133045725:3155:20
Unknown pseudo-class or pseudo-element '-webkit-scrollbar-thumb'.  Ruleset ignored due to bad selector. 133045725:3237:20
Expected ':' but found 'cursor'.  Declaration dropped. 133045725
Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. photon.635.css:1:27
Expected media feature name but found '-webkit-min-device-pixel-ratio'. photon.635.css:1:9779
Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. yotsubanew.635.css:1:27
Expected media feature name but found '-webkit-min-device-pixel-ratio'. yotsubanew.635.css:1:9938
Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. futabanew.635.css:1:27
Expected media feature name but found '-webkit-min-device-pixel-ratio'. futabanew.635.css:1:9169
Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. tomorrow.635.css:1:27
Expected media feature name but found '-webkit-min-device-pixel-ratio'. tomorrow.635.css:1:9857
Error in parsing value for '-moz-text-size-adjust'.  Declaration dropped. burichannew.635.css:1:27
Expected media feature name but found '-webkit-min-device-pixel-ratio'. burichannew.635.css:1:9162
Expected declaration but found '*'.  Skipped to next declaration. data:

I cant post anything after this because it is too long and it wont let me post, but its basically a huge stream of gibberish letters.

**Comment by ccd0** [comment]
https://stackoverflow.com/questions/18877643/error-in-local-storage-ns-error-file-corrupted-firefox

**Comment by Question2** [comment]
So i should move the webappstore files somewhere else to fix it?

**Comment by ccd0** [comment]
> So i should move the webappstore files somewhere else to fix it?

That should work.

**Comment by ccd0** [comment]
Did it work?

**Comment by ccd0** [comment]
Assuming it worked.
