### ISSUE TITLE
Can't move the thread updater to a different location

### ISSUE THREAD

**Issue by whocares1** [ccd0/4chan-x#567]
So I used to have the thread updater button at the bottom right of my screen, but after a reinstall, the button is fixed to the bottom left of the screen. It cannot be dragged even though the stats is be movable

**Comment by ccd0** [comment]
You have to drag it by a small region on top.

**Comment by ccd0** [comment]
I agree it's annoying and should be improved, though. #165

**Comment by ccd0** [comment]
Did dragging by the top work for you?
