### ISSUE TITLE
Relative Date Title: Hovering over dates doesn't work anymore

### ISSUE THREAD

**Issue by ididntknowicoulddothatXD** [ccd0/4chan-x#568]
That's the only thing in the console when using 4chan X vanilla, without any extension that could disable it in some way:
script.js:12235 'Range.detach' is now a no-op, as per DOM (http://dom.spec.whatwg.org/#dom-range-detach).

**Comment by ccd0** [comment]
Works for me.  More details?

**Comment by ididntknowicoulddothatXD** [comment]
Yes. I just downloaded and seeded a torrent using Halite. Apparently, it somehow disabled hovering in general for some reason. I stopped seeding, deleted the torrent, closed the client and now everything works.

**Comment by ididntknowicoulddothatXD** [comment]
Closing/minimizing the torrent client fixed the problem.
False positive.
