### ISSUE TITLE
Don't try to run 4chan X on robots.txt

### ISSUE THREAD

**Issue by spaghetti2514** [ccd0/4chan-x#574]
Or probably anything else that isn't a webpage

![](http://i1.someimage.com/A1niAQf.png)

**Comment by ccd0** [comment]
Odd, it doesn't do that for me.  Are you on the latest version?

**Comment by spaghetti2514** [comment]
I'm on 1.11.14.10, so not quite.

I should point out that it doesn't run on www.4chan.org/robots.txt, but does on **boards.**4chan.org/robots.txt

**Comment by ccd0** [comment]
My mistake, I just had the Toggleable Thread Watcher setting turned on.  When I turn that off it's showing up for me, too.

**Comment by ccd0** [comment]
This should be fixed now.  Any other pages 4chan X is doing something to where it shouldn't?

**Comment by spaghetti2514** [comment]
Not that I've ever run into
