### ISSUE TITLE
Turn Persistent QR off by default?

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#584]
Right now, the only reason I have it on by default is because it works better with OneeChan that way (at least under OneeChan's current defaults, which add the sidebar).  For most people not using OneeChan, I think it's an annoyance.  What does everyone else think?  And how many people are using 4chan X with/without OneeChan?  (I don't use OneeChan myself except for testing.)

The change would only affect new installs / freshly reset settings.

**Comment by spaghetti2514** [comment]
I leave persistent QR off and don't use OneeChan.

Personally I just don't see the point in using it. With or without persistent QR, replying to a post is done by clicking the post link. A non-reply is either started by pressing "q" with persistent off, or clicking the QR field with persistent on. It doesn't really offer me any advantage in speed or convenience to make the QR constantly visible, and just wastes space for no reason.

I do specifically remember thinking "why is this on by default; it seems like a really niche desire" the last few times I installed 4chan X.
