### ISSUE TITLE
Cooldown timer bug 1.11.16.2

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#592]
Submitter: Brandon
Email: 1c2751fe@opayq.com
This seems to be a recent bug. Here's how to recreate it.

- Have a post queued in one thread (counting down)
- Interrupt it by making a post in a different thread, so that the 1st thread will still try to post
- You'll get the "you must wait 1 minute" etc warning
- However, even after 1 minute, the warning will be stuck. The only way to fix this is to refresh the thread. Pretty annoying during image dumps.

**Comment by an-electric-sheep** [comment]
> The only way to fix this is to refresh the thread. 

I think there may be other issues too. E.g. when posting a duplicate file I keep getting the duplicate file error even after removing the file from the form, reloading the page fixes it.

**Comment by ccd0** [comment]
Thanks for reporting!  Can you confirm whether v1.11.16.3 has fixed it?

**Comment by an-electric-sheep** [comment]
the issues i've been seeing are fixed
