### ISSUE TITLE
Maxthon support

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#593]
Change line 13314 from
postObjects = req.response.posts;
to
postObjects = JSON.parse(req.response).posts;
Otherwise it throws "Cannot read property '0' of undefined" on the next line every time the updater is called

Windows, Maxthon 4.4.8.1000, Violentmonkey 2.3.32, 4chan-X 1.11.16.2 beta

**Comment by ccd0** [comment]
That request is done with a `responseType` of `'json'` so the current code is correct and the proposed code would break 4chan X.

This sounds like a problem with either Maxthon or Violentmonkey.  The thing to do is to create a script that does nothing but trigger the bug and report it to the appropriate developers.

**Comment by PokeFroge** [comment]
Maxthon does not natively support `xhr.responseType="json"` (it is based on an older version of Blink web engine), in ViolentMonkey it is emulated with JSON.parse
https://github.com/Violentmonkey/Violentmonkey-mx/blob/0115f5b570ec672806bfea2c747e4f9f47a288d5/src/injected.js#L161
The Userscript already uses GM_xmlhttpRequest in a few places, but `$.ajax` function uses native XMLHttpRequest (that function is linked to thread updater, JSON navigation, and other things), you can see it being used on line 533 in the stable version 1.11.15.7

**Comment by ccd0** [comment]
> Blink

Do you mean WebKit?

Anyway, 4chan X uses `xhr.responseType="json"` a lot, so I'm not sure a backporting the code is worth all the changes and testing.  Especially since it's probably not the only thing that's broken.  You're welcome to do a backport yourself, but I don't think I want those changes in the main version.

**Comment by PokeFroge** [comment]
`responseType="json"` is already supported in Violentmonkey if you use the Userscript-specific `GM_xmlhttpRequest` function, which is what I suggested you to change. Another benefit of using `GM_xmlhttpRequest` instead of browser native `XMLHttpRequest` does not only benefit from cross domain scripting, but also allows to bypass other extensions like AdBlockers, it would be specifically useful for the /adv/ board that cannot be posted on using 4chan-x if EasyList is active

**Comment by ccd0** [comment]
Changing everything to `GM_xmlhttpRequest` would require even more work, would break core functions in browsers that don't support it, and would break core functions every time a new version of Greasemonkey breaks something in `GM_xmlhttpRequest`.  And I need to use regular `XMLHttpRequest` in the Chrome extension version anyway.  It's a definite no-go.

**Comment by PokeFroge** [comment]
> Changing everything to GM_xmlhttpRequest would require even more work,
> And I need to use regular XMLHttpRequest in the Chrome extension version anyway.

`XMLHttpRequest` is referenced only once in userscript version, in `$.ajax` function. The rest functions use `GM_xmlhttpRequest`. Fixing _one_ function is indeed a lot of work. The statement about Chrome extension is irrelevant, because [according to this](https://github.com/ccd0/4chan-x/blob/2379b0f31da60a03f0dd9e0350b8dde3d3fe64e8/src/General/CrossOrigin.coffee#L89) it should take care of itself

**Comment by PokeFroge** [comment]
Temporary fix:
```javascript
if(window.mxZoomFactor){ // Browser detection (Maxthon)
  r.__defineGetter__('response', function(){ // Make the response variable output what we want
    if(/\.json$/.test(url)){ // Output parsed JSON object if request URL ends with .json
      return JSON.parse(r.responseText);
    }else{ // Otherwise just output plain text
      return r.responseText;
    }
  })
}
```
Inserted before the `return r;` (between lines 558 and 559)

**Comment by ccd0** [comment]
Something like that could work, but we need a way to test for JSON responseType support, or it will just break things down the road.  Have you tested it?

**Comment by ccd0** [comment]
> we need a way to test for JSON responseType support

Looks like testing `xhr.responseType` after it's set works.  So maybe this won't be such an issue to fix after all.

**Comment by PokeFroge** [comment]
Generally it should not break anything, because it works like a forced shim: it will still work even if the browser will eventually support `responseType="json"`, what it could break on would be the URLs that don't end with .json and are expected to be already parsed. When I done the tests, the `responseType`, when referenced, always returned an empty string, so I assume it is write-only, you can't read it once it had been written to, at least in Maxthon

When posting in a thread it prints some errors in console after doing a POST request to `https://sys.4chan.org/s4s/post`, but otherwise the post goes through and you can see it if the thread is refreshed
```
Uncaught InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable.
  (anonymous function)
  QR.response
```
(no line was referenced)

**Comment by PokeFroge** [comment]
I think I figured out why `e.responseType` wasn't returning anything in Maxthon, when you set a `responseType` variable it seems like it's being checked whenever or not the `responseType` is supported and only then it sets. When I set `responseType` to `"blob"` it actually returned the correct value, so I assume that's how it can be tested if it's not supported in other browsers 
```javascript
var xhr=new XMLHttpRequest()
xhr.responseType="json"
xhr.responseType
// ""
xhr.responseType="blob"
xhr.responseType
// "blob"
xhr.responseType="json"
xhr.responseType
// "blob"

**Comment by ccd0** [comment]
> what it could break on would be the URLs that don't end with .json and are expected to be already parsed.

The obvious way to fix that is to do that test before assigning the getter.

The other little fix needed is that sometimes we pass in the `responseType` through `options`.

So what's needed is to change

      if (/\.json$/.test(url)) {
        r.responseType = 'json';
      }
      $.extend(r, options);

to

      if (/\.json$/.test(url)) {
        options.responseType = 'json';
      }
      $.extend(r, options);
      if (options.responseType === 'json' && r.responseType !== 'json') {
        Object.defineProperty(r, 'response', {
          get: function() {
            return JSON.parse(r.responseText);
          }
        });
      }

**Comment by PokeFroge** [comment]
Very nice, this change fixes InvalidStateError I mentioned earlier
I do not know if it is in any way related, but the quick reply window looks strange on all boards in Maxthon, all of the possible QR buttons always appear. Under same configuration, [left is Chrome and right is Maxthon](http://i.imgur.com/T5nylEi.png). The board pictured is /g/, notice the Mona font and TEX buttons, also spoiler image checkbox on a board that doesn't support it, and /f/ tags dropdown

**Comment by ccd0** [comment]
> Do you mean WebKit?

Okay, looks like it is Blink, just a rather old version (from 2013, same year as the fork from WebKit).

**Comment by ccd0** [comment]
*should be

    if (/\.json$/.test(url) && options.responseType == null) {
      options.responseType = 'json';
    }
    $.extend(r, options);
    if (options.responseType === 'json' && r.responseType !== 'json') {
      Object.defineProperty(r, 'response', {
        get: function() {
          return JSON.parse(r.responseText);
        }
      });
    }

**Comment by ccd0** [comment]
make that: `options && options.responseType === 'json'`

**Comment by ccd0** [comment]
Oops, still wrong:
`options && options.responseType == null`
`options && options.responseType === 'json'`

**Comment by ccd0** [comment]
And in the $.ajax thing, it was also necessary to deal with the case where options was null (0575eb2a7943c3f9b4aeaed165650c5339c9a6fa).

> the quick reply window looks strange on all boards in Maxthon

Apparently Maxthon barfs on encountering `@supports` blocks.  I've moved the one use of `@supports` to the end of the stylesheet.

The newest beta version (v1.11.17.0) should fix the problems reported so far.
