### ISSUE TITLE
Add option to filter posts which quote more than n posts

### ISSUE THREAD

**Issue by DrLore** [ccd0/4chan-x#601]
Would it be possible to add an option to filter posts which reply to more than a given number of posts?

At the moment, if someone decides to reply to every post in the thread, you have to copy down the post number from one of the posts they reply to, use find in page to go to the post and hide it, then go back to where you were reading from, which also mucks up the unread post counter.

I have a global regex '/(>>\d+\s+){5,}/' which will filter people who put 5 post links in a row, but it doesn't filter people who put a comment on those replies.

**Comment by ccd0** [comment]
`/(?:>>\d(?:(?!>>\d)[^])*){20}/` filters posts with more than 20 quotes.
