### ISSUE TITLE
Track posts read on index page?

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#625]
Scrolling past posts on the index page would update how far you've read in a thread.

**Comment by spaghetti2514** [comment]
What about when there are more unread posts in the thread than are visible in the thread preview? Just don't update it at all?

Or is this only for threads expanded to full size from the index?

**Comment by ccd0** [comment]
It could update it only if the last read post was visible in the thread preview.

**Comment by ccd0** [comment]
I think what I'm going to do instead of having it update on scrolling is to add a link at the bottom of the thread that you can manually click on to indicate you've read all the posts.

**Comment by ccd0** [comment]
Also, having the unread line would help.
