### ISSUE TITLE
downloadthemall

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#627]
4chan x now breaks downthemall when it changes the links
 href="//i.4cdn.org/b/1448040771216.jpg" doesn't work,
I guess I can contact the downthemall guys too.
I'm a gigantic faggot and it's not that important. Sorry.

**Comment by ccd0** [comment]
Can you elaborate?  What precisely doesn't work?

**Comment by thenewdesu** [comment]
Well, There is nothing wrong with 4chan x itself, But it breaks all the links.
I have to turn it off to use downthemall to use it.
>https://downthemall.net/

**Comment by ccd0** [comment]
I enabled DowntThemAll and don't see a problem.  Maybe there are particular settings that trigger the bug?  Can you reproduce it in a fresh profile?

**Comment by zixaphir** [comment]
It's the sauce links. You have to use a fast filter to ignore them. `/^https?:\/\/i\.4cdn.org.+/` should work

**Comment by ccd0** [comment]
I thought you meant the links didn't open in your browser.  What zixaphir said should work.
