### ISSUE TITLE
[Request] Display watch/hide thread buttons in the catalog, instead of the drop down list

### ISSUE THREAD

**Issue by HASJ** [ccd0/4chan-x#629]
Just the two, you can leave the report button inside the drop down list.
For reasons, I like to have a clean a catalog of stuff I don't like and some boards can have dozens of threads and also dozens of clicks I have to do because the watch/hide options are inside the drop down list, multiplied by 2.
You could use these characters to keep it resourceless (just a suggestion): ♥ ⊠
No need to be default, could just be a catalog option to accomodate more faggots like me.

**Comment by ccd0** [comment]
You can do this with shift+click and alt+click.

**Comment by HASJ** [comment]
Oh shit.
