### ISSUE TITLE
Inline report windows

### ISSUE THREAD

**Issue by an-electric-sheep** [ccd0/4chan-x#638]
Handling multiple report popups is quite a hassle in my experience. I think it might be more efficient to put them in a fixed-positioned stack of iframes, similar to the quick reply dialog.

Maybe including a small reload button in case you get the "you already reported a post, please wait a little while" text.

**Comment by Fasmea** [comment]
This was even in the inline extension, iirc.

**Comment by ccd0** [comment]
Merging into #47.
