### ISSUE TITLE
Minor issue: /p/ is called "Photography", not "Photo"

### ISSUE THREAD

**Issue by Fasmea** [ccd0/4chan-x#642]
If I use "[p-replace]" I'd expect it to read "Photography" and not "Photo"; it's not the full title of the board.
If this was intentional, please excuse me.

**Comment by ccd0** [comment]
This happens because 4chan uses "Photo" as the tooltip in the original board list. I've reported this inconsistency to them.

On the other hand, if we fix #384 by getting the title from elsewhere (for example, boards.json), this problem should go away on our end.
