### ISSUE TITLE
Fix the /news/ catalog to resemble /f/ instead of the other boards

### ISSUE THREAD

**Issue by nonamethesecond** [ccd0/4chan-x#643]
Currently 4chanX shows the /news/ catalog as the standard catalog for every other board, only with "no file" displaying instead of a picture. The inline /news/ catalog is however resembling /f/.
http://boards.4chan.org/news/catalog

**Comment by Fasmea** [comment]
https://github.com/ccd0/4chan-x/issues/636#issuecomment-160335573
Relevant?

**Comment by Fasmea** [comment]
Pardon. I meant https://github.com/ccd0/4chan-x/issues/590

**Comment by ccd0** [comment]
Yeah, going to change this to a duplicate now that the presence of images on /news/ makes this less urgent.
