### ISSUE TITLE
Periods of unresponsiveness during first load of catalogue

### ISSUE THREAD

**Issue by miwu** [ccd0/4chan-x#646]
On first load of catalogue for a board the page will become unresponsive for seconds (avg. 5 - 15) at a time, with small windows of interactivity (scrolling, clicking a thread, etc.). No hard actions will complete until the 'catches' stop, and then they will execute (e.g., clicking a thumbnail in-between the unresponsive periods will not actually navigate to the thread until after the page would otherwise resume normal functionality).

__Step taken to attempt resolution__
Reset 4chanx settings
Disable oneechan
Disable privacybadger / ublock / https everywhere

There are no messages in browser console. Dev console mentions something about high-entropy storage, but it seems standard.

Apologies if this turns out not to be 4chanx related, but the problem goes away when 4chanx is disabled, and remains when oneechan is disabled but 4chanx is enabled.

**Comment by ccd0** [comment]
What browser and version?  What version of 4chan X are you on?  Can you try some [older versions](https://github.com/ccd0/4chan-x/blob/master/CHANGELOG.md) and see if it happens in them?

**Comment by ccd0** [comment]
Also, is this the 4chan X catalog or the native one (https://boards.4chan.org/board/catalog)?

**Comment by miwu** [comment]
I'm using Firefox dev 44.0a2. This occurs on both 4chanx and native catalogue, when 4chanx is enabled. I'll give the old versions a shot and report back.

**Comment by ccd0** [comment]
It would be helpful to check if it happens in stable Firefox, too.

**Comment by ccd0** [comment]
> Disable privacybadger / ublock

Just to check, are these all your extensions besides Greasemonkey?

**Comment by ccd0** [comment]
Does it happen in a fresh profile?

**Comment by miwu** [comment]
Old builds seem to have the same problem. Firefox stable seems to be working correctly. I have other addons, but with all them disabled except greasemonkey the problem persists. A fresh profile on dev has the same problem, a fresh profile on stable also works correctly.

**Comment by miwu** [comment]
Possibly something wrong with dev, since all my addons are the same between them.

**Comment by ccd0** [comment]
Is this still happening?

**Comment by miwu** [comment]
@ccd0 I'd stopped using Firefox since the 20th of December or so, and as such haven't experienced it. I did check using Nightly just now and if the problem is still there, it's almost non-existant.
