### ISSUE TITLE
Autohide Scroll with the header

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#647]
If you have your side scroll bar set to auto hide until moving the mouse to the very right of your screen it makes it pretty much impossible to click on the arrow for the header/updater/img expansion options because it's so close to the edge of the browser window.

Just an annoyance on my end and easily remedied by forcing the scroll bar to show at all times (forcing a browser restart) when I want to change something, but incredibly annoying nonetheless.

**Comment by spaghetti2514** [comment]
For anyone coming across this issue looking for a basic fix, I use
```#shortcuts {
  margin-right: 15px !important;
}```
in my custom CSS to account for the scrollbar overlap

Might need to be adjusted for larger scrollbars.

**Comment by ccd0** [comment]
The latest beta (v1.11.30.0) attempts to autodetect this situation and moves the shortcuts 12px if needed.
