### ISSUE TITLE
Use default index/inline extension on /adv/

### ISSUE THREAD

**Issue by Fasmea** [ccd0/4chan-x#649]
I blocked half of 4chan now thanks to hiro's retarded advert policy. https://boards.4chan.org/qa/thread/362590

Since I sometimes do browse /adv/ and I don't want to fully whitelist 4chan anymore, it would be better to disable 4chan X on said board if this option is checked, since 4chan X is broken with my current settings on /adv/.

Thanks for listening.

**Comment by Fasmea** [comment]
Maybe automatically redirect to HTTP-version on /adv/ if checked? 4chan X seems to use two settings; one in HTTPS and one in HTTP.

**Comment by ccd0** [comment]
Add

    @@||4chan.org/adv/
    @@||4cdn.org/adv/

to your filter list.  It will override the broken filter in EasyList.  It doesn't unblock any ads.

**Comment by Fasmea** [comment]
Cool, it works, thank you. What exactly are these tags doing? The ads haven't been unblocked too.

**Comment by Fasmea** [comment]
Test

**Comment by ccd0** [comment]
One of EasyList's filters prevents blocks anything from `.org/adv/` which blocks a lot of stuff on /adv/ that shouldn't be blocked. The filters above tell it to not block anything from `4chan.org/adv/` or `4cdn.org/adv/`. As far as I know, there are no ads served directly from `4chan.org` or `4cdn.org`; they are served from third-party sites.
