### ISSUE TITLE
Linkify grabs really weird text blocks to link

### ISSUE THREAD

**Issue by spaghetti2514** [ccd0/4chan-x#650]
![screen shot 2015-12-01 at 12 27 53 am](https://cloud.githubusercontent.com/assets/1966861/11493878/c0feee2e-97c2-11e5-8e58-189d78ba293b.png)

Red text is a single linkified link. Notice how it grabs a character from the previous line.

The actual href for that link is "gindex.dynu.com"

4chan X 1.11.19.0

**Comment by ccd0** [comment]
This should be better as of v1.11.19.0.

**Comment by spaghetti2514** [comment]
Dunno if you want to leave this open to catch any other classes of false positives, but the specific one I mentioned is fine now.

![screen shot 2015-12-01 at 3 44 07 pm](https://cloud.githubusercontent.com/assets/1966861/11515235/793f89ba-9842-11e5-80f4-c85eaa7005e4.png)
