### ISSUE TITLE
Mark post as submitted by the user function

### ISSUE THREAD

**Issue by lc-guy** [ccd0/4chan-x#651]
A function (maybe in the post's arrow menu?) to mark that post as "sent by the user" would be nice if, for example, I posted from another device and want to have notifications/new replies shown on the computer running 4chan X.

**Comment by ccd0** [comment]
requested again in
https://rbt.asia/g/thread/S53725582#p53731068

**Comment by ccd0** [comment]
Merging into #195, although this one had a clearer title so I'm copying it.
