### ISSUE TITLE
catalog problem

### ISSUE THREAD

**Issue by ajloveslily14** [ccd0/4chan-x#655]
heyo I have catalog image hover selected, yet on the catalog it doesn't enlarge the images on hover

**Comment by ccd0** [comment]
Are you using the 4chan X catalog or the native catalog?  It only works in the 4chan X one.

**Comment by ajloveslily14** [comment]
I'm using the 4chanx one

**Comment by ccd0** [comment]
Can you tell me your browser, the page you were on?
Does it work with all other extensions disabled?
Can you post your exported settings?

**Comment by ajloveslily14** [comment]
on chrome dev(latest) on http://boards.4chan.org/cm/catalog

Nope

http://pastebin.com/gSVPhUaA

**Comment by ccd0** [comment]
> http://boards.4chan.org/cm/catalog

That's the native catalog; the 4chan X one is at http://boards.4chan.org/cm/#catalog.

**Comment by ajloveslily14** [comment]
Thats weird, howcome its doing that? I have the other one enabled...

**Comment by ccd0** [comment]
Do you know how you got to http://boards.4chan.org/cm/catalog? If you have `Use 4chan X Catalog` on, the `[Catalog]` links should point to the 4chan X catalog. But you can still get to the native one at http://boards.4chan.org/cm/catalog (with an `/`) if you follow a bookmark or something.

**Comment by ajloveslily14** [comment]
okay, thanks sorry for the trouble
