### ISSUE TITLE
Desktop Notifications no longer clickable

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#656]
The desktop notification pop up doesn't take me to the thread or post when I click on it in the newest update.

**Comment by ccd0** [comment]
Working for me.  More details?

**Comment by nanosaur** [comment]
I'm using Chrome and Tampermonkey both up to date. I tried checking out the problem on Firefox and it works fine on there. I've already tried uninstalling 4chanx and turning off all the other extensions and still nothing.

**Comment by ccd0** [comment]
It seems to be a Tampermonkey issue.
https://github.com/derjanb/tampermonkey/issues/253
I'll see if I can work around it, though.

**Comment by ccd0** [comment]
Does the latest version work for you?

**Comment by nanosaur** [comment]
All better, thanks.
