### ISSUE TITLE
Active thread redirecting to archive

### ISSUE THREAD

**Issue by oluapris** [ccd0/4chan-x#667]
This thread /v/thread/320013168/ hasn't been archived yet but I get redirected to the archive if I try to open it. If I try to open it with 4chan X deactivated, I just see this http://i.imgur.com/bifNZgP.png, but I can view the thread just fine on my phone. Is this a problem with Chrome or the extension?

**Comment by ccd0** [comment]
Could be a temporary glitch on 4chan's end.  It's working for me now.  Is it still broken if you reload?

**Comment by ccd0** [comment]
Whatever happened, it appears the thread has been deleted for real now.
