### ISSUE TITLE
Google Image Search not working

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#670]
Using the sauce link searches Google with the wrong string and gives "The URL doesn't refer to an image, or the image is not publicly accessible." error.

Parameter used:
https://www.google.com/searchbyimage?image_url=%URL

Might be because of a change on Google's side.

Try to search an image with the sauce with the parameter above and then open the full image and right click and click "Search Google for image" and compare the resulting links.

**Comment by bakugo** [comment]
Noticed this too, looks like google reverse image search respects robots.txt now, and everything on  i.4cdn.org is blocked.

**Comment by ccd0** [comment]
> Try to search an image with the sauce with the parameter above and then open the full image and right click and click "Search Google for image" and compare the resulting links.

Right click and "Search Google for image" works because it's uploading the file instead of searching by URL.

**Comment by tenkuu** [comment]
>it's uploading the file instead of searching by URL.

I'm trying to do this with "Image Search Options" on Firefox but I'm getting ```400 Bad Request```

URL = ```https://www.google.ca/searchbyimage/upload```

Variables = ```encoded_image=::$IMGDATA::```
- [x] Use POST instead of GET

**Comment by saero** [comment]
I still have this issue. Firefox 39.0.3, with latest 4chan x.

**Comment by ccd0** [comment]
Can you paste your sauce settings here?

**Comment by ccd0** [comment]
It looks like it's fixed on Google's end now, so I should be able to remove the `?s.jpg` hack.
