### ISSUE TITLE
remove the show hidden threads option on the catalog

### ISSUE THREAD

**Issue by dunnotbh** [ccd0/4chan-x#671]
See this?
http://i.imgur.com/4e8Gutc.png
I want it gone, if I filter certain threads it's because I don't want to see them period, I want them completely gone.
The hide stubs option doesn't work on the catalog, is there a way to do that?

**Comment by ccd0** [comment]
You can add `#hidden-label {display: none;}` to custom CSS.

**Comment by dunnotbh** [comment]
that did the trick, thanks
