### ISSUE TITLE
Source search with ibsearch.xxx

### ISSUE THREAD

**Issue by HASJ** [ccd0/4chan-x#686]
https://ibsearch.xxx/

It uses md5 hash and other stuff to search for source. Is it possible?

**Comment by ccd0** [comment]
Looks like I'd have to convert the MD5 from base64 to hex, but should be doable.

**Comment by ccd0** [comment]
Although one issue is that 4chan strips metadata from JPEG files, so searching by hash may not work.

**Comment by HASJ** [comment]
Oh yeah... I forgot about that. Why do they even do that...

**Comment by ccd0** [comment]
Mostly people taking photos of themselves and leaving in the location data, I think.

**Comment by pokeball99** [comment]
@ccd0 yea likely, infact if you look at one of the first 4chan related github repos, you can see someone made something to do just that

**Comment by ccd0** [comment]
> Looks like I'd have to convert the MD5 from base64 to hex, but should be doable.

In the newest beta (v1.11.22.1) you can now use the hexadecimal version of the MD5 in your sauce settings:
`https://ibsearch.xxx/images/?q=md5%3A%hMD5`

**Comment by HASJ** [comment]
Thanks! Working perfectly!

**Comment by ccd0** [comment]
I should probably add this to the sauce examples.
