### ISSUE TITLE
Add a Werk/Fappe Tyme indicator

### ISSUE THREAD

**Issue by iiiGerardoiii** [ccd0/4chan-x#70]
It would be great to have an indicator that only shows up when you have Werk or Fappe Tyme enabled. People might forget it's enabled.

e.g.
![captura de pantalla 2014-05-24 08 292](https://cloud.githubusercontent.com/assets/6264194/3074702/4b1d5b02-e34e-11e3-8285-ae3d17695d78.png)

**Comment by ccd0** [comment]
Not sure if we still need an indicator now that Fappe Tyme is non-persistent.  Thoughts?

**Comment by iiiGerardoiii** [comment]
I think Fappe Tyme being non-persistent is good enough, thanks!
