### ISSUE TITLE
Get rid of hidden original link from File Info Formatting

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#703]
I want to look at this again to see if I can do this without breaking anything.
Maybe we can insert the original file link into the reformatted file info so that event listeners are preserved.

**Comment by MrSeyker** [comment]
As the person that originally requested this, I'd like some more info on what's the current issue.
The original filename doesn't show anywhere in DTA now, truncated or otherwise.

**Comment by ccd0** [comment]
On second thought, I think it's better to keep it.
