### ISSUE TITLE
Reply expansion not working upon reinstallation 

### ISSUE THREAD

**Issue by PseudoLain** [ccd0/4chan-x#718]
I recently had to reinstall all my extensions and stuff
Upon reinstalling this + OneeChan (nebuk's) I've been unable to "expand" replies to a particular comment, instead it takes me to the comment in the thread. Not sure when this changed or if it's an issue, but this seems to be the only place I can find out.
It's not a big issue, just really annoying, as the reply expansion was so great as opposed to the auto-threading option which I find a bit awkward. Is there a work around or should I just get over it? I'm ignorant as all hell when it comes to coding, so I apologize if this is a stupid request.

**Comment by ccd0** [comment]
Turn `Quote Inlining` on and `Inline Cross-thread Quotes Only` off.

**Comment by PseudoLain** [comment]
You're the best, thanks for the help it's working now.

Also, thanks for making this public. I'm not sure how much work it takes to make this but I really appreciate it. I honestly couldn't imagine using 4chan without this <3
