### ISSUE TITLE
"Oekaki Links" crashed on node Post No.663365178 (b).

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#723]
Submitter: Sebastian Oeltjen
Email: dtinytop@hotmail.com
[Please describe the steps needed to reproduce this error.]

Script: 4chan X ccd0 v1.11.21.5 userscript
User agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:43.0) Gecko/20100101 Firefox/43.0
URL: http://boards.4chan.org/b/thread/663364918

TypeError: el is null
$.on@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:810:7
QR.oekaki.node@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:9168:14
Callbacks.prototype.execute@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:1217:13
Main.callbackNodes@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:17924:9
Fetcher.prototype.insert@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:2340:1
Fetcher@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:2319:9
QuotePreview.mouseover@chrome://greasemonkey-modules/content/sandbox.js -> 4chan-X.user.js:6508:1

**Comment by ccd0** [comment]
Are you using any other extensions / userscripts besides 4chan X that might be causing a conflict?

**Comment by soeltjen** [comment]
I was not using any other scripts

**Comment by ccd0** [comment]
I'm not sure why it would happen then, but unless you still have this problem, we may as well close this since the code where the error happened no longer exists since moving the edit link to the menu.

**Comment by soeltjen** [comment]
It only happened once, so closing it is fine with me


Sent from Outlook Mobile






On Tue, Apr 19, 2016 at 5:12 PM -0700, "ccd0" <notifications@github.com> wrote:





I'm not sure why it would happen then, but unless you still have this problem, we may as well close this since the code where the error happened no longer exists since moving the edit link to the menu.

---
