### ISSUE TITLE
Report captcha reverts to v2

### ISSUE THREAD

**Issue by saero** [ccd0/4chan-x#727]
I have the captcha set to v1 and now my report functions are only image-based v2 recaptcha.

What gives? Did Google break it again?

**Comment by bakugo** [comment]
The report captcha was changed today by 4chan to be the same as the posting captcha, this needs to be fixed in 4chan X. The layout of the report window was also changed.

**Comment by saero** [comment]
Thanks for the feedback guys, I appreciate the rapid response. Keep up the awesome work, ccd0, I know it's thankless at times.
