### ISSUE TITLE
Preload next webm in Gallery mode

### ISSUE THREAD

**Issue by chinatsu-chan** [ccd0/4chan-x#728]
Would be nice. Takes fucking forever for the current video to load and the video gets all fucked in the video tag. Trying to expand all and then go to Gallery mode doesn't help much. Preloading each subsequent video as you go through them would be much nicer.

**Comment by chinatsu-chan** [comment]
Messed up with title. Meant to say preload.

**Comment by ccd0** [comment]
It already does this.

**Comment by chinatsu-chan** [comment]
Oh, well, certainly does not feel like it.
