### ISSUE TITLE
Image thumbnails not loading

### ISSUE THREAD

**Issue by vtimdon** [ccd0/4chan-x#738]
As of the latest update the image thumbnails do not load at all. Could you fix this as soon as possible?

**Comment by ccd0** [comment]
Working for me. Is this happening consistently and only with 4chan X enabled?

**Comment by vtimdon** [comment]
Yep, when it's disabled the thumbnails load perfectly.

**Comment by ccd0** [comment]
What page? What browser? Are you using any other extensions, and if so, what happens when you turn them off? Can you export and post your settings?

**Comment by vtimdon** [comment]
I mainly browse /mu/ so I'm seeing that happen on every page there. I'm using Safari on OSX and I'm not using any other extensions.

**Comment by vtimdon** [comment]
I'm not sure how to export, how do I do that?

**Comment by ccd0** [comment]
"Export" at the top of the settings panel.

**Comment by ccd0** [comment]
Are there any error messages in the console?

**Comment by vtimdon** [comment]
I can't find the option to export browser settings. 
Nope, no error messages, nothing relating to 4chanX anyways.

**Comment by ccd0** [comment]
4chan X settings. Click the wrench in the header, then click the "Export" link at the top right of the panel.

What userscript manager are you using, JS Blocker or Tampermonkey, and what version?

**Comment by vtimdon** [comment]
I'm using Tampermonkey. 
Here's what I get when I hit export. 
https://drive.google.com/file/d/0B5Bg8qnUURo9N2dIYUI3OXRpTlE/view?usp=sharing

**Comment by ccd0** [comment]
I meant the 4chan X settings on the 4chan page, not the Tampermonkey settings page.

Can you test if [previous versions](https://github.com/ccd0/4chan-x/blob/master/CHANGELOG.md) work?
Does it work if you use [JS Blocker](http://jsblocker.toggleable.com/) instead?

**Comment by vtimdon** [comment]
Oops, sorry. Here are the settings. 
https://boards.4chan.org/mu/#cfg=%7B%22settings%22%3A%22%7B%5C%22quotePreview%5C%22%3Atrue%2C%5C%22backlinks%5C%22%3Atrue%2C%5C%22quickReply%5C%22%3Atrue%2C%5C%22threadUpdater%5C%22%3Atrue%2C%5C%22threadHiding%5C%22%3Atrue%2C%5C%22altCaptcha%5C%22%3Afalse%2C%5C%22alwaysAutoUpdate%5C%22%3Atrue%2C%5C%22topPageNav%5C%22%3Afalse%2C%5C%22threadWatcher%5C%22%3Afalse%2C%5C%22imageExpansion%5C%22%3Atrue%2C%5C%22fitToScreenExpansion%5C%22%3Afalse%2C%5C%22threadExpansion%5C%22%3Atrue%2C%5C%22alwaysDepage%5C%22%3Afalse%2C%5C%22localTime%5C%22%3Atrue%2C%5C%22stickyNav%5C%22%3Afalse%2C%5C%22keyBinds%5C%22%3Afalse%2C%5C%22inlineQuotes%5C%22%3Afalse%2C%5C%22filter%5C%22%3Atrue%2C%5C%22revealSpoilers%5C%22%3Afalse%2C%5C%22imageHover%5C%22%3Afalse%2C%5C%22threadStats%5C%22%3Atrue%2C%5C%22IDColor%5C%22%3Atrue%2C%5C%22noPictures%5C%22%3Afalse%2C%5C%22embedYouTube%5C%22%3Atrue%2C%5C%22embedSoundCloud%5C%22%3Afalse%2C%5C%22updaterSound%5C%22%3Afalse%2C%5C%22customCSS%5C%22%3Afalse%2C%5C%22autoScroll%5C%22%3Afalse%2C%5C%22hideStubs%5C%22%3Afalse%2C%5C%22compactThreads%5C%22%3Afalse%2C%5C%22centeredThreads%5C%22%3Afalse%2C%5C%22dropDownNav%5C%22%3Afalse%2C%5C%22autoHideNav%5C%22%3Afalse%2C%5C%22classicNav%5C%22%3Afalse%2C%5C%22fixedThreadWatcher%5C%22%3Afalse%2C%5C%22persistentQR%5C%22%3Afalse%2C%5C%22forceHTTPS%5C%22%3Afalse%2C%5C%22darkTheme%5C%22%3Afalse%2C%5C%22linkify%5C%22%3Afalse%2C%5C%22unmuteWebm%5C%22%3Afalse%2C%5C%22disableAll%5C%22%3Atrue%2C%5C%22reportButton%5C%22%3Afalse%2C%5C%22QR-position%5C%22%3A%5C%22right%3A%200px%3B%20top%3A%2010%25%3B%5C%22%2C%5C%22customMenu%5C%22%3Afalse%2C%5C%22imageHoverBg%5C%22%3Afalse%7D%22%2C%22filters%22%3A%22%5B%7B%5C%22active%5C%22%3Atrue%2C%5C%22pattern%5C%22%3A%5C%22kpop%20general%5C%22%2C%5C%22boards%5C%22%3A%5C%22%2Fmu%2F%5C%22%2C%5C%22type%5C%22%3A5%2C%5C%22auto%5C%22%3Atrue%2C%5C%22hide%5C%22%3Atrue%7D%2C%7B%5C%22active%5C%22%3Atrue%2C%5C%22pattern%5C%22%3A%5C%22%2Fkpg%2F%5C%22%2C%5C%22boards%5C%22%3A%5C%22%2Fmu%2F%5C%22%2C%5C%22type%5C%22%3A5%2C%5C%22auto%5C%22%3Atrue%2C%5C%22hide%5C%22%3Atrue%7D%5D%22%7D

The thumbnails actually did show up on the previous version, directly after I updated yesterday they stopped showing up.

**Comment by ccd0** [comment]
Those are the settings from the native extension.

But I realized you probably just have Werk Tyme turned on by accident. Just press Shift+W or uncheck "Werk Tyme" in the menu in the header. Sorry, should have realized that sooner.

**Comment by vtimdon** [comment]
That fixed it. Thanks
