### ISSUE TITLE
Extremely laggy when typing in Quick Reply box

### ISSUE THREAD

**Issue by HeyItsJono** [ccd0/4chan-x#739]
Hey there,
I'm getting a weird issue where typing in the QR box is super laggy and slow, even though nothing's loading and my CPU usage, etc is all normal. Typing in the original reply form on the page works fine and has no lag but it just seems to be the QR box that's giving the issue with lag. Any ideas?

**Comment by ccd0** [comment]
What browser?
Have you tried temporarily disabling other extensions to check for a conflict?

**Comment by HeyItsJono** [comment]
Chrome  48.0.2564.82 m.
Hmm, I checked in Incognito and the lag doesn't seem to be present, so I guess it must be an extension, but I have no clue which... Any ideas as to what the extension would have to do to cause something like this, so that I can narrow it down? I'd rather avoid disabling/reenabling every extension I have because I have heaps. I don't have any other 4chan specific ones though.

**Comment by ccd0** [comment]
Just to double check, you did enable 4chan X in incognito? You weren't testing the native extension?

>Any ideas as to what the extension would have to do to cause something like this, so that I can narrow it down?

Well, 4chan X does have the character counter on the Quick Reply (hidden below half the max count but still updated), so if the extension does something expensive every time some text on the page changes, that would cause lag.

**Comment by ccd0** [comment]
Also, you can do "Inspect Element" on the QR comment field and check if any extension besides 4chan X has registered a listener on the `input` event.

**Comment by HeyItsJono** [comment]
Yup, I enabled 4chan X in Incognito so the native extension should've been disabled as per X's feature. I did Inspect Element but I can't find out where the input event is or how to see registered listeners, all I see are a bunch of CSS properties as usual. I clicked the Event Listeners tab but it's completely blank on the div with the id "qr". I can't think of any extension that might react to standard text input, and it's weird because it only seems to be in the QR box, not in any other textbox including the standard reply textbox.

**Comment by ccd0** [comment]
Well, for example, a badly written "replace all X with Y" extension might listen for any change to the page text and scan the whole document for occurrences of X on every change. So when 4chan X updates the character counter in the QR, there would be lag.
