### ISSUE TITLE
dead threads in the /b/ catalog now redirect to https://4ch.be instead of https://fgts.jp/b/?

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#740]
I'm now getting redirected to 4ch.be/b/ which doesn't even store the full pics posted on /b/, and is fucky 99% of the time. What is this shit?

**Comment by ccd0** [comment]
You can change the archives used at the top of the "Advanced" settings panel. I changed the defaults temporarily because some of the archives were down at the time. I'll revisit that shortly.

**Comment by ccd0** [comment]
fgts.jp is back to its normal position now.
