### ISSUE TITLE
Random black boxes appearing on page

### ISSUE THREAD

**Issue by DeckardEdward** [ccd0/4chan-x#748]
Recently, 4chan X has started to occasionally spawn big black spoiler blocks all over pages when I run my cursor over clickable elements. It doesn't do it every time, and they go away when I scroll, but something tells me they shouldn't be there in the first place.

Examples can be find here:
https://dl.dropboxusercontent.com/u/25349796/Pictures/boxes1.png
https://dl.dropboxusercontent.com/u/25349796/Pictures/boxes2.png
https://dl.dropboxusercontent.com/u/25349796/Pictures/boxes3.png

Also, my browser seems to seize up when I'm scrolling through long threads. It seems to only happen on 4chan. I'll put in a separate ticket for this if you think I should.

Edit: I'm using Firefox.

**Comment by nebukazar** [comment]
Does this happen without Oneechan enabled? 
Do you have an AMD card?

I've had this happen to me before. See: https://github.com/nebukazar/OneeChan/issues/34

**Comment by DeckardEdward** [comment]
It doesn't seem to be happening with Oneechan disabled. I probably should have checked that first and taken this over to your bugtracker instead of CCD0's.

I have an Nvidia card, but I could probably do with a driver update. I'll run up the changes from your thread and drop an update on my problem here when I'm done.

**Comment by DeckardEdward** [comment]
I've updated my drivers, disabled hardware acceleration, and re-enabled Oneechan, and it appears that the black boxes aren't spawning anymore. I think this issue might be resolved.

Thanks, Neb!
