### ISSUE TITLE
Can't save 4chan images/pages in linux via palemoon?

### ISSUE THREAD

**Issue by Zzooouhh** [ccd0/4chan-x#754]
I'm using Palemoon 26 in KDE OpenSUSE and my current profile is located within a Windows install on a separate partition. Had to fiddle around a bit to get saving files/pages working properly on both Palemoon installs at once (kept searching for a non-existent path from the original Windows install), but now it works - except for all the sites under the 4chanx script.

First I thought it was just a hotkey conflict so I removed all instances of "Ctrl+S" or any of its variations from 4chanx, but no dice - saving from the right click menu doesn't work either, the command simply gets ignored without any error message. I've attempted this on Greasemonkey 1.15.1 and also [this unofficial GM fork](https://github.com/janekptacijarabaci/greasemonkey/releases/tag/3.7beta1Fork), version 3.6 with the same results. The same script works without problems in Windows and I haven't noticed bugs with any other 4chanx feature in Linux so far; also [8chanX](https://github.com/Pashe/8chanX) doesn't have this issue. I realize that this is a highly specific setup, so I'll appreciate any kind of suggestions for where the problem might lie here. (Does 4chanx interact with the download path in some way?)

**Comment by ccd0** [comment]
This doesn't sound like something 4chan X should have any effect on. Have you tested it with 4chan X disabled?

**Comment by Zzooouhh** [comment]
Hm, this is strange... I remember once I've tried disabling it and it worked, unfortunately I don't remember the exact settings anymore. But I've just tried it again and it still doesn't work - more than that, saving from rbt.asia doesn't work either and I don't have any script for that site. So I suppose it could be a Palemoon issue then.

**Comment by ccd0** [comment]
Probably. Might be something intermittent, and it working the first time you tried disabling 4chan X was a coincidence.

**Comment by Zzooouhh** [comment]
Seems like [this](http://forums.mozillazine.org/viewtopic.php?f=38&t=2937119&p=14172449) is the issue I'm experiencing. Closing since at this point it's clearly not 4chanX related.
