### ISSUE TITLE
/f/ Purge Position

### ISSUE THREAD

**Issue by vampiricwulf** [ccd0/4chan-x#757]
Idk if you'd be interested in it: https://github.com/zixaphir/appchan-x/commit/8b5cbc6541de85a0e494701fcd213ae9abec76e0?diff=split#diff-489d4ea258d753385c966fd4a57da710

**Comment by ccd0** [comment]
Thanks. Should go out next beta.

**Comment by vampiricwulf** [comment]
Seinkyuu~
