### ISSUE TITLE
Webm issue with Noscript addon

### ISSUE THREAD

**Issue by swoonet** [ccd0/4chan-x#76]
Noscript 2.6.8.26
Palemoon 24.5.0 x86

I've tried to tinker with the various settings of Noscript without much success, and short of disabling it there does not appear to be much I can do except hope that a solution can be found either in a later update, or someone discovering settings either within the extension or Noscript that fixes this.

With default settings of both 4chan x and Noscript, Webm files will not load for me, displaying instead a placeholder or nothing at all when expanded/hover expanded. 

With settings adjusted down to allow more permissions/allowing certain archives for some reason?, hover expanding causes the Webm to load after hovering over the same one twice, but stops playing after a few seconds and generally does not appear to function. Bypassing the hover activation and clicking to expand has it play normally.

Using the gallery function does not appear to have any issue with viewing Webms, all of this only occurs when trying to view them in a thread, and the type/behavior of the issue seems different for different boards. 

This does not happen when viewing 4chan without 4chan x, and I think given the above it may have something to do with the way webms are loaded with this extension active, directing/referencing the archives for some reason.

**Comment by ccd0** [comment]
Is this still happening?

**Comment by swoonet** [comment]
Sorry for the late response. Unfortunately, I cannot say for certain as I had long since changed browsers, after which the problem stopped happening.
--------------------------------------------
On Tue, 10/27/15, ccd0 <notifications@github.com> wrote:

 Subject: Re: [4chan-x] Webm issue with Noscript addon (#76)
 To: "ccd0/4chan-x" <4chan-x@noreply.github.com>
 Cc: "swoonet" <justdo3999@yahoo.com>
 Date: Tuesday, October 27, 2015, 12:05 AM
 
 Is this still happening?
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by ccd0** [comment]
Thanks.  I suppose I might as well close this then.
