### ISSUE TITLE
4chan's <wbr> tags break TeX

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#765]
We should figure out how to remove them without causing unwanted wrapping between the post and side arrows.

**Comment by an-electric-sheep** [comment]
maybe replace with a breaking zero-width unicode char?

**Comment by ccd0** [comment]
Would still break TeX if they appeared in the middle of a tag.

**Comment by ccd0** [comment]
I decided to just remove them if there was TeX in the post since TeX can cause the unwanted wrapping effect with or without the `<wbr>` tags.
