### ISSUE TITLE
Quite Inlining not working

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#770]
Quote inlining stopped working for me, not really sure why. Worked fine for me, until 4chan x stopped functioning entirely on a second computer that I shared addons with via Chrome. Reinstalled 4chan X, after that it just didn't work anymore, instead of opening the replies within the same text box, it simply jfumps to the post. Thought at first it was an options issue, but checked and made sure, quote inlining is activated. It simply jumps to the post all the time. Full clear of browser cache and history does not help. 

Here are my exported options, though I recently reset them to the default: 

http://pastebin.com/07dU2XAG

Checking the console, I get the following error: Failed to load resource: net::ERR_BLOCKED_BY_CLIENT in http://s.zkcdn.net/ados.js

**Comment by ccd0** [comment]
Turn off "Inline Cross-thread Quotes Only".

**Comment by Gmoth** [comment]
Welp I'm retarded, that was the issue. I don't remember that being a default option in the past, but I might be wrong. Eitherway, thanks.

**Comment by ccd0** [comment]
> I don't remember that being a default option in the past

It wasn't.

**Comment by sonsais** [comment]
I have this issue, inline cross read quotes only didnt fix it
