### ISSUE TITLE
NoScript issues (was: Index refresh failed Error (0))

### ISSUE THREAD

**Issue by Talcon** [ccd0/4chan-x#771]
I get this error when I open up 4chan /v/ as I first start up my browser. Once I manually refresh, the issue is gone. If I close the tab, and open 4chan again, it doesn't reappear. It happens consistently, but only when I first load up 4chan.

I'm using Firefox 44.0.1. I don't remember if this started happening once I updated Firefox to its latest  version. My versions of 4chan X and Greasemonkey are up to date, I reinstalled them just to be sure

This is what I get from shift+ctrl+J
https://a.pomf.cat/beszuv.jpg

**Comment by ccd0** [comment]
It doesn't happen for me.
It looks like http://a.4cdn.org/v/catalog.json isn't being loaded correctly. Do you have any extensions that might be interfering with it loading? What happens if you open http://a.4cdn.org/v/catalog.json as you first start Firefox?

**Comment by Talcon** [comment]
Just a bunch of jumbled words. I disabled every add-on (except NoScript, but just in case I enabled every script on 4chan) and the error still happens. Weirdly, the problem went away for the next two times I started up 4chan (/v/ is my homepage), but after that it came back

**Comment by CptWinters** [comment]
I have the same problem.
I also get posting errors (the post appears fine, just that it doesn't notify me with a (you) after I get a reply) whenever I do my first post after opening the browser, but works fine after though it sometimes does it again.

This only started happening after updating Firefox to version 44, so I guess it has to do with that.

**Comment by ccd0** [comment]
@CptWinters
Are you using any other extensions?

@Talcon
> except NoScript, but just in case I enabled every script on 4chan

NoScript does other stuff than just blocking scripts. What happens with NoScript disabled? This may be a NoScript-specific issue that will have to be fixed in NoScript.

**Comment by ccd0** [comment]
Also, if it's a NoScript bug, it may be blocking something even though you've set it to not block it. Please test without it so we can see if that's what it is.

**Comment by CptWinters** [comment]
@ccd0 I now tried disabling NoScript, and it indeed does appear to be an issue related to it, as everything loads fine without it.

I'd assumed it was something related to FF44 as dragging and dropping links into Steam chat windows stopped working also after updating to FF44, though this still doesn't work after disabling NoScript. Though that's an issue completely unrelated to this.

**Comment by Talcon** [comment]
I disabled NoScript, it worked consistently the next three times. I re-enabled it, problem came back. It's definitely NoScript.

**Comment by Talcon** [comment]
I don't recall tinkering with any 4chan script since problem started, any idea and I'm enabling everything except google analytics, is there anything I can do on my end to fix this?

**Comment by ccd0** [comment]
Make sure NoScript is up to date, and if it is, you could try downgrading Firefox to ESR until NoScript is compatible.

**Comment by Talcon** [comment]
Thanks!

**Comment by ccd0** [comment]
Probably also the cause of #771:



> For some reason, whenever I try to post anything on 4chan, it gives me the message about how it's encountered an error while posting. The weird thing is that it still updates the thread with my post, but it doesn't have any (You) backlinks or notifications. This only just recently started, the earliest instance of this being yesterday.
> 
> Here's an example: https://u.pomf.is/yxgbaj.png

**Comment by ccd0** [comment]
Did this ever get fixed, or at least reported?

**Comment by Talcon** [comment]
oh, yeah, sorry, I got it fixed, I think I just downgraded Firefox version, and turned off automatic updates. Haven't looked back since,

**Comment by ccd0** [comment]
That's not a fix. Can anyone that's tested the current versions of Firefox and Noscript comment?

**Comment by Talcon** [comment]
Just updated to 45.0.1 (current version) and I was able to load my homepage, /v/, without any problems. Refreshed a couple times to be sure. Everything is swell. Thanks for following up!
