### ISSUE TITLE
"4chan X encountered an error while posting"

### ISSUE THREAD

**Issue by WaifuWilson** [ccd0/4chan-x#775]
For some reason, whenever  I try to post anything on 4chan, it gives me the message about how it's encountered an error while posting. The weird thing is that it still updates the thread with my post, but it doesn't have any (You) backlinks or notifications. This only just recently started, the earliest instance of this being yesterday.

Here's an example: https://u.pomf.is/yxgbaj.png

**Comment by ccd0** [comment]
Do you have any other extensions? Try disabling them temporarily to see if one of them is causing this.

**Comment by ccd0** [comment]
It could also just be 4chan having problems. Is it still happening?

**Comment by zackultimate** [comment]
Hello.

I've been experiencing the very same issue as OP.
After various tried, I found out there seems to be a compatibly issue with the most recent version of nonscript. Disabling it seems to fix the issue for me.

Any tips? Scripts are of course completely allowed for 4chan.

**Comment by ccd0** [comment]
All I can suggest is reporting the bug and temporarily downgrading Firefox to ESR until it's fixed.
