### ISSUE TITLE
webm problems

### ISSUE THREAD

**Issue by jimmyrustles** [ccd0/4chan-x#780]
Whenever I hover over a webm it'll play but I can't use any of the options (pause/play without clicking on it and having it load in a new tab, is there an option to make it not load in a new tab and it just stays in the same place, with me able to control it? Is there also an option to just have the webm pause if I move the mouse away from the webm? Whenever I hover the mouse on or off it'll just replay the webm instead of pausing.

**Comment by ccd0** [comment]
Check "Image Expansion" and uncheck "Restart when Opened".

**Comment by jimmyrustles** [comment]
Awesome, is there any chance you could implement a way to control the webm
just via mouseover instead of clicking on it and opening it's own tab?

**Comment by ccd0** [comment]
If you have "Image Expansion" checked and you click on it, it should expand inline. If you've changed that and refreshed the tab and it's still opening another tab when you click them, you have a problem. What browser are you using? Are there any error messages in the console that appear when you click them? Have you tried temp-disabling all other extensions to check for a conflict?

**Comment by jimmyrustles** [comment]
Holy shit, checked Image Expansion and it works great! Thanks!
