### ISSUE TITLE
Name & tripcode not saved in form after posting

### ISSUE THREAD

**Issue by neo0031** [ccd0/4chan-x#781]
As titled, name/tripcode input into name space in the quick response form is not saved after posting. Specifically, the input information is not there in the form after triggering another quick response or normal response. It does not seem to suggest it either after typing the correct first letter.

Chrome 48.0

**Comment by ccd0** [comment]
Could you be more specific about what you are doing when this happens? What board are you on and what page are you posting from the first time? Is the second post from the same page or another page? Do you have `Persistent QR` on? What are your other settings? Do you close or hide the QR between the posts? Are you using any other extensions?

If you post with a name in one tab and then go to another tab where you have previously opened the QR, not seeing your name is expected behavior. Is that what's happening or is it something else?

**Comment by neo0031** [comment]
I do apologise for not being more specific. I will try and answer your questions above.

This occurs on any board. This seems to be limited to a name/tripcode I have used "before" (I do not know when the cut off was). The second post is on the same page, same browser tab, same browser session. I do not close the QR form but I do not have Persistent QR on.

Furthermore the name field, on another mouse click, will suggest my "names" remembered from other browser forms (not 4chan), but do not seem to suggest the name/tripcode I have input there. I cannot be sure whether this is a fault with the 4chanX extension, with Chrome, or a combination of both.

My other extensions do not interfere with the use of 4chan except that of Adblock.

**Comment by ccd0** [comment]
Can you post your exported settings?
Also, can you test whether it happens with all other extensions disabled?

**Comment by neo0031** [comment]
I do not seem to be able to find where the exported settings are saved.

However I did try disabling all extensions except 4chanX and it seemed to work. (Name field remembers name after post, and even after deleting the form information, the suggestion comes up after clicking the form again)

I do apologise for not trying this obvious solution earlier on. I will now try to see which other extensions are causing the problem.

**Comment by ccd0** [comment]
Did you ever find out what extension was causing the problem?

**Comment by neo0031** [comment]
Sadly no, as Chrome/the form started being able to remember the name I have input after disabling all extensions last time and enabling them all.

However if the same thing occurs again I will take note to check all the extensions one by one to see which one is interfering with the plugin/browser's ability to remember inputted form data.

**Comment by ccd0** [comment]
Fair enough. Thanks!
