### ISSUE TITLE
No longer recognizes my posts

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#792]
For the last week or so, I haven't seen a (you).  It could have been when I upgraded to FF 44.0.2

**Comment by ccd0** [comment]
Make sure "Remember Your Posts" and "Mark Quotes of You" are turned on.

**Comment by BestName** [comment]
Could be just 4chan being shit. For the past few months I've been getting posting errors on every other post and although my posts always go through 4chan x does not recognize them as my own due to the error.

**Comment by ccd0** [comment]
This is probably the NoScript issue: #771
