### ISSUE TITLE
Issue with per-board sort type

### ISSUE THREAD

**Issue by saxamaphone69** [ccd0/4chan-x#813]
I have `fit-title-sort:"reply count"` in my header.
Click it, /fit/ loads, sorted by reply count, as expected.
I go back to /fa/ (which is `fa-title` in my header) and it is sorted by reply count.

1.11.28.2 and latest Chrome.

Essentially, 4chan X should remember the sort type of all previous boards before going to one that is specifically sorted.

**Comment by ccd0** [comment]
Do you have Per-board sort type on? It's in the header menu under Index Navigation.

**Comment by saxamaphone69** [comment]
I did not!
Wasn't aware it was an option in the header.
I would've assumed it'd be on by default - especially if you're willingly going through the effort in the advanced tab to set that in the header.
My mistake; apologies!

**Comment by ccd0** [comment]
>I would've assumed it'd be on by default

It is in new installs, but if you've already changed it as a global setting, it will stay that way on upgrade.

**Comment by saxamaphone69** [comment]
My same old install, and I hadn't (hence why I didn't realise there was an option). Ah well, no worries. Thanks @ccd0.

**Comment by ccd0** [comment]
I mean if you've ever changed the sort order.
