### ISSUE TITLE
.ogg video files

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#817]
https://rbt.asia/g/thread/S53637056#p53638207
>4chanX embeds ogg as audio
>TRIGGERD

Most .ogg files are audio, but if we can, video files with .ogg extensions should be embedded correctly. Perhaps we could use a video element for both?

**Comment by r3c0d3x** [comment]
Made a JSFiddle that could help fix this bug: https://jsfiddle.net/r3c0d3x/4sqh2a16/6/embedded/js,html,result/dark/

I'd file a PR with a fix but I don't know the codebase (or CoffeeScript) very well yet.

**Comment by ccd0** [comment]
By your example, I think we do care, because it leaves an empty space above the controls that we'd like to get rid of. We can do that by adding a CSS class once we know it's audio-only.

`videoTracks` doesn't seem to have very good browser support at the moment, but we could use `videoHeight`.

**Comment by r3c0d3x** [comment]
`videoHeight` appears to be working fine:
https://jsfiddle.net/r3c0d3x/4sqh2a16/7/embedded/js,html,result/dark/

**Comment by ccd0** [comment]
I decided to just switch to an audio element instead of trying to get the CSS to work out.
5dd9b7da3b0491635770a7dd1a08d22ca5e5d82b
Should be fixed in the newest beta (v1.11.32.1).
