### ISSUE TITLE
md5 and image filter checking

### ISSUE THREAD

**Issue by Gostavikyi** [ccd0/4chan-x#819]
Is there away to check multiple md5 codes at once to see what the picture actually is?

**Comment by ccd0** [comment]
You want to know what the MD5 of an image is? 4chan lists it as the `data-md5` attribute of the thumbnail which you can see through right click > Inspect Element. You could also look at the URL for searching the archive for that MD5, or make a new filter.

#240 asked for a way to add it to the file info. Is that something that would be useful to you?

**Comment by Xibster** [comment]
I don't mind adding the picture to the filter to find out the md5 code. I want preview multiple pictures from the md5 filiter menu. Maybe hover your cursor over the hashcode and it will show the picture for the code.

**Comment by ccd0** [comment]
In theory it could be done, but we'd have to search the archives for the MD5.
