### ISSUE TITLE
Loading icon stuck on

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#832]
From https://rbt.asia/g/thread/S53824932:

![1459609281667](https://cloud.githubusercontent.com/assets/5894749/14229999/ee84270c-f8fb-11e5-870d-b29a23d25cc2.png)

> Using ccd0's 4chan X thread tabs sometimes get stuck on the loading icon, why is this? Didn't happen before. Is anyone getting the same?
> It's pretty annoying. If I go to the network tab the only request is the json of the current thread to update

I personally haven't seen this and it would help to have more info about when it happens and what browser / settings / other extensions the people seeing it are using.

**Comment by geldimedov** [comment]
I have this problem too. Ublock Origin is the only other addon I have enabled (aside from Greasemonkey, obviously).

Sometimes it works, sometimes it doesn't. The status bar usually tells me that it's transferring info or something of that sort from 4cdn. I'll take a better look at it the next time it does this. The temporary solution for that particular tab is usually to just hit esc to stop it from loading whatever it is it's loading.

**Comment by KillerJaguar** [comment]
I'm having this problem as well, but it only happens when I open enough threads after having Firefox open for several hours. Eventually it starts doing this for every following thread I open.

**Comment by g4ts** [comment]
Same problem, same browser (Firefox). It happens especially when I visit 4chan from a Private Browsing window: when I switch back to a normal window, the icon is stuck on loading until I manually stop it. If I restart the browser, it behaves normally again. 
Maybe it's worth something, but it happens only with threads' tabs, the 4chan-X catalog ones always sport the correct favicon.

**Comment by ccd0** [comment]
For anyone having or who has had this problem, which version of the captcha are/were you using? It might be something wrong with the captcha given #917.

**Comment by robertdhernandez** [comment]
I'm using captcha v1

**Comment by ccd0** [comment]
Also it might help to see your settings in general. Can you export and post them?

And are you using OneeChan or any other userscripts?

**Comment by robertdhernandez** [comment]
[My settings](https://dl.dropboxusercontent.com/u/3877425/4chan%20X%20v1.11.29.5-1463791235828.json)

I'm not using OneeChan. The only other script I have running is 4chan Linkify.

**Comment by ccd0** [comment]
from https://desustorage.org/a/thread/141815371/#141818454:
> People using 4chan X ITT, do you have a problem with the page constantly loading?
> it seems there's data transferred constantly from i.4cdn.org
> sorry for asking here by the way

**Comment by robertdhernandez** [comment]
Yeah, it says "Transfering data from s.4chan.org..." or i.4chan.org

**Comment by ccd0** [comment]
@robertdhernandez
Can you check the Network tab in your console (F12) to see specifically what's downloading? Also, you should be able to see there whether something downloading repeatedly, or just taking a long time.

**Comment by robertdhernandez** [comment]
I checked the network tab and it seemed like everything was loaded proper. But when I checked the console after switching tabs I got:

>14:51:30.475 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://i.4cdn.org/v/1464806289103s.jpg. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>

Doing a little research, I saw someone mention a [similar problem](https://github.com/cs-education/sysbuild/issues/111) with an addon I have, [HTTPS Everywhere](https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/). I'll disable it and see if it still happens.

**Comment by ccd0** [comment]
Do you have the SSL Observatory turned on? Some people have reported it causing performance problems.

**Comment by ccd0** [comment]
Also any other extensions (not just userscripts)?
And do you know specifically where you got the 4chan Linkify script from?

Unfortunately 4chan doesn't support CORS on i.4cdn.org at the moment, so such errors are expected if you make AJAX requests for images, but there shouldn't be anything in 4chan X making such a request (except through GM_xmlhttpRequest).

**Comment by ccd0** [comment]
Another question: Do you have ads blocked or unblocked? If they're unblocked, it might be an ad loading.

**Comment by ccd0** [comment]
Icarus77 wrote in #952: 
> So I'm using Cyberfox (but I've also tried normal Firefox and Waterfox) and have had this persisting issue with 4chan X where the tab clover icon will work fine, but then within a few minutes of having the web browser open, the icon will just constantly have the swirling icon as if the page is loading infinitely, even though the page is already fully loaded. It affects 4chan only, and affects all boards.
> 
> Does anyone know how to fix this? It's kind of annoying because once this happens I can't see the red/green/blue clover icon with the notification for when I have a reply or if the thread's dead/archived. I have to restart my browser to fix it every time, then it just happens again a few minutes later.
>

**Comment by ccd0** [comment]
Also, do you have Flash enabled?

**Comment by ccd0** [comment]
> It happens especially after I open a Private Browsing window: when I switch back to a normal window and browse 4chan, the icon is stuck on loading until I manually stop it. If I restart the browser, it behaves normally again.

Managed to reproduce it this way although it's still finicky when it happens. Seems it was trying to load the beeping sound the thread updater makes. I don't know why it would get stuck loading that as it's a data URI and not something it has to fetch over the network, but it was happening. Probably a Firefox bug. In any case, it should be fixed now.
