### ISSUE TITLE
captcha is getting unbearably bad

### ISSUE THREAD

**Issue by ghost** [ccd0/4chan-x#838]
i don't know if this is on your end or theirs but the captcha has gotten really awful lately. it takes minutes at a time for the captcha to actually appear in the window. if the captcha bugs out and rejects my post i have to reload the entire thread again and open the QR window and pray the captcha window actually appears. usually it doesn't.

**Comment by ccd0** [comment]
Could be connection problems. Recaptcha gets very shitty when you're using it over a non-perfect Internet connection. In most cases, you shouldn't have to reload the page, though, unless it isn't showing up at all, which may mean Google's initial Javascript didn't load. You may often have to destroy and recreate the captcha, which you can do by clicking on the `Captchas: __` link.

You might try turning on either of `Use Recaptcha v1` or `Force Noscript Captcha` to see if that improves things.
