### ISSUE TITLE
I'm blind

### ISSUE THREAD

**Issue by deadman3000** [ccd0/4chan-x#843]
So when can we expect 4chan X to become style aware? Unless I switch back to the default user style I can't read this for ***t

http://i.imgur.com/jslq4mt.jpg

This is a request of sorts. Thanks for the constant updates though. You are doing Zod's work.

**Comment by ccd0** [comment]
How are you selecting the style? It can detect the selected style if you select it from the dropdown at the bottom of the web page. It doesn't currently work if you select it using your browser's native style selection UI.

**Comment by gregBurgers** [comment]
I get the same if I disable 4chan .css's from loading using uMatrix and paste the tomorrow theme .css in the 4chan-x custom CSS box.

**Comment by ccd0** [comment]
@gregBurgers
See
https://github.com/ccd0/4chan-x/issues/481#issuecomment-143639414

**Comment by ccd0** [comment]
Merging into #481; let me know if that's a mistake.
