### ISSUE TITLE
Thread/board update error

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#850]
Submitter: tom
Email: dick@harry.org
Fail to update boards or thread. Turning JSON off is temporary fix only, as it is no longer 'auto'.

**Comment by ccd0** [comment]
Sounds like either a connection issue or a temporary issue on 4chan's end, which happens from time to time. If it keeps happening, look at your other extensions and try temporarily disabling them to see if they're blocking the JSON.

**Comment by OnTheGrind** [comment]
The error is persistent if I enable JSON updating the board will show with no threads in it and flash an error. I have temporarily disabled ALL extensions except that which 4chanx is required to run. I still have the same issue. 

Can you think of another possible reason? 

Thanks bro.

**Comment by ccd0** [comment]
What version of your browser and userscript engine are you using?

Can you check that you can see
http://a.4cdn.org/g/catalog.json
and it isn't being blocked by something?

Do you get any errors in your console when you try to open the board? (In Firefox you may have to look at the browser console (control+shift+J) rather than the web console).

**Comment by OnTheGrind** [comment]
Firefox 45.0.2
Scriptish 0.1.11.1-Signed
4chanx 1.11.32.2

When I click the catalog.json it just shows text. `[{"page":1,"threads":[{"no":51971506,"sticky":1,"closed":1,` And so on.

index refresh failed Error (0)

Well, the console shows a problem...

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://a.4cdn.org/diy/thread/984384.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

TypeError: getTabForContentWindow is not a function background.js:151:14
GET 
XHR 
http://a.4cdn.org/diy/thread/984384.json [HTTP/1.1 200 OK 84ms]
GET 
XHR 
http://a.4cdn.org/diy/thread/984384.json [HTTP/1.1 200 OK 903ms]
GET 
XHR 
http://a.4cdn.org/diy/thread/984384.json [HTTP/1.1 200 OK 74ms]
GET 
XHR 
http://a.4cdn.org/diy/thread/984384.json

I disabled all extension except scriptish, 4chanx. Restarted firefox, still the same issue.

**Comment by ccd0** [comment]
Scriptish hasn't been updated in years so it's no surprise things are breaking. You should use Greasemonkey.

**Comment by OnTheGrind** [comment]
I made an error, I meant greasemonkey.

![test](https://cloud.githubusercontent.com/assets/18671146/14807112/5fdfff2c-0b47-11e6-83ec-78176cf8cfc5.png)

**Comment by ccd0** [comment]
Do you get any error when you go to http://boards.4chan.org/diy/thread/984384 and paste
`x = new XMLHttpRequest(); x.open('GET', 'http://a.4cdn.org/diy/thread/984384.json'); x.send()`
in the web console (control+shift+K)?

**Comment by OnTheGrind** [comment]
`x = new XMLHttpRequest(); x.open('GET', 'http://a.4cdn.org/diy/thread/984384.json'); x.send()
undefined
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://a.4cdn.org/diy/threads.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

I have googled the CORS header, which seems FFox is blocking the JSON request because its cross-site and the JSON host is missing the Acces-Control-Allow-Origin Header.

![pastelol](https://cloud.githubusercontent.com/assets/18671146/14833966/ce6c1376-0bcf-11e6-9713-0fa0ba7c57d7.png)
`

**Comment by ccd0** [comment]
> I then installed cors everywhere addon for firefox @ https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/?src=search . The issue seems to have been resolved.

You've allowed any website to read from any website. That's very dangerous if you ever visit sites that need to be secure (your bank, webmail) in that browser. I wouldn't consider that a reasonable fix.

Are you routing your web traffic through that Sophos thing I see in your taskbar? That's very likely what's breaking it. Try turning off at least the web filtering part of it.

> It is curious why other Firefox users aren't experiencing the same issue?

Because 4chan does send the correct header. Something between you and 4chan is altering the headers.
![screenshot from 2016-04-26 19-22-42](https://cloud.githubusercontent.com/assets/5894749/14839980/69beaf32-0be4-11e6-9b89-9a5b0854d366.png)

**Comment by ccd0** [comment]
Also make sure Sophos is updated. It's known that older versions had this problem, but it's supposed to be fixed:
https://community.sophos.com/products/endpoint-security-control/f/3/t/4905

**Comment by OnTheGrind** [comment]
ccd0. 

Yes, it appears to be Sophos. I am using the latest free version. 1.0.3.

I would've never suspected Sophos to be honest. Oddly, I've had sophos about 2 weeks, but this behavior is more recent. "Web threats" is turned off, so wtf? Why would an A/V be doing firewall/UTM duties..

Thanks bro.
