### ISSUE TITLE
[Feature Request] "X posts by this ID."

### ISSUE THREAD

**Issue by Sarteck** [ccd0/4chan-x#851]
Without 4chanX installed, when hovering over a PostID, I am able to see "X posts by this ID" where X is the amount of posts that IP has in the thread.

With the extension installed, hovering merely shows "Highlight posts by this ID."

I cannot seem to find an option to change this feature to show the amount of posts by an ID.  Am I just blind?If not, can this feature be added?

**Comment by ccd0** [comment]
Also requested at #970.

**Comment by ccd0** [comment]
It's in the latest beta now (v1.12.0.1).
