### ISSUE TITLE
4chanX not starting

### ISSUE THREAD

**Issue by pachuco** [ccd0/4chan-x#855]
Specs:
PaleMoon Atom v 26.2.1
Scriptish v 0.1.11.1

4chanX for GreaseMonkey of versions v1.11.31.1 and v1.11.31.0 is not starting up at all.
Reverted to v1.11.30.3, problem solved.

**Comment by ccd0** [comment]
I'm surprised Scriptish was even working at all. I did not manage to get it to work myself. Try Greasemonkey.  Both [version 1.15](https://addons.mozilla.org/en-US/firefox/addon/greasemonkey/versions/1.15.1-signed) and https://github.com/janekptacijarabaci/greasemonkey/releases/latest should work with Pale Moon.

**Comment by ccd0** [comment]
Got http://forum.palemoon.org/viewtopic.php?f=46&t=8215#p55122 working and found what changed. This affects some other setups as well, so I'll put out a fix soon.

**Comment by ccd0** [comment]
Should be fixed now, although I would still recommend using Greasemonkey.
