### ISSUE TITLE
Filters not working correctly 

### ISSUE THREAD

**Issue by Xibster** [ccd0/4chan-x#856]
Sometimes the filters doesn't work anymore. Is there a limit to how much I can filter or this a bug?

**Comment by ccd0** [comment]
Can you give an example of a filter that's not working?
Be sure to reload the page after changing the filters.

**Comment by Xibster** [comment]
Clearing the cache worked. Is there a limit on how much I can filter?

**Comment by ccd0** [comment]
Not unless you're going past what Greasemonkey / Chrome can store, which is unlikely.

**Comment by ccd0** [comment]
Is this still happening?

**Comment by Xibster** [comment]
no
