### ISSUE TITLE
Auto updater forces scrolls to beginning of thread.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#874]
Submitter: Thomas
Email: thomasbags@gmail.com
Every time the auto updater updates, or is manually activated the page scroll position is forced back to the top of the page.  This is using the script version with Tapermonkey for Google Chrome.

**Comment by ccd0** [comment]
Not seeing this on my end. Can you export and post your settings somewhere? What versions of everything are you on? Are you using any other extensions?

**Comment by ferongr** [comment]
I see this. Chrome 52.0.2723.2 dev-m (64-bit), Tampermonkey.

**Comment by ccd0** [comment]
@ferongr
Any particular board/thread, or all of them?

**Comment by ferongr** [comment]
All of them. It happens when new replies are appended to the thread after
either auto-updating or manually updating with auto-update disabled.

**Comment by ccd0** [comment]
@ferongr
Thanks, I'm seeing it now.
Working on a diagnosis and fix.

**Comment by ccd0** [comment]
Don't know why it happens yet, but it seems to be specific to Chrome Dev + Tampermonkey.

Chrome Stable + Tampermonkey = no bug
Chrome Dev + 4chan X chrome extension = no bug
Chrome Dev + Violentmonkey = no bug
Chrome Dev + Tampermonkey = **bug**
Chrome Dev + Tampermonkey Beta = **bug**

So it's probably something that changed in Chrome that needs to be updated in Tampermonkey. It doesn't seem to be fixed in Tampermonkey Beta yet, so I'll see if I can make a reduced test case and report it upstream.

In the meantime, some workarounds are downgrading Chrome or using the Chrome extension or the userscript with Violentmonkey.

**Comment by ccd0** [comment]
Looks like turning off `Reply Pruning` fixes it too. That's a recent feature, so it might actually be something wrong on 4chan X's end.

**Comment by ccd0** [comment]
The bug in Tampermonkey seems to be that `window.scrollY` is undefined when accessed by userscripts with `grant` other than `none`.

Still, we can probably alleviate this on our end. The code in question was designed to prevent scrolling, but it's doing a lot of scrolling by what ought to be 0 when it doesn't need to scroll at all.

**Comment by ccd0** [comment]
Looks like a good workaround would be to use `window.scrollBy` instead of `window.scroll`. That way if things break we don't scroll to the top.

**Comment by ccd0** [comment]
Latest beta (v1.11.33.0) should no longer scroll to the top for Chrome Dev + Tampermonkey users.

**Comment by ccd0** [comment]
I think this is the same issue as
https://github.com/tampermonkey/tampermonkey/issues/291

**Comment by ferongr** [comment]
[This time at the right place(I hope)...]

I can confirm the issue doesn't happen with the latest beta of 4chan-x. Thanks for the fix.
