### ISSUE TITLE
styling: changing .opContainer and .thread display to table breaks things

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#895]
Submitter: anonymous
using https://paste.installgentoo.com/view/97df0d3e as a sample style

unedited, the style breaks thread filtering as such: http://i.imgur.com/zIaNjxz.png
commenting out the opContainer line fixes thread filtering but breaks the op's image: http://i.imgur.com/iHb8Tqc.png

pls fix

**Comment by ccd0** [comment]
Try adding `:not([hidden])` after `.opContainer` and `.thread`.

**Comment by phallus** [comment]
no change on my end

**Comment by ccd0** [comment]
Looks like you need `.opContainer:not([hidden]):not(.stub ~ *)`.
In general, you can use "Inspect Element" to find out what rule you're unintentionally overriding.

**Comment by phallus** [comment]
sadly stylish prevents combiners in :not(); however, i was able to fix the issue using `.opContainer > [hidden], .stub ~ * { display: none !important; }` in addition to the original style

**Comment by ccd0** [comment]
> sadly stylish prevents combiners in :not();

My mistake, it's right, that isn't valid CSS.
Good to hear you fixed it.
