### ISSUE TITLE
v1.12: Options / features slated for removal, minimum browser requirements, etc.

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#904]
Just want to put this out there in case there are any objections.

- <s>`Exempt Archives from Encryption` will be merged into an upcoming `HTTPS Only` option (#885).</s>
- `Restart when Opened`. The restarting was a bad idea (#159). It will be disabled by default soon, <s>and the option removed at some point thereafter</s>. It would be good to fix #903 first, though.
- `Show Name and Subject` was added for Name Sync compatibility and is no longer needed for that purpose. If you want the unused fields to be displayed, you can add `#qr .persona .field {display: block !important;}` to custom CSS.
- The `disabled` option in the archive choices section of the Advanced settings. A better way to disable access to a particular archive will be to add (using 4plebs as an example) `{"uid": 3, "boards": []}` to the upcoming `Archive Lists` setting. This also means that archives requiring login credentials (such as the defunct Foolz Beta) will no longer be disabled by default. If any such archives are created in the future, I will suggest putting them on a separate list that users can add to their archive settings, instead of adding them to the main list and excluding boards that they are the only archive for, as was formerly done.
- The `sandbox` setting for Sauce links will be removed. It's confusing for users, and its purpose is better served by ad blockers.
- The non-prefixed `blink`, `webkit`, `gecko`, and `edge` classes will no longer be added to the document. They will be replaced with `ua-blink`, `ua-webkit`, `ua-gecko`, and `ua-edge`, which will be added starting in v1.11.35.0.

Any other suggestions?

<s>I'm also thinking of dropping the leading "1." from the version number, which would make these changes take place in 12.0.0.</s>

**new (June 15)**:
- The options to disable `QR Shortcut`, `Bottom QR Link`, and `Quote Highlighting` will be removed. I expect few people have these turned off, and those who don't want them will be able to get rid of them with custom CSS.
- <s>The option to disable `Open Post in New Tab` will be removed.</s>
- <s>The `Fappe Tyme` and `Werk Tyme` settings will be combined into one setting `Fappe and Werk Tyme` that adds both items to the menu.</s>
- `Thread Excerpt` will be removed for being largely obsolete; 4chan adds thread excerpts to titles by default, even on /f/ now.
- `Remove Thread Excerpt` will also be removed unless there are objections. I think it has few users.

**new (June 17)**:
A few CSS classes and IDs are being removed. Some users may need to update their custom CSS:
- `.index-refresh-shortcut` is now `#shortcut-index-refresh > a`
- `#fappe-indicator` is now `#shortcut-fappe`
- `#werk-indicator` is now `#shortcut-werk`
- `#appchan-gal` is now `#shortcut-gallery > a`
- `.qr-shortcut` is now `#shortcut-qr > a`

**Comment by ccd0** [comment]
I'm also going to be dropping some obsolete workarounds. New minimum Chromium version will be 38 (when `Set` was implemented). Anyone on Maxthon 4.4 (Chromium 30 based) will need to update to 4.9 (Chromium 39 based).

**Comment by ccd0** [comment]
I'll probably also drop the practice of putting attributions in the changelog. They tended to be more confusing than helpful, and people can check the commit log to see who did what.

**Comment by ccd0** [comment]
Will need to test on Safari how much of a97aaab79f1d5e54b6c0d3db28323716f3dfbf6c can be safely removed.

**Comment by saxamaphone69** [comment]
Sounds good @ccd0!

Unless I'm mistaken, I would have thought it would be version '1.12', not '12.0'? A drastic change would bump the major number (redesign, several new features implemented, etc), this is just removing a few options.

If you remove `Show Name and Subject`, maybe make a mention of how to achieve it in CSS on the Wiki or something? (I don't use it, but just saying).

I'm all for you bumping up the minimum browser version requirements (I'm more of an evergreen Chrome/Firefox supporter - just think of all the things [ES6] you could do), as I would assume it removes a great deal of workaround code. I admire you for supporting so many browsers: it would be interesting to know how many people are using 4chan X on non-evergreen-Chrome/Firefox.

Keep it up dude

**Comment by ccd0** [comment]
> Unless I'm mistaken, I would have thought it would be version '1.12', not '12.0'? A drastic change would bump the major number (redesign, several new features implemented, etc), this is just removing a few options.

It's a breaking change for some users, but if removing the "1." is more confusing than not removing it, I'll leave it be.

> If you remove Show Name and Subject, maybe make a mention of how to achieve it in CSS on the Wiki or something? (I don't use it, but just saying).

I'll mention it in the changelog.

**Comment by ccd0** [comment]
Adding the `sandbox` setting for Sauce links on the removal list.

**Comment by ccd0** [comment]
Adding the `blink`, `webkit`, `gecko`, and `edge` classes.

**Comment by ccd0** [comment]
Addendum to the archive changes: This also means that archives requiring login credentials (such as the defunct Foolz Beta) will no longer be disabled by default. If any such archives are created in the future, I will suggest putting them on a separate list that users can add to their archive settings, instead of adding them to the main list and excluding boards that they are the only archive for, as was formerly done.

**Comment by ccd0** [comment]
I decided not to get rid of `Exempt Archives from Encryption`, but I'm still going to turn it off by default.

**Comment by ccd0** [comment]
Some additional proposals:

- The options to disable `QR Shortcut`, `Bottom QR Link`, and `Quote Highlighting` will be removed. I expect few people have these turned off, and those who don't want them will be able to git rid of them with custom CSS.
- The option to disable `Open Post in New Tab` will be removed.
- The `Fappe Tyme` and `Werk Tyme` settings will be combined into one setting `Fappe and Werk Tyme` that adds both items to the menu.
- `Thread Excerpt` will be removed for being largely obsolete; 4chan adds thread excerpts to titles by default, even on /f/ now.
- `Remove Thread Excerpt` will also be removed unless there are objections. I think it has few users.

Not really an option/feature removal, but `Show New Thread Option in Threads` will be turned on by default.

**Comment by ccd0** [comment]
A few CSS classes and IDs are being removed. Some users may need to update their custom CSS:
- `.index-refresh-shortcut` is now `#shortcut-index-refresh > a`
- `#fappe-indicator` is now `#shortcut-fappe`
- `#werk-indicator` is now `#shortcut-werk`
- `#appchan-gal` is now `#shortcut-gallery > a`
- `.qr-shortcut` is now `#shortcut-qr > a`

**Comment by ccd0** [comment]
Never got around to the `Fappe and Werk Tyme` thing, but it might happen next option pruning.
The `Open Post in New Tab` option was restored due to negative reactions to its removal.

The changes are now in the stable version.

**Comment by ccd0** [comment]
`Restart when Opened` also restored. (#987)

**Comment by ccd0** [comment]
Since the `Set` polyfill is low-cost (for now), and I botched updating the version requirement, it's been reverted for now.
