### ISSUE TITLE
Cannot install script with Tampermonkey.

### ISSUE THREAD

**Issue by ferongr** [ccd0/4chan-x#909]
Chrome 52.0.2729.4 dev-m (64-bit)
Tampermonkey stable.

Clicking on the install link of the stable version on the repo's readme initiates a download of the script instead of showing the script installation screen.

**Comment by ferongr** [comment]
Same thing happens on the 4chan-x website. This happens when the userscript is loaded fro the 4chan-x.net domain. The beta link loaded from Github install properly. I have a sneaking suspicion it's due to the speed of your server, I get around 60-80 KB/s from 4chan-x.net.

**Comment by ccd0** [comment]
> I have a sneaking suspicion it's due to the speed of your server, I get around 60-80 KB/s from 4chan-x.net.

I can confirm this; for me it's faster than that, but if I throttle the traffic with `tc` I see this issue both with 4chan-x.net and Github.

I noticed that gzip encoding wasn't turned on for Javascript files; I've fixed that, and it should be ~3x faster now. Can you test it again? If that's not enough I can look into putting it behind a CDN again.

**Comment by ferongr** [comment]
Yep, it worked, Tampermonkey install screen showed up in less than 3 seconds (and my connection is saturated by bittorrent). I'll have to try again tomorrow at the same time I reported the issue to verify this.

**Comment by ferongr** [comment]
Seems to be working today too. Thanks for the fix.
