### ISSUE TITLE
4chan x and Greasemonkey 2.0 still conflict with firefox 30.0

### ISSUE THREAD

**Issue by Dudemanguy911** [ccd0/4chan-x#91]
I have no idea why this randomly happened, but suddenly, 4chan x would simply not load on any of the boards. Greasemonkey said the script was activated, but it was simply not on the page anymore as if I had never installed it. What's more puzzling, I didn't change nor update a single thing when this happened and I've been running this setup without issues for a good while. My only guess is that google changed their javascript and somehow caused this bug. As an extra note, any scripts running on sites that relied on google scripts (4chan, youtube, etc.) would simply not work (however, scripts on non-google sites worked without issue). Fortunately, reverting back to Greasemonkey 1.15 seems to be a good workaround as the front page hints, but I have encountered 4chan x and the latest greasemonkey to also conflict on firefox 30 for whatever reason. So updating to firefox 30 as a workaround for this issue no longer seems to work, or at least, did not work for me.

**Comment by ccd0** [comment]
Is this still happening?
