### ISSUE TITLE
Suggestion: In the thread watcher, provide the option to highlight any response in a thread that you authored, whether the response quotes you or not.

### ISSUE THREAD

**Issue by thebugjim** [ccd0/4chan-x#913]
When I create a thread myself, I like to read every response to the thread, whether it quotes me or not. Thus, I would like the option to have the thread watcher turn red and highlight it any time a post i made gets a response.

**Comment by ccd0** [comment]
Done. Turn off "Require OP Quote Link" in the Thread Watcher menu.
