### ISSUE TITLE
captcha doesn't show (was: threads never finish loading, captcha doesn't show)

### ISSUE THREAD

**Issue by miniwabestcat** [ccd0/4chan-x#917]
using 4chanx 1.11.34.5 on firefox (whatever latest stable version is now) threads never finish loading (the loading icon keeps showing in tab), all messages are there and new ones appear when posted however the captcha doesn't load so i have to disable 4chanx to post

the odd thing is that it started a couple of days ago without installing any other script or whatever

i'm using noscript but even allowing all scripts on site/globally/disabling or uninstalling it the problem is still there

**Comment by ccd0** [comment]
Can you post your exported settings?

**Comment by ccd0** [comment]
And in particular, which captcha are you using?

**Comment by ccd0** [comment]
Are you using any other extensions besides Greasemonkey and Noscript?

**Comment by miniwabestcat** [comment]
[4chan X v1.11.34.5-1463736013791.zip](https://github.com/ccd0/4chan-x/files/274248/4chan.X.v1.11.34.5-1463736013791.zip)
settings

the capcha is the one with pictures, never changed any setting about that so it should be default

other plugins, adbock, firebug, noscript, image search options and search by image for google, already tried with all of the disabled

**Comment by ccd0** [comment]
At precisely what stage does the captcha fail? Is it that you can't bring up the checkbox or that you can't bring up the challenge when you click the checkbox?

What does your network activity look like when you try to open the captcha? (Clicking the "Captchas: #" should open and close that section of the Quick Reply.) This is what I get:

![network](https://cloud.githubusercontent.com/assets/5894749/15424085/8cbe8f30-1e35-11e6-9e06-ab12c64525af.png)

Do you see any error messages in the console, especially at the time you try to open the captcha?

Another thing to check is if you're using any kind of web filtering software or antivirus (they often include web filters), as that's another thing that can malfunction and block things.

You might also try seeing whether clearing your cookies on google.com, or working in a fresh profile, makes a difference.

**Comment by miniwabestcat** [comment]
so uh the problem just stopped, now i get a "Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json" popup when opening catalog that never happened before but everything seems to work fine

**Comment by ccd0** [comment]
> now i get a "Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json" popup when opening catalog that never happened before but everything seems to work fine

4chan X updates the archive list separate from the script updates now. If you want to keep the archive list updated, unblock mayhemydg.github.io in NoScript, otherwise you can turn the update checking off at `Advanced > Archives > Auto-update`.

**Comment by ccd0** [comment]
The loading icon thing is issue #832 and should be fixed now.
Closing since the captcha issue seems to have resolved on your end somehow. Let me know if it recurs.
