### ISSUE TITLE
4chan Affected After Deleting Extension

### ISSUE THREAD

**Issue by EJ-301** [ccd0/4chan-x#928]
I removed the 4chan X extension and now certain features on 4chan are either altered or missing (images open in new tab automatically, update button missing, hovering over >>XXXXXX does not show reply, etc.). How can I get it back to normal?

**Comment by ccd0** [comment]
You need to re-enable the native extension:
https://github.com/ccd0/4chan-x#please-note

But the blinking issue is fixed, if that's why you disabled it.
