### ISSUE TITLE
Page "blinks"

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#930]
Submitter: Hubi
Email: thehubipl@gmail.com
When the script is on, 4chan starts to "blink" (ie. every element except the background disappears and appears continuously).
I also use mGET, however after uninstalling the script the issue remains. Turning off JavaScript or 4chan X seem to repair the issue.

**Comment by SeraphimKnight** [comment]
Same issue here, disabling 4chanX stops the page from blinking.

**Comment by sergiooliveira28** [comment]
Same. Like SeraphimKnight, disabling the extension removes the "blinking".
