### ISSUE TITLE
fgts.jp is down

### ISSUE THREAD

**Issue by neiiosolipsism** [ccd0/4chan-x#933]
The 4chan archive is down, I don't know if it's going to remain down but it's been a while.

**Comment by r3c0d3x** [comment]
Already removed it from the official archives.json repo some time back.

**Comment by r3c0d3x** [comment]
As of 11:08:29 AM EST, fgts.jp is dead for good: https://archive.is/78Buf

**Comment by ccd0** [comment]
Sad to hear.
It will be out of the list if when the beta becomes stable or there's another hotfix.
I'll also need to remove the fgts-specific reporting code.
