### ISSUE TITLE
11.33.7 : "Focus to load recaptcha" not working

### ISSUE THREAD

**Issue by Question2** [ccd0/4chan-x#935]
The quick reply "focus to load recaptcha" isnt working (clicking there doesnt load the recaptcha). Clicking the original form button does nothing either. This is on pale moon 26.2.1 btw.

**Comment by Question2** [comment]
Disregard, found the problem.

**Comment by ccd0** [comment]
What was the problem?

**Comment by Question2** [comment]
I just installed a new add on that was accidentally blocking the recaptcha.
