### ISSUE TITLE
Filters for SFW/NSFW boards only

### ISSUE THREAD

**Issue by usernamestring** [ccd0/4chan-x#944]
Is it possible to add an option to the filter for applying regexp only while on SFW boards? It's annoying having to use the boards: or exclude: filters followed by a long list of boards every time I want to hide a nasty pic or webm only on blue boards.
Thank you and thanks for keeping 4chan-x alive.

**Comment by ccd0** [comment]
Seems like a good idea.

**Comment by ccd0** [comment]
Currently blocked on changing filters to work async, see discussion in #985.

**Comment by ccd0** [comment]
Now in stable.
