### ISSUE TITLE
How do I pin watched threads to the top?

### ISSUE THREAD

**Issue by HASJ** [ccd0/4chan-x#948]
Also, would it be possible to filter watched threads? Like a selector to show Watched/Non-Watched/Hidden threads?
Guess I should make another issue for it. Right?

**Comment by ccd0** [comment]
> How do I pin watched threads to the top?

header menu > Index Navigation > Pin Watched Threads

> Also, would it be possible to filter watched threads? Like a selector to show Watched/Non-Watched/Hidden threads?

Sorry, not sure what you want to do. Could you elaborate? Is something you'd want to use in combination with other filters (like excluding threads from a filter if you have the thread watched), or do you just want an index-like view of all watched/non-watched threads? An example use case might be helpful.

>  Guess I should make another issue for it. Right?

Probably, issues get lost if they're only mentioned as comments in other issues.

**Comment by ccd0** [comment]
I'm going to close this; please make a new issue about the watched threads suggestion if you still want it.
