### ISSUE TITLE
4chan affected after uninstalling extension

### ISSUE THREAD

**Issue by puked** [ccd0/4chan-x#949]
I'm having the same problems as this person https://github.com/ccd0/4chan-x/issues/928
I re-enabled the native extension but it didn't work.

**Comment by ccd0** [comment]
Did you reload the page after doing so?

**Comment by puked** [comment]
Yeah

**Comment by ccd0** [comment]
Did you press the "Save Settings" button after unchecking "Disable the native extension"? Sometimes people have accidentally hidden that button with an ad blocker.

**Comment by i-cant-git** [comment]
Clear cookies

**Comment by puked** [comment]
Thanks

**Comment by ccd0** [comment]
What worked?

**Comment by puked** [comment]
The save settings button was blocked
