### ISSUE TITLE
Where is the beep sound stored? I want to change it!

### ISSUE THREAD

**Issue by Kittenzpaw** [ccd0/4chan-x#950]
I want to change the sound to something else, if possible. I have many, slow threads on standby in tabs in another window. While wearing headphones with high volume listening to music; a loud, jump-scaring beep attacks me when someone posts.

I do very appreciate the notification, but it's absolutely ear shattering and would like to change the sound to something safer.

**Comment by vampiricwulf** [comment]
What a hearty laugh this gave me!
Anyway, if you're compiling X yourself, then just replace the beep.wav file in src/Monitoring/ThreadUpdater/.
If you're "lazy" and just want to edit the already compiled script, you'll want to convert the sound you want to replace with beep into Base64 and edit a string in the script.
Using something like http://www.opinionatedgeek.com/DotNet/Tools/Base64Encode/ will convert it into Base64 and replacing the part of the string after ```data:audio/wav;base64,``` with the Base64 text on https://github.com/ccd0/4chan-x/blob/master/builds/4chan-X.user.js#L16989 is how you'd accomplish that.

**Comment by ccd0** [comment]
Merging into #603.
