### ISSUE TITLE
Loading issue with Firefox

### ISSUE THREAD

**Issue by Icarus77** [ccd0/4chan-x#952]
So I'm using Cyberfox (but I've also tried normal Firefox and Waterfox) and have had this persisting issue with 4chan X where the tab clover icon will work fine, but then within a few minutes of having the web browser open, the icon will just constantly have the swirling icon as if the page is loading infinitely, even though the page is already fully loaded. It affects 4chan only, and affects all boards. 

Does anyone know how to fix this? It's kind of annoying because once this happens I can't see the red/green/blue clover icon with the notification for when I have a reply or if the thread's dead/archived. I have to restart my browser to fix it every time, then it just happens again a few minutes later.

**Comment by ccd0** [comment]
Merging this into #832. Can you see anything loading in the network tab of the console (F12)?

Also, any other userscripts / extensions? Do you have ads blocked or unblocked? Which version of the captcha do you use?

**Comment by Icarus77** [comment]
I'll get back to you on it when it starts happening again. Just reset browser.
