### ISSUE TITLE
exclude setting for filters excludes filters beneath it

### ISSUE THREAD

**Issue by lazy-lemon** [ccd0/4chan-x#953]
Whenever I set a filter to exclude certain boards, it will set the filters beneath it to exclude those boards as well. 

Something like this:
```
/filter 1/
/filter 2/;exclude:board
/filter 3/
/filter 4/
/filter 5/
```

Filter 1 will work on whatever board, but filters 2-5 will not.

**Comment by epicgirl1998** [comment]
as the gamer who contributed this feature i am having trouble reproducing your issue

unless i somehow misunderstood it

https://a.pomf.cat/gitsrv.png

in my screenshot the filter below the excluded one is doing its thing correctly

can you post your filters or something so i can look at them more

**Comment by ccd0** [comment]
I found a bug, but it only happens if the line beneath the exclude uses the `boards` setting, for example:

    /1$/
    /2$/;exclude:c
    /3$/;boards:c

Is this consistent with the problem you're seeing?

**Comment by ccd0** [comment]
Can you check whether the beta version fixes it for you?

**Comment by lazy-lemon** [comment]
Sorry to have kept you waiting. You're right. I hadn't noticed that before, but it had to be `exclude` then `board` for the bug to trigger.  I tried the beta version, and the problem seems to have been fixed, so thank you.
