### ISSUE TITLE
Connection error.

### ISSUE THREAD

**Issue by azurekite** [ccd0/4chan-x#954]
Hey guys, I've been getting since yesterday an error message saying "Error fetching archive data from https://mayhemydg.github.io/archives.json/archives.json Connection Error"
I'm trying to figure out what's up with this but it's been almost 2 years since I've dealt with this things that I forgot what the hell I need to do. 
Any help is appreciated.

**Comment by ccd0** [comment]
4chan X is trying to check the archive list, and you have another extension that's blocking it. Either whitelist the requests to that URL in whatever extension's blocking it, or turn off auto-updates under `Advanced > Archives > Auto-update`.

**Comment by azurekite** [comment]
Ah, now I feel like an idiot for not seeing that it was getting blocked. Thanks for the help.

**Comment by weedy** [comment]
It's not an extension. It's FF40+

"4chan X failed to load: https://mayhemydg.github.io/archives.json/archives.json" 4chan-X.user.js:3958:20

Content Security Policy: The page's settings blocked the loading of a resource at https://s.zkcdn.net/ados.js ("script-src http://s.4cdn.org https://s.4cdn.org http://www.google.com https://www.google.com https://www.gstatic.com http://cdn.mathjax.org https://cdn.mathjax.org https://boards.4chan.org 'unsafe-inline' 'unsafe-eval'").

**Comment by ccd0** [comment]
@weedy
If you're having a problem where you're seeing this message, have you checked with a [new profile](https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles)?
