### ISSUE TITLE
Lag caused by 4chan x and scriptsafe when clicking quotes

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#958]
Submitter: azdsgdrhedh
Email: nononnono@ageseg.com
Just like in the title, when I have Scriptsafe on, chrome freezes for 5 good seconds when clicking quotes on a thread.

**Comment by andryou** [comment]
This issue is caused by ScriptSafe (sorry!) - beta version with a fix and more info here: https://github.com/andryou/scriptsafe/issues/40
