### ISSUE TITLE
Connection error while posting

### ISSUE THREAD

**Issue by d3athrow** [ccd0/4chan-x#965]
Getting a constant connection error while posting if the image size is over a certain amount but well under the board's maximum file size. http://ss13.moe/uploads/2016-06-13_11-15-23.png Posting the same image with the original form works fine, modifying the file to be smaller works as well.

**Comment by ccd0** [comment]
https://github.com/ccd0/4chan-x/wiki/Frequently-Asked-Questions#connection-errors

What browser and what version of the browser and 4chan X are you using? Have you tried disabling any other extensions, as well as any antivirus software that may be filtering your connection? Is there a difference between the original post form and quick reply if `Show Upload Progress` is turned off?

**Comment by petroid** [comment]
I get connection error while posting even without picture.
Browser: Opera 38.0.2220.29
Tampermonkey 4.1.5231
![clipboard-1](https://cloud.githubusercontent.com/assets/246256/16023137/10f92264-31c4-11e6-96e3-7be82a308c79.png)

**Comment by ccd0** [comment]
@petroid
Are you in Russia?
Does turning off `Show Upload Progress` make a difference?

**Comment by Radost** [comment]
I am in Russia and turning off `Show Upload Progress` indeed made a difference.

**Comment by petroid** [comment]
I'm in Russia too. Turning off `Show Upload Progress` fixed connection error.

**Comment by d3athrow** [comment]
@ccd0 
Firefox 47.0a2
4chanx v1.11.35.4
Greasemonkey 3.8beta3
Issue persists even with show upload progress turned off.

**Comment by ccd0** [comment]
@d3athrow
Try updating Firefox and Greasemonkey and seeing if that fixes it.

**Comment by d3athrow** [comment]
@ccd0 No change

**Comment by ccd0** [comment]
Can you post what versions you updated to?
And does it happen in a freshly created profile with just Greasemonkey and 4chan X installed?

**Comment by d3athrow** [comment]
49.0a2 (2016-06-16) and greasemonkey is apparently up to date

**Comment by d3athrow** [comment]
Upon completely uninstalling and reinstalling Firefox the issue is fixed somehow.
