### ISSUE TITLE
Add a 'Mobile time' kind of like 'werk time' option

### ISSUE THREAD

**Issue by Xinnx** [ccd0/4chan-x#966]
I don't know if it is possible but a feature that would strip 4chan down to practically text boards would be nice. Specifically with the goal of reducing asset loading.I have noticed that the Werk time option doesn't prevent the picture thumbnails from being loaded it just hides them. 

tl;dr if it is not absolutely needed to view text posts prevent the page from loading it or defer loading until it is needed.

I would like to see this feature because I tether my laptop to my phone for mobile data and loading just the main page on most boards racks up 250-350kb of data for each load. Now browser caching should take care of subsequent page refreshes but it would be nice to see a 'minimal mode' or something.

EDIT: Added last paragraph with my reasoning behind the enhancement

**Comment by dzamie** [comment]
I'm inclined to say it's impossible. In most if not all popular browsers, &lt;img&gt; tags start loading once their src is read, so extensions/addons/scripts, which start loading after the page has started to load, are "lagging behind" the browser's attempt to display images. So it's very likely if not definite that this would be outside the scope of a browser addon.

**Comment by zixaphir** [comment]
Kinda sorta. If we could trash the HTML loading of the browser and defer to
a dynamic creation of the page from JSON, we could completely forego
creating image elements at all, therefore bypassing any browser mechanisms
from mattering. But would it be worth the trouble?

**Comment by i-cant-git** [comment]
If OP wants block images, he can add `i.4cdn.org 127.0.0.1` to *hosts* file. (Cross-platform)
Second option is blocking images through uBlock (Firefox/Chrome) which is same as above.

As @zixaphir said it's possible to ignore HTML and create posts using 4chan API but it's not worth the trouble in my opinion (i.e re-inventing the wheel).

**Comment by Xinnx** [comment]
I am going to close this issue because I believe it was resolved through the use of hosts files or using a adblocker such as uBlock.
