### ISSUE TITLE
Filtering words only from OP posts

### ISSUE THREAD

**Issue by gotmilk0112** [ccd0/4chan-x#969]
I can't figure out how to do it.

I can filter words from anywhere just fine, but I cannot for the life of me seem to figure out how the "op:only" flag works. In general, the guide doesn't really give any examples of how to use them.

I tried:

/texthere/op:only;
op:only;/texthere/
/texthere/;op:only

None of them work, often giving an error:
Invalid flags supplied to RegExp constructor 'op'

**Comment by i-cant-git** [comment]
brah, you need to add Regex flag, which is /texthere/i;op:only
i = case insensitive, look regex flags

**Comment by ccd0** [comment]
/texthere/;op:only
(with special characters in texthere escaped with a backslash) should work, but the matching will be case sensitive.
