### ISSUE TITLE
Quick reply + uploading images with randomize filenames = connection error

### ISSUE THREAD

**Issue by Question2** [ccd0/4chan-x#972]
Seems to have started happening yesterday. Uploading images via quick reply and randomize filenames always gives a connection error...if i use the original reply form (which doesnt have randomize filenames), it works just fine. I can also use the quick reply form to post text without images.

But if the randomize filename option is used when uploading images via the quick reply form, i always get a connection error imemdiately.

This is for version 1.11.35.5 btw.

Edit : Just tried disabling randomize filenames and it didnt help. So i can upload images via the original form but not the quick reply form that 4chanX uses.

**Comment by Question2** [comment]
Actually the entire quick reply form won't work for me anymore. Just says connection error.

**Comment by Question2** [comment]
Hmm, just tried disabling the upload progress thing and that seems to work...not in russia though.

**Comment by ccd0** [comment]
Probably not something that can be fixed on 4chan X's end except by disabling `Show Upload Progress` as you did. It might be worth repeating this with the native extension quick reply and reporting it to https://www.4chan.org/feedback along with your IP address and the details from the network tab on your console (F12) when you try to post with it. (Russians have reported that the OPTIONS request to sys.4chan.org/post gets a 403 response.)
