### ISSUE TITLE
How does 4chanx track which posts are yours?

### ISSUE THREAD

**Issue by Question2** [ccd0/4chan-x#973]
More of a question, but how does 4chan track which posts are yours so that replies to them will display the (you)?

**Comment by ccd0** [comment]
If you're using Greasemonkey, it uses [GM_setValue](https://wiki.greasespot.net/GM_setValue).

**Comment by Question2** [comment]
Is it a cookie or something?

**Comment by i-cant-git** [comment]
If you read the page @ccd0 linked, it says right there

> Since Greasemonkey 1.13 values are saved per userscript in a SQLite database [1]. You can find the corresponding database by the userscript basedir as defined in the config.xml. The values are only accessible by opening the database is an SQLite reader, like add-on SQLite Manager.
