### ISSUE TITLE
Using numpad to complete ReCAPTCHA in Firefox locks the browser

### ISSUE THREAD

**Issue by HASJ** [ccd0/4chan-x#978]
Doesn't happen in Chrome.
Normal and noscript mode.
Doesn't raise CPU usage, just locks up mouse and keyboard responses.

**Comment by ccd0** [comment]
What Firefox and Greasemonkey versions?
Have you tried temporarily disabling other extensions to see if there's a conflict?

**Comment by HASJ** [comment]
Okay, sorry for the delayed response.
Letting only Greasemonkey/4chan X to run, it worked normally.
Culprit must be a combination of extensions but since I'm not using Firefox anymore, I don't have the issue.
I can try to pinpoint it if you want though.
