### ISSUE TITLE
Why do images open new tabs instead of expanding?

### ISSUE THREAD

**Issue by thegreenderpity** [ccd0/4chan-x#979]
I'm a noob at this, but it's getting pretty annoying. Anyone know how to help?

**Comment by ccd0** [comment]
Make sure `Image Expansion` and then try this stuff:
https://github.com/ccd0/4chan-x/blob/master/CONTRIBUTING.md#reporting-bugs

**Comment by thegreenderpity** [comment]
Everything is up to date. The issue only started after installing 4chan X,
but when it's disabled, the pictures still open in different tabs. I
wouldn't call it a bug per say, but I still need help.

**Comment by ccd0** [comment]
If you have both 4chan X and the native extension disabled, it's normal for images to open in a new tab.
If you have 4chan X enabled and `Image Expansion` turned on in your settings, images should expand when clicked instead. If they don't, please tell me test disabling other extensions, tell me what versions of everything you're running, and check for console errors.

**Comment by ccd0** [comment]
Is this still happening?
