### ISSUE TITLE
Posts opened in new tab in Pale Moon at wrong position

### ISSUE THREAD

**Issue by ccd0** [ccd0/4chan-x#980]
Question2 in https://github.com/ccd0/4chan-x/issues/938#issuecomment-227181412:
> "Create new thread in a new tab" was apparently working...but for some reason, pale moon was shoving all the newly created tabs to the very end of the tab bar, so I didnt notice them at all. This didnt used to happen, not sure what changed. Im not sure if thats fixed now...i will have to get back to you on that.

**Comment by janekptacijarabaci** [comment]
Hello.
I think the following might help you:
See https://github.com/greasemonkey/greasemonkey/issues/2269
See also https://github.com/greasemonkey/greasemonkey/pull/2257
(https://tampermonkey.net/documentation.php#GM_openInTab)
(`about:config` - `browser.tabs.insertRelatedAfterCurrent`)

**Comment by ccd0** [comment]
Thanks. Looking at this again, there's no bug at all; it's just that Pale Moon has a different default for `browser.tabs.insertRelatedAfterCurrent`.

**Comment by ccd0** [comment]
For Pale Moon users: If you want new tabs to open after the current tab, open your Pale Moon settings, select `Tabs`, and check `Insert related tabs next to the current tab`.
