### ISSUE TITLE
Issue With WebM's

### ISSUE THREAD

**Issue by Iwastheturkey3** [ccd0/4chan-x#989]
WebM's no longer work at all within the 4chanX extension.  They don't expand when I click on them, nor do they show when I hover.  The gallery doesn't work either.  They only work if I open them in a new tab or disable the 4chanX extension.  I haven't changed any settings and the problem started yesterday.  
EDIT: Just tried updating chrome and that did not fix it.

**Comment by ccd0** [comment]
What version of Chrome and 4chan X (and Violentmonkey/Tampermonkey, if applicable) are you using? Have you tried temporarily disabling all other extensions to check for a conflict?

**Comment by Iwastheturkey3** [comment]
4chan X: 1.12.0.8
Chrome: 51.0.2704.106 m
Ill try disabling other extensions and report back.

**Comment by ccd0** [comment]
The native extension doesn't seem to work with that extension installed either. It's probably a generic problem that it's causing with HTML video. You might want to file a bug report on the Audio EQ page.
